import Link from 'next/link';
import { ArrowRight, CheckCircle2, FileText } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';
import { siteUrl } from '@/lib/routes';
import type { BosphorasProgrammaticSeoPage } from '@/data/bosphorasProgrammaticSeoPages';

type Profile = { use: string; allowed: string; notAllowed: string; route: string; duration: string; docs: string[]; mistakes: string[]; ikamet: string };

const profiles: Record<string, Profile> = {
  'turkey-visa-types-hub': { use: 'comparer toutes les options d entree et de sejour en Turquie', allowed: 'identifier la bonne voie entre sans visa, e-Visa, visa consulaire, travail, etudes, famille, transit ou ikamet', notAllowed: 'choisir une categorie au hasard sans verifier nationalite, passeport et objectif reel', route: 'hub central Bosphoras pour orienter vers la bonne page visa', duration: 'variable selon nationalite, passeport et projet', docs: ['passeport ou document de voyage', 'nationalite exacte', 'motif du sejour', 'duree prevue'], mistakes: ['confondre visa et residence', 'ne pas compter les jours deja utilises', 'oublier le passage vers ikamet'], ikamet: 'des que le sejour devient long, familial, immobilier, professionnel ou structure' },
  'turkey-tourist-visa': { use: 'tourisme, visite privee, court sejour familial ou decouverte de la Turquie', allowed: 'visiter la Turquie sans travailler et sans s installer durablement', notAllowed: 'ne permet pas de travailler, etudier durablement ou rester apres la duree autorisee', route: 'e-Visa si la nationalite est eligible, sinon visa consulaire', duration: 'souvent 30, 60 ou 90 jours selon nationalite et type de visa', docs: ['passeport valide', 'hebergement ou adresse', 'billet retour ou continuation', 'moyens financiers'], mistakes: ['venir travailler avec un visa touristique', 'confondre tourisme et residence', 'depasser la duree autorisee'], ikamet: 'si le visiteur veut rester plus longtemps, louer, acheter ou vivre en Turquie' },
  'turkey-e-visa-main': { use: 'autorisation officielle en ligne pour tourisme ou commerce court', allowed: 'tourisme, commerce et rendez-vous courts selon eligibilite du pays', notAllowed: 'ne couvre pas travail, etudes, residence longue ou activite locale permanente', route: 'demande sur la plateforme officielle e-Visa uniquement', duration: 'duree et nombre d entrees variables selon nationalite', docs: ['passeport valide', 'email', 'paiement en ligne', 'document conditionnel si demande'], mistakes: ['utiliser un faux site e-Visa', 'croire que e-Visa permet de travailler', 'ne pas verifier les conditions du pays'], ikamet: 'avant expiration si le sejour devient un projet de residence' },
  'turkey-business-visa': { use: 'rendez-vous, salons, prospection, negociation, visite fournisseur ou client', allowed: 'activites commerciales courtes sans emploi local', notAllowed: 'ne permet pas d etre salarie en Turquie ou d exploiter localement une activite', route: 'e-Visa ou visa consulaire selon nationalite et passeport', duration: 'court sejour limite par la regle applicable au pays', docs: ['invitation commerciale', 'preuve de societe', 'planning de rendez-vous', 'passeport'], mistakes: ['confondre business visit et travail local', 'venir sans invitation si elle est requise', 'ne pas preparer banque ou societe'], ikamet: 'si les rendez-vous debouchent sur societe, bureau, personnel ou investissement' },
  'turkey-investor-visa': { use: 'preparer investissement immobilier, societe, banque, due diligence ou installation', allowed: 'rencontrer avocat, banque, promoteur, vendeur, comptable ou partenaire', notAllowed: 'ne donne pas automatiquement residence ou nationalite', route: 'court sejour, e-Visa ou visa consulaire selon nationalite puis ikamet si projet confirme', duration: 'depend du visa d entree et de la strategie de residence', docs: ['preuve du projet', 'rendez-vous avocat ou banque', 'budget ou justificatifs', 'passeport'], mistakes: ['acheter avant verification juridique', 'confondre tapu et residence', 'oublier fiscalite et banque'], ikamet: 'des que investissement immobilier, societe ou installation familiale devient concret' },
  'turkey-work-visa': { use: 'travailler legalement en Turquie avec employeur ou cadre autorise', allowed: 'activite professionnelle seulement avec permis de travail et procedure adaptee', notAllowed: 'ne permet pas de travailler avec visa touristique, e-Visa ou simple entree business', route: 'demande via mission turque avec implication de l employeur et permis de travail', duration: 'liee au permis de travail et a la decision administrative', docs: ['contrat ou offre', 'documents employeur', 'passeport', 'diplomes si demandes'], mistakes: ['commencer a travailler comme touriste', 'oublier le role de l employeur', 'ne pas demander le permis de travail'], ikamet: 'le permis de travail peut couvrir le sejour mais la famille doit etre traitee separement' },
  'turkey-student-visa': { use: 'etudier en Turquie dans une ecole, universite ou programme reconnu', allowed: 'entrer pour suivre un programme d etudes identifie', notAllowed: 'ne permet pas un cursus long sans statut etudiant adapte', route: 'procedure etudiant via mission turque selon admission et nationalite', duration: 'liee au programme et a la residence etudiant apres arrivee', docs: ['lettre admission', 'passeport', 'preuve de ressources', 'assurance'], mistakes: ['arriver sans admission', 'ne pas preparer residence etudiant', 'confondre court sejour et scolarite'], ikamet: 'apres arrivee pour couvrir la duree des etudes' },
  'turkey-family-visa': { use: 'rejoindre conjoint, enfants ou organiser installation familiale', allowed: 'preparer entree et residence familiale selon lien familial', notAllowed: 'ne fonctionne pas sans documents familiaux solides', route: 'visa ou entree selon nationalite puis residence familiale ou courte duree', duration: 'depend du visa d entree puis du type de residence', docs: ['acte mariage', 'acte naissance', 'traductions', 'apostilles'], mistakes: ['ne pas prouver le lien familial', 'oublier documents enfants', 'ne pas preparer adresse et assurance'], ikamet: 'quand la famille veut rester ensemble au dela du court sejour' },
  'turkey-property-owner-visa': { use: 'venir comme proprietaire immobilier ou futur acheteur en Turquie', allowed: 'organiser visite, achat, due diligence, tapu et residence liee au bien', notAllowed: 'penser que l achat donne automatiquement residence', route: 'entree selon nationalite, puis ikamet proprietaire si dossier eligible', duration: 'court sejour au depart, puis residence selon dossier immobilier', docs: ['tapu ou compromis', 'adresse du bien', 'passeport', 'assurance'], mistakes: ['acheter dans une zone problematique', 'ne pas verifier l adresse', 'confondre immobilier et citoyennete'], ikamet: 'quand le bien sert de base de residence ou d installation familiale' },
  'turkey-transit-visa': { use: 'transiter par aeroport turc avec ou sans sortie de zone internationale', allowed: 'correspondance ou escale selon nationalite et document de voyage', notAllowed: 'ne permet pas de sortir de l aeroport si une entree exige visa', route: 'verification selon nationalite, aeroport, compagnie et sortie de zone internationale', duration: 'liee au temps d escale et au statut entree ou transit', docs: ['billet continuation', 'passeport', 'visa destination finale si demande'], mistakes: ['confondre transit airside et entree', 'prevoir sortie aeroport sans visa', 'ne pas verifier la compagnie'], ikamet: 'normalement non concerne sauf si le transit devient sejour en Turquie' },
  'turkey-visa-overstay': { use: 'comprendre les risques apres depassement de duree en Turquie', allowed: 'analyser sortie, amende, restriction et strategie future', notAllowed: 'ne doit pas etre attendu jusqu au controle aeroport sans plan', route: 'analyse du nombre de jours, type d entree, historique et decision possible', duration: 'chaque jour au dela de l autorisation compte', docs: ['passeport', 'tampons entree sortie', 'historique voyages'], mistakes: ['ignorer les jours utilises', 'deposer ikamet trop tard', 'sortir sans comprendre risque retour'], ikamet: 'un overstay peut compliquer l ikamet, il faut agir avant expiration quand possible' },
  'extend-stay-in-turkey': { use: 'prolonger legalement un sejour avant expiration', allowed: 'preparer ikamet, adresse, assurance et motif coherent', notAllowed: 'ne consiste pas a rester simplement plus longtemps', route: 'demande ikamet ou autre procedure avant expiration du court sejour', duration: 'depend du nombre de jours restants et du type de residence', docs: ['adresse', 'assurance', 'passeport', 'justificatifs du motif'], mistakes: ['attendre dernier jour', 'ne pas avoir adresse valable', 'oublier assurance'], ikamet: 'solution principale quand un court sejour devient residence' }
};

const relatedKeys = ['turkey-visa-types-hub','turkey-tourist-visa','turkey-e-visa-main','enter-turkey-without-visa','turkey-90-days-in-180','turkey-passport-or-id-card','turkey-business-visa','turkey-investor-visa','turkey-work-visa','turkey-student-visa','turkey-family-visa','turkey-transit-visa','turkey-residence-permit-main','turkey-ikamet-main'];

function profileFor(key: string): Profile { return profiles[key] ?? profiles['turkey-visa-types-hub']; }
function assessmentHref(locale: Locale) { return locale === 'fr' ? '/diagnostic-prive' : locale === 'en' ? '/en/private-assessment' : locale === 'ru' ? '/ru/chastnaya-konsultatsiya' : '/ar/تقييم-خاص'; }
function titleFor(locale: Locale, fr: string, en: string, ru: string, ar: string) { return locale === 'fr' ? fr : locale === 'en' ? en : locale === 'ru' ? ru : ar; }

export function BosphorasVisaTypeSeoPageV2({ page, locale, allPages }: { page: BosphorasProgrammaticSeoPage; locale: Locale; allPages: BosphorasProgrammaticSeoPage[] }) {
  const p = profileFor(page.key);
  const canonical = `${siteUrl}${page.slugs[locale]}`;
  const related = relatedKeys.map((key) => allPages.find((item) => item.key === key)).filter(Boolean) as BosphorasProgrammaticSeoPage[];
  const faq = [[`${page.titles[locale]} : est-ce automatique ?`, 'Non. Bosphoras verifie nationalite, passeport, motif, duree et documents avant de proposer une strategie.'], ['Ce visa permet-il de travailler ?', page.key === 'turkey-work-visa' ? 'Oui uniquement avec permis de travail et procedure employeur.' : p.notAllowed], ['Quand passer vers l ikamet ?', p.ikamet]];
  return <>
    <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: page.titles[locale], description: `${page.titles[locale]} - ${p.use}`, inLanguage: locale, datePublished: '2026-06-05', dateModified: '2026-06-05', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: canonical, keywords: page.focus.join(', ') }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
    <Header locale={locale} currentPath={page.slugs[locale]} />
    <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
      <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Bosphoras · Visa Turquie</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">{page.titles[locale]}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{p.use}. {p.allowed}. {p.notAllowed}</p><Link href={assessmentHref(locale)} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{titleFor(locale, 'Verifier mon dossier', 'Check my file', 'Проверить dossier', 'فحص ملفي')}<ArrowRight size={16} /></Link></div></section>
      <Block title={titleFor(locale, 'Regles propres a cette page', 'Specific rules for this page', 'Правила этой страницы', 'قواعد هذه الصفحة')} items={[p.allowed, p.notAllowed, p.route, p.duration]} dark={false} />
      <Block title={titleFor(locale, 'Documents a preparer', 'Documents to prepare', 'Документы', 'الوثائق المطلوبة')} items={p.docs} dark={false} />
      <Block title={titleFor(locale, 'Erreurs a eviter', 'Mistakes to avoid', 'Ошибки', 'الأخطاء')} items={p.mistakes} dark />
      <Block title={titleFor(locale, 'Passage vers residence / ikamet', 'Move to residence / ikamet', 'Переход к residence / ikamet', 'الانتقال إلى الإقامة / الإيكامت')} items={[p.ikamet]} dark />
      <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1200px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">{titleFor(locale, 'Comparer avec les autres options', 'Compare with other options', 'Сравнить с другими вариантами', 'قارن مع الخيارات الأخرى')}</h2><div className="mt-8 grid gap-3 md:grid-cols-4">{related.map((item) => <Link key={item.key} href={item.slugs[locale]} className="border border-[#d8c7a1] bg-white p-5 text-sm font-semibold leading-7 text-[#121826] hover:bg-[#f8f1e7]">{item.titles[locale]}</Link>)}</div></div></section>
      <section className="px-5 pb-20 md:px-8 md:pb-28"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">FAQ</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
    </main><Footer locale={locale} /></>;
}

function Block({ title, items, dark }: { title: string; items: string[]; dark: boolean }) {
  return <section className={`${dark ? 'bg-[#121826] text-white' : 'bg-[#f8f1e7] text-[#101827]'} px-5 py-16 md:px-8 md:py-24`}><div className="mx-auto max-w-[1200px]"><div className="flex items-center gap-3"><FileText className={`${dark ? 'text-[#d2a863]' : 'text-[#8a6728]'} h-8 w-8`} /><h2 className="font-serif text-4xl tracking-[-0.03em]">{title}</h2></div><div className="mt-8 grid gap-3 md:grid-cols-2">{items.map((item) => <div key={item} className={`${dark ? 'border-white/15 bg-white/5 text-white/75' : 'border-[#d8c7a1] bg-white text-[#3e4857]'} flex gap-3 border p-5 text-sm leading-7`}><CheckCircle2 className={`${dark ? 'text-[#d2a863]' : 'text-[#8a6728]'} mt-1 h-4 w-4 flex-none`} />{item}</div>)}</div></div></section>;
}
