import Link from 'next/link';
import { AlertTriangle, ArrowRight, CheckCircle2, FileText, Flag, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';
import { siteUrl } from '@/lib/routes';
import type { BosphorasProgrammaticSeoPage } from '@/data/bosphorasProgrammaticSeoPages';

type CountryRule = {
  country: Record<Locale, string>;
  entry: Record<Locale, string[]>;
  residence: Record<Locale, string[]>;
  warning: Record<Locale, string>;
};

const rules: Record<string, CountryRule> = {
  'british-citizens-turkey-visa': {
    country: { fr: 'ressortissant britannique / anglais', en: 'British citizen', ru: 'гражданин Великобритании', ar: 'مواطن بريطاني' },
    entry: {
      fr: ['Passeport britannique ordinaire : entrée sans visa jusqu’à 90 jours sur une période de 180 jours pour tourisme ou affaires courtes.', 'Les passeports British National Overseas, British Subject et British Protected Person ne suivent pas le régime du passeport britannique ordinaire et doivent passer par une mission diplomatique turque.', 'Un séjour sans visa ne permet pas de travailler en Turquie ni de rester au-delà de la durée autorisée.', 'Le passeport doit rester valable suffisamment longtemps après l’entrée ; la règle pratique turque exige généralement une validité dépassant la durée du séjour.'],
      en: ['Ordinary British passport holders may enter visa-free for up to 90 days within a 180-day period for tourism or short business visits.', 'British National Overseas, British Subject and British Protected Person passports do not follow the ordinary British passport regime and require application through a Turkish mission.', 'Visa-free stay does not allow work in Turkey or staying beyond the authorised period.', 'The passport must remain valid long enough after entry; Turkish practice generally requires validity beyond the stay period.'],
      ru: ['Обычный британский паспорт: въезд без визы до 90 дней в период 180 дней для туризма или коротких деловых поездок.', 'Паспорта British National Overseas, British Subject и British Protected Person не подпадают под режим обычного британского паспорта и требуют обращения в турецкую миссию.', 'Безвизовый въезд не дает права работать в Турции или оставаться дольше разрешенного срока.', 'Паспорт должен быть действителен достаточно долго после въезда; на практике Турция обычно требует срок действия сверх периода пребывания.'],
      ar: ['حاملو الجواز البريطاني العادي يمكنهم الدخول بدون تأشيرة حتى 90 يوماً ضمن فترة 180 يوماً للسياحة أو الزيارات التجارية القصيرة.', 'جوازات British National Overseas وBritish Subject وBritish Protected Person لا تتبع نظام الجواز البريطاني العادي وتتطلب طلباً عبر بعثة تركية.', 'الدخول بدون تأشيرة لا يسمح بالعمل في تركيا ولا بالبقاء بعد المدة المسموحة.', 'يجب أن يبقى الجواز صالحاً لمدة كافية بعد الدخول؛ الممارسة التركية تتطلب عادة صلاحية تتجاوز مدة الإقامة.'],
    },
    residence: {
      fr: ['Pour rester plus longtemps, un Britannique doit préparer un ikamet avant l’expiration des 90 jours.', 'Les dossiers les plus fréquents concernent propriétaires immobiliers, familles, retraités, entrepreneurs, investisseurs et long séjour à Istanbul, Bodrum ou Antalya.', 'Il faut anticiper adresse, assurance santé, justificatifs financiers, rendez-vous, traduction éventuelle de documents et renouvellement.', 'La résidence administrative ne remplace pas l’analyse fiscale : résidence réelle, centre des intérêts et revenus étrangers doivent être vérifiés séparément.'],
      en: ['To stay longer, a British citizen should prepare an ikamet before the 90 days expire.', 'Common cases include property owners, families, retirees, entrepreneurs, investors and long stays in Istanbul, Bodrum or Antalya.', 'Address, health insurance, financial evidence, appointment, possible document translation and renewal must be anticipated.', 'Administrative residence does not replace tax analysis: real residence, centre of interests and foreign income must be checked separately.'],
      ru: ['Чтобы остаться дольше, британцу нужно готовить ikamet до окончания 90 дней.', 'Частые случаи: владельцы недвижимости, семьи, пенсионеры, предприниматели, инвесторы и длительное пребывание в Istanbul, Bodrum или Antalya.', 'Нужно заранее подготовить адрес, страховку, финансовые подтверждения, запись, возможные переводы документов и продление.', 'Административная резиденция не заменяет налоговый анализ: реальное проживание, центр интересов и иностранные доходы нужно проверять отдельно.'],
      ar: ['للبقاء مدة أطول يجب على المواطن البريطاني تحضير الإيكامت قبل انتهاء 90 يوماً.', 'الحالات الشائعة: مالكو العقار، العائلات، المتقاعدون، رواد الأعمال، المستثمرون والإقامة الطويلة في Istanbul أو Bodrum أو Antalya.', 'يجب تجهيز العنوان، التأمين الصحي، الإثباتات المالية، الموعد، ترجمة الوثائق عند الحاجة والتجديد.', 'الإقامة الإدارية لا تعني التحليل الضريبي: يجب فحص الإقامة الحقيقية ومركز المصالح والدخل الأجنبي بشكل منفصل.'],
    },
    warning: {
      fr: 'Règle à confirmer avant départ sur source officielle, surtout si le passeport n’est pas un passeport britannique ordinaire.',
      en: 'Rule to confirm before travel from official sources, especially if the passport is not an ordinary British passport.',
      ru: 'Правило нужно подтвердить по официальным источникам перед поездкой, особенно если паспорт не ordinary British passport.',
      ar: 'يجب تأكيد القاعدة من المصادر الرسمية قبل السفر، خصوصاً إذا لم يكن الجواز بريطانياً عادياً.',
    },
  },
  'french-citizens-turkey-visa': {
    country: { fr: 'ressortissant français', en: 'French citizen', ru: 'гражданин Франции', ar: 'مواطن فرنسي' },
    entry: {
      fr: ['Les Français peuvent entrer en Turquie sans visa pour un court séjour touristique ou d’affaires, généralement jusqu’à 90 jours sur une période de 180 jours.', 'La France fait partie des pays pour lesquels l’entrée avec carte nationale d’identité peut être possible selon les conditions en vigueur.', 'Le passeport ou la carte d’identité doit être valide et adapté au voyage ; il faut éviter tout document expirant pendant le séjour.', 'Le séjour sans visa ne donne pas automatiquement le droit de travailler, de créer une présence permanente ou de devenir résident fiscal.'],
      en: ['French citizens can enter Turkey visa-free for short tourism or business stays, generally up to 90 days within a 180-day period.', 'France is among the countries for which entry with a national ID card may be possible under current conditions.', 'Passport or ID card must be valid and suitable for travel; documents expiring during the stay should be avoided.', 'Visa-free stay does not automatically allow work, permanent presence or tax residence.'],
      ru: ['Французы могут въезжать в Турцию без визы для короткого туризма или бизнеса, обычно до 90 дней в период 180 дней.', 'Франция входит в число стран, для которых возможен въезд по национальной ID-карте при действующих условиях.', 'Паспорт или ID-карта должны быть действительными и подходить для поездки; нельзя рисковать документом, истекающим во время пребывания.', 'Безвизовый режим не дает автоматически право работать, создавать постоянное присутствие или становиться налоговым резидентом.'],
      ar: ['يمكن للفرنسيين دخول تركيا بدون تأشيرة لإقامة سياحية أو تجارية قصيرة، عادة حتى 90 يوماً ضمن فترة 180 يوماً.', 'فرنسا من الدول التي قد تسمح لها تركيا بالدخول ببطاقة الهوية الوطنية وفق الشروط السارية.', 'يجب أن يكون جواز السفر أو بطاقة الهوية صالحاً ومناسباً للسفر؛ يجب تجنب وثيقة تنتهي أثناء الإقامة.', 'الدخول بدون تأشيرة لا يعطي تلقائياً حق العمل أو الوجود الدائم أو الإقامة الضريبية.'],
    },
    residence: {
      fr: ['Un Français qui souhaite rester plus longtemps doit préparer une demande d’ikamet avant la fin de la durée autorisée.', 'La stratégie dépend du projet : location, achat immobilier, famille, retraite, entreprise, revenus étrangers ou installation progressive.', 'Les documents doivent souvent inclure adresse en Turquie, assurance santé, justificatifs, photos, passeport ou carte d’identité selon le dossier.', 'La convention fiscale France-Turquie doit être analysée si le client conserve revenus, société, biens ou famille en France.'],
      en: ['A French citizen who wants to stay longer should prepare an ikamet before the authorised stay expires.', 'The strategy depends on the project: rental, property purchase, family, retirement, company, foreign income or gradual relocation.', 'Documents often include Turkish address, health insurance, evidence, photos, passport or ID depending on the file.', 'The France-Turkey tax treaty must be analysed if the client keeps income, company, assets or family ties in France.'],
      ru: ['Француз, который хочет остаться дольше, должен подготовить ikamet до окончания разрешенного срока.', 'Стратегия зависит от проекта: аренда, покупка недвижимости, семья, пенсия, компания, иностранные доходы или постепенный переезд.', 'Документы часто включают адрес в Турции, страховку, подтверждения, фото, паспорт или ID в зависимости от dossier.', 'Налоговое соглашение Франция-Турция нужно анализировать, если остаются доходы, компания, активы или семья во Франции.'],
      ar: ['الفرنسي الذي يريد البقاء مدة أطول يجب أن يحضر الإيكامت قبل نهاية المدة المسموحة.', 'الاستراتيجية تعتمد على المشروع: إيجار، شراء عقار، عائلة، تقاعد، شركة، دخل أجنبي أو انتقال تدريجي.', 'الوثائق غالباً تشمل عنواناً في تركيا، تأميناً صحياً، إثباتات، صوراً، جوازاً أو بطاقة هوية حسب الملف.', 'يجب تحليل الاتفاقية الضريبية بين فرنسا وتركيا إذا بقي للعميل دخل أو شركة أو أصول أو عائلة في فرنسا.'],
    },
    warning: { fr: 'Pour un Français, le vrai sujet n’est pas seulement l’entrée sans visa : c’est le passage propre vers l’ikamet et la résidence fiscale si le projet devient long terme.', en: 'For a French citizen, the real issue is not only visa-free entry: it is the clean transition to ikamet and tax residence if the project becomes long-term.', ru: 'Для француза главный вопрос не только безвизовый въезд: важно правильно перейти к ikamet и налоговой резиденции, если проект становится долгосрочным.', ar: 'بالنسبة للفرنسي، الموضوع ليس فقط الدخول بدون تأشيرة: المهم هو الانتقال الصحيح إلى الإيكامت والإقامة الضريبية إذا أصبح المشروع طويل الأجل.' },
  },
  'kazakh-citizens-turkey-visa': {
    country: { fr: 'ressortissant kazakh', en: 'Kazakh citizen', ru: 'гражданин Казахстана', ar: 'مواطن كازاخستاني' },
    entry: {
      fr: ['Les citoyens kazakhs peuvent généralement entrer en Turquie sans visa pour un court séjour, avec une limite connue de 90 jours sur 180 jours.', 'Le passeport reste le document principal pour l’entrée ; la carte d’identité kazakhe ne doit pas être supposée suffisante sans confirmation officielle.', 'Le séjour sans visa est adapté au tourisme, aux visites familiales, à la prospection immobilière ou business courte.', 'Pour travailler, étudier ou rester durablement, une procédure différente doit être préparée.'],
      en: ['Kazakh citizens can generally enter Turkey visa-free for a short stay, with a commonly used limit of 90 days within 180 days.', 'Passport remains the main entry document; a Kazakh ID card should not be assumed sufficient without official confirmation.', 'Visa-free stay is suitable for tourism, family visits, property search or short business visits.', 'For work, study or long-term stay, a different procedure must be prepared.'],
      ru: ['Граждане Казахстана обычно могут въезжать в Турцию без визы для короткого пребывания, с известным лимитом 90 дней в 180 дней.', 'Основной документ для въезда — паспорт; казахстанскую ID-карту нельзя считать достаточной без официального подтверждения.', 'Безвизовый въезд подходит для туризма, семейных поездок, поиска недвижимости или короткого business visit.', 'Для работы, учебы или долгого проживания нужна другая процедура.'],
      ar: ['يمكن لمواطني كازاخستان عادة دخول تركيا بدون تأشيرة لإقامة قصيرة، مع حد معروف 90 يوماً ضمن 180 يوماً.', 'يبقى جواز السفر الوثيقة الرئيسية للدخول؛ لا يجب اعتبار بطاقة الهوية الكازاخستانية كافية دون تأكيد رسمي.', 'الإقامة بدون تأشيرة مناسبة للسياحة، الزيارات العائلية، البحث عن عقار أو زيارة عمل قصيرة.', 'للعمل أو الدراسة أو الإقامة الطويلة يجب تحضير إجراء مختلف.'],
    },
    residence: {
      fr: ['Un Kazakh qui souhaite vivre en Turquie doit préparer un ikamet : adresse, assurance, documents, rendez-vous et justification du projet.', 'Les profils fréquents : famille, investisseur immobilier, entrepreneur, étudiant, retraité ou long séjour entre Kazakhstan et Turquie.', 'L’installation doit être coordonnée avec banque, assurance, logement, écoles éventuelles et preuve de présence.', 'Pour les revenus internationaux ou sociétés hors Turquie, il faut séparer résidence administrative et fiscalité.'],
      en: ['A Kazakh citizen planning to live in Turkey should prepare an ikamet: address, insurance, documents, appointment and project justification.', 'Common profiles: family, property investor, entrepreneur, student, retiree or long stay between Kazakhstan and Turkey.', 'Relocation should be coordinated with banking, insurance, housing, possible schools and proof of presence.', 'For international income or companies outside Turkey, administrative residence and tax matters must be separated.'],
      ru: ['Казахстанцу, который хочет жить в Турции, нужно готовить ikamet: адрес, страховка, документы, запись и обоснование проекта.', 'Частые профили: семья, инвестор в недвижимость, предприниматель, студент, пенсионер или длительное проживание между Казахстаном и Турцией.', 'Переезд нужно координировать с банком, страховкой, жильем, школами при необходимости и доказательствами присутствия.', 'Для международных доходов или компаний вне Турции нужно разделять административную резиденцию и налоги.'],
      ar: ['الكازاخستاني الذي يريد العيش في تركيا يجب أن يحضر الإيكامت: عنوان، تأمين، وثائق، موعد وتبرير المشروع.', 'الملفات الشائعة: عائلة، مستثمر عقاري، رائد أعمال، طالب، متقاعد أو إقامة طويلة بين كازاخستان وتركيا.', 'يجب تنسيق الانتقال مع البنك، التأمين، السكن، المدارس عند الحاجة وإثبات التواجد.', 'للدخل الدولي أو الشركات خارج تركيا يجب فصل الإقامة الإدارية عن الضرائب.'],
    },
    warning: { fr: 'Pour les Kazakhs, le sujet clé est souvent le passage du séjour sans visa vers un ikamet propre si la famille ou l’investissement s’installe.', en: 'For Kazakh citizens, the key issue is often moving from visa-free stay to a clean ikamet when family or investment becomes settled.', ru: 'Для граждан Казахстана ключевой вопрос часто — переход от безвизового пребывания к правильному ikamet, если семья или инвестиции закрепляются.', ar: 'بالنسبة للكازاخستانيين، المسألة الأساسية غالباً هي الانتقال من الإقامة بدون تأشيرة إلى إيكامت صحيح عندما تستقر العائلة أو الاستثمار.' },
  },
  'russian-citizens-turkey-visa': {
    country: { fr: 'ressortissant russe', en: 'Russian citizen', ru: 'гражданин России', ar: 'مواطن روسي' },
    entry: {
      fr: ['Les citoyens russes avec passeport ordinaire peuvent généralement entrer sans visa pour tourisme ou affaires courtes jusqu’à 60 jours par entrée.', 'La limite globale connue est de 90 jours sur une période de 180 jours, ce qui impose de compter les entrées et sorties.', 'Certains passeports officiels ou diplomatiques ont des règles différentes, par exemple 30 jours ou 90 jours selon le type.', 'Le dépassement de durée peut compliquer un futur ikamet ou une réentrée.'],
      en: ['Russian citizens with ordinary passports can generally enter visa-free for tourism or short business visits for up to 60 days per entry.', 'The commonly used overall limit is 90 days within a 180-day period, which requires tracking entries and exits.', 'Some official or diplomatic passports have different rules, for example 30 days or 90 days depending on passport type.', 'Overstaying can complicate future ikamet or re-entry.'],
      ru: ['Граждане России с обычным паспортом обычно могут въезжать без визы для туризма или коротких деловых поездок до 60 дней за въезд.', 'Общий известный лимит — 90 дней в период 180 дней, поэтому нужно считать въезды и выезды.', 'Для служебных или дипломатических паспортов могут действовать другие правила, например 30 или 90 дней в зависимости от типа.', 'Превышение срока может осложнить будущий ikamet или повторный въезд.'],
      ar: ['المواطنون الروس بجواز عادي يمكنهم عادة الدخول بدون تأشيرة للسياحة أو الزيارات التجارية القصيرة حتى 60 يوماً لكل دخول.', 'الحد الإجمالي المعروف هو 90 يوماً ضمن 180 يوماً، لذلك يجب احتساب الدخول والخروج.', 'بعض الجوازات الرسمية أو الدبلوماسية لها قواعد مختلفة مثل 30 أو 90 يوماً حسب النوع.', 'تجاوز المدة قد يعقد الإيكامت أو الدخول لاحقاً.'],
    },
    residence: {
      fr: ['Un Russe qui dépasse le séjour court doit préparer un ikamet avant expiration, surtout en cas de famille, location, achat immobilier ou activité business.', 'Les dossiers doivent être solides : adresse réelle, assurance, documents, justification financière, historique d’entrées et objectif du séjour.', 'Istanbul, Antalya et Bodrum attirent des profils russophones, mais les conditions administratives peuvent évoluer selon les périodes.', 'Pour banque, société, immobilier ou fiscalité, une coordination locale évite les erreurs de dossier.'],
      en: ['A Russian citizen staying beyond a short visit should prepare an ikamet before expiry, especially for family, rental, property purchase or business activity.', 'Files must be solid: real address, insurance, documents, financial evidence, entry history and purpose of stay.', 'Istanbul, Antalya and Bodrum attract Russian-speaking profiles, but administrative conditions may evolve over time.', 'For banking, company, property or tax, local coordination helps avoid file mistakes.'],
      ru: ['Россиянину, который остается дольше короткого срока, нужно готовить ikamet до истечения срока, особенно при семье, аренде, покупке недвижимости или business activity.', 'Dossier должен быть сильным: реальный адрес, страховка, документы, финансовое подтверждение, история въездов и цель пребывания.', 'Istanbul, Antalya и Bodrum привлекают русскоязычные профили, но административные условия могут меняться по периодам.', 'Для банка, компании, недвижимости или налогов локальная координация помогает избежать ошибок dossier.'],
      ar: ['الروسي الذي يريد البقاء بعد الزيارة القصيرة يجب أن يحضر الإيكامت قبل انتهاء المدة، خصوصاً للعائلة أو الإيجار أو شراء العقار أو النشاط التجاري.', 'يجب أن يكون الملف قوياً: عنوان حقيقي، تأمين، وثائق، إثبات مالي، تاريخ الدخول وسبب الإقامة.', 'Istanbul وAntalya وBodrum تجذب ملفات ناطقة بالروسية، لكن الشروط الإدارية قد تتغير حسب الفترة.', 'للبنك أو الشركة أو العقار أو الضرائب، التنسيق المحلي يساعد على تجنب أخطاء الملف.'],
    },
    warning: { fr: 'Pour les Russes, la différence 60 jours par entrée / 90 jours sur 180 jours doit être expliquée clairement et vérifiée avant toute stratégie de séjour.', en: 'For Russian citizens, the difference between 60 days per entry and 90 days within 180 days must be clearly explained and verified before any stay strategy.', ru: 'Для россиян нужно четко объяснить и проверить разницу между 60 днями за въезд и 90 днями в 180 дней перед любой стратегией пребывания.', ar: 'بالنسبة للروس، يجب شرح والتحقق من الفرق بين 60 يوماً لكل دخول و90 يوماً ضمن 180 يوماً قبل أي استراتيجية إقامة.' },
  },
  'american-citizens-turkey-visa': {
    country: { fr: 'ressortissant américain', en: 'US citizen', ru: 'гражданин США', ar: 'مواطن أمريكي' },
    entry: {
      fr: ['Les Américains avec passeport ordinaire peuvent généralement entrer sans visa jusqu’à 90 jours sur une période de 180 jours pour tourisme ou affaires courtes.', 'Les passeports officiels ou de service peuvent être soumis à visa, contrairement au passeport ordinaire.', 'Le séjour sans visa ne permet pas de travailler, d’étudier ou de rester durablement sans procédure adaptée.', 'Le passeport doit être valide et l’objet du voyage doit rester cohérent avec le statut d’entrée.'],
      en: ['US citizens with ordinary passports can generally enter visa-free for up to 90 days within a 180-day period for tourism or short business visits.', 'Official or service passports may require a visa, unlike ordinary passports.', 'Visa-free stay does not allow work, study or long-term stay without the appropriate procedure.', 'The passport must be valid and the purpose of travel must remain consistent with the entry status.'],
      ru: ['Граждане США с обычным паспортом обычно могут въезжать без визы до 90 дней в период 180 дней для туризма или коротких business visits.', 'Official/service passports могут требовать визу, в отличие от обычного паспорта.', 'Безвизовый режим не дает право работать, учиться или оставаться длительно без подходящей процедуры.', 'Паспорт должен быть действителен, а цель поездки должна соответствовать статусу въезда.'],
      ar: ['الأمريكيون بجواز عادي يمكنهم عادة دخول تركيا بدون تأشيرة حتى 90 يوماً ضمن 180 يوماً للسياحة أو الأعمال القصيرة.', 'الجوازات الرسمية أو الخدمة قد تحتاج إلى تأشيرة، على عكس الجواز العادي.', 'الدخول بدون تأشيرة لا يسمح بالعمل أو الدراسة أو الإقامة الطويلة دون إجراء مناسب.', 'يجب أن يكون الجواز صالحاً وأن يكون سبب السفر متوافقاً مع نوع الدخول.'],
    },
    residence: {
      fr: ['Un Américain qui souhaite rester en Turquie doit préparer un ikamet avant la fin des 90 jours.', 'Les profils fréquents : achat immobilier, startup, retraite, famille, investissement, base entre États-Unis, Europe, Dubaï et Turquie.', 'Le dossier doit intégrer assurance, adresse, documents financiers et plan de présence réelle.', 'Les revenus américains et obligations fiscales US doivent être traités avec prudence : la résidence turque ne supprime pas automatiquement les obligations américaines.'],
      en: ['A US citizen planning to stay in Turkey should prepare an ikamet before the 90 days expire.', 'Common profiles: property purchase, startup, retirement, family, investment, base between the US, Europe, Dubai and Turkey.', 'The file should include insurance, address, financial documents and real presence planning.', 'US income and US tax obligations require caution: Turkish residence does not automatically remove US obligations.'],
      ru: ['Американцу, который хочет остаться в Турции, нужно готовить ikamet до окончания 90 дней.', 'Частые профили: недвижимость, startup, пенсия, семья, инвестиции, база между США, Европой, Dubai и Турцией.', 'Dossier должен включать страховку, адрес, финансовые документы и план реального присутствия.', 'Доходы и налоговые обязательства США требуют осторожности: турецкая резиденция не отменяет автоматически обязательства США.'],
      ar: ['الأمريكي الذي يريد البقاء في تركيا يجب أن يحضر الإيكامت قبل انتهاء 90 يوماً.', 'الملفات الشائعة: شراء عقار، startup، تقاعد، عائلة، استثمار، قاعدة بين الولايات المتحدة وأوروبا ودبي وتركيا.', 'يجب أن يشمل الملف التأمين والعنوان والوثائق المالية وخطة التواجد الحقيقي.', 'الدخل والالتزامات الضريبية الأمريكية تحتاج حذراً: الإقامة التركية لا تلغي تلقائياً الالتزامات الأمريكية.'],
    },
    warning: { fr: 'Pour un Américain, l’analyse doit inclure les obligations fiscales américaines en parallèle de la résidence turque.', en: 'For a US citizen, the analysis must include US tax obligations alongside Turkish residence.', ru: 'Для гражданина США анализ должен включать налоговые обязательства США параллельно с турецкой резиденцией.', ar: 'بالنسبة للمواطن الأمريكي، يجب أن يشمل التحليل الالتزامات الضريبية الأمريكية إلى جانب الإقامة التركية.' },
  },
  'canadian-citizens-turkey-visa': {
    country: { fr: 'ressortissant canadien', en: 'Canadian citizen', ru: 'гражданин Канады', ar: 'مواطن كندي' },
    entry: {
      fr: ['Les Canadiens avec passeport ordinaire peuvent généralement entrer sans visa jusqu’à 90 jours sur une période de 180 jours.', 'Les passeports officiels peuvent relever de règles différentes et doivent être vérifiés avant départ.', 'Le court séjour convient au tourisme, aux rendez-vous immobiliers, aux visites familiales ou business courtes.', 'Pour travailler, étudier ou s’installer, il faut préparer une procédure adaptée.'],
      en: ['Canadian citizens with ordinary passports can generally enter visa-free for up to 90 days within a 180-day period.', 'Official passports may follow different rules and should be checked before travel.', 'Short stay is suitable for tourism, property appointments, family visits or short business visits.', 'For work, study or relocation, an appropriate procedure must be prepared.'],
      ru: ['Канадцы с обычным паспортом обычно могут въезжать без визы до 90 дней в период 180 дней.', 'Официальные паспорта могут подпадать под другие правила и должны быть проверены до поездки.', 'Короткий stay подходит для туризма, встреч по недвижимости, семейных визитов или коротких деловых поездок.', 'Для работы, учебы или переезда нужна соответствующая процедура.'],
      ar: ['الكنديون بجواز عادي يمكنهم عادة الدخول بدون تأشيرة حتى 90 يوماً ضمن 180 يوماً.', 'الجوازات الرسمية قد تخضع لقواعد مختلفة ويجب التحقق منها قبل السفر.', 'الإقامة القصيرة مناسبة للسياحة أو مواعيد العقار أو الزيارات العائلية أو الأعمال القصيرة.', 'للعمل أو الدراسة أو الانتقال يجب تحضير إجراء مناسب.'],
    },
    residence: {
      fr: ['Un Canadien qui veut vivre plus longtemps en Turquie doit préparer un ikamet avant la fin des 90 jours.', 'Les dossiers fréquents : famille, retraite, investissement immobilier, entrepreneur, résidence entre Canada et Turquie.', 'Il faut préparer adresse, assurance, justificatifs financiers, rendez-vous et documents familiaux si applicable.', 'La fiscalité canadienne et la résidence turque doivent être analysées séparément avant un changement de vie.'],
      en: ['A Canadian citizen planning to live longer in Turkey should prepare an ikamet before the 90 days expire.', 'Common cases: family, retirement, property investment, entrepreneur, residence between Canada and Turkey.', 'Address, insurance, financial proof, appointment and family documents if applicable must be prepared.', 'Canadian tax matters and Turkish residence should be analysed separately before a life change.'],
      ru: ['Канадцу, который хочет жить дольше в Турции, нужно готовить ikamet до окончания 90 дней.', 'Частые случаи: семья, пенсия, недвижимость, предпринимательство, проживание между Канадой и Турцией.', 'Нужно подготовить адрес, страховку, финансовые подтверждения, запись и семейные документы при необходимости.', 'Канадские налоги и турецкую резиденцию нужно анализировать отдельно до изменения жизни.'],
      ar: ['الكندي الذي يريد العيش مدة أطول في تركيا يجب أن يحضر الإيكامت قبل انتهاء 90 يوماً.', 'الحالات الشائعة: العائلة، التقاعد، الاستثمار العقاري، رائد أعمال، إقامة بين كندا وتركيا.', 'يجب تحضير العنوان، التأمين، الإثبات المالي، الموعد والوثائق العائلية عند الحاجة.', 'يجب تحليل الضرائب الكندية والإقامة التركية بشكل منفصل قبل تغيير نمط الحياة.'],
    },
    warning: { fr: 'Pour un Canadien, le sujet important est de distinguer court séjour sans visa, résidence administrative et résidence fiscale réelle.', en: 'For a Canadian citizen, the key point is distinguishing visa-free short stay, administrative residence and real tax residence.', ru: 'Для канадца важно отличать краткий безвизовый stay, административную резиденцию и реальную налоговую резиденцию.', ar: 'بالنسبة للكندي، النقطة الأساسية هي التمييز بين الإقامة القصيرة بدون تأشيرة، الإقامة الإدارية والإقامة الضريبية الحقيقية.' },
  },
};

const labels: Record<Locale, Record<string, string>> = {
  fr: { guide: 'Guide pays par pays', updated: 'Mis à jour le 5 juin 2026', entry: 'Règles d’entrée pour cette nationalité', residence: 'Résidence, ikamet et installation', documents: 'Documents à préparer', warning: 'Point de vigilance', faq: 'Questions fréquentes', cta: 'Vérifier mon cas' },
  en: { guide: 'Country-specific guide', updated: 'Updated on June 5, 2026', entry: 'Entry rules for this nationality', residence: 'Residence, ikamet and relocation', documents: 'Documents to prepare', warning: 'Important point', faq: 'FAQ', cta: 'Check my case' },
  ru: { guide: 'Гид по стране', updated: 'Обновлено 5 июня 2026', entry: 'Правила въезда для этого гражданства', residence: 'ВНЖ, ikamet и переезд', documents: 'Документы для подготовки', warning: 'Важный момент', faq: 'Частые вопросы', cta: 'Проверить мой случай' },
  ar: { guide: 'دليل حسب الجنسية', updated: 'تم التحديث في 5 يونيو 2026', entry: 'قواعد الدخول لهذه الجنسية', residence: 'الإقامة والإيكامت والانتقال', documents: 'الوثائق المطلوبة', warning: 'نقطة مهمة', faq: 'الأسئلة الشائعة', cta: 'فحص حالتي' },
};

function assessmentHref(locale: Locale) {
  return locale === 'fr' ? '/diagnostic-prive' : locale === 'en' ? '/en/private-assessment' : locale === 'ru' ? '/ru/chastnaya-konsultatsiya' : '/ar/تقييم-خاص';
}

function baseUrl(page: BosphorasProgrammaticSeoPage, locale: Locale) {
  return `${siteUrl}${page.slugs[locale]}`;
}

function defaultRule(page: BosphorasProgrammaticSeoPage): CountryRule {
  return {
    country: { fr: page.titles.fr, en: page.titles.en, ru: page.titles.ru, ar: page.titles.ar },
    entry: {
      fr: ['Les règles doivent être vérifiées selon la nationalité exacte, le type de passeport et le motif du voyage.', 'La durée de séjour peut varier selon le pays : 30, 60 ou 90 jours, souvent dans une période de 180 jours.', 'Certaines nationalités peuvent utiliser e-Visa, d’autres sont exemptées, d’autres doivent passer par une mission turque.'],
      en: ['Rules must be checked according to exact nationality, passport type and travel purpose.', 'Stay duration may vary by country: 30, 60 or 90 days, often within a 180-day period.', 'Some nationalities can use e-Visa, some are exempt, others must apply through a Turkish mission.'],
      ru: ['Правила нужно проверять по точному гражданству, типу паспорта и цели поездки.', 'Срок пребывания может зависеть от страны: 30, 60 или 90 дней, часто в период 180 дней.', 'Некоторые гражданства могут использовать e-Visa, некоторые освобождены, другие должны обращаться в турецкую миссию.'],
      ar: ['يجب فحص القواعد حسب الجنسية الدقيقة ونوع الجواز وسبب السفر.', 'مدة الإقامة قد تختلف حسب الدولة: 30 أو 60 أو 90 يوماً، غالباً ضمن فترة 180 يوماً.', 'بعض الجنسيات يمكنها استخدام e-Visa، وبعضها معفى، وبعضها يجب أن يقدم عبر بعثة تركية.'],
    },
    residence: {
      fr: ['Pour rester plus longtemps, il faut préparer un ikamet avant l’expiration de la durée autorisée.', 'L’adresse, l’assurance santé, les documents, le rendez-vous et les justificatifs doivent être préparés correctement.'],
      en: ['To stay longer, an ikamet should be prepared before the authorised period expires.', 'Address, health insurance, documents, appointment and evidence must be prepared correctly.'],
      ru: ['Чтобы остаться дольше, ikamet нужно готовить до окончания разрешенного срока.', 'Адрес, страховка, документы, запись и подтверждения должны быть подготовлены правильно.'],
      ar: ['للبقاء مدة أطول يجب تحضير الإيكامت قبل انتهاء المدة المسموحة.', 'يجب تجهيز العنوان والتأمين والوثائق والموعد والإثباتات بشكل صحيح.'],
    },
    warning: { fr: 'Bosphoras vérifie chaque nationalité sur source officielle avant de construire une stratégie de séjour ou résidence.', en: 'Bosphoras checks each nationality on official sources before building a stay or residence strategy.', ru: 'Bosphoras проверяет каждое гражданство по официальным источникам перед стратегией пребывания или ВНЖ.', ar: 'يتحقق Bosphoras من كل جنسية عبر مصادر رسمية قبل بناء استراتيجية إقامة.' },
  };
}

function documents(locale: Locale) {
  if (locale === 'fr') return ['passeport ordinaire ou document officiel adapté','carte nationale d’identité si accord applicable','preuve de durée de séjour restante','adresse en Turquie pour l’ikamet','assurance santé compatible','photos biométriques','justificatifs financiers si demandés','documents familiaux traduits/apostillés si nécessaire','historique des entrées/sorties','vérification officielle avant départ'];
  if (locale === 'en') return ['ordinary passport or suitable official document','national ID card if an agreement applies','proof of remaining authorised stay','address in Turkey for ikamet','compatible health insurance','biometric photos','financial evidence if requested','family documents translated/apostilled if needed','entry/exit history','official verification before travel'];
  if (locale === 'ru') return ['обычный паспорт или подходящий официальный документ','ID-карта, если действует соглашение','остаток разрешенного срока пребывания','адрес в Турции для ikamet','подходящая медицинская страховка','биометрические фото','финансовые подтверждения при необходимости','семейные документы с переводом/апостилем при необходимости','история въездов/выездов','официальная проверка перед поездкой'];
  return ['جواز عادي أو وثيقة رسمية مناسبة','بطاقة هوية إذا كان الاتفاق ينطبق','إثبات المدة المتبقية من الإقامة المسموحة','عنوان في تركيا للإيكامت','تأمين صحي مناسب','صور بيومترية','إثبات مالي عند الطلب','وثائق عائلية مترجمة/مصدقة عند الحاجة','تاريخ الدخول والخروج','تحقق رسمي قبل السفر'];
}

function faq(page: BosphorasProgrammaticSeoPage, rule: CountryRule, locale: Locale): Array<[string, string]> {
  if (locale === 'fr') return [[`Un ${rule.country.fr} peut-il entrer en Turquie sans visa ?`, rule.entry.fr[0]], ['Peut-il rester plus longtemps ?', 'Oui, mais il doit préparer une demande de résidence / ikamet avant l’expiration de la durée autorisée.'], ['Peut-il travailler avec une entrée sans visa ?', 'Non. Le travail, les études ou une installation durable demandent une procédure adaptée.'], ['Bosphoras vérifie quoi ?', 'Nationalité, type de passeport, durée restante, motif du séjour, documents, adresse, assurance, banque, fiscalité et stratégie d’installation.']];
  if (locale === 'en') return [[`Can a ${rule.country.en} enter Turkey visa-free?`, rule.entry.en[0]], ['Can they stay longer?', 'Yes, but a residence permit / ikamet file should be prepared before the authorised stay expires.'], ['Can they work with visa-free entry?', 'No. Work, study or long-term relocation require the appropriate procedure.'], ['What does Bosphoras check?', 'Nationality, passport type, remaining days, travel purpose, documents, address, insurance, banking, tax and relocation strategy.']];
  if (locale === 'ru') return [[`Может ли ${rule.country.ru} въехать в Турцию без визы?`, rule.entry.ru[0]], ['Можно ли остаться дольше?', 'Да, но ВНЖ / ikamet нужно готовить до окончания разрешенного срока.'], ['Можно ли работать по безвизовому въезду?', 'Нет. Работа, учеба или долгий переезд требуют подходящую процедуру.'], ['Что проверяет Bosphoras?', 'Гражданство, тип паспорта, оставшиеся дни, цель поездки, документы, адрес, страховка, банк, налоги и стратегия переезда.']];
  return [[`هل يمكن لـ ${rule.country.ar} دخول تركيا بدون تأشيرة؟`, rule.entry.ar[0]], ['هل يمكنه البقاء مدة أطول؟', 'نعم، لكن يجب تحضير ملف الإقامة / الإيكامت قبل انتهاء المدة المسموحة.'], ['هل يمكنه العمل بدخول بدون تأشيرة؟', 'لا. العمل أو الدراسة أو الانتقال الطويل يحتاج إجراء مناسباً.'], ['ماذا يفحص Bosphoras؟', 'الجنسية، نوع الجواز، الأيام المتبقية، سبب السفر، الوثائق، العنوان، التأمين، البنك، الضرائب واستراتيجية الانتقال.']];
}

export function BosphorasCountryVisaSeoPage({ page, locale }: { page: BosphorasProgrammaticSeoPage; locale: Locale }) {
  const rule = rules[page.key] ?? defaultRule(page);
  const l = labels[locale];
  const pageFaq = faq(page, rule, locale);
  const canonical = baseUrl(page, locale);
  const description = `${page.titles[locale]} — ${rule.entry[locale][0]} ${rule.warning[locale]}`.slice(0, 300);
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: page.titles[locale], description, inLanguage: locale, datePublished: '2026-06-05', dateModified: '2026-06-05', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: canonical, keywords: page.focus.join(', ') }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: pageFaq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={page.slugs[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{l.guide} · {l.updated}</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">{page.titles[locale]}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{description}</p><Link href={assessmentHref(locale)} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{l.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1200px]"><Flag className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{l.entry}</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{rule.entry[locale].map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div></div></section>
        <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto max-w-[1200px]"><ShieldCheck className="h-8 w-8 text-[#d2a863]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{l.residence}</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{rule.residence[locale].map((item) => <div key={item} className="border border-white/15 bg-white/5 p-5 text-sm leading-7 text-white/75">{item}</div>)}</div></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1200px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{l.documents}</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{documents(locale).map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div><div className="mt-8 border-l-4 border-[#8a6728] bg-white p-7"><AlertTriangle className="h-8 w-8 text-[#8a6728]" /><h3 className="mt-4 font-serif text-2xl">{l.warning}</h3><p className="mt-4 leading-8 text-[#3e4857]">{rule.warning[locale]}</p></div></div></section>
        <section className="px-5 pb-20 md:px-8 md:pb-28"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">{l.faq}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{pageFaq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
