import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/digital-nomad-turquie-fiscalite-revenus-etrangers',
  en: '/en/digital-nomad-turkey-tax-foreign-income',
  ru: '/ru/digital-nomad-turtsiya-nalogi-inostrannye-dohody',
  ar: '/ar/digital-nomad-turkey-tax-foreign-income',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = { title:string; metaTitle:string; description:string; eyebrow:string; hero:string; cta:string; asideTitle:string; finalTitle:string; finalText:string; faqTitle:string; checklist:string[]; sections:Array<[string,string]>; faq:Array<[string,string]> };

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Digital nomad en Turquie : fiscalité, revenus étrangers et résidence fiscale',
    metaTitle: 'Digital nomad en Turquie : fiscalité et revenus étrangers',
    description: 'Digital nomad en Turquie : résidence fiscale, revenus étrangers, télétravail, freelance, société étrangère, banque, visa, famille et exonération fiscale potentielle pour nouveaux résidents.',
    eyebrow: 'Digital nomad · Revenus étrangers · Turquie',
    hero: 'Vivre en Turquie tout en travaillant à distance peut être une option attractive. Mais pour un digital nomad, un freelance, un consultant ou un entrepreneur en ligne, la vraie question est de savoir comment seront traités les revenus, la société, la résidence fiscale, les comptes bancaires et l’installation réelle en Turquie.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant de vous installer en Turquie',
    finalTitle: 'Votre activité à distance doit être cohérente avec votre résidence réelle',
    finalText: 'Avant de vous installer, de transférer vos revenus ou de structurer votre société, Bosphoras peut organiser une analyse privée de votre situation : fiscalité, revenus étrangers, société, banque, assurance, résidence, logement, famille et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Votre résidence fiscale réelle', 'Le lieu où vous travaillez physiquement', 'La nature de vos revenus étrangers', 'Votre société étrangère éventuelle', 'Vos contrats, factures et comptes bancaires', 'Votre visa ou titre de séjour', 'Votre assurance santé et logement', 'La cohérence avec votre pays d’origine'],
    sections: [
      ['Pourquoi un digital nomad doit préparer son installation fiscale', 'Le digital nomad pense souvent que ses revenus sont étrangers parce que ses clients sont à l’étranger ou parce que l’argent arrive sur un compte bancaire hors de Turquie. Mais la fiscalité ne dépend pas uniquement du pays du client ou de la banque. Il faut analyser où vous vivez réellement, où vous travaillez physiquement, où se trouvent vos clients, où votre société est enregistrée, où les contrats sont signés, où les factures sont émises, où les paiements sont reçus et où se trouve votre résidence fiscale.'],
      ['Résidence fiscale en Turquie : le point de départ', 'Avant de savoir si vos revenus étrangers peuvent bénéficier d’un traitement favorable, il faut déterminer si vous devenez résident fiscal en Turquie. La résidence fiscale ne se résume pas à un logement, un visa, une carte de résidence ou un compte bancaire turc. Elle dépend du temps passé en Turquie, de votre lieu de vie principal, de votre foyer, de votre famille, de votre activité, de vos revenus, de vos comptes bancaires et de votre centre d’intérêts économiques.'],
      ['Revenus étrangers : attention à la définition', 'Pour un digital nomad, les revenus peuvent venir de plusieurs sources : consulting, freelance, développement web, marketing digital, e-commerce, formation en ligne, coaching, affiliation, création de contenu, revenus YouTube, SaaS, agence digitale, dividendes d’une société étrangère ou salaire d’un employeur étranger. Ces revenus ne doivent pas être mis dans la même catégorie. Un salaire, une facture freelance, un dividende, une plus-value ou un revenu publicitaire peuvent être traités différemment.'],
      ['Ce que la nouvelle exonération turque pourrait changer', 'Si la Turquie confirme un régime favorable pour certains nouveaux résidents, certains digital nomads pourraient s’y intéresser. Le régime annoncé pourrait concerner certains revenus et gains de source étrangère, sous conditions. Mais il faut vérifier le texte final, la nature exacte des revenus, le pays des clients, le pays de la société, le lieu où le travail est réalisé, la résidence fiscale réelle, la date d’installation en Turquie et l’existence d’une activité de source turque.'],
      ['Freelance ou consultant avec clients étrangers', 'Un consultant ou freelance peut travailler depuis la Turquie pour des clients situés en France, au Royaume-Uni, aux États-Unis, en Allemagne, aux Émirats, au Kazakhstan ou ailleurs. Il faut analyser où le travail est physiquement réalisé, où se trouvent les clients, où les contrats sont signés, quelle entité facture, où se trouve le compte bancaire, où les revenus sont déclarés, si une société étrangère existe et si une société turque doit être envisagée.'],
      ['Société étrangère et activité depuis la Turquie', 'Beaucoup de digital nomads utilisent une société étrangère : société française, LTD britannique, LLC américaine, société aux Émirats, à Hong Kong, à Singapour, en Estonie, au Kazakhstan ou holding personnelle. Le risque principal est la direction effective. Si vous vivez en Turquie, travaillez depuis la Turquie, gérez les clients depuis la Turquie et prenez toutes les décisions depuis la Turquie, il faut analyser si la société étrangère reste réellement étrangère dans son fonctionnement.'],
      ['Salarié à distance pour une société étrangère', 'Certains digital nomads travaillent à distance comme salariés ou dirigeants pour une société étrangère. Il faut vérifier le contrat de travail, le pays de l’employeur, le lieu réel d’exécution du travail, les cotisations sociales, l’assurance santé, la durée de présence en Turquie, les obligations de l’employeur et les règles de résidence fiscale. Un employeur étranger peut ne pas vouloir créer d’obligations en Turquie.'],
      ['E-commerce, SaaS et revenus en ligne', 'Les revenus en ligne doivent aussi être analysés avec précision : produits physiques, produits digitaux, abonnements SaaS, formations en ligne, services marketing, applications, publicité, affiliation ou contenu premium. Pour chaque modèle, il faut vérifier où se trouve la société, où sont les clients, où la valeur est créée, où les décisions sont prises, où les paiements arrivent et quel pays impose les bénéfices.'],
      ['Banque, paiements et conformité', 'Un digital nomad peut recevoir de l’argent via compte bancaire étranger, compte bancaire turc, Stripe, Wise, Payoneer, plateformes freelance, crypto-actifs, revenus publicitaires ou marketplaces. Les banques turques peuvent demander contrats clients, factures, déclarations fiscales, statuts de société, preuve d’origine des fonds, relevés bancaires, justificatifs de paiement, certificat de résidence fiscale et explication de l’activité.'],
      ['Visa, résidence et installation réelle', 'Vivre en Turquie en tant que digital nomad ne se résume pas à louer un appartement. Il faut organiser le titre de séjour, l’adresse réelle, l’assurance santé, le compte bancaire, les preuves de résidence, les contrats de location, la vie familiale, un coworking ou bureau éventuel, les déplacements internationaux et le calendrier de présence. Une résidence fiscale doit correspondre à une vie réelle.'],
      ['Famille, conjoint et enfants', 'Un digital nomad peut venir seul, mais certains profils viennent avec conjoint et enfants. Il faut anticiper école, assurance santé familiale, logement adapté, quartier de vie, sécurité, transport, médecins, activités des enfants et vie entre plusieurs pays. Si vous dites vivre en Turquie mais que votre famille, votre logement principal et votre vie quotidienne restent ailleurs, votre résidence fiscale peut être contestée dans un autre pays.'],
      ['Pays d’origine : éviter les mauvaises surprises', 'Quitter son pays ne signifie pas automatiquement quitter sa fiscalité. Votre pays d’origine peut continuer à vous considérer résident fiscal si vous y gardez votre foyer, votre famille, une société dirigée depuis ce pays, vos principaux revenus, beaucoup de temps de présence ou vos intérêts économiques. Avant de vous installer en Turquie, il faut coordonner la sortie du pays d’origine avec l’entrée réelle en Turquie.'],
      ['Les erreurs à éviter', 'La première erreur est de penser que client étranger veut automatiquement dire revenu étranger exonéré. La deuxième est de vivre en Turquie tout en conservant une société étrangère sans analyse. La troisième est de négliger la banque et l’origine des fonds. La quatrième est d’ignorer les obligations du pays d’origine. La cinquième est de confondre visa, résidence administrative et résidence fiscale.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste ou un expert-comptable. Notre rôle est de coordonner votre installation en Turquie et de vous aider à poser les bonnes questions avant de structurer votre activité : résidence fiscale, revenus en ligne, société étrangère, fiscalistes turcs et étrangers, banque, assurance santé, logement, installation familiale, immobilier, avocats, comptables et partenaires locaux.'],
    ],
    faq: [['Un digital nomad peut-il devenir résident fiscal en Turquie ?', 'Oui, selon sa situation réelle : temps passé en Turquie, lieu de vie principal, revenus, famille, activité, comptes bancaires et centre d’intérêts économiques.'], ['Mes revenus sont-ils étrangers si mes clients sont à l’étranger ?', 'Pas automatiquement. Il faut analyser où le travail est réalisé, quelle entité facture, où la société est dirigée, où les revenus sont déclarés et quelle résidence fiscale s’applique.'], ['Une société étrangère suffit-elle à éviter la fiscalité turque ?', 'Non. Si la société est réellement pilotée depuis la Turquie, il faut analyser le risque de direction effective et les conséquences fiscales.'], ['Un salarié à distance peut-il vivre en Turquie ?', 'Oui, mais il faut vérifier le contrat de travail, le pays de l’employeur, les cotisations sociales, l’assurance santé, la durée de présence et les obligations potentielles.'], ['La nouvelle exonération turque peut-elle concerner les digital nomads ?', 'Potentiellement, selon le texte final, la nature des revenus, la source des revenus et les conditions d’éligibilité. Chaque situation doit être analysée.'], ['Bosphoras donne-t-il un conseil fiscal ?', 'Non. Bosphoras coordonne l’analyse privée et les bons interlocuteurs : fiscalistes, avocats, comptables, banques, assurance, immobilier et partenaires d’installation en Turquie.']],
  },
  en: {
    title: 'Digital Nomad in Turkey: tax residence, foreign income and remote work',
    metaTitle: 'Digital Nomad Turkey: Tax and Foreign Income Guide',
    description: 'Digital nomad in Turkey: tax residence, foreign income, remote work, freelancing, foreign company, banking, residence permit, family and potential tax exemption.',
    eyebrow: 'Digital nomad · Foreign income · Turkey',
    hero: 'Living in Turkey while working remotely can be attractive. But for a digital nomad, freelancer, consultant or online entrepreneur, the key issue is how income, company structure, tax residence, banking and real relocation will be treated.',
    cta: 'Request a private assessment',
    asideTitle: 'Before moving to Turkey',
    finalTitle: 'Remote work must be consistent with your real residence',
    finalText: 'Before relocating, transferring income or structuring a company, Bosphoras can organize a private review of your situation: tax, foreign income, company, banking, insurance, residence, housing, family and relocation to Turkey.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Your real tax residence', 'Where you physically work', 'Nature of foreign income', 'Any foreign company structure', 'Contracts, invoices and bank accounts', 'Residence permit or visa position', 'Health insurance and housing', 'Consistency with your former country'],
    sections: [
      ['Why digital nomads should prepare tax residence before moving', 'Digital nomads often assume income is foreign because clients are abroad or payments arrive in a foreign bank account. Tax analysis is not based only on client location or bank location. You should review where you live, where you physically work, where clients are located, where your company is registered, where contracts are signed, where invoices are issued, where payments are received and where your tax residence is located.'],
      ['Tax residence in Turkey: the starting point', 'Before considering favorable treatment for foreign income, you must determine whether you become Turkish tax resident. Tax residence is not just a residence permit, apartment or Turkish bank account. It depends on time spent in Turkey, main home, family, activity, income, bank accounts and center of economic interests.'],
      ['Foreign income: the definition matters', 'Digital nomad income may include consulting, freelance work, web development, digital marketing, e-commerce, online courses, coaching, affiliate income, content creation, YouTube revenue, SaaS, agency revenue, dividends from a foreign company or salary from a foreign employer. These categories should not be treated as one single type of income.'],
      ['What the Turkish exemption could change', 'If Turkey confirms a favorable regime for certain new residents, some digital nomads may be interested. The announced regime may cover certain foreign-source income and gains, subject to conditions. But the final text, income type, client country, company country, place of work, real tax residence, relocation date and any Turkish-source activity must be reviewed.'],
      ['Freelancers and consultants with foreign clients', 'A consultant or freelancer may work from Turkey for clients in the UK, US, Germany, UAE, Kazakhstan, France or elsewhere. You should review where the work is physically performed, where clients are located, where contracts are signed, which entity invoices, where the bank account is located, where income is reported, whether a foreign company exists and whether a Turkish structure should be considered.'],
      ['Foreign company and activity from Turkey', 'Many digital nomads use foreign companies such as a UK LTD, US LLC, UAE company, Hong Kong company, Singapore company, Estonian company, Kazakh company or personal holding. The main issue is effective management. If you live, work, manage clients and make decisions from Turkey, the foreign company structure should be reviewed carefully.'],
      ['Remote employee for a foreign company', 'Some digital nomads work remotely as employees or executives for a foreign employer. Employment contract, employer country, actual work location, social security, health insurance, time spent in Turkey, employer obligations and tax residence rules should be checked before relocating.'],
      ['E-commerce, SaaS and online revenue', 'Online revenue can include physical products, digital products, SaaS subscriptions, online courses, marketing services, apps, advertising, affiliate income or premium content. For each model, you should review where the company is located, where clients are, where value is created, where decisions are made, where payments arrive and which country taxes the profits.'],
      ['Banking, payments and compliance', 'A digital nomad may receive money through foreign bank accounts, Turkish bank accounts, Stripe, Wise, Payoneer, freelance platforms, crypto-assets, ad networks or marketplaces. Turkish banks may ask for client contracts, invoices, tax filings, company documents, source-of-funds evidence, bank statements, payment proofs, tax residence certificates and an explanation of the activity.'],
      ['Visa, residence and real life in Turkey', 'Living in Turkey as a digital nomad is not only about renting an apartment. Residence permit, real address, health insurance, bank account, residence evidence, rental contracts, family life, coworking or office, international travel and presence calendar should be organized. Tax residence should match real life.'],
      ['Family, spouse and children', 'Some digital nomads relocate with a spouse and children. School, family health insurance, housing, neighborhood, safety, transport, doctors, children’s activities and life between several countries should be anticipated. If your family and main home remain elsewhere, your residence position may be challenged in another country.'],
      ['Former country: avoid surprises', 'Leaving a country does not automatically end its tax interest in you. Your former country may still consider you resident if home, family, company management, main income, time spent or economic interests remain there. Departure from the former country and real entry into Turkey should be coordinated.'],
      ['Mistakes to avoid', 'Do not assume foreign clients automatically mean exempt foreign income. Do not live in Turkey with a foreign company without analysis. Do not ignore banking and source of funds. Do not ignore obligations in your former country. Do not confuse visa, administrative residence and tax residence.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers or accountants. Its role is to coordinate your relocation to Turkey and help prepare the right questions before structuring your activity: tax residence, online income, foreign company, Turkish and foreign tax advisors, banking, health insurance, housing, family relocation, real estate, lawyers, accountants and local partners.'],
    ],
    faq: [['Can a digital nomad become tax resident in Turkey?', 'Yes, depending on real life: time spent in Turkey, main home, income, family, activity, bank accounts and center of economic interests.'], ['Is my income foreign if my clients are abroad?', 'Not automatically. You must review where the work is performed, which entity invoices, where the company is managed, where income is reported and which tax residence applies.'], ['Is a foreign company enough to avoid Turkish tax?', 'No. If the company is effectively managed from Turkey, effective management and tax consequences must be reviewed.'], ['Can a remote employee live in Turkey?', 'Yes, but the employment contract, employer country, social security, health insurance, time spent and employer obligations should be reviewed.'], ['Could the Turkish exemption apply to digital nomads?', 'Potentially, depending on final rules, income type, source and eligibility conditions. Each situation must be reviewed.'], ['Does Bosphoras provide tax advice?', 'No. Bosphoras coordinates the private review and connects clients with suitable tax advisors, lawyers, accountants, banks, insurance and relocation partners.']],
  },
  ru: {
    title: 'Digital nomad в Турции: налоги, иностранные доходы и удалённая работа',
    metaTitle: 'Digital nomad в Турции: налоги и иностранные доходы',
    description: 'Digital nomad в Турции: налоговая резиденция, иностранные доходы, удалённая работа, фриланс, иностранная компания, банки, ВНЖ и семья.',
    eyebrow: 'Digital nomad · Иностранные доходы · Турция',
    hero: 'Жить в Турции и работать удалённо может быть привлекательным решением. Но для digital nomad, фрилансера, консультанта, IT-специалиста или онлайн-предпринимателя важно заранее понять, как будут рассматриваться доходы, компания, налоговая резиденция, банки и реальная установка в Турции.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед переездом в Турцию',
    finalTitle: 'Удалённая работа должна соответствовать реальной резиденции',
    finalText: 'До переезда, перевода доходов или структурирования компании Bosphoras может организовать частный анализ вашей ситуации: налоги, иностранные доходы, компания, банк, страхование, резиденция, жилье, семья и переезд в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Реальная налоговая резиденция', 'Где вы физически работаете', 'Тип иностранных доходов', 'Иностранная компания, если есть', 'Договоры, invoices и счета', 'ВНЖ или визовая ситуация', 'Медицинская страховка и жилье', 'Логика выхода из прежней страны'],
    sections: [
      ['Почему digital nomad должен подготовить налоговую установку', 'Digital nomad часто думает, что доход иностранный, потому что клиенты за рубежом или деньги поступают на иностранный счет. Но налоговый анализ зависит не только от клиента или банка. Нужно смотреть, где вы живете, где физически работаете, где клиенты, где зарегистрирована компания, где подписываются договоры, где выставляются счета, куда приходят деньги и где находится ваша налоговая резиденция.'],
      ['Налоговая резиденция в Турции', 'Прежде чем говорить о льготном режиме для иностранных доходов, нужно понять, становитесь ли вы налоговым резидентом Турции. Резиденция — это не только ВНЖ, квартира или банковский счет. Важны дни пребывания, основное место жизни, семья, деятельность, доходы, счета и центр экономических интересов.'],
      ['Иностранные доходы: определение важно', 'Доход digital nomad может включать консалтинг, фриланс, веб-разработку, digital marketing, e-commerce, онлайн-курсы, coaching, affiliate, контент, YouTube, SaaS, агентство, дивиденды иностранной компании или зарплату от иностранного работодателя. Эти категории нельзя автоматически объединять.'],
      ['Что может изменить турецкая льгота', 'Если Турция подтвердит благоприятный режим для отдельных новых резидентов, digital nomads могут заинтересоваться. Но нужно проверить финальный текст, тип дохода, страну клиентов, страну компании, место выполнения работы, реальную резиденцию, дату переезда и наличие деятельности из турецкого источника.'],
      ['Фриланс и консалтинг с иностранными клиентами', 'Фрилансер или консультант может работать из Турции для клиентов во Франции, Великобритании, США, Германии, ОАЭ, Казахстане или других странах. Нужно анализировать, где выполняется работа, где клиенты, где подписываются договоры, какая entity выставляет счета, где банк, где декларируются доходы, есть ли иностранная компания и нужна ли турецкая структура.'],
      ['Иностранная компания и деятельность из Турции', 'Многие digital nomads используют иностранные компании: французская компания, UK LTD, US LLC, компания в ОАЭ, Гонконге, Сингапуре, Эстонии, Казахстане или личный holding. Главный риск — фактическое управление. Если вы живете и работаете из Турции, управляете клиентами и принимаете решения в Турции, структуру нужно анализировать.'],
      ['Удалённый сотрудник иностранной компании', 'Некоторые работают как сотрудники или руководители иностранной компании. Нужно проверить трудовой договор, страну работодателя, реальное место выполнения работы, социальные взносы, медицинскую страховку, длительность пребывания в Турции, обязательства работодателя и налоговую резиденцию.'],
      ['E-commerce, SaaS и онлайн-доходы', 'Онлайн-доходы могут включать физические товары, цифровые продукты, SaaS, курсы, маркетинговые услуги, приложения, рекламу, affiliate или premium content. По каждой модели нужно понять, где компания, где клиенты, где создается value, где принимаются решения, куда приходят платежи и какая страна облагает прибыль.'],
      ['Банк, платежи и compliance', 'Digital nomad может получать деньги через иностранные счета, турецкий счет, Stripe, Wise, Payoneer, freelance-платформы, crypto-assets, рекламу или marketplaces. Турецкие банки могут запросить договоры с клиентами, invoices, налоговые декларации, документы компании, источник средств, банковские выписки, доказательства платежей, сертификат резиденции и объяснение деятельности.'],
      ['ВНЖ, резиденция и реальная жизнь', 'Жизнь в Турции — это не только аренда квартиры. Нужно организовать ВНЖ, реальный адрес, медицинскую страховку, счет, доказательства проживания, договор аренды, семейную жизнь, coworking или офис, поездки и календарь пребывания. Налоговая резиденция должна соответствовать реальной жизни.'],
      ['Семья, супруг и дети', 'Некоторые переезжают с семьей. Нужно заранее продумать школу, семейную страховку, жилье, район, безопасность, транспорт, врачей, занятия детей и жизнь между странами. Если семья и главный дом остаются в другой стране, резиденцию могут оспорить.'],
      ['Прежняя страна: избегайте сюрпризов', 'Выезд из страны не означает автоматического выхода из ее налоговой системы. Прежняя страна может считать вас резидентом, если там остаются дом, семья, управление компанией, основные доходы, много времени пребывания или экономические интересы. Выход из прежней страны и вход в Турцию нужно согласовать.'],
      ['Ошибки, которых нужно избегать', 'Не думайте, что иностранный клиент автоматически означает освобожденный иностранный доход. Не живите в Турции с иностранной компанией без анализа. Не игнорируйте банк и происхождение средств. Не забывайте обязанности прежней страны. Не смешивайте визу, административную резиденцию и налоговую резиденцию.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов или бухгалтеров. Его роль — координировать установку в Турции и помочь задать правильные вопросы: резиденция, онлайн-доходы, иностранная компания, специалисты в Турции и за рубежом, банки, страховка, жилье, семья, недвижимость, юристы, бухгалтеры и местные партнеры.'],
    ],
    faq: [['Может ли digital nomad стать налоговым резидентом Турции?', 'Да, в зависимости от реальной жизни: дней в Турции, основного жилья, доходов, семьи, деятельности, счетов и центра экономических интересов.'], ['Считается ли доход иностранным, если клиенты за рубежом?', 'Не автоматически. Нужно анализировать, где выполняется работа, какая entity выставляет счет, где управляется компания, где декларируется доход и какая резиденция применяется.'], ['Достаточно ли иностранной компании, чтобы избежать турецких налогов?', 'Нет. Если компания фактически управляется из Турции, нужно анализировать effective management и налоговые последствия.'], ['Может ли удалённый сотрудник жить в Турции?', 'Да, но нужно проверить трудовой договор, страну работодателя, социальные взносы, страховку, время пребывания и обязательства работодателя.'], ['Может ли турецкая льгота касаться digital nomads?', 'Потенциально, в зависимости от финальных правил, типа дохода, источника и условий допуска.'], ['Bosphoras дает налоговую консультацию?', 'Нет. Bosphoras координирует частный анализ и связывает клиентов с налоговыми специалистами, юристами, бухгалтерами, банками, страхованием и партнерами по переезду.']],
  },
  ar: {
    title: 'Digital Nomad في تركيا: الضرائب، الدخل الأجنبي والعمل عن بُعد',
    metaTitle: 'Digital Nomad في تركيا: الضرائب والدخل الأجنبي',
    description: 'Digital nomad في تركيا: الإقامة الضريبية، الدخل الأجنبي، العمل عن بُعد، الفريلانس، الشركة الأجنبية، البنوك، الإقامة والعائلة.',
    eyebrow: 'Digital nomad · الدخل الأجنبي · تركيا',
    hero: 'العيش في تركيا والعمل عن بُعد قد يكون خياراً جذاباً. لكن بالنسبة للفريلانسر أو المستشار أو رائد الأعمال الرقمي، السؤال المهم هو كيفية التعامل مع الدخل، الشركة، الإقامة الضريبية، البنوك والانتقال الحقيقي إلى تركيا.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل الانتقال إلى تركيا',
    finalTitle: 'العمل عن بُعد يجب أن يكون منسجماً مع الإقامة الحقيقية',
    finalText: 'قبل الانتقال أو تحويل الدخل أو تنظيم الشركة، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك: الضرائب، الدخل الأجنبي، الشركة، البنوك، التأمين، الإقامة، السكن، العائلة والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['إقامتك الضريبية الحقيقية', 'مكان العمل الفعلي', 'طبيعة الدخل الأجنبي', 'الشركة الأجنبية إن وجدت', 'العقود والفواتير والحسابات', 'الإقامة أو التأشيرة', 'التأمين الصحي والسكن', 'الانسجام مع بلدك السابق'],
    sections: [
      ['لماذا يجب على digital nomad تحضير وضعه الضريبي', 'كثير من العاملين عن بُعد يعتقدون أن الدخل أجنبي لأن العملاء في الخارج أو لأن الأموال تصل إلى حساب خارج تركيا. لكن التحليل الضريبي لا يعتمد فقط على مكان العميل أو البنك. يجب مراجعة أين تعيش، أين تعمل فعلياً، أين العملاء، أين الشركة مسجلة، أين العقود والفواتير، أين تصل المدفوعات وأين تقع إقامتك الضريبية.'],
      ['الإقامة الضريبية في تركيا', 'قبل التفكير في معاملة ملائمة للدخل الأجنبي، يجب تحديد ما إذا كنت ستصبح مقيماً ضريبياً في تركيا. الإقامة ليست مجرد تصريح أو شقة أو حساب بنكي. إنها تعتمد على مدة البقاء، مكان الحياة الرئيسي، الأسرة، النشاط، الدخل، الحسابات ومركز المصالح الاقتصادية.'],
      ['الدخل الأجنبي: التعريف مهم', 'دخل digital nomad قد يشمل الاستشارات، الفريلانس، تطوير الويب، التسويق الرقمي، التجارة الإلكترونية، الدورات، coaching، affiliate، المحتوى، YouTube، SaaS، وكالة رقمية، أرباح شركة أجنبية أو راتب من صاحب عمل أجنبي. هذه الفئات لا تعالج دائماً بنفس الطريقة.'],
      ['ما الذي قد تغيره الإعفاءات التركية', 'إذا أكدت تركيا نظاماً مناسباً لبعض المقيمين الجدد، قد يهتم بعض digital nomads. لكن يجب مراجعة النص النهائي، نوع الدخل، بلد العملاء، بلد الشركة، مكان تنفيذ العمل، الإقامة الحقيقية، تاريخ الانتقال وأي نشاط من مصدر تركي.'],
      ['فريلانسر أو مستشار مع عملاء أجانب', 'قد يعمل المستشار أو الفريلانسر من تركيا لعملاء في فرنسا أو بريطانيا أو الولايات المتحدة أو ألمانيا أو الخليج أو كازاخستان. يجب تحليل أين ينفذ العمل، أين العملاء، أين العقود، أي كيان يصدر الفواتير، أين الحساب البنكي، أين يصرح بالدخل وهل توجد شركة أجنبية أو يجب التفكير في هيكل تركي.'],
      ['شركة أجنبية ونشاط من تركيا', 'كثير من digital nomads يستخدمون شركة أجنبية: شركة في فرنسا، UK LTD، US LLC، الإمارات، هونغ كونغ، سنغافورة، إستونيا، كازاخستان أو holding شخصي. الخطر الرئيسي هو الإدارة الفعلية. إذا كنت تعيش وتعمل وتدير العملاء وتتخذ القرارات من تركيا، يجب تحليل الهيكل.'],
      ['موظف عن بُعد لدى شركة أجنبية', 'بعض الأشخاص يعملون كموظفين أو مديرين عن بُعد لشركة أجنبية. يجب مراجعة عقد العمل، بلد صاحب العمل، مكان تنفيذ العمل، الاشتراكات الاجتماعية، التأمين الصحي، مدة البقاء في تركيا، التزامات صاحب العمل وقواعد الإقامة الضريبية.'],
      ['E-commerce وSaaS والدخل عبر الإنترنت', 'الدخل عبر الإنترنت قد يشمل منتجات مادية، منتجات رقمية، اشتراكات SaaS، دورات، خدمات تسويق، تطبيقات، إعلانات، affiliate أو محتوى مدفوع. لكل نموذج يجب فهم أين الشركة، أين العملاء، أين تخلق القيمة، أين القرارات، أين تصل المدفوعات وأي بلد يفرض الضريبة على الأرباح.'],
      ['البنوك والمدفوعات والامتثال', 'قد يستلم digital nomad الأموال عبر حساب أجنبي، حساب تركي، Stripe، Wise، Payoneer، منصات فريلانس، crypto-assets، إعلانات أو marketplaces. قد تطلب البنوك التركية عقود العملاء، الفواتير، التصريحات الضريبية، مستندات الشركة، مصدر الأموال، كشوف الحساب، إثبات المدفوعات، شهادة الإقامة الضريبية وشرح النشاط.'],
      ['التأشيرة والإقامة والحياة الحقيقية', 'العيش في تركيا لا يعني فقط استئجار شقة. يجب تنظيم تصريح الإقامة، العنوان الحقيقي، التأمين الصحي، الحساب البنكي، إثباتات السكن، عقد الإيجار، الحياة العائلية، coworking أو مكتب، السفر الدولي وجدول الحضور. الإقامة الضريبية يجب أن تطابق الحياة الحقيقية.'],
      ['العائلة والزوج أو الزوجة والأطفال', 'بعض العاملين عن بُعد ينتقلون مع العائلة. يجب التفكير في المدرسة، التأمين الصحي العائلي، السكن، المنطقة، الأمان، النقل، الأطباء، أنشطة الأطفال والحياة بين عدة دول. إذا بقيت الأسرة والمنزل الرئيسي في بلد آخر، قد يتم الاعتراض على الإقامة.'],
      ['البلد السابق: تجنب المفاجآت', 'مغادرة بلد لا تعني تلقائياً مغادرة نظامه الضريبي. قد يستمر البلد السابق في اعتبارك مقيماً إذا بقي المنزل، الأسرة، إدارة الشركة، الدخل الرئيسي، الوقت أو المصالح الاقتصادية هناك. يجب تنسيق الخروج من البلد السابق مع الدخول الحقيقي إلى تركيا.'],
      ['أخطاء يجب تجنبها', 'لا تفترض أن العميل الأجنبي يعني تلقائياً دخلاً أجنبياً معفى. لا تعش في تركيا مع شركة أجنبية دون تحليل. لا تتجاهل البنك ومصدر الأموال. لا تتجاهل التزامات بلدك السابق. لا تخلط بين التأشيرة والإقامة الإدارية والإقامة الضريبية.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامين الضريبيين أو المحاسبين. دوره هو تنسيق انتقالك إلى تركيا ومساعدتك على طرح الأسئلة الصحيحة: الإقامة، الدخل الرقمي، الشركة الأجنبية، المستشارون في تركيا والخارج، البنوك، التأمين، السكن، العائلة، العقار، المحامون، المحاسبون والشركاء المحليون.'],
    ],
    faq: [['هل يمكن لـ digital nomad أن يصبح مقيماً ضريبياً في تركيا؟', 'نعم، حسب الحياة الفعلية: مدة البقاء، مكان السكن الرئيسي، الدخل، الأسرة، النشاط، الحسابات ومركز المصالح الاقتصادية.'], ['هل يعتبر دخلي أجنبياً إذا كان العملاء في الخارج؟', 'ليس تلقائياً. يجب تحليل مكان تنفيذ العمل، أي كيان يصدر الفواتير، أين تدار الشركة، أين يصرح بالدخل وأي إقامة ضريبية تطبق.'], ['هل تكفي شركة أجنبية لتجنب الضرائب التركية؟', 'لا. إذا كانت الشركة تدار فعلياً من تركيا، يجب تحليل الإدارة الفعلية والنتائج الضريبية.'], ['هل يمكن للموظف عن بُعد العيش في تركيا؟', 'نعم، لكن يجب مراجعة عقد العمل، بلد صاحب العمل، الاشتراكات الاجتماعية، التأمين، مدة البقاء والتزامات صاحب العمل.'], ['هل يمكن أن يشمل الإعفاء التركي digital nomads؟', 'محتمل حسب القواعد النهائية، نوع الدخل، المصدر وشروط الأهلية. يجب تحليل كل حالة.'], ['هل يقدم Bosphoras استشارة ضريبية؟', 'لا. Bosphoras ينسق المراجعة الخاصة ويربط العملاء بالمستشارين الضريبيين والمحامين والمحاسبين والبنوك والتأمين وشركاء الانتقال.']],
  },
};

export function getDigitalNomadTaxMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function DigitalNomadTaxClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
