import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/retraite-etrangere-turquie-fiscalite',
  en: '/en/foreign-pension-tax-turkey',
  ru: '/ru/inostrannaya-pensiya-turtsiya-nalogi',
  ar: '/ar/foreign-pension-tax-turkey',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = { title:string; metaTitle:string; description:string; eyebrow:string; hero:string; cta:string; asideTitle:string; finalTitle:string; finalText:string; faqTitle:string; checklist:string[]; sections:Array<[string,string]>; faq:Array<[string,string]> };

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Retraite française en Turquie : fiscalité, pension, résidence et assurance santé',
    metaTitle: 'Retraite française en Turquie : fiscalité et pension',
    description: 'Retraite française en Turquie : pension française, retraite complémentaire, résidence fiscale, convention France-Turquie, assurance santé, banque, immobilier et installation.',
    eyebrow: 'Retraite française · Résidence en Turquie',
    hero: 'Vivre sa retraite en Turquie peut être attractif pour un retraité français ou francophone. Mais avant de s’installer à Istanbul, Antalya, Bodrum, Izmir ou Alanya, il faut comprendre comment votre pension française, votre résidence fiscale, votre assurance santé, vos comptes bancaires et vos biens en France seront traités.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant de vivre votre retraite en Turquie',
    finalTitle: 'Une retraite en Turquie doit être préparée avant le départ fiscal et familial',
    finalText: 'Avant de transférer votre résidence, votre pension ou vos comptes bancaires, Bosphoras peut organiser une analyse privée de votre situation : pension française, fiscalité, banque, assurance santé, logement, immobilier, famille, succession et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Votre résidence fiscale française actuelle', 'La nature de votre pension française', 'Retraite de base, complémentaire ou publique', 'La convention France-Turquie', 'Vos biens immobiliers en France', 'Votre assurance santé et couverture médicale', 'Vos virements de pension et comptes bancaires', 'Votre famille, conjoint et héritiers'],
    sections: [
      ['Pourquoi préparer sa retraite en Turquie avant de s’installer', 'Une installation en Turquie ne se résume pas à louer un appartement, acheter une villa ou ouvrir un compte bancaire. Un retraité français peut conserver une pension française, une retraite complémentaire, une pension publique, des revenus locatifs en France, une assurance-vie, des placements financiers, des comptes bancaires français, de l’immobilier en France, une couverture santé spécifique et une famille restée en France. Avant de s’installer, il faut comprendre ce qui restera imposable en France, ce qui peut être traité en Turquie et comment organiser la vie quotidienne de manière cohérente.'],
      ['Résidence fiscale : le point de départ', 'Avant de parler de fiscalité de la retraite, il faut déterminer où vous serez résident fiscal. La résidence fiscale ne dépend pas uniquement d’un titre de séjour turc, d’un bail ou d’un compte bancaire. Elle dépend de votre lieu de vie principal, du temps passé en Turquie, de votre foyer, de votre conjoint, de vos revenus principaux, de vos comptes bancaires, de vos biens immobiliers et de votre centre d’intérêts économiques. Si vous vivez en Turquie mais conservez votre foyer et vos intérêts principaux en France, la situation doit être analysée avec prudence.'],
      ['Pension française : toutes les retraites ne sont pas identiques', 'Une pension française peut avoir plusieurs formes : retraite de base, retraite complémentaire, pension de fonctionnaire, pension du secteur privé, pension publique, pension militaire, pension d’invalidité, rente privée, assurance-vie ou revenus de capitalisation. Chaque type de pension peut être traité différemment selon la convention fiscale, votre résidence réelle et votre situation personnelle. Il ne faut donc pas supposer que toutes les retraites françaises suivent la même règle.'],
      ['Convention France-Turquie : éviter la double imposition', 'Lorsqu’une pension française est versée à une personne vivant en Turquie, la France et la Turquie peuvent être concernées. La convention fiscale peut déterminer quel pays a le droit d’imposer la pension, dans quelles conditions et comment éviter une double imposition. Mais une convention ne signifie pas automatiquement absence d’impôt. Elle peut distinguer pensions privées, pensions publiques, retraites de fonctionnaires, revenus de sécurité sociale, rentes privées et autres revenus personnels.'],
      ['Immobilier et revenus conservés en France', 'Beaucoup de retraités français conservent un appartement, une maison, une résidence secondaire, un bien locatif ou des placements en France. Ces actifs peuvent maintenir un lien fiscal avec la France. Les loyers, plus-values, taxes locales, obligations déclaratives et revenus financiers doivent être analysés séparément de la pension. Une retraite en Turquie peut être cohérente, mais elle doit intégrer les actifs qui restent en France.'],
      ['Assurance santé et couverture médicale', 'Pour un retraité, la santé est aussi importante que la fiscalité. Avant de s’installer en Turquie, il faut organiser assurance santé internationale, couverture hospitalière, consultations, médicaments réguliers, spécialistes, urgences, rapatriement éventuel, couverture du conjoint et suivi médical en France. La Turquie dispose d’hôpitaux privés et d’une offre médicale développée, mais votre couverture réelle, les exclusions et les remboursements doivent être vérifiés.'],
      ['Banque, virements de pension et conformité', 'Recevoir une pension française en Turquie peut impliquer des flux bancaires réguliers. Les banques peuvent demander preuve de pension, attestation de retraite, déclarations fiscales, certificat de résidence fiscale, relevés bancaires, preuve d’origine des fonds, documents traduits si nécessaire et justificatifs de revenus complémentaires. Un dossier bancaire clair facilite les virements, l’achat immobilier, l’assurance et la relation bancaire.'],
      ['Immobilier en Turquie et choix du lieu de retraite', 'Istanbul, Antalya, Bodrum, Izmir, Alanya, Fethiye ou Mersin peuvent répondre à des styles de vie différents. Le choix du logement doit intégrer accès aux hôpitaux, proximité de l’aéroport, sécurité du quartier, charges, climat, services quotidiens, communauté étrangère, possibilité de revente et transmission aux héritiers. Louer d’abord peut parfois permettre de tester la ville avant d’acheter.'],
      ['Famille, conjoint, enfants et héritiers', 'Une retraite à l’étranger concerne aussi le conjoint, les enfants, les petits-enfants et les héritiers. Il faut anticiper qui vit réellement en Turquie, qui dépend financièrement de vous, qui peut prendre des décisions médicales, comment les comptes seront accessibles, comment le logement sera transmis et comment éviter les conflits familiaux. La retraite est aussi un sujet patrimonial et familial.'],
      ['Les erreurs à éviter', 'La première erreur est de croire que vivre en Turquie rend automatiquement la pension non imposable en France. La deuxième est de confondre titre de séjour et résidence fiscale. La troisième est de négliger la convention France-Turquie. La quatrième est de transférer sa pension sans préparer le dossier bancaire. La cinquième est d’acheter un bien immobilier sans penser à la santé, à la succession et à la revente.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste, un conseiller patrimonial ou un expert-comptable. Notre rôle est de coordonner votre installation en Turquie avec les bons interlocuteurs : analyse de résidence fiscale, pension française, fiscalistes français et turcs, banque, assurance santé, logement, immobilier, organisation familiale, succession et partenaires locaux.'],
    ],
    faq: [['Une retraite française est-elle imposable en Turquie ?', 'Cela dépend de votre résidence fiscale réelle, de la nature de la pension et de la convention France-Turquie.'], ['Une pension française peut-elle rester imposable en France ?', 'Dans certains cas, oui. Il faut analyser la nature de la pension, votre résidence fiscale réelle et vos autres revenus français.'], ['Le titre de séjour turc suffit-il à changer ma résidence fiscale ?', 'Non. La résidence fiscale dépend de votre vie réelle, du temps passé, du foyer, des revenus, des actifs et du centre d’intérêts économiques.'], ['Peut-on recevoir sa pension française sur un compte turc ?', 'Oui, mais la banque peut demander preuve de pension, origine des fonds, certificat de résidence fiscale et documents complémentaires.'], ['Faut-il acheter un bien immobilier pour vivre sa retraite en Turquie ?', 'Pas forcément. Louer d’abord peut permettre de tester la ville, les hôpitaux, le quartier, le coût de vie et la qualité de vie.'], ['Bosphoras donne-t-il un conseil fiscal ?', 'Non. Bosphoras coordonne l’analyse privée et les bons interlocuteurs : fiscalistes, avocats, banques, assurance santé, immobilier, comptables et partenaires d’installation en Turquie.']],
  },
  en: {
    title: 'UK and US Pension in Turkey: tax residence, retirement income and healthcare',
    metaTitle: 'UK and US Pension in Turkey: Tax and Retirement Guide',
    description: 'UK and US pension in Turkey: State Pension, private pension, Social Security, IRA, 401k, tax residence, healthcare, banking, property and relocation planning.',
    eyebrow: 'UK & US retirees · Pension tax · Turkey',
    hero: 'Turkey can be attractive for British and American retirees looking for lifestyle, healthcare access, property and a more flexible retirement base. Before relocating, you should understand how UK pensions, US retirement income, tax residence, banking, healthcare and family matters may be treated.',
    cta: 'Request a private assessment',
    asideTitle: 'Before retiring in Turkey',
    finalTitle: 'Retirement in Turkey should be planned before moving income and residence',
    finalText: 'Before moving residence, pension payments or bank accounts to Turkey, Bosphoras can organize a private review of your situation: UK or US pension, tax residence, banking, healthcare, housing, property, family, estate planning and relocation.',
    faqTitle: 'Frequently asked questions',
    checklist: ['UK State Pension or private pension', 'US Social Security, IRA or 401k', 'Your tax residence position', 'Applicable tax treaty questions', 'Healthcare and insurance coverage', 'Banking and pension transfers', 'Property in the UK, US or Turkey', 'Family and estate planning'],
    sections: [
      ['Why British and American retirees should prepare before moving', 'Relocating to Turkey is not only about renting an apartment, buying property or opening a bank account. A British retiree may receive UK State Pension, private pension, occupational pension, rental income, investment income or ISA-related assets. An American retiree may receive Social Security, IRA distributions, 401k income, brokerage income, rental income or business distributions. Each income stream should be reviewed before relocation.'],
      ['Tax residence is the starting point', 'Before analyzing pension taxation, you should determine where you will be tax resident. Tax residence is not just a Turkish residence permit, lease or bank account. It depends on where you live, how much time you spend in Turkey, where your home and family are, where your income and assets are located and where your center of economic interests remains.'],
      ['UK pension and retirement income', 'For British retirees, the analysis may include UK State Pension, private pension, occupational pension, lump-sum withdrawals, rental income from UK property, investment income and bank accounts. A move to Turkey should be coordinated with UK tax residence, double tax treaty questions, pension provider requirements, bank compliance and healthcare coverage.'],
      ['US Social Security, IRA and 401k income', 'For American retirees, the analysis may include Social Security, IRA distributions, 401k income, annuities, brokerage accounts, rental income, dividends and capital gains. US citizens and green card holders may have continuing US tax and reporting obligations even when living abroad. This makes the US case different from many other countries and requires careful coordination.'],
      ['Treaties and double taxation', 'When retirement income is paid from the UK or the United States to a person living in Turkey, more than one country may be involved. Treaty analysis can determine which country may tax certain pension categories and whether double taxation relief is available. Public pensions, private pensions, Social Security-type benefits, annuities and investment income may not be treated the same way.'],
      ['Healthcare and insurance', 'Healthcare is central for retirees. Before moving to Turkey, you should organize international health insurance, hospital coverage, regular medication, specialists, emergencies, possible repatriation, spouse coverage and continuing medical care in the UK or US. Turkey has strong private hospitals in major cities, but exclusions, reimbursement rules and pre-existing conditions must be reviewed.'],
      ['Banking and pension transfers', 'Receiving UK or US retirement income in Turkey can involve regular international transfers. Banks may request proof of pension, retirement statements, tax filings, tax residence certificates, bank statements, source-of-funds evidence and supporting documents for additional income. A prepared file can make account opening, transfers, property purchases and insurance easier.'],
      ['Property in Turkey and former-country assets', 'Many retirees keep property in the UK or US while buying or renting in Turkey. Property kept abroad may continue to generate rental income, local taxes, reporting obligations and estate planning issues. Turkish property should also be reviewed for inheritance, local costs, resale, insurance, bank transfers and practical daily life.'],
      ['Family, spouse and estate planning', 'A retirement move affects the spouse, children, grandchildren and heirs. You should consider who will live in Turkey, who depends on you financially, who can make medical decisions, how accounts will be accessed, how property will be inherited and how to prevent family disputes. Retirement abroad is also a family and estate planning matter.'],
      ['Mistakes to avoid', 'Do not assume moving to Turkey automatically changes pension taxation. Do not confuse a residence permit with tax residence. Do not ignore UK or US reporting obligations. Do not transfer pensions without preparing banking documentation. Do not buy property without reviewing healthcare, inheritance and resale. Do not ignore investment income, rental income and capital gains.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers, accountants or financial advisors. Its role is to coordinate your relocation to Turkey with suitable professionals: tax residence review, pension income mapping, Turkish and foreign tax advisors, banking preparation, healthcare insurance, housing, property, family organization, estate planning and local partners.'],
    ],
    faq: [['Can UK pension be received while living in Turkey?', 'Yes, but tax residence, pension type, treaty position, banking and healthcare should be reviewed.'], ['Can US Social Security or IRA income be received in Turkey?', 'Potentially yes, but US citizens may keep US tax and reporting obligations. The income type and treaty position should be reviewed.'], ['Does a Turkish residence permit change my tax residence?', 'No. Tax residence depends on real life, time spent, home, family, income, assets and center of economic interests.'], ['Can I receive pension payments into a Turkish bank account?', 'Yes, but banks may request pension evidence, tax documents, source-of-funds proof and residence information.'], ['Should I buy property before retiring in Turkey?', 'Not necessarily. Renting first may help test the city, hospitals, neighborhood, cost of living and lifestyle.'], ['Does Bosphoras provide tax advice?', 'No. Bosphoras coordinates the private review and connects clients with suitable tax advisors, lawyers, banks, healthcare insurance, accountants and relocation partners.']],
  },
  ru: {
    title: 'Иностранная пенсия в Турции: Россия, Казахстан, Узбекистан, Кыргызстан и страны СНГ',
    metaTitle: 'Иностранная пенсия в Турции: налоги и переезд',
    description: 'Иностранная пенсия в Турции для русскоязычных пенсионеров: Россия, Казахстан, Узбекистан, Кыргызстан, банки, медицина, ВНЖ, недвижимость и семья.',
    eyebrow: 'Пенсия · СНГ · Турция',
    hero: 'Турция может быть привлекательной базой для русскоязычных пенсионеров и семей из России, Казахстана, Узбекистана, Кыргызстана и других стран СНГ. Но до переезда нужно понять, как будут организованы пенсия, налоговая резиденция, банковские переводы, медицинская страховка и семейная жизнь.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед переездом на пенсию в Турцию',
    finalTitle: 'Пенсия в Турции должна быть удобной, понятной и документально подготовленной',
    finalText: 'До перевода резиденции, пенсионных доходов или счетов Bosphoras может организовать частный анализ вашей ситуации: пенсия, налоги, банк, медицина, жилье, недвижимость, семья, наследство и переезд в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Пенсия из России, Казахстана или СНГ', 'Текущая налоговая резиденция', 'Банковские переводы и источник средств', 'Недвижимость в стране происхождения', 'Медицинская страховка в Турции', 'ВНЖ и реальное проживание', 'Семья и наследники', 'Документы, переводы и апостили'],
    sections: [
      ['Почему нужно готовить переезд до установки в Турции', 'Переезд на пенсию в Турцию — это не только аренда квартиры или покупка недвижимости. У пенсионера из России, Казахстана, Узбекистана, Кыргызстана, Азербайджана или другой страны СНГ могут быть пенсия, банковские счета, недвижимость в стране происхождения, семейные активы, медицинские потребности, дети и наследники в разных странах. Все это нужно подготовить до переезда.'],
      ['Налоговая резиденция — отправная точка', 'Прежде чем анализировать пенсию, нужно понять, где вы являетесь налоговым резидентом. ВНЖ, квартира или счет в Турции сами по себе не решают вопрос. Важны фактическое место жизни, количество дней в Турции, семья, жилье, счета, имущество, доходы и центр экономических интересов. Если значительная часть жизни остается в прежней стране, ситуация должна быть проверена.'],
      ['Пенсия из России и стран СНГ', 'Пенсионный доход может поступать из России, Казахстана, Узбекистана, Кыргызстана, Азербайджана, Украины или другой страны. Он может быть государственной пенсией, профессиональной пенсией, частной выплатой, социальной выплатой, накопительной пенсией или семейным доходом. Каждый тип дохода должен быть проанализирован отдельно с учетом страны источника, банковских переводов и резиденции.'],
      ['Казахстан, Узбекистан, Кыргызстан и Центральная Азия', 'Для клиентов из Центральной Азии важны банковские переводы, валютный контроль, подтверждение происхождения средств, документы о пенсии, недвижимость, семейные обязательства и медицинское обслуживание. Некоторые семьи могут жить между Алматы, Астаной, Ташкентом, Бишкеком и Турцией. Такая жизнь должна быть документально понятной для банков и налоговых специалистов.'],
      ['Банки, переводы пенсии и compliance', 'Получение пенсии или семейных средств в Турции может требовать подготовки. Турецкие банки могут попросить документы о пенсии, банковские выписки, подтверждение происхождения средств, налоговую резиденцию, договоры продажи имущества, переводы документов, апостили и объяснение структуры доходов. Подготовленный файл облегчает открытие счета, переводы, покупку недвижимости и страховку.'],
      ['Медицина и страховка', 'Для пенсионера медицина не менее важна, чем налоги. Перед переездом нужно организовать медицинскую страховку, госпитальное покрытие, регулярные лекарства, врачей, специалистов, экстренную помощь, возможное возвращение в страну происхождения и покрытие супруга или супруги. В Турции развиты частные клиники, но условия страховки и исключения нужно проверять заранее.'],
      ['Недвижимость и выбор города', 'Стамбул, Анталья, Аланья, Бодрум, Измир, Фетхие и Мерсин предлагают разные форматы жизни. Выбор жилья должен учитывать больницы, аэропорт, климат, район, безопасность, ежемесячные расходы, русскоязычное окружение, транспорт, возможность перепродажи и наследование. Иногда лучше сначала арендовать и протестировать город.'],
      ['Семья, наследники и документы', 'Переезд на пенсию затрагивает семью, детей, внуков и наследников. Нужно заранее понять, кто будет жить в Турции, кто финансово зависит от пенсионера, кто сможет принимать медицинские решения, как будут доступны счета, как будет передана недвижимость и какие документы нужны наследникам.'],
      ['Доходы помимо пенсии', 'Многие пенсионеры имеют не только пенсию, но и аренду, проценты, дивиденды, продажу недвижимости, семейный бизнес, портфель или помощь от детей. Эти доходы нужно отделять от пенсии. Один тип дохода может иметь один режим, а аренда, дивиденды или продажа недвижимости — другой.'],
      ['Ошибки, которых нужно избегать', 'Не стоит считать, что ВНЖ автоматически меняет налоговую резиденцию. Не переводите крупные суммы без документов. Не покупайте недвижимость без анализа медицины, наследства и банков. Не игнорируйте страну происхождения, где может остаться недвижимость, счета или налоговые обязанности. Не откладывайте страховку и медицинские вопросы.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов, бухгалтеров или медицинских страховщиков. Его роль — координировать установку в Турции: анализ резиденции, pension income, банки, документы, переводы, медицинская страховка, жилье, недвижимость, семья, наследство, юристы, бухгалтеры и местные партнеры.'],
    ],
    faq: [['Можно ли получать иностранную пенсию, живя в Турции?', 'Да, но нужно анализировать резиденцию, страну источника, банковские переводы, документы и возможные налоговые правила.'], ['Пенсия из России, Казахстана или СНГ облагается в Турции?', 'Это зависит от типа пенсии, резиденции, страны источника и применимых правил. Ситуацию нужно анализировать индивидуально.'], ['Достаточно ли ВНЖ для налоговой резиденции?', 'Нет. Налоговая резиденция зависит от реальной жизни, дней пребывания, семьи, жилья, активов и центра интересов.'], ['Можно ли переводить пенсию на турецкий счет?', 'Да, но банк может запросить документы о пенсии, источник средств, выписки, налоговую резиденцию, переводы и апостили.'], ['Стоит ли сразу покупать недвижимость в Турции?', 'Не всегда. Аренда сначала может позволить проверить город, медицину, район, расходы и образ жизни.'], ['Bosphoras дает налоговую консультацию?', 'Нет. Bosphoras координирует частный анализ и связывает клиентов с налоговыми специалистами, юристами, банками, страховщиками и партнерами по переезду.']],
  },
  ar: {
    title: 'المعاش الأجنبي في تركيا: الإمارات، السعودية، قطر ودول الخليج',
    metaTitle: 'المعاش الأجنبي في تركيا: التقاعد والضرائب',
    description: 'المعاش الأجنبي في تركيا للمستثمرين والعائلات العربية: الإمارات، السعودية، قطر، الكويت، البحرين، عمان، الضرائب، البنوك، التأمين الصحي والعقار.',
    eyebrow: 'التقاعد · الخليج · تركيا',
    hero: 'قد تكون تركيا خياراً مناسباً للمتقاعدين والعائلات العربية من الإمارات، السعودية، قطر، الكويت، البحرين، عمان ودول أخرى. لكن قبل الانتقال، يجب تنظيم المعاش، الإقامة الضريبية، البنوك، التأمين الصحي، العقار والعائلة.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل التقاعد في تركيا',
    finalTitle: 'التقاعد في تركيا يجب أن يكون منظماً للعائلة والبنوك والصحة',
    finalText: 'قبل نقل الإقامة أو المعاش أو الحسابات إلى تركيا، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك: المعاش، الضرائب، البنك، التأمين الصحي، السكن، العقار، العائلة، الميراث والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['المعاش من الإمارات أو السعودية أو الخليج', 'الإقامة الضريبية الحالية', 'البنوك ومصدر الأموال', 'العقار في بلدك أو تركيا', 'التأمين الصحي والتغطية الطبية', 'الإقامة والحياة الفعلية في تركيا', 'العائلة والورثة', 'المستندات والترجمات والتصديقات'],
    sections: [
      ['لماذا يجب تحضير التقاعد قبل الانتقال', 'الانتقال إلى تركيا للتقاعد لا يعني فقط شراء شقة أو فتح حساب بنكي. قد يكون لدى المتقاعد العربي معاش من الإمارات أو السعودية أو قطر أو الكويت أو البحرين أو عمان، حسابات بنكية، عقار في بلده، استثمارات، دخل عائلي، تأمين صحي، أبناء وورثة في عدة دول. يجب تنظيم هذه العناصر قبل الانتقال.'],
      ['الإقامة الضريبية هي نقطة البداية', 'قبل تحليل المعاش، يجب تحديد مكان إقامتك الضريبية. تصريح الإقامة أو شقة في تركيا أو حساب بنكي لا يكفي وحده. الأهم هو مكان الحياة الفعلي، عدد أيام الإقامة، العائلة، السكن، الحسابات، الأصول، الدخل ومركز المصالح الاقتصادية.'],
      ['المعاش من الإمارات والسعودية وقطر ودول الخليج', 'قد يكون المعاش أو الدخل التقاعدي قادماً من الإمارات، السعودية، قطر، الكويت، البحرين، عمان أو دولة أخرى. وقد يكون معاشاً حكومياً، معاشاً مهنياً، دخل استثماري، دخل من شركة عائلية، توزيعات، إيجارات أو دخل من أصول مالية. كل فئة يجب تحليلها بشكل منفصل.'],
      ['البنوك والتحويلات ومصدر الأموال', 'تلقي المعاش أو تحويل أموال عائلية إلى تركيا قد يتطلب ملفاً واضحاً. قد تطلب البنوك التركية إثبات المعاش، كشوفات بنكية، مصدر الأموال، شهادة إقامة ضريبية، عقود بيع عقار، مستندات شركة، ترجمات، تصديقات وشرح هيكل الثروة. ملف مرتب يسهل فتح الحسابات والتحويلات وشراء العقار والتأمين.'],
      ['التأمين الصحي والطب', 'بالنسبة للمتقاعد، الصحة موضوع أساسي. يجب تنظيم التأمين الصحي، تغطية المستشفيات، الأدوية المنتظمة، الأطباء المتخصصين، الطوارئ، احتمال العلاج في بلد آخر، وتغطية الزوج أو الزوجة. تركيا لديها مستشفيات خاصة متطورة، لكن يجب مراجعة الشروط والاستثناءات والتغطية مسبقاً.'],
      ['العقار واختيار المدينة', 'إسطنبول، أنطاليا، ألانيا، بودروم، إزمير، فتحية ومرسين تقدم أنماط حياة مختلفة. اختيار العقار يجب أن يأخذ في الاعتبار المستشفيات، المطار، المناخ، الحي، الأمان، المصاريف الشهرية، الخدمات، الجالية العربية أو الدولية، إمكانية إعادة البيع والميراث. أحياناً يكون الإيجار أولاً أفضل من الشراء مباشرة.'],
      ['العائلة والورثة والميراث', 'التقاعد في الخارج يمس الزوج أو الزوجة، الأبناء، الأحفاد والورثة. يجب معرفة من سيعيش في تركيا، من يعتمد عليك مالياً، من يمكنه اتخاذ قرارات طبية، كيف ستكون الحسابات متاحة، كيف سينتقل العقار وكيف يمكن تجنب الخلافات العائلية.'],
      ['دخل إضافي بجانب المعاش', 'كثير من المتقاعدين لا يعتمدون فقط على معاش. قد يكون لديهم إيجارات، أرباح، فوائد، محفظة استثمارية، بيع عقار، مكاسب رأسمالية، شركة عائلية أو دخل من الأبناء. هذه الأنواع يجب تحليلها بشكل منفصل عن المعاش.'],
      ['بلدك الأصلي لا يختفي تلقائياً', 'مغادرة بلد الإقامة أو نقل جزء من الحياة إلى تركيا لا يعني انتهاء كل الالتزامات في البلد السابق. قد تبقى لديك عقارات، حسابات، دخل، شركات، عائلة أو التزامات تصريحية. يجب تنسيق الانتقال إلى تركيا مع الوضع في بلدك الحالي.'],
      ['أخطاء يجب تجنبها', 'لا تفترض أن الانتقال إلى تركيا يجعل المعاش غير خاضع لأي قواعد في بلد المصدر. لا تخلط بين تصريح الإقامة والإقامة الضريبية. لا تحول أموالاً كبيرة دون مستندات. لا تشتر عقاراً دون التفكير في الصحة والميراث وإعادة البيع. لا تهمل الدخل الإضافي مثل الإيجارات والأرباح.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامي الضريبي أو المحاسب أو شركة التأمين. دوره هو تنسيق انتقالك إلى تركيا مع المختصين: تحليل الإقامة، المعاش والدخل، البنوك، المستندات، التأمين الصحي، السكن، العقار، العائلة، الميراث، المحامون، المحاسبون والشركاء المحليون.'],
    ],
    faq: [['هل يمكن تلقي معاش أجنبي أثناء العيش في تركيا؟', 'نعم، لكن يجب تحليل الإقامة الضريبية، بلد المصدر، التحويلات البنكية، المستندات والقواعد المطبقة.'], ['هل معاش الإمارات أو السعودية أو الخليج خاضع للضريبة في تركيا؟', 'يعتمد ذلك على نوع المعاش، الإقامة، بلد المصدر والقواعد النهائية. يجب تحليل كل حالة بشكل مستقل.'], ['هل تصريح الإقامة يكفي لتغيير الإقامة الضريبية؟', 'لا. الإقامة الضريبية تعتمد على الحياة الفعلية، عدد الأيام، العائلة، السكن، الأصول ومركز المصالح.'], ['هل يمكن تحويل المعاش إلى حساب تركي؟', 'نعم، لكن البنك قد يطلب إثبات المعاش، مصدر الأموال، كشوفات، شهادة إقامة ضريبية، ترجمات وتصديقات.'], ['هل يجب شراء عقار فوراً عند التقاعد في تركيا؟', 'ليس دائماً. الإيجار أولاً قد يسمح باختبار المدينة والمستشفيات والحي والتكاليف ونمط الحياة.'], ['هل يقدم Bosphoras استشارة ضريبية؟', 'لا. Bosphoras ينسق المراجعة الخاصة ويربط العملاء بالمستشارين الضريبيين والمحامين والبنوك والتأمين وشركاء الانتقال.']],
  },
};

export function getForeignPensionTaxMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function ForeignPensionTaxClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
