import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/impot-dividendes-etrangers-turquie',
  en: '/en/foreign-dividends-tax-turkey',
  ru: '/ru/nalog-na-inostrannye-dividendy-v-turtsii',
  ar: '/ar/foreign-dividends-tax-turkey-arab-investors',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = {
  title: string;
  metaTitle: string;
  description: string;
  eyebrow: string;
  hero: string;
  cta: string;
  asideTitle: string;
  finalTitle: string;
  finalText: string;
  faqTitle: string;
  checklist: string[];
  sections: Array<[string, string]>;
  faq: Array<[string, string]>;
};

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Impôt sur les dividendes étrangers en Turquie : résidence fiscale, société étrangère et investisseurs',
    metaTitle: 'Impôt sur les dividendes étrangers en Turquie : investisseurs 2026',
    description: 'Dividendes étrangers en Turquie : résidence fiscale, société étrangère, retenue à la source, convention fiscale, exonération potentielle de 20 ans et stratégie pour entrepreneurs, actionnaires et investisseurs.',
    eyebrow: 'Dividendes étrangers · Fiscalité Turquie',
    hero: 'Recevoir des dividendes d’une société étrangère tout en vivant en Turquie peut devenir une question fiscale importante. Si vous envisagez de devenir résident fiscal en Turquie, il faut comprendre comment vos dividendes étrangers seront traités, dans quel pays ils peuvent être imposés et quels justificatifs seront nécessaires.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant de distribuer vos dividendes',
    finalTitle: 'Vos dividendes doivent être préparés avant le changement de résidence',
    finalText: 'Avant de changer de résidence ou de distribuer vos dividendes, Bosphoras peut organiser une analyse privée de votre situation : société, dividendes, retenue à la source, convention fiscale, résidence, banque, conformité et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Le pays de votre société distributrice', 'Votre résidence fiscale réelle', 'La retenue à la source éventuelle', 'La convention fiscale applicable', 'La direction effective de la société', 'Le calendrier de distribution', 'La banque et les justificatifs demandés', 'La cohérence de votre installation en Turquie'],
    sections: [
      ['Pourquoi les dividendes étrangers doivent être analysés avant votre installation', 'Les dividendes ne sont pas de simples virements bancaires. Ils sont liés à une société, à un pays de source, à une fiscalité locale, à une éventuelle convention fiscale et à votre propre résidence fiscale. Avant de vous installer en Turquie, il faut comprendre où se trouve la société qui verse les dividendes, où elle réalise ses bénéfices, où elle est réellement dirigée, quel pays peut prélever une retenue à la source, quelle convention fiscale s’applique, si vous êtes encore résident fiscal de votre pays d’origine et à quelle date les dividendes sont décidés et versés.'],
      ['Résidence fiscale en Turquie : le point de départ', 'Avant de savoir si vos dividendes étrangers peuvent bénéficier d’un traitement favorable en Turquie, il faut d’abord déterminer si vous devenez réellement résident fiscal turc. La résidence fiscale ne se résume pas à une carte de résidence, à un logement à Istanbul ou à un compte bancaire turc. Elle dépend de votre situation réelle : où vous vivez principalement, où vit votre famille, où se trouve votre foyer, où sont vos sociétés, vos comptes bancaires, vos principaux actifs et votre centre d’intérêts économiques.'],
      ['Ce que la nouvelle exonération turque pourrait changer', 'La Turquie a annoncé une mesure visant certains nouveaux résidents, avec une exonération potentielle de longue durée sur certains revenus et gains de source étrangère. Dans ce contexte, les dividendes étrangers peuvent devenir un sujet très intéressant. Un dividende versé par une société étrangère pourrait être considéré comme un revenu de source étrangère, mais cela ne doit jamais être supposé automatiquement. Il faut vérifier le texte final, la nature du dividende, le pays de la société distributrice, la résidence fiscale de l’actionnaire, la convention fiscale, la date de distribution et la retenue à la source éventuelle.'],
      ['Un dividende étranger peut concerner plusieurs pays', 'Un dividende étranger peut être analysé dans plusieurs pays à la fois. Si vous vivez en Turquie et recevez des dividendes d’une société française, il faut regarder la fiscalité française, la retenue à la source éventuelle, la convention France-Turquie, votre résidence fiscale réelle, le traitement du dividende en Turquie, la date de distribution et les justificatifs demandés par la banque. Si vous recevez des dividendes d’actions américaines, britanniques, suisses, émiraties ou kazakhes, l’analyse sera différente.'],
      ['Société étrangère ou société dirigée depuis la Turquie ?', 'Une société peut être juridiquement étrangère, mais poser des questions fiscales si elle est réellement dirigée depuis la Turquie. Vous pouvez conserver une société en France, au Royaume-Uni, aux Émirats, au Kazakhstan ou à Hong Kong tout en vivant à Istanbul. Mais si les décisions importantes sont prises depuis la Turquie, si les contrats sont négociés depuis la Turquie, si l’équipe dirigeante vit en Turquie ou si l’activité est pilotée depuis la Turquie, il faut analyser le risque de direction effective.'],
      ['Dividendes français : attention à la France', 'Si vous êtes Français ou francophone avec une société en France, le sujet est particulièrement important. Vous pouvez conserver une SAS, une SARL, une holding française, des actions françaises, une société familiale ou une société opérationnelle en France. Même si vous devenez résident fiscal en Turquie, la France peut conserver certains droits d’imposition sur les dividendes de source française. Il faut vérifier si vous êtes réellement non-résident fiscal français, si la France applique une retenue à la source, si la convention France-Turquie limite cette retenue et à quel moment le dividende sera distribué.'],
      ['Dividendes de holding étrangère', 'Si vous détenez une holding, l’analyse doit être encore plus précise. Une holding peut être située en France, au Luxembourg, aux Pays-Bas, aux Émirats, à Chypre, à Malte, au Royaume-Uni, à Singapour, à Hong Kong ou ailleurs. Mais sa localisation juridique ne suffit pas. Il faut vérifier si elle a une vraie fonction, où sont prises les décisions, où sont les administrateurs, où est la banque, quels revenus elle remonte, quelles conventions fiscales s’appliquent, s’il existe un risque anti-abus et si la structure est compréhensible pour les banques.'],
      ['Dividendes d’actions cotées et portefeuille financier', 'Tous les dividendes ne viennent pas d’une société que vous contrôlez. Vous pouvez aussi recevoir des dividendes à travers des actions américaines, européennes, britanniques, des ETF distribuants, des fonds internationaux, un portefeuille bancaire, une banque privée ou un compte-titres étranger. Dans ce cas, il faut analyser le pays de l’émetteur, la retenue à la source, le pays du dépositaire bancaire, votre résidence fiscale, les formulaires fiscaux transmis à la banque, le traitement du dividende en Turquie et les justificatifs demandés lors du transfert des fonds.'],
      ['Le calendrier de distribution est essentiel', 'La date à laquelle les dividendes sont décidés et versés peut changer l’analyse. Il faut distinguer un dividende distribué avant l’installation en Turquie, pendant une période de transition, après l’installation, décidé avant le départ mais payé après, issu de bénéfices accumulés avant l’installation ou issu de bénéfices générés après l’installation. Ce calendrier doit être préparé avant le changement de résidence. Distribuer trop tôt, trop tard ou sans coordination peut créer une imposition inattendue, une double imposition ou une difficulté bancaire.'],
      ['Retenue à la source : le pays de la société peut prélever un impôt', 'Même si la Turquie applique un traitement favorable à certains dividendes étrangers, le pays de la société distributrice peut prélever une retenue à la source. Une société française, américaine, suisse, britannique, émiratie, kazakhe ou européenne peut avoir ses propres règles. Il faut donc toujours poser deux questions : la Turquie impose-t-elle ce dividende, et le pays de source prélève-t-il un impôt avant que le dividende arrive ?'],
      ['Banque, conformité et origine des fonds', 'Recevoir des dividendes étrangers n’est pas seulement une question fiscale. C’est aussi une question bancaire. Une banque peut demander les statuts de la société, les procès-verbaux de distribution, les déclarations fiscales, la preuve de détention des actions, les états financiers, la preuve d’origine des fonds, le certificat de résidence fiscale et l’explication de la structure. Un dossier bien préparé facilite l’ouverture de compte, la réception des fonds, l’achat immobilier, l’assurance, les transferts internationaux et la relation bancaire.'],
      ['Les erreurs à éviter', 'La première erreur est de penser que des dividendes sont automatiquement exonérés parce que la société est étrangère. La deuxième est de croire qu’un changement de résidence en Turquie supprime automatiquement l’impôt dans le pays de la société. La troisième est de distribuer les dividendes sans réfléchir au calendrier. La quatrième est de négliger la banque et les justificatifs d’origine des fonds. La cinquième est de croire qu’une holding règle tous les sujets sans analyse.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste ou un expert-comptable. Notre rôle est de coordonner votre dossier et de vous aider à poser les bonnes questions avant de prendre une décision. Bosphoras peut organiser l’analyse de votre résidence fiscale, la cartographie de vos sociétés et participations, l’identification des dividendes attendus, l’analyse du pays de source, la coordination avec fiscalistes français, turcs ou internationaux, la préparation bancaire, la conformité, l’installation en Turquie, l’assurance santé, l’accompagnement immobilier et la coordination familiale.'],
    ],
    faq: [['Les dividendes étrangers sont-ils imposables en Turquie ?', 'Si vous êtes résident fiscal en Turquie, vos revenus mondiaux peuvent en principe être concernés. Le nouveau régime annoncé pourrait créer une exception pour certains revenus étrangers de nouveaux résidents, mais cela doit être confirmé selon le texte final et votre situation.'], ['La nouvelle exonération de 20 ans couvre-t-elle les dividendes étrangers ?', 'Potentiellement, si les dividendes entrent bien dans les revenus de source étrangère couverts par le texte final et si votre profil respecte les conditions.'], ['Une société française peut-elle verser des dividendes à un résident fiscal turc ?', 'Oui, mais il faut analyser la fiscalité française, la retenue à la source, la convention France-Turquie et le traitement du dividende côté turc.'], ['Une holding étrangère suffit-elle à éviter l’impôt ?', 'Non. Une holding doit avoir une vraie logique économique et une structure cohérente. Il faut analyser la substance, la direction effective, la banque, les conventions fiscales et les règles anti-abus.'], ['Le pays de source peut-il prélever un impôt même si la Turquie exonère ?', 'Oui. Une exonération en Turquie ne supprime pas automatiquement une retenue à la source dans le pays qui verse le dividende.'], ['Bosphoras donne-t-il un conseil fiscal ?', 'Non. Bosphoras coordonne l’analyse privée et les bons interlocuteurs : fiscalistes, avocats, banques, comptables, assurance, immobilier et partenaires d’installation en Turquie.']],
  },
  en: {
    title: 'Foreign Dividends Tax in Turkey: companies, investors and tax residence',
    metaTitle: 'Foreign Dividends Tax Turkey: Investor Guide 2026',
    description: 'Foreign dividends in Turkey: tax residence, foreign companies, withholding tax, tax treaties, potential 20-year exemption and planning for founders, shareholders and investors.',
    eyebrow: 'Foreign dividends · Turkey tax',
    hero: 'Receiving dividends from a foreign company while living in Turkey can become a major tax question. If you are considering Turkish tax residence, you need to understand how foreign dividends may be treated, which country may tax them and what documents banks and advisors may require.',
    cta: 'Request a private assessment',
    asideTitle: 'Before distributing dividends',
    finalTitle: 'Foreign dividends should be planned before changing residence',
    finalText: 'Before changing residence or distributing dividends, Bosphoras can organize a private review of your situation: company, dividends, withholding tax, treaty position, residence, banking, compliance and relocation to Turkey.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Country of the distributing company', 'Your real tax residence', 'Potential withholding tax', 'Applicable tax treaty', 'Effective management of the company', 'Dividend distribution calendar', 'Banking and supporting documents', 'Consistency of your relocation to Turkey'],
    sections: [
      ['Why foreign dividends should be reviewed before relocation', 'Dividends are not simple bank transfers. They are linked to a company, a source country, local taxation, a possible tax treaty and your own tax residence. Before relocating to Turkey, you should understand where the distributing company is located, where it generates profits, where it is effectively managed, which country may levy withholding tax, which treaty applies, whether your former country can still tax you and when the dividends are declared and paid.'],
      ['Turkish tax residence: the starting point', 'Before determining whether foreign dividends may benefit from favorable treatment in Turkey, you must first know whether you are truly becoming a Turkish tax resident. Tax residence is not just a residence permit, an apartment in Istanbul or a Turkish bank account. It depends on where you mainly live, where your family lives, where your companies, bank accounts, main assets and center of economic interests are located.'],
      ['What the new Turkish exemption could change', 'Turkey has announced a measure for certain new residents, with a potential long-term exemption on some foreign-source income and gains. In this context, foreign dividends may become highly relevant. A dividend paid by a foreign company could be considered foreign-source income, but this should never be assumed automatically. The final text, the nature of the dividend, the country of the distributing company, shareholder residence, the applicable treaty, distribution date and withholding tax must all be reviewed.'],
      ['A foreign dividend can involve several countries', 'A foreign dividend may need to be analyzed in several countries at the same time. If you live in Turkey and receive dividends from a UK, US, UAE, Swiss, Singapore, Hong Kong or European company, the analysis will vary. Each country may have its own withholding tax rules, reporting requirements, tax treaty provisions and evidence of residence.'],
      ['Foreign company or company managed from Turkey?', 'A company may be legally foreign but raise tax questions if it is effectively managed from Turkey. You may keep a company in the UK, the UAE, the United States, Singapore, Hong Kong or Cyprus while living in Istanbul. But if important decisions are taken from Turkey, contracts are negotiated from Turkey or the management team lives in Turkey, effective management risk should be reviewed.'],
      ['Holding companies and shareholder structures', 'If you hold shares through a holding company, the analysis becomes more technical. A holding may be located in the UAE, Cyprus, Luxembourg, the Netherlands, the UK, Singapore or Hong Kong. Its legal address is not enough. Substance, decision-making, directors, bank accounts, income flows, treaty access, anti-abuse rules and banking clarity must all be reviewed.'],
      ['Listed shares and private banking portfolios', 'Not all dividends come from a company you control. You may receive dividends from US stocks, European shares, UK companies, distributing ETFs, international funds, private banking portfolios or foreign brokerage accounts. The analysis then focuses on the issuer country, withholding tax, custodian bank, your tax residence, bank forms, potential tax credits and Turkish treatment if you become resident.'],
      ['Distribution timing matters', 'The date when dividends are declared and paid can change the outcome. You should distinguish dividends distributed before relocation, during a transition period, after Turkish residence begins, decided before departure but paid after, paid out of profits accumulated before relocation or generated after relocation. Timing should be prepared before changing residence.'],
      ['Withholding tax in the source country', 'Even if Turkey applies favorable treatment to certain foreign dividends, the country of the distributing company may levy withholding tax. A US, UK, Swiss, UAE, Singapore or European company can have its own rules. The right questions are not only whether Turkey taxes the dividend, but also whether the source country taxes it before it arrives.'],
      ['Banking, compliance and source of funds', 'Receiving foreign dividends is also a banking and compliance matter. Banks may request company documents, dividend resolutions, tax filings, proof of share ownership, financial statements, source-of-funds evidence, a tax residence certificate and an explanation of the structure. A prepared file helps with account opening, incoming transfers, real estate purchases, insurance and international banking relationships.'],
      ['Mistakes to avoid', 'Do not assume that dividends are automatically exempt because the company is foreign. Do not assume that moving to Turkey removes tax in the company’s country. Do not distribute dividends without reviewing the calendar. Do not ignore banking evidence and source of funds. Do not assume that a holding company solves every issue without analysis.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers or accountants. Its role is to coordinate the file and help you ask the right questions before making a decision. Bosphoras can organize residence analysis, company mapping, expected dividend review, source-country analysis, coordination with Turkish and international tax advisors, banking preparation, compliance, relocation, health insurance, real estate support and family coordination.'],
    ],
    faq: [['Are foreign dividends taxable in Turkey?', 'If you are Turkish tax resident, worldwide income may generally be relevant. The announced regime may create an exception for certain foreign income of new residents, but this depends on the final text and your situation.'], ['Could the 20-year exemption cover foreign dividends?', 'Potentially, if dividends fall within the foreign-source income covered by the final rules and your profile qualifies.'], ['Can a foreign company pay dividends to a Turkish tax resident?', 'Yes, but source-country tax, withholding tax, the applicable treaty and Turkish treatment must be reviewed.'], ['Is a foreign holding enough to avoid tax?', 'No. A holding must have economic purpose and a coherent structure. Substance, effective management, banking, treaties and anti-abuse rules must be reviewed.'], ['Can the source country tax dividends even if Turkey exempts them?', 'Yes. A Turkish exemption does not automatically remove withholding tax in the country paying the dividend.'], ['Does Bosphoras provide tax advice?', 'No. Bosphoras coordinates the private review and connects clients with suitable tax advisors, lawyers, banks, accountants and relocation partners.']],
  },
  ru: {
    title: 'Налог на иностранные дивиденды в Турции: компании, инвесторы и налоговая резиденция',
    metaTitle: 'Налог на иностранные дивиденды в Турции: гид 2026',
    description: 'Иностранные дивиденды в Турции: налоговая резиденция, иностранные компании, удержание у источника, соглашения, потенциальное освобождение и планирование для инвесторов.',
    eyebrow: 'Иностранные дивиденды · Налоги Турции',
    hero: 'Получение дивидендов от иностранной компании при жизни в Турции может стать важным налоговым вопросом. Перед переездом нужно понять, как будут рассматриваться иностранные дивиденды, какая страна может удержать налог и какие документы потребуют банки.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед распределением дивидендов',
    finalTitle: 'Дивиденды нужно планировать до смены резиденции',
    finalText: 'До смены резиденции или распределения дивидендов Bosphoras может организовать частный анализ вашей ситуации: компания, дивиденды, удержание у источника, соглашение, резиденция, банк, compliance и переезд в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Страна компании, выплачивающей дивиденды', 'Ваша реальная налоговая резиденция', 'Возможное удержание налога у источника', 'Применимое налоговое соглашение', 'Фактическое управление компанией', 'Календарь распределения дивидендов', 'Банк и подтверждающие документы', 'Логика вашего переезда в Турцию'],
    sections: [
      ['Почему иностранные дивиденды нужно анализировать до переезда', 'Дивиденды — это не просто банковский перевод. Они связаны с компанией, страной источника, локальным налогообложением, возможным налоговым соглашением и вашей собственной налоговой резиденцией. До переезда в Турцию нужно понять, где находится компания, где она получает прибыль, где фактически управляется, какая страна может удержать налог у источника, какое соглашение применяется, сохраняет ли прежняя страна право налогообложения и когда дивиденды объявляются и выплачиваются.'],
      ['Налоговая резиденция Турции: отправная точка', 'Прежде чем понять, могут ли иностранные дивиденды получить благоприятный режим в Турции, нужно определить, становитесь ли вы реально налоговым резидентом Турции. Резиденция — это не только ВНЖ, квартира в Стамбуле или турецкий счет. Важны место жизни, семья, компании, банковские счета, основные активы и центр экономических интересов.'],
      ['Что может изменить новое турецкое освобождение', 'Турция объявила меру для отдельных новых резидентов с потенциальным долгосрочным освобождением некоторых иностранных доходов и gains. В этом контексте иностранные дивиденды становятся важной темой. Дивиденд от иностранной компании может считаться иностранным доходом, но это нельзя предполагать автоматически. Нужно проверять финальный текст, природу дивиденда, страну компании, резиденцию акционера, соглашение, дату выплаты и удержание у источника.'],
      ['Иностранный дивиденд может касаться нескольких стран', 'Иностранный дивиденд может анализироваться сразу в нескольких странах. Если вы живете в Турции и получаете дивиденды из компании в Казахстане, ОАЭ, Европе, США, Великобритании, Швейцарии или другой стране, анализ будет различаться. У каждой страны могут быть собственные правила удержания, отчетности, соглашений и подтверждения резиденции.'],
      ['Иностранная компания или компания, управляемая из Турции?', 'Компания может юридически быть иностранной, но вызывать налоговые вопросы, если фактически управляется из Турции. Можно сохранить компанию в Казахстане, ОАЭ, Великобритании, США, Сингапуре или Гонконге, живя в Стамбуле. Но если важные решения принимаются из Турции, договоры обсуждаются из Турции или руководство живет в Турции, нужно анализировать риск фактического управления.'],
      ['Холдинги и структура акционера', 'Если вы владеете долями через холдинг, анализ становится более техническим. Холдинг может находиться в ОАЭ, Кипре, Люксембурге, Нидерландах, Великобритании, Сингапуре, Гонконге или Казахстане. Юридического адреса недостаточно. Нужно анализировать substance, решения, директоров, банки, потоки доходов, доступ к соглашениям, антиабузные правила и понятность структуры для банков.'],
      ['Публичные акции и инвестиционный портфель', 'Не все дивиденды поступают от контролируемой компании. Вы можете получать дивиденды по акциям США, Европы, Великобритании, ETF, фондам, портфелю private banking или иностранному брокерскому счету. Анализ касается страны эмитента, удержания у источника, депозитария, вашей налоговой резиденции, банковских форм, возможных налоговых кредитов и турецкого режима после переезда.'],
      ['Календарь выплаты имеет значение', 'Дата объявления и выплаты дивидендов может изменить результат. Нужно различать дивиденды до переезда, во время переходного периода, после начала турецкой резиденции, объявленные до отъезда, но выплаченные после, выплаченные из прибыли прошлых лет или из прибыли, созданной после переезда. Календарь лучше готовить до смены резиденции.'],
      ['Удержание налога в стране источника', 'Даже если Турция применит благоприятный режим к некоторым иностранным дивидендам, страна компании может удержать налог у источника. Компания в Казахстане, США, Великобритании, Швейцарии, ОАЭ или Европе может иметь свои правила. Важно спрашивать не только облагает ли Турция дивиденд, но и удерживает ли налог страна источника до поступления средств.'],
      ['Банки, compliance и происхождение средств', 'Иностранные дивиденды — это также банковский и compliance-вопрос. Банки могут запросить документы компании, решения о распределении, налоговые декларации, подтверждение владения акциями, финансовую отчетность, источник средств, сертификат налоговой резиденции и объяснение структуры. Подготовленный файл облегчает счета, переводы, покупку недвижимости, страхование и банковские отношения.'],
      ['Ошибки, которых нужно избегать', 'Не стоит считать, что дивиденды автоматически освобождены, потому что компания иностранная. Не стоит считать, что переезд в Турцию отменяет налог в стране компании. Не нужно распределять дивиденды без анализа календаря. Нельзя игнорировать банковские доказательства и происхождение средств. Холдинг также не решает все вопросы без анализа.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов или бухгалтеров. Его роль — координировать файл и помочь задать правильные вопросы до решения. Bosphoras может организовать анализ резиденции, карту компаний, ожидаемые дивиденды, анализ страны источника, координацию с турецкими и международными налоговыми специалистами, подготовку банка, compliance, переезд, страхование, недвижимость и семейную координацию.'],
    ],
    faq: [['Облагаются ли иностранные дивиденды в Турции?', 'Если вы налоговый резидент Турции, мировой доход может быть релевантен. Объявленный режим может создать исключение для отдельных иностранных доходов новых резидентов, но это зависит от финального текста и вашей ситуации.'], ['Может ли освобождение на 20 лет охватывать иностранные дивиденды?', 'Потенциально, если дивиденды попадут в иностранные доходы, охваченные финальными правилами, и ваш профиль соответствует условиям.'], ['Может ли иностранная компания платить дивиденды резиденту Турции?', 'Да, но нужно анализировать налог страны источника, удержание, соглашение и турецкий режим.'], ['Достаточно ли иностранного холдинга для избежания налога?', 'Нет. Холдинг должен иметь экономическую цель и понятную структуру. Нужно анализировать substance, фактическое управление, банки, соглашения и антиабузные правила.'], ['Может ли страна источника удержать налог, даже если Турция освобождает дивиденды?', 'Да. Освобождение в Турции не отменяет автоматически удержание налога в стране, выплачивающей дивиденд.'], ['Bosphoras дает налоговую консультацию?', 'Нет. Bosphoras координирует частный анализ и связывает клиентов с подходящими налоговыми специалистами, юристами, банками, бухгалтерами и партнерами по переезду.']],
  },
  ar: {
    title: 'ضريبة الأرباح الأجنبية في تركيا للمستثمرين العرب',
    metaTitle: 'ضريبة الأرباح الأجنبية في تركيا للمستثمرين العرب 2026',
    description: 'الأرباح الأجنبية في تركيا للمستثمرين العرب: الإقامة الضريبية، الشركات الخليجية والدولية، الضريبة المقتطعة، الاتفاقيات، البنوك ومصدر الأموال.',
    eyebrow: 'الأرباح الأجنبية · المستثمرون العرب',
    hero: 'تلقي أرباح من شركة أجنبية أثناء العيش في تركيا قد يصبح موضوعاً ضريبياً وبنكياً مهماً. إذا كنت مستثمراً عربياً أو تملك شركة في الخليج أو خارج تركيا، يجب فهم كيفية التعامل مع هذه الأرباح قبل نقل الإقامة أو توزيع الأموال.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل توزيع الأرباح',
    finalTitle: 'الأرباح الأجنبية يجب تنظيمها قبل نقل الإقامة',
    finalText: 'قبل تغيير الإقامة أو توزيع الأرباح، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك: الشركة، الأرباح، الضريبة المقتطعة، الاتفاقية الضريبية، الإقامة، البنك، الامتثال والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['بلد الشركة التي توزع الأرباح', 'إقامتك الضريبية الفعلية', 'الضريبة المقتطعة المحتملة', 'الاتفاقية الضريبية المطبقة', 'الإدارة الفعلية للشركة', 'توقيت توزيع الأرباح', 'البنك والمستندات المطلوبة', 'انسجام انتقالك إلى تركيا'],
    sections: [
      ['لماذا يجب تحليل الأرباح الأجنبية قبل الانتقال', 'الأرباح ليست مجرد تحويل بنكي. إنها مرتبطة بشركة، بلد مصدر، ضرائب محلية، اتفاقية ضريبية محتملة وإقامتك الضريبية. قبل الانتقال إلى تركيا يجب فهم أين توجد الشركة التي توزع الأرباح، أين تحقق أرباحها، أين تدار فعلياً، أي بلد قد يقتطع ضريبة، أي اتفاقية تنطبق، وهل لا يزال بلدك السابق قادراً على فرض ضريبة عليك ومتى يتم إعلان ودفع الأرباح.'],
      ['الإقامة الضريبية في تركيا هي نقطة البداية', 'قبل معرفة ما إذا كانت الأرباح الأجنبية قد تستفيد من معاملة ملائمة في تركيا، يجب أولاً تحديد ما إذا كنت ستصبح فعلاً مقيماً ضريبياً في تركيا. الإقامة الضريبية ليست مجرد تصريح إقامة أو شقة في إسطنبول أو حساب بنكي تركي. إنها تعتمد على مكان حياتك الفعلي، العائلة، الشركات، الحسابات البنكية، الأصول الرئيسية ومركز المصالح الاقتصادية.'],
      ['ما الذي قد يغيره الإعفاء التركي الجديد', 'أعلنت تركيا عن إجراء لبعض المقيمين الجدد، مع إعفاء محتمل طويل الأجل على بعض الدخل والمكاسب من مصدر أجنبي. في هذا السياق، تصبح الأرباح الأجنبية مهمة جداً. قد تعتبر الأرباح المدفوعة من شركة أجنبية دخلاً من مصدر أجنبي، لكن لا يجب افتراض ذلك تلقائياً. يجب مراجعة النص النهائي، طبيعة الأرباح، بلد الشركة، إقامة المساهم، الاتفاقية، تاريخ التوزيع والضريبة المقتطعة.'],
      ['الأرباح الأجنبية قد تخص عدة دول', 'قد يتم تحليل الأرباح الأجنبية في عدة دول في الوقت نفسه. إذا كنت تعيش في تركيا وتتلقى أرباحاً من شركة في الإمارات، السعودية، قطر، الكويت، البحرين، أوروبا، الولايات المتحدة أو دولة أخرى، فسيختلف التحليل. لكل بلد قواعده في الضريبة المقتطعة، التصريح، الاتفاقيات وإثبات الإقامة.'],
      ['شركة أجنبية أو شركة تدار من تركيا؟', 'قد تكون الشركة أجنبية قانونياً لكنها تثير أسئلة ضريبية إذا كانت تدار فعلياً من تركيا. يمكنك الاحتفاظ بشركة في الإمارات أو السعودية أو قطر أو الكويت أو البحرين أو أوروبا أثناء العيش في إسطنبول. لكن إذا كانت القرارات المهمة تتخذ من تركيا، أو العقود تفاوض من تركيا، أو الإدارة تعيش في تركيا، يجب تحليل خطر الإدارة الفعلية.'],
      ['الهولدينغ وهيكل المساهم', 'إذا كنت تملك الأسهم عبر holding، يصبح التحليل أكثر تقنية. قد يكون الهولدينغ في الإمارات، البحرين، قطر، أوروبا، سنغافورة، هونغ كونغ أو غيرها. العنوان القانوني لا يكفي. يجب تحليل الوظيفة الاقتصادية، القرارات، المديرين، البنوك، تدفقات الدخل، الاتفاقيات، قواعد مكافحة الإساءة ومدى وضوح الهيكل للبنوك.'],
      ['الأسهم المدرجة والمحافظ الاستثمارية', 'ليست كل الأرباح من شركة تسيطر عليها. قد تتلقى أرباحاً من أسهم أمريكية، أوروبية، بريطانية، ETF، صناديق دولية، محفظة بنك خاص أو حساب وساطة أجنبي. هنا يتركز التحليل على بلد المصدر، الضريبة المقتطعة، البنك الحافظ، إقامتك الضريبية، النماذج البنكية، أي ائتمان ضريبي محتمل والمعاملة في تركيا بعد الإقامة.'],
      ['توقيت توزيع الأرباح مهم', 'تاريخ إعلان ودفع الأرباح قد يغير النتيجة. يجب التمييز بين أرباح موزعة قبل الانتقال إلى تركيا، أثناء مرحلة انتقالية، بعد بداية الإقامة التركية، أرباح تقررت قبل المغادرة ودُفعت بعدها، أرباح من سنوات سابقة أو أرباح ناتجة بعد الانتقال. يجب تحضير التوقيت قبل تغيير الإقامة.'],
      ['الضريبة المقتطعة في بلد المصدر', 'حتى إذا طبقت تركيا معاملة ملائمة لبعض الأرباح الأجنبية، قد يقتطع بلد الشركة ضريبة من المصدر. شركة في الإمارات أو السعودية أو قطر أو الكويت أو أوروبا أو الولايات المتحدة قد يكون لديها قواعد خاصة. السؤال ليس فقط هل تفرض تركيا ضريبة، بل أيضاً هل يقتطع بلد المصدر ضريبة قبل وصول الأرباح.'],
      ['البنوك والامتثال ومصدر الأموال', 'الأرباح الأجنبية موضوع بنكي وامتثال أيضاً. قد تطلب البنوك مستندات الشركة، قرارات توزيع الأرباح، التصريحات الضريبية، إثبات ملكية الأسهم، القوائم المالية، مصدر الأموال، شهادة الإقامة الضريبية وشرح الهيكل. ملف مرتب يسهل فتح الحسابات، التحويلات، شراء العقار، التأمين والعلاقة البنكية الدولية.'],
      ['أخطاء يجب تجنبها', 'لا يجب افتراض أن الأرباح معفاة تلقائياً لأن الشركة أجنبية. لا يجب افتراض أن الانتقال إلى تركيا يلغي الضريبة في بلد الشركة. لا يجب توزيع الأرباح دون مراجعة التوقيت. لا يجب تجاهل مستندات البنك ومصدر الأموال. ولا يجب الاعتقاد أن الهولدينغ يحل كل شيء دون تحليل.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامي الضريبي أو المحاسب. دوره هو تنسيق الملف ومساعدتك على طرح الأسئلة الصحيحة قبل القرار. يمكن لـ Bosphoras تنظيم تحليل الإقامة، خريطة الشركات، مراجعة الأرباح المتوقعة، تحليل بلد المصدر، التنسيق مع مستشارين أتراك ودوليين، التحضير البنكي، الامتثال، الانتقال، التأمين الصحي، العقار والتنسيق العائلي.'],
    ],
    faq: [['هل الأرباح الأجنبية خاضعة للضريبة في تركيا؟', 'إذا كنت مقيماً ضريبياً في تركيا، فقد يكون الدخل العالمي ذا صلة. النظام المعلن قد ينشئ استثناءً لبعض الدخل الأجنبي للمقيمين الجدد، لكن ذلك يعتمد على النص النهائي ووضعك.'], ['هل يمكن أن يشمل إعفاء 20 سنة الأرباح الأجنبية؟', 'محتمل إذا دخلت الأرباح ضمن الدخل الأجنبي المشمول بالقواعد النهائية وكان ملفك مؤهلاً.'], ['هل يمكن لشركة في الخليج دفع أرباح لمقيم ضريبي في تركيا؟', 'نعم، لكن يجب تحليل ضريبة بلد المصدر، الضريبة المقتطعة، الاتفاقية الضريبية والمعاملة في تركيا.'], ['هل يكفي الهولدينغ الأجنبي لتجنب الضريبة؟', 'لا. يجب أن يكون للهولدينغ هدف اقتصادي وهيكل واضح. يجب تحليل substance، الإدارة الفعلية، البنوك، الاتفاقيات وقواعد مكافحة الإساءة.'], ['هل يمكن لبلد المصدر اقتطاع ضريبة حتى لو أعفت تركيا الأرباح؟', 'نعم. الإعفاء في تركيا لا يلغي تلقائياً الضريبة المقتطعة في البلد الذي يدفع الأرباح.'], ['هل يقدم Bosphoras استشارة ضريبية؟', 'لا. Bosphoras ينسق المراجعة الخاصة ويربط العملاء بالمستشارين الضريبيين والمحامين والبنوك والمحاسبين وشركاء الانتقال المناسبين.']],
  },
};

export function getForeignDividendsTaxMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function ForeignDividendsTaxClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
