import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/plus-values-etrangeres-turquie-fiscalite',
  en: '/en/foreign-capital-gains-tax-turkey',
  ru: '/ru/inostrannye-prirosty-kapitala-turtsiya-nalogi',
  ar: '/ar/foreign-capital-gains-tax-turkey-arab-investors',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = {
  title: string;
  metaTitle: string;
  description: string;
  eyebrow: string;
  hero: string;
  cta: string;
  asideTitle: string;
  finalTitle: string;
  finalText: string;
  faqTitle: string;
  checklist: string[];
  sections: Array<[string, string]>;
  faq: Array<[string, string]>;
};

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Plus-values étrangères en Turquie : fiscalité, résidence et vente d’actifs hors de Turquie',
    metaTitle: 'Plus-values étrangères en Turquie : fiscalité investisseurs 2026',
    description: 'Plus-values étrangères en Turquie : vente d’actions, société, immobilier, portefeuille financier, résidence fiscale, convention fiscale et exonération potentielle pour nouveaux résidents.',
    eyebrow: 'Plus-values étrangères · Fiscalité Turquie',
    hero: 'Vendre des actifs à l’étranger tout en vivant en Turquie peut avoir des conséquences fiscales importantes. Si vous envisagez de devenir résident fiscal en Turquie, il faut préparer le calendrier, le pays de source, la résidence fiscale et les justificatifs avant de signer ou d’encaisser.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant de vendre un actif étranger',
    finalTitle: 'Une plus-value importante doit être préparée avant la vente',
    finalText: 'Avant de signer ou d’encaisser une plus-value importante, Bosphoras peut organiser une analyse privée de votre situation : actifs, résidence fiscale, calendrier, convention fiscale, banque, conformité, origine des fonds et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Le pays où se trouve l’actif vendu', 'Votre résidence fiscale au moment de la vente', 'La date d’acquisition et la date de vente', 'La nature exacte de l’actif', 'La convention fiscale applicable', 'Les plus-values latentes existantes', 'Les justificatifs bancaires et fiscaux', 'La cohérence de votre installation en Turquie'],
    sections: [
      ['Pourquoi les plus-values étrangères doivent être préparées avant votre installation', 'Une plus-value n’est pas seulement un bénéfice réalisé sur une vente. Elle dépend du pays où se trouve l’actif, du pays où vous êtes résident fiscal au moment de la vente, de la date d’acquisition, de la date de vente, du prix d’achat, du prix de vente, de la nature exacte de l’actif, de la convention fiscale applicable et des règles de votre pays d’origine. Une vente réalisée avant le départ, pendant la transition ou après l’installation en Turquie peut produire des résultats différents.'],
      ['Résidence fiscale : le point de départ', 'Avant de savoir si une plus-value étrangère peut être traitée favorablement en Turquie, il faut d’abord savoir où vous êtes réellement résident fiscal au moment de la vente. La résidence fiscale ne se limite pas à une carte de résidence, à un logement ou à un compte bancaire. Elle dépend de votre lieu de vie principal, de votre famille, de votre foyer, de vos sociétés, de vos actifs, de vos comptes bancaires, de vos décisions importantes et de votre centre d’intérêts économiques.'],
      ['Ce que la mesure turque pourrait changer', 'La mesure annoncée par la Turquie vise certains nouveaux résidents et pourrait concerner des revenus et gains de source étrangère. Cela peut inclure, selon le texte final, certaines plus-values réalisées sur des actifs étrangers. Mais il faut vérifier le texte définitif, la nature de l’actif vendu, le pays où l’actif est situé, la résidence fiscale du vendeur, la date de vente, la convention fiscale applicable, l’existence d’une imposition dans le pays de source et les justificatifs nécessaires.'],
      ['Vente d’actions étrangères', 'La vente d’actions étrangères est l’un des cas les plus fréquents. Vous pouvez vendre des actions cotées américaines, européennes, britanniques, des titres détenus via une banque privée, des ETF, des participations minoritaires ou des titres détenus dans un portefeuille international. Il faut analyser le pays de l’émetteur, le pays du compte-titres, votre résidence fiscale au moment de la vente, la convention fiscale, les dates d’acquisition et de vente, les justificatifs bancaires et l’éventuelle imposition dans le pays de source.'],
      ['Vente de parts de société ou d’entreprise', 'Si vous vendez une société ou des parts de société, l’analyse devient plus sensible. Il faut vérifier où la société est immatriculée, où elle exerce réellement son activité, où elle est effectivement dirigée, où se trouvent ses clients, ses actifs principaux, son équipe et ses contrats. Une société peut être étrangère juridiquement, mais si elle est dirigée depuis la Turquie ou si son activité est liée à un autre pays, l’analyse peut devenir plus complexe.'],
      ['Vente d’un bien immobilier situé hors de Turquie', 'Les plus-values immobilières sont souvent traitées différemment des plus-values financières. Si vous vendez un appartement, une villa, un immeuble ou un local commercial situé hors de Turquie, le pays où se trouve le bien peut conserver un droit d’imposition. Même si vous vivez en Turquie, le pays de situation du bien peut demander une déclaration et prélever un impôt sur la plus-value.'],
      ['Vente de participation dans une holding', 'La vente de parts d’une holding étrangère doit être analysée avec prudence. Une holding peut détenir des sociétés opérationnelles, des actifs immobiliers, des portefeuilles financiers, des participations familiales ou des droits économiques dans plusieurs pays. La fiscalité peut dépendre du pays de la holding, des actifs sous-jacents, des conventions fiscales, des règles anti-abus, du lieu de direction effective, du pays de résidence du vendeur et du calendrier de vente.'],
      ['Le calendrier de vente est essentiel', 'Le moment de la vente peut changer l’analyse. Il faut distinguer une vente réalisée avant l’installation en Turquie, pendant une période de transition, après l’installation, avec promesse signée avant le départ, paiement reçu après l’installation, earn-out ou complément de prix payé plus tard. Une vente peut être décidée à une date, signée à une autre date et payée plus tard. Ces détails peuvent influencer la fiscalité, la banque, les justificatifs et la cohérence du dossier de résidence.'],
      ['Plus-values latentes avant l’installation', 'Si vous possédez déjà des actifs avec une forte plus-value latente, il faut les identifier avant de changer de résidence. Cela peut concerner des actions avec forte hausse, des parts de société, de l’immobilier ancien, un portefeuille financier, des crypto-actifs, une holding familiale ou des actifs professionnels. L’objectif n’est pas forcément de vendre avant le départ, mais de comprendre ce qui existe déjà et quel pays pourrait imposer la vente future.'],
      ['Pays d’origine : attention au départ fiscal', 'Votre pays d’origine peut continuer à s’intéresser à vos plus-values après votre départ si vous êtes encore considéré résident fiscal, si votre foyer reste dans le pays, si vos sociétés restent dirigées depuis ce pays, si vos principaux actifs y restent situés ou si vous êtes concerné par des obligations déclaratives de sortie. Pour un Français, la question de l’exit tax peut devenir importante dans certains cas de détention de participations.'],
      ['Banque, conformité et origine des fonds', 'Une plus-value étrangère importante peut entraîner des demandes bancaires. Une banque peut demander contrat de vente, preuve d’acquisition, preuve du prix de vente, déclarations fiscales, preuve de paiement de l’impôt, statuts de société, registre des actionnaires, relevés de portefeuille, acte de vente immobilier, justificatif d’origine des fonds, certificat de résidence fiscale et explication de la structure patrimoniale.'],
      ['Les erreurs à éviter', 'La première erreur est de vendre un actif important sans vérifier votre résidence fiscale au moment de la vente. La deuxième est de penser qu’une plus-value étrangère est automatiquement exonérée parce que vous vivez en Turquie. La troisième est d’oublier que le pays où se trouve l’actif peut conserver un droit d’imposition. La quatrième est de ne pas préparer les justificatifs bancaires. La cinquième est de signer, vendre ou encaisser pendant une période de transition mal documentée.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste, un notaire ou un expert-comptable. Notre rôle est de coordonner votre dossier et de vous aider à préparer les bonnes questions avant une vente importante ou un changement de résidence. Bosphoras peut organiser l’analyse de votre résidence fiscale, la cartographie de vos actifs étrangers, l’identification des plus-values latentes, l’analyse du calendrier de vente, la coordination avec fiscalistes turcs et internationaux, la préparation bancaire, la conformité et l’installation privée en Turquie.'],
    ],
    faq: [['Les plus-values étrangères sont-elles imposables en Turquie ?', 'Si vous êtes résident fiscal en Turquie, vos revenus et gains mondiaux peuvent en principe être concernés. La mesure annoncée pourrait créer une exception pour certains gains étrangers de nouveaux résidents, sous conditions.'], ['La nouvelle exonération de 20 ans peut-elle couvrir les plus-values étrangères ?', 'Potentiellement, si le texte final couvre les gains de source étrangère et si votre profil respecte les conditions. Il faut vérifier la nature de l’actif, la date de vente, le pays de source et les règles définitives.'], ['Une plus-value sur actions étrangères peut-elle être exonérée ?', 'Potentiellement, mais il faut analyser le pays de l’émetteur, le dépositaire, la résidence fiscale au moment de la vente, la convention fiscale et les justificatifs bancaires.'], ['Une plus-value immobilière hors de Turquie peut-elle rester imposable dans le pays du bien ?', 'Oui. Le pays où se trouve le bien immobilier peut conserver un droit d’imposition, même si vous vivez en Turquie.'], ['Faut-il vendre ses actifs avant de s’installer en Turquie ?', 'Pas forcément. Il faut d’abord analyser les plus-values latentes, le calendrier, la fiscalité du pays de source, votre résidence fiscale actuelle et votre future résidence en Turquie.'], ['Bosphoras donne-t-il un conseil fiscal ?', 'Non. Bosphoras coordonne l’analyse privée et les bons interlocuteurs : fiscalistes, avocats, banques, comptables, notaires, assurance, immobilier et partenaires d’installation en Turquie.']],
  },
  en: {
    title: 'Foreign Capital Gains Tax in Turkey: selling assets before or after relocation',
    metaTitle: 'Foreign Capital Gains Tax Turkey: Investor Guide 2026',
    description: 'Foreign capital gains in Turkey: sale of shares, companies, real estate, investment portfolios, tax residence, treaties and potential exemption for new residents.',
    eyebrow: 'Foreign capital gains · Turkey tax',
    hero: 'Selling foreign assets while living in Turkey can create important tax and banking consequences. Before selling shares, a company, real estate or an investment portfolio, you should understand how timing, tax residence, source country and documentation may affect the transaction.',
    cta: 'Request a private assessment',
    asideTitle: 'Before selling a foreign asset',
    finalTitle: 'A major capital gain should be reviewed before the sale',
    finalText: 'Before signing or receiving proceeds from a major sale, Bosphoras can organize a private review of your assets, tax residence, transaction calendar, treaty position, banking, compliance, source of funds and relocation to Turkey.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Country where the asset is located', 'Your tax residence at the sale date', 'Acquisition and sale dates', 'Exact nature of the asset', 'Applicable tax treaty', 'Existing unrealized gains', 'Banking and tax documents', 'Consistency of your relocation to Turkey'],
    sections: [
      ['Why foreign capital gains should be reviewed before relocation', 'A capital gain is not only the profit made on a sale. It depends on where the asset is located, where you are tax resident when the sale occurs, the acquisition date, sale date, purchase price, sale price, type of asset, applicable tax treaty, source-country rules and the rules of your former country. A sale before relocation, during a transition period or after becoming resident in Turkey may lead to different outcomes.'],
      ['Tax residence is the starting point', 'Before knowing whether a foreign capital gain may receive favorable treatment in Turkey, you must first determine where you are truly tax resident at the time of the sale. Tax residence is not just a residence permit, apartment or bank account. It depends on your real place of life, family, home, companies, assets, bank accounts, decision-making and center of economic interests.'],
      ['What the Turkish measure could change', 'Turkey has announced a measure for certain new residents that may cover foreign-source income and gains. Depending on the final rules, some gains on foreign assets may be relevant. But the final text, asset type, asset location, seller residence, sale date, applicable treaty, source-country taxation and supporting documents must all be reviewed.'],
      ['Sale of foreign shares', 'Selling foreign shares is one of the most common situations. You may sell US, European or UK listed shares, ETFs, private banking securities, minority interests or securities held in an international portfolio. The issuer country, brokerage or custodian country, your residence at the sale date, treaties, acquisition and sale dates, banking evidence and source-country rules must be documented.'],
      ['Sale of a company or company shares', 'If you sell a company or shares in a private company, the analysis becomes more sensitive. You should review where the company is incorporated, where it operates, where it is effectively managed, where clients are located, where its main assets sit, where the team is based and where contracts are signed. A company may be legally foreign while creating tax questions in another jurisdiction.'],
      ['Sale of real estate outside Turkey', 'Real estate gains are often treated differently from financial gains. If you sell an apartment, villa, building or commercial property outside Turkey, the country where the property is located may keep taxing rights. Even if you live in Turkey, that country may require a filing and tax payment on the gain.'],
      ['Sale of holding company shares', 'Selling shares in a foreign holding company requires caution. A holding may own operating companies, real estate, financial portfolios, family participations or economic rights in several countries. Tax treatment may depend on the holding jurisdiction, underlying assets, tax treaties, anti-abuse rules, effective management, seller residence and sale calendar.'],
      ['Timing of the sale matters', 'The sale date can change the result. You should distinguish a sale before relocation, during a transition period, after Turkish residence begins, a sale agreement signed before departure, proceeds received after relocation, an earn-out paid later or assets acquired before and after the residence change. These details may affect tax, banking documentation and consistency of the residence file.'],
      ['Unrealized gains before relocation', 'If you already own assets with large unrealized gains, they should be identified before changing residence. This may include appreciated shares, company interests, old real estate, financial portfolios, crypto-assets, family holdings or professional assets. The goal is not necessarily to sell before relocation, but to understand what already exists and which country may tax a future sale.'],
      ['Former country and exit issues', 'Your former country may still be interested in your capital gains after departure if you remain tax resident there, if your home or family remains there, if companies are still managed there, if major assets are located there or if exit reporting or anti-abuse rules apply. These issues should be reviewed before a sale is signed.'],
      ['Banking, compliance and source of funds', 'A significant foreign capital gain can trigger banking requests. Banks may ask for sale agreements, acquisition proof, sale price evidence, tax filings, proof of tax payment, company documents, shareholder registers, portfolio statements, property deeds, source-of-funds evidence, tax residence certificates and an explanation of your wealth structure.'],
      ['Mistakes to avoid', 'Do not sell a major asset without reviewing tax residence at the sale date. Do not assume that a foreign gain is automatically exempt because you live in Turkey. Do not forget that the country where the asset is located may tax the gain. Do not ignore banking evidence. Do not sign, sell or receive proceeds during a poorly documented transition period.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers, notaries or accountants. Its role is to coordinate the file and help prepare the right questions before a significant sale or change of residence. Bosphoras can organize residence analysis, asset mapping, review of unrealized gains, transaction calendar analysis, coordination with Turkish and international advisors, banking preparation, compliance and private relocation to Turkey.'],
    ],
    faq: [['Are foreign capital gains taxable in Turkey?', 'If you are Turkish tax resident, worldwide income and gains may generally be relevant. The announced measure may create an exception for certain foreign gains of new residents, subject to conditions.'], ['Could the 20-year exemption cover foreign capital gains?', 'Potentially, if the final rules cover foreign-source gains and your profile qualifies. Asset type, sale date, source country and final legislation must be reviewed.'], ['Can gains on foreign shares be exempt?', 'Potentially, but issuer country, custodian, residence at sale date, tax treaty and banking evidence must be reviewed.'], ['Can foreign real estate gains remain taxable in the property country?', 'Yes. The country where the property is located may keep taxing rights even if you live in Turkey.'], ['Should I sell assets before moving to Turkey?', 'Not necessarily. First review unrealized gains, timing, source-country taxation, current tax residence and future Turkish residence.'], ['Does Bosphoras provide tax advice?', 'No. Bosphoras coordinates the private review and connects clients with suitable tax advisors, lawyers, banks, accountants, notaries and relocation partners.']],
  },
  ru: {
    title: 'Иностранные приросты капитала в Турции: налоги, резиденция и продажа активов',
    metaTitle: 'Иностранные приросты капитала в Турции: налоги 2026',
    description: 'Иностранные приросты капитала в Турции: продажа акций, компаний, недвижимости, портфелей, налоговая резиденция, соглашения и потенциальное освобождение.',
    eyebrow: 'Иностранный прирост капитала · Налоги Турции',
    hero: 'Продажа активов за рубежом при жизни в Турции может иметь важные налоговые и банковские последствия. До продажи акций, бизнеса, недвижимости или инвестиционного портфеля нужно понять роль календаря, резиденции, страны источника и документов.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед продажей иностранного актива',
    finalTitle: 'Крупную plus-value нужно готовить до сделки',
    finalText: 'До подписания сделки или получения средств Bosphoras может организовать частный анализ ваших активов, налоговой резиденции, календаря сделки, соглашений, банка, compliance, происхождения средств и переезда в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Страна, где находится актив', 'Ваша резиденция на дату продажи', 'Даты покупки и продажи', 'Точная природа актива', 'Применимое налоговое соглашение', 'Существующие скрытые приросты', 'Банковские и налоговые документы', 'Логика вашего переезда в Турцию'],
    sections: [
      ['Почему иностранные приросты капитала нужно анализировать до переезда', 'Прирост капитала — это не просто прибыль от продажи. Он зависит от страны актива, вашей налоговой резиденции на дату сделки, даты приобретения, даты продажи, цены покупки, цены продажи, типа актива, налогового соглашения, правил страны источника и правил прежней страны. Сделка до переезда, в переходный период или после начала резиденции в Турции может дать разные результаты.'],
      ['Налоговая резиденция — отправная точка', 'Прежде чем понять, может ли иностранный прирост получить благоприятный режим в Турции, нужно определить, где вы реально являетесь налоговым резидентом на дату продажи. Важны не только ВНЖ, квартира или счет, а реальное место жизни, семья, дом, компании, активы, банки, принятие решений и центр экономических интересов.'],
      ['Что может изменить турецкая мера', 'Турция объявила меру для отдельных новых резидентов, которая может охватывать иностранные доходы и gains. В зависимости от финальных правил, некоторые приросты по иностранным активам могут быть релевантны. Но нужно проверять финальный текст, тип актива, страну актива, резиденцию продавца, дату продажи, соглашение, налог в стране источника и документы.'],
      ['Продажа иностранных акций', 'Продажа иностранных акций — частый случай. Это могут быть акции США, Европы, Великобритании, ETF, бумаги в private banking, миноритарные доли или активы на международном брокерском счете. Нужно анализировать страну эмитента, страну брокера или депозитария, резиденцию на дату продажи, соглашения, даты покупки и продажи, банковские доказательства и правила страны источника.'],
      ['Продажа компании или долей', 'Если вы продаете бизнес или доли в частной компании, анализ становится более чувствительным. Нужно проверить, где компания зарегистрирована, где работает, где фактически управляется, где клиенты, основные активы, команда и контракты. Юридически иностранная компания может создавать налоговые вопросы в другой юрисдикции.'],
      ['Продажа недвижимости за пределами Турции', 'Приросты по недвижимости часто обрабатываются иначе, чем финансовые gains. Если вы продаете квартиру, виллу, здание или коммерческий объект за пределами Турции, страна расположения недвижимости может сохранять право налогообложения. Даже если вы живете в Турции, эта страна может требовать декларацию и уплату налога.'],
      ['Продажа долей холдинга', 'Продажа долей иностранного холдинга требует осторожности. Холдинг может владеть операционными компаниями, недвижимостью, портфелями, семейными долями или правами в разных странах. Налоговый режим может зависеть от страны холдинга, нижележащих активов, соглашений, антиабузных правил, фактического управления, резиденции продавца и календаря сделки.'],
      ['Календарь сделки имеет значение', 'Дата продажи может менять результат. Нужно различать сделку до переезда, в переходный период, после начала турецкой резиденции, договор до отъезда, получение денег после переезда, earn-out или доплату позже. Эти детали влияют на налоги, банковские документы и логику файла резиденции.'],
      ['Скрытые приросты до переезда', 'Если у вас уже есть активы с большой нереализованной прибылью, их нужно определить до смены резиденции. Это могут быть выросшие акции, доли компаний, старая недвижимость, портфели, криптоактивы, семейный холдинг или профессиональные активы. Цель — понять, что уже существует и какая страна может обложить будущую продажу.'],
      ['Прежняя страна и exit issues', 'Прежняя страна может интересоваться вашими gains после выезда, если вы все еще считаетесь ее резидентом, если дом или семья остаются там, если компании управляются оттуда, если значимые активы расположены там или применяются правила exit tax, отчетности или anti-abuse. Эти вопросы нужно закрыть до подписания сделки.'],
      ['Банк, compliance и происхождение средств', 'Крупная иностранная plus-value может вызвать запросы банка. Могут потребоваться договор продажи, доказательство покупки, подтверждение цены, декларации, подтверждение оплаты налога, документы компании, реестр акционеров, отчеты портфеля, документы недвижимости, источник средств, сертификат резиденции и объяснение структуры капитала.'],
      ['Ошибки, которых нужно избегать', 'Не продавайте крупный актив без проверки резиденции на дату сделки. Не считайте иностранную plus-value автоматически освобожденной из-за жизни в Турции. Не забывайте, что страна актива может облагать gain. Не игнорируйте банковские доказательства. Не подписывайте и не получайте деньги в плохо документированный переходный период.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов, нотариусов или бухгалтеров. Его роль — координировать файл и помочь подготовить правильные вопросы до крупной сделки или смены резиденции. Bosphoras может организовать анализ резиденции, карту активов, review скрытых приростов, календарь сделки, координацию с турецкими и международными советниками, подготовку банка, compliance и частный переезд в Турцию.'],
    ],
    faq: [['Облагаются ли иностранные приросты капитала в Турции?', 'Если вы налоговый резидент Турции, мировые доходы и gains могут быть релевантны. Объявленная мера может создать исключение для отдельных иностранных gains новых резидентов.'], ['Может ли освобождение на 20 лет охватывать иностранные приросты капитала?', 'Потенциально, если финальные правила охватывают foreign-source gains и ваш профиль подходит. Нужно проверить тип актива, дату продажи, страну источника и финальный закон.'], ['Может ли gain по иностранным акциям быть освобожден?', 'Потенциально, но нужно анализировать страну эмитента, депозитария, резиденцию на дату продажи, соглашение и банковские доказательства.'], ['Может ли gain по иностранной недвижимости оставаться облагаемым в стране объекта?', 'Да. Страна расположения недвижимости может сохранять право налогообложения, даже если вы живете в Турции.'], ['Нужно ли продавать активы до переезда в Турцию?', 'Не обязательно. Сначала нужно анализировать скрытые приросты, календарь, налог страны источника, текущую резиденцию и будущую резиденцию в Турции.'], ['Bosphoras дает налоговую консультацию?', 'Нет. Bosphoras координирует частный анализ и связывает клиентов с налоговыми специалистами, юристами, банками, бухгалтерами, нотариусами и партнерами по переезду.']],
  },
  ar: {
    title: 'ضريبة المكاسب الرأسمالية الأجنبية في تركيا للمستثمرين العرب',
    metaTitle: 'ضريبة المكاسب الرأسمالية الأجنبية في تركيا 2026',
    description: 'المكاسب الرأسمالية الأجنبية في تركيا للمستثمرين العرب: بيع الأسهم، الشركات، العقار، المحافظ الاستثمارية، الإقامة الضريبية، الاتفاقيات والبنوك.',
    eyebrow: 'المكاسب الرأسمالية الأجنبية · المستثمرون العرب',
    hero: 'بيع أصول خارج تركيا أثناء العيش في تركيا قد يخلق نتائج ضريبية وبنكية مهمة. قبل بيع أسهم أو شركة أو عقار أو محفظة استثمارية، يجب فهم أثر التوقيت، الإقامة الضريبية، بلد المصدر والمستندات المطلوبة.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل بيع أصل أجنبي',
    finalTitle: 'المكاسب الكبيرة يجب تحضيرها قبل البيع',
    finalText: 'قبل توقيع البيع أو استلام مبلغ مهم، يمكن لـ Bosphoras تنظيم مراجعة خاصة لأصولك، إقامتك الضريبية، جدول العملية، الاتفاقيات، البنك، الامتثال، مصدر الأموال والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['بلد وجود الأصل', 'إقامتك الضريبية عند البيع', 'تاريخ الشراء وتاريخ البيع', 'طبيعة الأصل بدقة', 'الاتفاقية الضريبية المطبقة', 'المكاسب غير المحققة الحالية', 'المستندات البنكية والضريبية', 'انسجام انتقالك إلى تركيا'],
    sections: [
      ['لماذا يجب تحليل المكاسب الأجنبية قبل الانتقال', 'المكسب الرأسمالي ليس مجرد ربح من بيع. إنه يعتمد على بلد وجود الأصل، إقامتك الضريبية وقت البيع، تاريخ الشراء، تاريخ البيع، سعر الشراء، سعر البيع، نوع الأصل، الاتفاقية الضريبية، قواعد بلد المصدر وقواعد بلدك السابق. البيع قبل الانتقال أو خلال مرحلة انتقالية أو بعد الإقامة في تركيا قد يعطي نتائج مختلفة.'],
      ['الإقامة الضريبية هي نقطة البداية', 'قبل معرفة ما إذا كان المكسب الأجنبي قد يستفيد من معاملة ملائمة في تركيا، يجب تحديد أين أنت مقيم ضريبياً فعلياً وقت البيع. الإقامة ليست فقط تصريح إقامة أو شقة أو حساب بنكي. إنها تعتمد على مكان الحياة، العائلة، المنزل، الشركات، الأصول، الحسابات، القرارات ومركز المصالح الاقتصادية.'],
      ['ما الذي قد تغيره التدابير التركية', 'أعلنت تركيا عن إجراء لبعض المقيمين الجدد قد يشمل الدخل والمكاسب من مصدر أجنبي. حسب القواعد النهائية، قد تكون بعض المكاسب على أصول أجنبية معنية. لكن يجب مراجعة النص النهائي، نوع الأصل، بلد الأصل، إقامة البائع، تاريخ البيع، الاتفاقية، ضريبة بلد المصدر والمستندات.'],
      ['بيع أسهم أجنبية', 'بيع الأسهم الأجنبية حالة شائعة. قد تبيع أسهماً أمريكية أو أوروبية أو بريطانية، ETF، أوراقاً عبر بنك خاص، حصصاً أقلية أو أصولاً في محفظة دولية. يجب تحليل بلد المصدر، بلد الوسيط أو البنك الحافظ، إقامتك وقت البيع، الاتفاقيات، تواريخ الشراء والبيع، الإثباتات البنكية وقواعد بلد المصدر.'],
      ['بيع شركة أو حصص شركة', 'إذا كنت تبيع شركة أو حصصاً في شركة خاصة، يصبح التحليل أكثر حساسية. يجب مراجعة مكان تسجيل الشركة، أين تعمل فعلياً، أين تدار، أين العملاء، الأصول الرئيسية، الفريق والعقود. قد تكون الشركة أجنبية قانونياً لكنها تثير أسئلة ضريبية في دولة أخرى.'],
      ['بيع عقار خارج تركيا', 'المكاسب العقارية غالباً تعامل بطريقة مختلفة عن المكاسب المالية. إذا كنت تبيع شقة أو فيلا أو مبنى أو عقاراً تجارياً خارج تركيا، قد يحتفظ بلد وجود العقار بحق فرض الضريبة. حتى لو كنت تعيش في تركيا، قد يطلب ذلك البلد تصريحاً وضريبة على المكسب.'],
      ['بيع حصص في holding', 'بيع حصص في holding أجنبي يحتاج إلى حذر. قد يملك الهولدينغ شركات تشغيلية أو عقارات أو محافظ مالية أو مشاركات عائلية في عدة دول. قد يعتمد النظام الضريبي على بلد الهولدينغ، الأصول الأساسية، الاتفاقيات، قواعد مكافحة الإساءة، الإدارة الفعلية، إقامة البائع وجدول البيع.'],
      ['توقيت البيع مهم', 'تاريخ البيع قد يغير النتيجة. يجب التمييز بين بيع قبل الانتقال، خلال مرحلة انتقالية، بعد بداية الإقامة التركية، اتفاق بيع وقع قبل المغادرة، مبلغ وصل بعد الانتقال، earn-out أو دفعة لاحقة. هذه التفاصيل تؤثر على الضرائب والمستندات البنكية ومنطق ملف الإقامة.'],
      ['المكاسب غير المحققة قبل الانتقال', 'إذا كنت تملك أصولاً ارتفعت قيمتها كثيراً، يجب تحديدها قبل تغيير الإقامة. قد يشمل ذلك أسهماً، حصص شركات، عقاراً قديماً، محافظ مالية، أصول كريبتو، holding عائلي أو أصولاً مهنية. الهدف ليس بالضرورة البيع قبل الانتقال، بل فهم الموجود وأي دولة قد تفرض ضريبة على بيع مستقبلي.'],
      ['بلدك السابق وقواعد الخروج', 'قد يستمر بلدك السابق في الاهتمام بمكاسبك بعد المغادرة إذا كنت لا تزال تعتبر مقيماً ضريبياً هناك، أو إذا بقي المنزل أو العائلة هناك، أو الشركات تدار من هناك، أو الأصول المهمة موجودة هناك، أو توجد قواعد خروج أو anti-abuse. يجب مراجعة هذه النقاط قبل توقيع البيع.'],
      ['البنك والامتثال ومصدر الأموال', 'المكسب الأجنبي الكبير قد يسبب طلبات بنكية. قد يطلب البنك عقد البيع، إثبات الشراء، إثبات سعر البيع، التصريحات الضريبية، إثبات دفع الضريبة، مستندات الشركة، سجل المساهمين، كشوف المحفظة، سندات العقار، إثبات مصدر الأموال، شهادة الإقامة الضريبية وشرح هيكل الثروة.'],
      ['أخطاء يجب تجنبها', 'لا تبع أصلاً مهماً دون مراجعة الإقامة الضريبية وقت البيع. لا تفترض أن المكسب الأجنبي معفى تلقائياً لأنك تعيش في تركيا. لا تنس أن بلد الأصل قد يفرض ضريبة. لا تتجاهل الإثباتات البنكية. لا توقع أو تستلم الأموال خلال مرحلة انتقالية غير موثقة.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامين الضريبيين أو الموثقين أو المحاسبين. دوره هو تنسيق الملف ومساعدتك على طرح الأسئلة الصحيحة قبل بيع مهم أو تغيير الإقامة. يمكن لـ Bosphoras تنظيم تحليل الإقامة، خريطة الأصول، مراجعة المكاسب غير المحققة، جدول العملية، التنسيق مع مستشارين أتراك ودوليين، التحضير البنكي، الامتثال والانتقال الخاص إلى تركيا.'],
    ],
    faq: [['هل المكاسب الرأسمالية الأجنبية خاضعة للضريبة في تركيا؟', 'إذا كنت مقيماً ضريبياً في تركيا، فقد يكون الدخل والمكاسب العالمية ذات صلة. التدبير المعلن قد ينشئ استثناءً لبعض المكاسب الأجنبية للمقيمين الجدد، بشروط.'], ['هل يمكن أن يشمل إعفاء 20 سنة المكاسب الأجنبية؟', 'محتمل إذا شملت القواعد النهائية المكاسب من مصدر أجنبي وكان ملفك مؤهلاً. يجب مراجعة نوع الأصل، تاريخ البيع، بلد المصدر والقانون النهائي.'], ['هل يمكن إعفاء مكاسب الأسهم الأجنبية؟', 'محتمل، لكن يجب تحليل بلد المصدر، البنك الحافظ، الإقامة وقت البيع، الاتفاقية والإثباتات البنكية.'], ['هل يمكن أن تبقى مكاسب العقار الأجنبي خاضعة في بلد العقار؟', 'نعم. بلد وجود العقار قد يحتفظ بحق الضريبة حتى إذا كنت تعيش في تركيا.'], ['هل يجب بيع الأصول قبل الانتقال إلى تركيا؟', 'ليس بالضرورة. يجب أولاً تحليل المكاسب غير المحققة، التوقيت، ضريبة بلد المصدر، الإقامة الحالية والإقامة المستقبلية في تركيا.'], ['هل يقدم Bosphoras استشارة ضريبية؟', 'لا. Bosphoras ينسق المراجعة الخاصة ويربط العملاء بالمستشارين الضريبيين والمحامين والبنوك والمحاسبين والموثقين وشركاء الانتقال.']],
  },
};

export function getForeignCapitalGainsTaxMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function ForeignCapitalGainsTaxClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
