import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/heritage-turquie-fiscalite-1-pourcent-investisseurs',
  en: '/en/turkey-inheritance-tax-1-percent-investors',
  ru: '/ru/nasledstvo-turtsiya-nalog-1-protsent-investory',
  ar: '/ar/turkey-inheritance-tax-1-percent-arab-investors',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = {
  title: string;
  metaTitle: string;
  description: string;
  eyebrow: string;
  hero: string;
  cta: string;
  asideTitle: string;
  finalTitle: string;
  finalText: string;
  faqTitle: string;
  checklist: string[];
  sections: Array<[string, string]>;
  faq: Array<[string, string]>;
};

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Héritage en Turquie : fiscalité, succession et transmission pour investisseurs étrangers',
    metaTitle: 'Héritage en Turquie : fiscalité à 1 % pour investisseurs',
    description: 'Héritage en Turquie, fiscalité successorale, immobilier, comptes bancaires, patrimoine familial, investisseurs étrangers et transmission : comprendre l’impact potentiel d’un taux à 1 % avant de s’installer ou d’acheter en Turquie.',
    eyebrow: 'Succession · Patrimoine familial · Turquie',
    hero: 'Préparer son installation en Turquie ne concerne pas seulement la résidence fiscale, les revenus étrangers ou l’immobilier. Pour une famille, un investisseur ou un entrepreneur, la transmission patrimoniale doit aussi être étudiée avant l’achat, l’installation ou le transfert d’une partie des actifs.',
    cta: 'Demander une analyse privée',
    asideTitle: 'À vérifier avant d’organiser votre patrimoine',
    finalTitle: 'Une transmission internationale doit être préparée avant l’urgence',
    finalText: 'Avant de structurer votre résidence, vos comptes ou votre immobilier, Bosphoras peut organiser une analyse privée de votre situation familiale et patrimoniale : succession, héritiers, biens, banque, fiscalité, assurance, immobilier et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Les biens détenus en Turquie', 'Les actifs et comptes à l’étranger', 'La résidence du défunt et des héritiers', 'La nationalité et la situation familiale', 'La loi civile applicable', 'Les documents successoraux nécessaires', 'La banque et la conformité', 'La coordination avec avocats, notaires et fiscalistes'],
    sections: [
      ['Pourquoi l’héritage doit être étudié avant l’installation', 'Beaucoup d’investisseurs pensent à la fiscalité sur les revenus, mais oublient la fiscalité sur la transmission. Une famille patrimoniale doit anticiper qui possède les actifs, où se trouvent les biens, qui sont les héritiers, dans quel pays vit la famille, où se trouvent les comptes bancaires, quelle loi civile s’applique, quelle fiscalité successorale peut s’appliquer et comment les actifs seront transmis. Une installation en Turquie peut modifier l’organisation familiale et patrimoniale.'],
      ['Immobilier en Turquie et succession', 'L’un des cas les plus fréquents concerne l’immobilier. Un investisseur étranger peut acheter un appartement à Istanbul, une villa à Bodrum, un bien à Antalya, un immeuble locatif, un bien familial, un bien détenu en direct ou un bien détenu via une société. En cas de décès, il faut déterminer comment le bien sera transmis, qui pourra hériter, quelles formalités devront être accomplies et quelle fiscalité s’appliquera.'],
      ['Comptes bancaires et actifs financiers en Turquie', 'Un investisseur peut détenir des comptes bancaires, dépôts, placements, titres ou liquidités en Turquie. En cas de succession, les banques peuvent demander acte de décès, documents d’identité des héritiers, certificat d’héritier, documents traduits et apostillés, justificatifs fiscaux, preuve de lien familial et instructions de transfert. Si le dossier n’a pas été préparé, les fonds peuvent rester bloqués longtemps.'],
      ['Fiscalité à 1 % : pourquoi cela peut attirer les familles patrimoniales', 'Si un régime fiscal très favorable est confirmé pour certains héritages ou transmissions, la Turquie peut devenir intéressante pour des familles qui comparent plusieurs destinations. Un taux faible peut être attractif pour des familles avec immobilier international, entrepreneurs avec patrimoine familial, investisseurs avec comptes bancaires et actifs financiers, clients de banque privée ou personnes comparant Turquie, Dubaï, Italie, Suisse, Monaco ou Portugal. Mais un taux attractif ne suffit pas : il faut vérifier les actifs concernés, les personnes concernées, les conditions et les formalités.'],
      ['Résidence fiscale et succession internationale', 'Une succession internationale peut impliquer plusieurs pays. Il faut regarder le pays de résidence du défunt, la nationalité du défunt, le pays de résidence des héritiers, le pays où se trouvent les biens, les comptes bancaires, la loi civile applicable, les conventions éventuelles et les règles fiscales locales. Un investisseur peut vivre en Turquie, posséder un bien en France, des comptes aux Émirats, une société au Royaume-Uni et des héritiers vivant dans plusieurs pays.'],
      ['Héritiers, famille et règles civiles', 'La fiscalité n’est qu’une partie du sujet. Il faut aussi comprendre qui hérite légalement, quelle part revient au conjoint, quelle part revient aux enfants, comment traiter les enfants issus de plusieurs unions, comment protéger le conjoint survivant, comment organiser une transmission volontaire, comment éviter les conflits entre héritiers et comment traiter les biens détenus dans plusieurs pays.'],
      ['Holding, société et transmission d’entreprise', 'Pour les entrepreneurs, la succession peut concerner non seulement des biens personnels, mais aussi une société. Il faut analyser qui détient les parts, où la société est immatriculée, où elle est réellement dirigée, qui doit reprendre la direction, comment les héritiers reçoivent les parts, quelle fiscalité s’applique, comment la banque comprend la structure et comment éviter le blocage de l’entreprise.'],
      ['Assurance-vie, trusts et structures étrangères', 'Certains investisseurs détiennent des actifs via assurance-vie, trust, fondation, holding, société patrimoniale, compte bancaire étranger ou contrat de capitalisation. Ces structures peuvent être utiles, mais elles peuvent aussi créer des questions fiscales, bancaires et juridiques lorsqu’une personne s’installe en Turquie ou y détient des actifs.'],
      ['Banque, conformité et succession', 'Les banques sont souvent au centre des successions internationales. Elles peuvent bloquer ou ralentir les opérations si le dossier n’est pas clair. Elles peuvent demander origine des fonds, preuve de propriété, documents successoraux, documents traduits et apostillés, certificat de résidence fiscale, explication de la structure familiale, preuve de lien entre héritiers et documents de société.'],
      ['Les erreurs à éviter', 'La première erreur est de penser que la succession se réglera automatiquement parce que les héritiers sont connus. La deuxième est d’acheter un bien en Turquie sans réfléchir à la transmission. La troisième est d’ouvrir des comptes bancaires sans organiser les documents familiaux. La quatrième est de comparer uniquement les taux d’impôt sans regarder les règles civiles. La cinquième est d’oublier que plusieurs pays peuvent intervenir dans une succession internationale.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat, un notaire ou un fiscaliste. Notre rôle est de coordonner votre dossier et de vous aider à poser les bonnes questions avant une installation, un achat immobilier ou une organisation patrimoniale en Turquie. Bosphoras peut organiser l’analyse de votre situation familiale, la cartographie des actifs, la coordination avec avocats et fiscalistes, l’organisation bancaire, l’accompagnement immobilier, l’assurance internationale, la préparation des documents et l’installation privée en Turquie.'],
    ],
    faq: [['L’héritage est-il imposé en Turquie ?', 'Une succession peut entraîner des obligations fiscales et administratives en Turquie, notamment si des biens ou comptes y sont situés. Le traitement exact dépend des actifs, du statut du défunt, des héritiers et des règles applicables.'], ['Le taux de 1 % s’applique-t-il à tous les héritages ?', 'Il faut vérifier les textes définitifs et les conditions exactes. Un taux attractif ne signifie pas qu’il s’applique automatiquement à tous les biens, toutes les personnes et toutes les situations.'], ['Un bien immobilier en Turquie peut-il être transmis à des héritiers étrangers ?', 'Oui, mais la transmission doit respecter les règles locales, les documents exigés, les formalités successorales et les éventuelles obligations fiscales.'], ['Une succession peut-elle concerner plusieurs pays ?', 'Oui. Une famille peut avoir des biens en Turquie, des comptes dans un autre pays, une société étrangère et des héritiers vivant ailleurs.'], ['Faut-il organiser sa succession avant d’acheter en Turquie ?', 'C’est fortement recommandé, surtout pour les familles patrimoniales, investisseurs immobiliers, entrepreneurs et personnes avec actifs dans plusieurs pays.'], ['Bosphoras donne-t-il un conseil juridique ou fiscal ?', 'Non. Bosphoras coordonne l’analyse privée et les bons interlocuteurs : avocats, fiscalistes, notaires ou équivalents locaux, banques, assurance, immobilier et partenaires d’installation en Turquie.']],
  },
  en: {
    title: 'Turkey Inheritance Tax: estate planning, property and succession for investors',
    metaTitle: 'Turkey Inheritance Tax for Investors: 1% Succession Planning',
    description: 'Turkey inheritance tax, estate planning, property, bank accounts, family wealth and succession for expats, investors and international families considering Turkey.',
    eyebrow: 'Inheritance · Estate planning · Turkey',
    hero: 'Relocating to Turkey or buying property there is not only about income tax, residence or lifestyle. For investors and international families, estate planning and succession should be reviewed before assets, bank accounts or family life become connected to Turkey.',
    cta: 'Request a private assessment',
    asideTitle: 'Before structuring family wealth',
    finalTitle: 'International succession should be prepared before it becomes urgent',
    finalText: 'Before structuring your residence, bank accounts or property in Turkey, Bosphoras can organize a private review of your family and wealth situation: succession, heirs, assets, banking, taxation, insurance, real estate and relocation to Turkey.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Assets held in Turkey', 'Foreign assets and bank accounts', 'Residence of the deceased and heirs', 'Nationality and family situation', 'Applicable civil law', 'Succession documents required', 'Banking and compliance', 'Coordination with lawyers, notaries and tax advisors'],
    sections: [
      ['Why inheritance should be reviewed before relocation', 'Many investors focus on income tax and foreign income, but forget succession. An international family should understand who owns the assets, where the assets are located, who the heirs are, where the family lives, where bank accounts are held, which civil law applies, what inheritance tax may apply and how assets will be transferred. A relocation to Turkey can affect both family organization and wealth planning.'],
      ['Turkish property and succession', 'Real estate is often the first issue. A foreign investor may buy an apartment in Istanbul, a villa in Bodrum, a property in Antalya, rental property or a family home. In the event of death, it is necessary to determine how the property will be transferred, who can inherit, which formalities are required and which tax treatment applies.'],
      ['Bank accounts and financial assets in Turkey', 'An investor may hold bank accounts, deposits, investments, securities or cash in Turkey. In a succession, banks may request death certificates, identity documents for heirs, inheritance certificates, translated and apostilled documents, tax evidence, proof of family relationship and transfer instructions. Without preparation, funds may remain blocked for a long time.'],
      ['Why a low inheritance tax rate may interest wealthy families', 'If a very favorable regime is confirmed for certain inheritances or transfers, Turkey may become relevant for families comparing several destinations. A low rate may be attractive for families with international real estate, entrepreneurs with family wealth, investors with bank accounts and financial assets, private banking clients or people comparing Turkey with Dubai, Italy, Switzerland, Monaco or Portugal. But the rate is only one part of the analysis.'],
      ['Tax residence and international succession', 'International succession may involve several countries. You should review the residence country of the deceased, nationality, residence of the heirs, countries where assets are located, bank accounts, applicable civil law, possible treaties and local tax rules. A person may live in Turkey, own property in Europe, hold accounts in the UAE, own a company in the UK and have heirs in several countries.'],
      ['Heirs, family and civil law rules', 'Taxation is only one part of succession. You also need to understand who inherits by law, the rights of the spouse, the rights of children, blended-family issues, protection of the surviving spouse, voluntary transfer planning, conflict prevention between heirs and treatment of assets located in several countries.'],
      ['Companies, holdings and business succession', 'For entrepreneurs, succession may involve a business, not only personal assets. You should review who owns the shares, where the company is incorporated, where it is effectively managed, who should take control, how heirs receive shares, what tax applies and how to avoid blocking the business.'],
      ['Life insurance, trusts and foreign structures', 'Some investors hold assets through life insurance, trusts, foundations, holding companies, family companies, foreign bank accounts or capitalisation contracts. These structures may be useful, but they can also create tax, banking and legal questions when a person relocates to Turkey or holds Turkish assets.'],
      ['Banking, compliance and inheritance', 'Banks are often central in international succession. They may slow or block operations if the file is unclear. They may ask for source of funds, ownership evidence, inheritance documents, translations, apostilles, tax residence certificates, explanations of the family structure, proof of relationship and company documents.'],
      ['Mistakes to avoid', 'Do not assume succession will be automatic because the heirs are known. Do not buy property in Turkey without thinking about transfer. Do not open bank accounts without organizing family documents. Do not compare only tax rates without reviewing civil law. Do not forget that several countries may be involved in one succession.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace lawyers, notaries or tax advisors. Its role is to coordinate the file and help prepare the right questions before relocation, property acquisition or wealth structuring in Turkey. Bosphoras can organize family situation review, asset mapping, coordination with lawyers and tax advisors, banking organization, real estate support, insurance, document preparation and private relocation to Turkey.'],
    ],
    faq: [['Is inheritance taxed in Turkey?', 'A succession may trigger tax and administrative obligations in Turkey, especially if assets or accounts are located there. The exact treatment depends on assets, status of the deceased, heirs and applicable rules.'], ['Does the 1% rate apply to all inheritances?', 'Final texts and exact conditions must be reviewed. An attractive rate does not automatically apply to all assets, people or situations.'], ['Can Turkish property be inherited by foreign heirs?', 'Yes, but the transfer must comply with local rules, required documents, succession formalities and possible tax obligations.'], ['Can one succession involve several countries?', 'Yes. A family may have property in Turkey, accounts elsewhere, a foreign company and heirs living in different jurisdictions.'], ['Should succession be organized before buying in Turkey?', 'It is strongly recommended, especially for wealthy families, real estate investors, entrepreneurs and people with assets in several countries.'], ['Does Bosphoras provide legal or tax advice?', 'No. Bosphoras coordinates the private review and connects clients with suitable lawyers, tax advisors, notaries or local equivalents, banks, insurance and relocation partners.']],
  },
  ru: {
    title: 'Наследство в Турции: налог, недвижимость и передача капитала для инвесторов',
    metaTitle: 'Наследство в Турции: налог 1% для инвесторов',
    description: 'Наследство в Турции, налог на наследство, недвижимость, банковские счета, семейный капитал и succession planning для русскоязычных инвесторов.',
    eyebrow: 'Наследство · Семейный капитал · Турция',
    hero: 'Переезд в Турцию или покупка недвижимости — это не только ВНЖ, налоги на доходы и качество жизни. Для русскоязычных инвесторов и семей важно заранее понять, как будут передаваться активы, счета, недвижимость и доли компаний.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед структурированием семейного капитала',
    finalTitle: 'Международное наследство нужно готовить заранее',
    finalText: 'До структурирования резиденции, счетов или недвижимости в Турции Bosphoras может организовать частный анализ семейной и имущественной ситуации: наследники, активы, банки, налоги, страхование, недвижимость и переезд в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Активы, находящиеся в Турции', 'Иностранные активы и счета', 'Резиденция наследодателя и наследников', 'Гражданство и семейная ситуация', 'Применимое гражданское право', 'Необходимые наследственные документы', 'Банки и compliance', 'Координация с юристами, нотариусами и налоговыми специалистами'],
    sections: [
      ['Почему наследство нужно анализировать до переезда', 'Многие инвесторы думают о налогах на доходы, но забывают о передаче капитала. Международная семья должна понимать, кто владеет активами, где они находятся, кто наследники, где живет семья, где открыты счета, какое гражданское право применяется, какой налог может возникнуть и как активы будут передаваться. Переезд в Турцию может изменить семейную и имущественную организацию.'],
      ['Недвижимость в Турции и наследство', 'Самый частый случай — недвижимость. Иностранный инвестор может купить квартиру в Стамбуле, виллу в Бодруме, объект в Анталье, арендную недвижимость или семейный дом. В случае смерти нужно определить, как объект будет передан, кто может наследовать, какие формальности нужны и какая налоговая обработка применяется.'],
      ['Банковские счета и финансовые активы в Турции', 'Инвестор может держать счета, депозиты, инвестиции, ценные бумаги или ликвидность в Турции. При наследстве банки могут запросить свидетельство о смерти, документы наследников, свидетельство наследника, переводы и апостили, налоговые документы, подтверждение родства и инструкции по переводу. Без подготовки средства могут быть заблокированы надолго.'],
      ['Почему низкий налог может заинтересовать семьи', 'Если благоприятный режим для отдельных наследств или передач будет подтвержден, Турция может стать интересной для семей, сравнивающих разные направления. Низкая ставка может быть привлекательна для семей с международной недвижимостью, предпринимателей, инвесторов с банковскими счетами и финансовыми активами, клиентов private banking или тех, кто сравнивает Турцию с Дубаем, Италией, Швейцарией, Монако или Португалией.'],
      ['Налоговая резиденция и международное наследство', 'Международное наследство может затрагивать несколько стран. Нужно анализировать страну резиденции наследодателя, гражданство, резиденцию наследников, страны активов, банковские счета, применимое гражданское право, возможные соглашения и местные налоговые правила. Один человек может жить в Турции, владеть недвижимостью в Европе, счетами в ОАЭ, компанией в Великобритании и иметь наследников в разных странах.'],
      ['Наследники, семья и гражданские правила', 'Налоги — только часть вопроса. Нужно понимать, кто наследует по закону, права супруга, права детей, ситуации нескольких браков, защиту пережившего супруга, добровольное планирование передачи, предотвращение конфликтов между наследниками и обработку активов в нескольких странах.'],
      ['Холдинг, компания и передача бизнеса', 'Для предпринимателей наследство может затрагивать не только личные активы, но и бизнес. Нужно анализировать, кто владеет долями, где зарегистрирована компания, где фактически управляется, кто должен принять управление, как наследники получают доли, какой налог применяется и как избежать блокировки бизнеса.'],
      ['Страхование жизни, trusts и иностранные структуры', 'Некоторые инвесторы держат активы через страхование жизни, trusts, фонды, холдинги, семейные компании, иностранные счета или capitalisation contracts. Эти структуры могут быть полезны, но могут создавать налоговые, банковские и юридические вопросы при переезде в Турцию или владении турецкими активами.'],
      ['Банки, compliance и наследство', 'Банки часто находятся в центре международного наследства. Они могут замедлить или заблокировать операции, если файл неясен. Они могут запросить происхождение средств, доказательство собственности, наследственные документы, переводы, апостили, сертификат налоговой резиденции, объяснение семейной структуры, подтверждение родства и документы компаний.'],
      ['Ошибки, которых нужно избегать', 'Не стоит думать, что наследство решится автоматически, потому что наследники известны. Не стоит покупать недвижимость в Турции без мысли о передаче. Не стоит открывать счета без семейных документов. Не стоит сравнивать только налоговые ставки без гражданского права. Не стоит забывать, что в одном наследстве могут участвовать несколько стран.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет юристов, нотариусов или налоговых специалистов. Его роль — координировать файл и помочь подготовить правильные вопросы до переезда, покупки недвижимости или структурирования капитала в Турции. Bosphoras может организовать анализ семейной ситуации, карту активов, координацию с юристами и налоговыми специалистами, банки, недвижимость, страхование, подготовку документов и частный переезд.'],
    ],
    faq: [['Облагается ли наследство в Турции?', 'Наследство может создавать налоговые и административные обязанности в Турции, особенно если активы или счета находятся там. Точный режим зависит от активов, статуса умершего, наследников и применимых правил.'], ['Ставка 1% применяется ко всем наследствам?', 'Нужно проверить финальные тексты и точные условия. Привлекательная ставка не означает автоматическое применение ко всем активам, людям и ситуациям.'], ['Может ли недвижимость в Турции перейти иностранным наследникам?', 'Да, но передача должна соответствовать местным правилам, документам, наследственным формальностям и возможным налоговым обязанностям.'], ['Может ли наследство затрагивать несколько стран?', 'Да. Семья может иметь недвижимость в Турции, счета в другой стране, иностранную компанию и наследников в разных юрисдикциях.'], ['Нужно ли организовать наследство до покупки в Турции?', 'Это настоятельно рекомендуется для семей с капиталом, инвесторов в недвижимость, предпринимателей и людей с активами в нескольких странах.'], ['Bosphoras дает юридическую или налоговую консультацию?', 'Нет. Bosphoras координирует частный анализ и связывает клиентов с юристами, налоговыми специалистами, нотариусами или местными эквивалентами, банками, страхованием и партнерами по переезду.']],
  },
  ar: {
    title: 'ضريبة الميراث في تركيا للمستثمرين العرب: العقار، الحسابات ونقل الثروة',
    metaTitle: 'ضريبة الميراث في تركيا للمستثمرين العرب 1%',
    description: 'الميراث في تركيا للمستثمرين العرب: ضريبة الميراث، العقار، الحسابات البنكية، الثروة العائلية، نقل الأصول والتخطيط قبل الشراء أو الانتقال.',
    eyebrow: 'الميراث · الثروة العائلية · تركيا',
    hero: 'الانتقال إلى تركيا أو شراء عقار فيها لا يتعلق فقط بالإقامة والضرائب ونمط الحياة. بالنسبة للمستثمرين والعائلات العربية، يجب دراسة الميراث ونقل الثروة قبل ربط الأصول أو الحسابات أو حياة العائلة بتركيا.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل تنظيم الثروة العائلية',
    finalTitle: 'الميراث الدولي يجب تحضيره قبل حدوثه',
    finalText: 'قبل تنظيم إقامتك أو حساباتك أو عقارك في تركيا، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك العائلي والمالي: الميراث، الورثة، الأصول، البنوك، الضرائب، التأمين، العقار والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['الأصول الموجودة في تركيا', 'الأصول والحسابات خارج تركيا', 'إقامة المتوفى والورثة', 'الجنسية والوضع العائلي', 'القانون المدني المطبق', 'مستندات الميراث المطلوبة', 'البنوك والامتثال', 'التنسيق مع المحامين والموثقين والمستشارين الضريبيين'],
    sections: [
      ['لماذا يجب دراسة الميراث قبل الانتقال', 'كثير من المستثمرين يركزون على ضريبة الدخل وينسون نقل الثروة. يجب على العائلة الدولية معرفة من يملك الأصول، أين توجد، من هم الورثة، أين تعيش العائلة، أين الحسابات البنكية، أي قانون مدني يطبق، أي ضريبة ميراث قد تظهر وكيف سيتم نقل الأصول. الانتقال إلى تركيا يمكن أن يؤثر على التنظيم العائلي والمالي.'],
      ['العقار في تركيا والميراث', 'العقار هو الحالة الأكثر شيوعاً. قد يشتري المستثمر العربي شقة في إسطنبول، فيلا في بودروم، عقاراً في أنطاليا، عقاراً مؤجراً أو منزلاً عائلياً. في حالة الوفاة يجب تحديد كيف سيتم نقل العقار، من يمكن أن يرث، ما formalities المطلوبة وما المعاملة الضريبية.'],
      ['الحسابات البنكية والأصول المالية في تركيا', 'قد يحتفظ المستثمر بحسابات بنكية أو ودائع أو استثمارات أو أوراق مالية أو سيولة في تركيا. في الميراث قد تطلب البنوك شهادة وفاة، وثائق هوية الورثة، شهادة حصر إرث، مستندات مترجمة ومصدقة، إثباتات ضريبية، إثبات صلة القرابة وتعليمات التحويل. دون تحضير يمكن أن تبقى الأموال مجمدة لفترة طويلة.'],
      ['لماذا قد تجذب ضريبة منخفضة العائلات الثرية', 'إذا تم تأكيد نظام مناسب لبعض حالات الميراث أو نقل الثروة، قد تصبح تركيا مهمة للعائلات التي تقارن بين عدة وجهات. معدل منخفض قد يجذب عائلات لديها عقار دولي، رواد أعمال، مستثمرين بحسابات وأصول مالية، عملاء بنوك خاصة أو أشخاص يقارنون تركيا بدبي، إيطاليا، سويسرا، موناكو أو البرتغال.'],
      ['الإقامة الضريبية والميراث الدولي', 'الميراث الدولي قد يشمل عدة دول. يجب مراجعة بلد إقامة المتوفى، الجنسية، إقامة الورثة، الدول التي توجد فيها الأصول، الحسابات البنكية، القانون المدني المطبق، الاتفاقيات المحتملة والقواعد الضريبية المحلية. قد يعيش شخص في تركيا ويملك عقاراً في أوروبا وحسابات في الخليج وشركة في بلد آخر وورثة في عدة دول.'],
      ['الورثة والعائلة والقواعد المدنية', 'الضريبة ليست سوى جزء من الموضوع. يجب فهم من يرث قانونياً، حقوق الزوج أو الزوجة، حقوق الأبناء، العائلات المتعددة، حماية الزوج الباقي، التخطيط الطوعي، منع النزاعات بين الورثة ومعالجة الأصول الموجودة في عدة دول.'],
      ['الشركات والهولدينغ ونقل الأعمال', 'بالنسبة لرواد الأعمال، قد يشمل الميراث شركة وليس فقط أصولاً شخصية. يجب تحليل من يملك الحصص، أين الشركة مسجلة، أين تدار فعلياً، من سيستلم الإدارة، كيف يحصل الورثة على الحصص، ما الضريبة المطبقة وكيف يمكن تجنب تعطيل الشركة.'],
      ['التأمين على الحياة وtrusts والهياكل الأجنبية', 'بعض المستثمرين يحتفظون بالأصول عبر تأمين حياة، trusts، foundations، holding، شركات عائلية، حسابات أجنبية أو عقود مالية. هذه الهياكل قد تكون مفيدة، لكنها قد تخلق أسئلة ضريبية وبنكية وقانونية عند الانتقال إلى تركيا أو امتلاك أصول تركية.'],
      ['البنوك والامتثال والميراث', 'البنوك غالباً في مركز الميراث الدولي. قد تبطئ أو توقف العمليات إذا كان الملف غير واضح. قد تطلب مصدر الأموال، إثبات الملكية، مستندات الميراث، ترجمات، تصديقات، شهادة إقامة ضريبية، شرح الهيكل العائلي، إثبات صلة القرابة ومستندات الشركات.'],
      ['أخطاء يجب تجنبها', 'لا تفترض أن الميراث سيتم تلقائياً لأن الورثة معروفون. لا تشتر عقاراً في تركيا دون التفكير في نقله لاحقاً. لا تفتح حسابات دون تنظيم مستندات العائلة. لا تقارن فقط معدلات الضريبة دون مراجعة القانون المدني. لا تنس أن عدة دول قد تدخل في ميراث واحد.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامين أو الموثقين أو المستشارين الضريبيين. دوره هو تنسيق الملف ومساعدتك على طرح الأسئلة الصحيحة قبل الانتقال أو شراء العقار أو تنظيم الثروة في تركيا. يمكن لـ Bosphoras تنظيم تحليل الوضع العائلي، خريطة الأصول، التنسيق مع المحامين والمستشارين، البنوك، العقار، التأمين، تحضير الوثائق والانتقال الخاص إلى تركيا.'],
    ],
    faq: [['هل يخضع الميراث للضريبة في تركيا؟', 'قد يخلق الميراث التزامات ضريبية وإدارية في تركيا، خصوصاً إذا كانت الأصول أو الحسابات موجودة هناك. المعاملة الدقيقة تعتمد على الأصول، وضع المتوفى، الورثة والقواعد المطبقة.'], ['هل تنطبق نسبة 1% على كل الميراث؟', 'يجب مراجعة النصوص النهائية والشروط الدقيقة. النسبة الجذابة لا تعني تطبيقها تلقائياً على كل الأصول والأشخاص والحالات.'], ['هل يمكن توريث عقار في تركيا لورثة أجانب؟', 'نعم، لكن النقل يجب أن يحترم القواعد المحلية والمستندات المطلوبة وإجراءات الميراث والالتزامات الضريبية المحتملة.'], ['هل يمكن أن يشمل الميراث عدة دول؟', 'نعم. قد تكون للعائلة أصول في تركيا وحسابات في بلد آخر وشركة أجنبية وورثة يعيشون في دول مختلفة.'], ['هل يجب تنظيم الميراث قبل الشراء في تركيا؟', 'ينصح بذلك بشدة للعائلات الثرية والمستثمرين العقاريين ورواد الأعمال والأشخاص الذين لديهم أصول في عدة دول.'], ['هل يقدم Bosphoras استشارة قانونية أو ضريبية؟', 'لا. Bosphoras ينسق المراجعة الخاصة ويربط العملاء بالمحامين والمستشارين الضريبيين والموثقين أو البدائل المحلية والبنوك والتأمين وشركاء الانتقال.']],
  },
};

export function getInheritanceTaxTurkeyMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function InheritanceTaxTurkeyClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
