import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, Landmark, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

export type LongTailTaxKey = 'taxResidenceForeignIncome' | 'nonDomTurkey' | 'frenchExpatTax' | 'foreignDividends' | 'foreignCapitalGains' | 'inheritanceOnePercent' | 'turkishDiaspora' | 'digitalNomadTax' | 'foreignPensionTax' | 'turkeyVsItalyNonDom';
export const longTailTaxKeys: LongTailTaxKey[] = ['taxResidenceForeignIncome','nonDomTurkey','frenchExpatTax','foreignDividends','foreignCapitalGains','inheritanceOnePercent','turkishDiaspora','digitalNomadTax','foreignPensionTax','turkeyVsItalyNonDom'];

export const longTailTaxSlugs: Record<LongTailTaxKey, Record<Locale, string>> = {
  taxResidenceForeignIncome: { fr: '/residence-fiscale-turquie-revenus-etrangers', en: '/en/turkey-tax-residence-foreign-income', ru: '/ru/nalogovaya-rezidentsiya-turtsiya-inostrannye-dohody', ar: '/ar/turkey-tax-residence-foreign-income' },
  nonDomTurkey: { fr: '/regime-non-dom-turquie-fiscalite', en: '/en/turkey-non-dom-tax-regime', ru: '/ru/turtsiya-non-dom-nalogovyy-rezhim', ar: '/ar/turkey-non-dom-tax-regime' },
  frenchExpatTax: { fr: '/expatrie-francais-turquie-fiscalite-revenus-etrangers', en: '/en/french-expat-turkey-tax-foreign-income', ru: '/ru/frantsuzskiy-expat-turtsiya-nalogi-inostrannye-dohody', ar: '/ar/french-expat-turkey-tax-foreign-income' },
  foreignDividends: { fr: '/impot-dividendes-etrangers-turquie', en: '/en/foreign-dividends-tax-turkey', ru: '/ru/nalog-dividendy-inostrannye-turtsiya', ar: '/ar/foreign-dividends-tax-turkey' },
  foreignCapitalGains: { fr: '/plus-values-etrangeres-turquie-fiscalite', en: '/en/foreign-capital-gains-tax-turkey', ru: '/ru/inostrannye-prirosty-kapitala-turtsiya-nalogi', ar: '/ar/foreign-capital-gains-tax-turkey' },
  inheritanceOnePercent: { fr: '/heritage-turquie-fiscalite-1-pourcent-investisseurs', en: '/en/turkey-inheritance-tax-1-percent-investors', ru: '/ru/nasledstvo-turtsiya-nalog-1-protsent-investory', ar: '/ar/turkey-inheritance-tax-1-percent-investors' },
  turkishDiaspora: { fr: '/turcs-de-l-etranger-exoneration-fiscale-turquie', en: '/en/turks-abroad-turkey-tax-exemption', ru: '/ru/turki-za-rubezhom-nalogovaya-lgota-turtsiya', ar: '/ar/turks-abroad-turkey-tax-exemption' },
  digitalNomadTax: { fr: '/digital-nomad-turquie-fiscalite-revenus-etrangers', en: '/en/digital-nomad-turkey-tax-foreign-income', ru: '/ru/digital-nomad-turtsiya-nalogi-inostrannye-dohody', ar: '/ar/digital-nomad-turkey-tax-foreign-income' },
  foreignPensionTax: { fr: '/retraite-etrangere-turquie-fiscalite', en: '/en/foreign-pension-tax-turkey', ru: '/ru/inostrannaya-pensiya-turtsiya-nalogi', ar: '/ar/foreign-pension-tax-turkey' },
  turkeyVsItalyNonDom: { fr: '/turquie-vs-italie-regime-non-dom-fiscalite', en: '/en/turkey-vs-italy-non-dom-tax-regime', ru: '/ru/turtsiya-vs-italiya-non-dom-nalogovyy-rezhim', ar: '/ar/turkey-vs-italy-non-dom-tax-regime' },
};

const titles: Record<LongTailTaxKey, Record<Locale, string>> = {
  taxResidenceForeignIncome: { fr: 'Résidence fiscale Turquie et revenus étrangers', en: 'Turkey tax residence and foreign income', ru: 'Налоговая резиденция Турции и иностранные доходы', ar: 'الإقامة الضريبية في تركيا والدخل الأجنبي' },
  nonDomTurkey: { fr: 'Régime non-dom Turquie : fiscalité des nouveaux résidents', en: 'Turkey non-dom regime: tax for new residents', ru: 'Режим non-dom в Турции: налоги для новых резидентов', ar: 'نظام non-dom في تركيا: ضرائب المقيمين الجدد' },
  frenchExpatTax: { fr: 'Expatrié français en Turquie : fiscalité et revenus étrangers', en: 'French expat in Turkey: tax and foreign income', ru: 'Французский экспат в Турции: налоги и иностранные доходы', ar: 'مغترب فرنسي في تركيا: الضرائب والدخل الأجنبي' },
  foreignDividends: { fr: 'Impôt sur les dividendes étrangers en Turquie', en: 'Foreign dividends tax in Turkey', ru: 'Налог на иностранные дивиденды в Турции', ar: 'ضريبة الأرباح الأجنبية في تركيا' },
  foreignCapitalGains: { fr: 'Plus-values étrangères en Turquie : fiscalité', en: 'Foreign capital gains in Turkey: tax', ru: 'Иностранные приросты капитала в Турции: налоги', ar: 'المكاسب الرأسمالية الأجنبية في تركيا: الضرائب' },
  inheritanceOnePercent: { fr: 'Héritage en Turquie : fiscalité à 1 % pour investisseurs', en: 'Turkey inheritance tax at 1% for investors', ru: 'Наследство в Турции: налог 1% для инвесторов', ar: 'الميراث في تركيا: ضريبة 1% للمستثمرين' },
  turkishDiaspora: { fr: 'Turcs de l’étranger et exonération fiscale en Turquie', en: 'Turks abroad and Turkey tax exemption', ru: 'Турки за рубежом и налоговая льгота в Турции', ar: 'الأتراك في الخارج والإعفاء الضريبي في تركيا' },
  digitalNomadTax: { fr: 'Digital nomad en Turquie : fiscalité et revenus étrangers', en: 'Digital nomad in Turkey: tax and foreign income', ru: 'Digital nomad в Турции: налоги и иностранные доходы', ar: 'Digital nomad في تركيا: الضرائب والدخل الأجنبي' },
  foreignPensionTax: { fr: 'Retraite étrangère en Turquie : fiscalité', en: 'Foreign pension in Turkey: tax', ru: 'Иностранная пенсия в Турции: налоги', ar: 'المعاش الأجنبي في تركيا: الضرائب' },
  turkeyVsItalyNonDom: { fr: 'Turquie vs Italie : régime non-dom et fiscalité', en: 'Turkey vs Italy: non-dom regime and tax', ru: 'Турция vs Италия: режим non-dom и налоги', ar: 'تركيا vs إيطاليا: نظام non-dom والضرائب' },
};

const labels = {
  fr: { guide: 'Guide privé · Fiscalité internationale Turquie', intro: 'Cette page fait partie du cluster Bosphoras dédié aux requêtes fiscales les plus qualifiées autour de la Turquie : résidence, revenus étrangers, non-dom, dividendes, plus-values, héritage, expatriés et investisseurs.', why: 'Pourquoi cette recherche va devenir importante', concerned: 'Profils concernés', verify: 'Points à vérifier avant toute décision', cta: 'Demander une analyse privée', faq: 'Questions fréquentes', warning: 'Cette page ne constitue pas un conseil fiscal. Les règles doivent être confirmées par les textes définitifs, les conventions fiscales applicables et une analyse personnalisée.' },
  en: { guide: 'Private guide · Turkey international tax', intro: 'This page is part of the Bosphoras cluster targeting the most qualified Turkey tax searches: residence, foreign income, non-dom, dividends, capital gains, inheritance, expats and investors.', why: 'Why this search will become important', concerned: 'Relevant profiles', verify: 'Points to verify before any decision', cta: 'Request a private assessment', faq: 'FAQ', warning: 'This page is not tax advice. Rules must be confirmed by final texts, applicable tax treaties and personalized review.' },
  ru: { guide: 'Частный гид · Международные налоги Турции', intro: 'Эта страница входит в кластер Bosphoras по самым квалифицированным налоговым запросам о Турции: резиденция, иностранные доходы, non-dom, дивиденды, прирост капитала, наследство, экспаты и инвесторы.', why: 'Почему этот запрос станет важным', concerned: 'Кого это касается', verify: 'Что проверить до решения', cta: 'Запросить частный анализ', faq: 'Частые вопросы', warning: 'Эта страница не является налоговой консультацией. Правила должны быть подтверждены финальными текстами, применимыми соглашениями и персональным анализом.' },
  ar: { guide: 'دليل خاص · الضرائب الدولية في تركيا', intro: 'هذه الصفحة جزء من مجموعة Bosphoras التي تستهدف أكثر عمليات البحث الضريبية تأهيلاً حول تركيا: الإقامة، الدخل الأجنبي، non-dom، الأرباح، المكاسب الرأسمالية، الميراث، المغتربين والمستثمرين.', why: 'لماذا سيصبح هذا البحث مهماً', concerned: 'الملفات المعنية', verify: 'ما يجب التحقق منه قبل أي قرار', cta: 'طلب تحليل خاص', faq: 'الأسئلة الشائعة', warning: 'هذه الصفحة لا تشكل استشارة ضريبية. يجب تأكيد القواعد عبر النصوص النهائية والاتفاقيات الضريبية والتحليل الشخصي.' },
};

const frBullets: Record<LongTailTaxKey, Array<[string, string]>> = {
  taxResidenceForeignIncome: [['Le vrai point de départ', 'Avant de parler d’exonération, il faut savoir si la personne devient résidente fiscale en Turquie et quels revenus entrent dans le champ turc.'], ['Revenus étrangers vs revenus turcs', 'La nouvelle fenêtre annoncée semble distinguer les revenus obtenus hors de Turquie et ceux de source turque, qui restent à analyser séparément.'], ['Condition des trois années précédentes', 'Le profil doit vérifier s’il a eu une résidence ou un assujettissement fiscal en Turquie récemment.'], ['Preuves et calendrier', 'Date d’arrivée, jours de présence, logement, banque, famille, société, revenus et documents doivent être cohérents.']],
  nonDomTurkey: [['Un terme déjà connu des investisseurs', 'Le mot non-dom parle aux profils qui connaissent Royaume-Uni, Italie, Malte, Chypre ou certains régimes européens.'], ['La Turquie peut créer une alternative', 'Une fenêtre de 20 ans sur certains revenus étrangers donnerait un angle très compétitif, sous réserve des textes finaux.'], ['Pas un simple slogan fiscal', 'Il faut vérifier résidence, domicile, nationalité, conventions fiscales, source des revenus et obligations déclaratives.'], ['Comparaison internationale', 'Italie, Portugal, Dubaï, Monaco, Chypre et Turquie doivent être comparés selon le profil réel.']],
  frenchExpatTax: [['France et Turquie', 'Un Français doit analyser sa résidence fiscale française, sa résidence turque et la convention fiscale entre les deux pays.'], ['Revenus français', 'Salaires, dividendes, immobilier, retraites, plus-values ou revenus professionnels français ne se traitent pas tous de la même manière.'], ['Installation familiale', 'Logement, école, santé, assurance, banque et centre d’intérêts comptent dans l’analyse.'], ['Exonération potentielle', 'La fenêtre turque peut être intéressante mais ne supprime pas automatiquement les obligations françaises.']],
  foreignDividends: [['Dividendes étrangers', 'Les dividendes de sociétés étrangères sont une requête très qualifiée pour entrepreneurs, holdings et investisseurs.'], ['Retenue à la source', 'Le pays de la société peut prélever une retenue avant même l’arrivée de l’argent en Turquie.'], ['Convention fiscale', 'Les traités peuvent modifier le taux réel et la méthode d’élimination de double imposition.'], ['Exonération 20 ans', 'Il faut vérifier si les dividendes entrent dans les revenus étrangers couverts par le dispositif final.']],
  foreignCapitalGains: [['Vente d’actions ou participations', 'Les plus-values sur actions, sociétés étrangères ou portefeuilles peuvent devenir un sujet central pour investisseurs mobiles.'], ['Immobilier hors Turquie', 'Une vente immobilière étrangère dépend souvent du pays où se situe le bien.'], ['Timing de résidence', 'La date de vente, la date d’installation et la date de résidence fiscale peuvent changer le résultat.'], ['Documentation', 'Prix d’acquisition, justificatifs, pays de source et conventions fiscales doivent être préparés.']],
  inheritanceOnePercent: [['Un angle patrimonial fort', 'Le taux annoncé de 1 % sur certaines transmissions peut attirer familles patrimoniales et clients de banque privée.'], ['Pas seulement l’impôt sur le revenu', 'La réforme touche aussi la transmission, le family office, la résidence et la conservation d’actifs.'], ['Actifs internationaux', 'Comptes, sociétés, immobilier, titres, or et patrimoine familial doivent être cartographiés.'], ['Transmission sécurisée', 'Il faut coordonner fiscalité turque, pays d’origine, droit successoral et stratégie familiale.']],
  turkishDiaspora: [['Retour de la diaspora', 'Les Turcs vivant à l’étranger peuvent chercher si un retour en Turquie ouvre une fenêtre fiscale sur leurs revenus étrangers.'], ['Revenus conservés à l’étranger', 'Salaire, société, dividendes, immobilier ou portefeuille hors Turquie doivent être analysés.'], ['Nationalité et résidence', 'La nationalité turque ne suffit pas : résidence fiscale, pays de source et historique fiscal comptent.'], ['Opportunité familiale', 'Retour partiel, installation des parents, enfants, patrimoine et immobilier en Turquie doivent être structurés.']],
  digitalNomadTax: [['Clients hors Turquie', 'Le nomade digital doit vérifier si ses revenus freelances ou remote proviennent réellement de l’étranger.'], ['Résidence et visa', 'Vivre à Istanbul, Antalya ou Bodrum ne règle pas seul la question fiscale.'], ['Source du revenu', 'Le lieu du client, du contrat, de la prestation et de la société peut changer l’analyse.'], ['Banque et facturation', 'Compte bancaire, plateforme de paiement, société étrangère ou freelance doivent être cohérents.']],
  foreignPensionTax: [['Pensions étrangères', 'Les retraités étrangers chercheront si leur pension peut être imposée en Turquie ou dans le pays payeur.'], ['Convention fiscale', 'La règle dépend souvent de la convention entre la Turquie et le pays d’origine.'], ['Santé et assurance', 'La fiscalité doit être liée à l’assurance santé, au logement, à la famille et au coût de vie.'], ['Profil patrimonial', 'Retraite, immobilier, placements et succession doivent être analysés ensemble.']],
  turkeyVsItalyNonDom: [['Italie comme référence', 'Le régime italien est déjà connu des grands patrimoines et crée une base de comparaison naturelle.'], ['Durée et coût', 'La Turquie pourrait se différencier par une fenêtre longue de 20 ans, mais les conditions finales sont déterminantes.'], ['Vie réelle', 'Dubaï, Italie, Portugal, Monaco et Turquie doivent être comparés sur fiscalité, famille, santé, banque et substance.'], ['Choix stratégique', 'Le meilleur pays dépend du type de revenus, de la nationalité, des actifs et de l’objectif familial.']],
};

const audiences: Record<LongTailTaxKey, string> = {
  taxResidenceForeignIncome: 'Entrepreneurs, investisseurs, rentiers, dirigeants, familles patrimoniales et expatriés qui envisagent de devenir résidents fiscaux en Turquie.',
  nonDomTurkey: 'Profils patrimoniaux qui connaissent déjà les régimes non-dom, family offices, entrepreneurs internationaux et investisseurs comparant plusieurs juridictions.',
  frenchExpatTax: 'Français vivant ou souhaitant vivre en Turquie, entrepreneurs français, retraités, investisseurs immobiliers et familles entre France et Turquie.',
  foreignDividends: 'Fondateurs, actionnaires, holdings, dirigeants, investisseurs en actions et clients de banque privée recevant des dividendes hors Turquie.',
  foreignCapitalGains: 'Investisseurs vendant actions, sociétés, participations, portefeuilles ou biens immobiliers situés hors de Turquie.',
  inheritanceOnePercent: 'Familles patrimoniales, clients private banking, family offices et investisseurs qui veulent préparer transmission et résidence.',
  turkishDiaspora: 'Turcs de l’étranger, binationaux, entrepreneurs de diaspora, familles installées en Europe, au Golfe ou en Amérique du Nord.',
  digitalNomadTax: 'Freelances, consultants, entrepreneurs SaaS, remote workers et nomades digitaux qui facturent des clients hors Turquie.',
  foreignPensionTax: 'Retraités étrangers, préretraités, expatriés français, familles souhaitant vivre à Istanbul, Antalya, Bodrum ou Izmir.',
  turkeyVsItalyNonDom: 'Grands patrimoines, investisseurs internationaux, family offices et entrepreneurs qui comparent Italie, Turquie, Dubaï, Portugal ou Monaco.',
};

function assessmentHref(locale: Locale) { return locale === 'fr' ? '/diagnostic-prive' : locale === 'en' ? '/en/private-assessment' : locale === 'ru' ? '/ru/chastnaya-konsultatsiya' : '/ar/تقييم-خاص'; }

export function getLongTailTaxMetadata(pageKey: LongTailTaxKey, locale: Locale): Metadata {
  const canonical = `https://bosphoras.com${longTailTaxSlugs[pageKey][locale]}`;
  const title = `${titles[pageKey][locale]} | Bosphoras`;
  const description = `${titles[pageKey][locale]} — ${labels[locale].intro}`;
  return { title, description, alternates: { canonical, languages: { fr: `https://bosphoras.com${longTailTaxSlugs[pageKey].fr}`, en: `https://bosphoras.com${longTailTaxSlugs[pageKey].en}`, ru: `https://bosphoras.com${longTailTaxSlugs[pageKey].ru}`, ar: `https://bosphoras.com${longTailTaxSlugs[pageKey].ar}`, 'x-default': `https://bosphoras.com${longTailTaxSlugs[pageKey].fr}` } }, openGraph: { title, description, url: canonical, siteName: 'Bosphoras', locale: locale === 'fr' ? 'fr_FR' : locale === 'en' ? 'en_US' : locale === 'ru' ? 'ru_RU' : 'ar_AR', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: title }] }, twitter: { card: 'summary_large_image', title, description, images: ['/images/og-default.jpg'] } };
}

export const longTailTaxFooterLinks: Record<Locale, Array<{ href: string; label: string }>> = {
  fr: longTailTaxKeys.map((k) => ({ href: longTailTaxSlugs[k].fr, label: titles[k].fr })),
  en: longTailTaxKeys.map((k) => ({ href: longTailTaxSlugs[k].en, label: titles[k].en })),
  ru: longTailTaxKeys.map((k) => ({ href: longTailTaxSlugs[k].ru, label: titles[k].ru })),
  ar: longTailTaxKeys.map((k) => ({ href: longTailTaxSlugs[k].ar, label: titles[k].ar })),
};

export function LongTailTaxSeoPage({ pageKey, locale }: { pageKey: LongTailTaxKey; locale: Locale }) {
  const l = labels[locale];
  const title = titles[pageKey][locale];
  const list = frBullets[pageKey];
  const faq = [
    [locale === 'fr' ? 'Cette opportunité fiscale est-elle garantie ?' : locale === 'en' ? 'Is this tax opportunity guaranteed?' : locale === 'ru' ? 'Эта налоговая возможность гарантирована?' : 'هل هذه الفرصة الضريبية مضمونة؟', locale === 'fr' ? 'Non. Le dispositif dépend des textes définitifs, des conditions d’éligibilité et de la situation personnelle du client.' : locale === 'en' ? 'No. The regime depends on final legislation, eligibility conditions and the client’s personal situation.' : locale === 'ru' ? 'Нет. Режим зависит от финальных текстов, условий права и личной ситуации клиента.' : 'لا. يعتمد النظام على النصوص النهائية وشروط الأهلية والوضع الشخصي للعميل.'],
    [locale === 'fr' ? 'Pourquoi faire un diagnostic privé ?' : locale === 'en' ? 'Why request a private assessment?' : locale === 'ru' ? 'Почему нужен частный анализ?' : 'لماذا طلب تحليل خاص؟', locale === 'fr' ? 'Parce que deux profils avec les mêmes revenus peuvent avoir une conclusion différente selon résidence, pays de source, convention fiscale, banque, famille et calendrier.' : locale === 'en' ? 'Because two profiles with similar income can have different outcomes depending on residence, source country, tax treaty, banking, family and timing.' : locale === 'ru' ? 'Потому что два профиля с похожими доходами могут получить разный результат по резиденции, стране источника, соглашению, банку, семье и срокам.' : 'لأن ملفين بدخل مشابه قد تكون نتيجتهما مختلفة حسب الإقامة ودولة المصدر والاتفاقية الضريبية والبنك والعائلة والتوقيت.'],
  ];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: title, description: l.intro, inLanguage: locale, datePublished: '2026-05-07', dateModified: '2026-05-07', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${longTailTaxSlugs[pageKey][locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={longTailTaxSlugs[pageKey][locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{l.guide}</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{title}</h1><p className="mt-8 max-w-3xl text-lg leading-9 text-white/80">{l.intro}</p><div className="mt-10"><Link href={assessmentHref(locale)} className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{l.cta}<ArrowRight size={16} /></Link></div></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-12 lg:grid-cols-[0.85fr_1.15fr]"><aside className="border border-[#d8c7a1] bg-[#fffaf0] p-8"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{l.why}</h2><p className="mt-5 leading-8 text-[#3e4857]">{audiences[pageKey]}</p></aside><div className="grid gap-4 md:grid-cols-2">{list.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-7"><Sparkles className="mb-5 h-5 w-5 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><Users className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{l.concerned}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{audiences[pageKey]}</p></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1000px]"><div className="border-l-4 border-[#8a6728] bg-white p-8"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{l.verify}</h2><p className="mt-5 text-lg leading-9 text-[#3e4857]">{l.warning}</p><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{['résidence fiscale actuelle','source des revenus','convention fiscale applicable','banque et conformité','preuves documentaires','calendrier d’installation'].map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></div></div></section>
        <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto flex max-w-[1200px] flex-col gap-8 md:flex-row md:items-center md:justify-between"><h2 className="font-serif text-4xl tracking-[-0.03em] md:text-6xl">Bosphoras Private Desk</h2><Link href={assessmentHref(locale)} className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-5 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{l.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">{l.faq}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
