import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/turcs-de-l-etranger-exoneration-fiscale-turquie',
  en: '/en/turks-abroad-turkey-tax-exemption',
  ru: '/ru/turki-za-rubezhom-nalogovaya-lgota-turtsiya',
  ar: '/ar/turks-abroad-turkey-tax-exemption',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = { title:string; metaTitle:string; description:string; eyebrow:string; hero:string; cta:string; asideTitle:string; finalTitle:string; finalText:string; faqTitle:string; checklist:string[]; sections:Array<[string,string]>; faq:Array<[string,string]> };

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Turcs de l’étranger : exonération fiscale en Turquie, retour et revenus étrangers',
    metaTitle: 'Turcs de l’étranger : exonération fiscale en Turquie et retour',
    description: 'Turcs vivant à l’étranger : retour en Turquie, résidence fiscale, revenus étrangers, dividendes, plus-values, immobilier, famille et exonération fiscale potentielle pour nouveaux résidents.',
    eyebrow: 'Diaspora turque · Retour en Turquie · Fiscalité',
    hero: 'Pour un Turc vivant à l’étranger, revenir en Turquie peut être un projet personnel, familial, patrimonial et professionnel. Si la Turquie confirme un régime fiscal favorable pour certains nouveaux résidents, il faut organiser le retour avant de transférer les fonds, les revenus, les sociétés ou la vie familiale.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant d’organiser votre retour',
    finalTitle: 'Un retour en Turquie doit être cohérent fiscalement, bancairement et familialement',
    finalText: 'Avant de transférer vos fonds, vos comptes, vos revenus ou votre résidence, Bosphoras peut organiser une analyse privée de votre situation : fiscalité, banque, société, dividendes, plus-values, immobilier, assurance, famille et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Votre résidence fiscale actuelle', 'Votre historique fiscal récent en Turquie', 'Vos revenus étrangers', 'Vos sociétés et dividendes', 'Vos plus-values et actifs étrangers', 'Vos biens immobiliers en Turquie et à l’étranger', 'La banque et l’origine des fonds', 'Votre installation familiale réelle'],
    sections: [
      ['Pourquoi les Turcs de l’étranger doivent préparer leur retour', 'Un retour en Turquie ne se résume pas à acheter un logement ou ouvrir un compte bancaire. Si vous vivez depuis plusieurs années à l’étranger, votre situation peut être liée à plusieurs pays : résidence fiscale actuelle, entreprise étrangère, revenus professionnels, dividendes, plus-values, comptes bancaires, immobilier, assurance santé, retraite, école des enfants, patrimoine familial et obligations déclaratives. Avant de revenir, il faut comprendre ce qui reste dans le pays de départ, ce qui sera transféré en Turquie et ce qui peut être concerné par la fiscalité turque.'],
      ['La condition des années précédentes', 'Le régime annoncé semble viser les personnes qui n’ont pas été résidentes fiscales ou contribuables en Turquie pendant une période précédente. Pour les Turcs de l’étranger, ce point est très important. Il faut vérifier si vous avez vécu récemment en Turquie, déclaré des revenus en Turquie, détenu une société turque, possédé un bien locatif, été enregistré fiscalement, passé une grande partie de l’année en Turquie ou perçu des revenus de source turque.'],
      ['Revenus étrangers : ce qui peut être concerné', 'Un Turc de l’étranger peut avoir plusieurs types de revenus hors de Turquie : dividendes d’une société étrangère, salaire, revenus professionnels, consulting, revenus immobiliers, intérêts bancaires, portefeuille financier, plus-values sur actions, vente d’entreprise, pension étrangère ou revenus familiaux. Si la Turquie confirme une exonération sur certains revenus étrangers pour des nouveaux résidents, ces catégories devront être analysées une par une.'],
      ['Entreprise à l’étranger et retour en Turquie', 'Beaucoup de Turcs de l’étranger possèdent une société dans leur pays de résidence : société en France, GmbH en Allemagne, société en Belgique ou aux Pays-Bas, LTD au Royaume-Uni, société aux Émirats, société au Kazakhstan, société familiale ou holding. Si vous revenez vivre en Turquie, il faut analyser où cette société sera réellement dirigée, où sont les clients, où se trouve l’équipe, où les contrats sont signés, où les décisions sont prises et où les bénéfices sont imposés.'],
      ['Dividendes et plus-values avant le retour', 'Si vous possédez une société ou un portefeuille financier, le calendrier de retour est essentiel. Il faut distinguer les dividendes distribués avant le retour, les dividendes distribués après le retour, la vente d’actions avant l’installation, la vente d’entreprise après le retour, les plus-values accumulées avant le changement de résidence et les revenus générés après l’installation en Turquie. Une distribution ou une vente mal placée dans le temps peut créer une double imposition ou une difficulté bancaire.'],
      ['Immobilier à l’étranger et immobilier en Turquie', 'Beaucoup de Turcs de l’étranger possèdent déjà un bien en Turquie ou envisagent d’en acheter un. Il faut distinguer résidence familiale en Turquie, bien locatif en Turquie, appartement conservé à l’étranger, maison familiale dans le pays de résidence, investissement immobilier étranger, vente d’un bien à l’étranger et achat à Istanbul, Bodrum, Antalya ou Izmir. Un bien situé à l’étranger peut rester imposable dans le pays où il se trouve. Un bien situé en Turquie peut générer des revenus de source turque.'],
      ['Banque, transfert de fonds et conformité', 'Le retour en Turquie peut impliquer des transferts importants : épargne personnelle, vente d’un bien immobilier, dividendes, vente de société, portefeuille financier, comptes étrangers ou capital familial. Les banques turques peuvent demander origine des fonds, déclarations fiscales, contrats de vente, statuts de société, relevés bancaires, preuve de propriété, certificat de résidence fiscale, documents traduits et apostillés et explication de la structure patrimoniale.'],
      ['Famille, enfants et installation réelle', 'Le retour en Turquie n’est pas seulement fiscal. Il peut concerner le logement familial, l’école des enfants, l’assurance santé, la couverture médicale, les déplacements entre deux pays, le conjoint, les parents, la continuité de l’entreprise, le niveau de vie et la sécurité patrimoniale. Si la famille reste principalement à l’étranger ou si l’entreprise continue d’être dirigée depuis l’étranger, le retour fiscal peut être plus difficile à justifier.'],
      ['Pays de départ : ne pas oublier les obligations locales', 'Quitter son pays de résidence actuelle ne signifie pas automatiquement quitter son système fiscal. Le pays de départ peut continuer à vous considérer résident fiscal si votre foyer reste sur place, si votre entreprise reste dirigée depuis ce pays, si vos principaux actifs y sont situés, si vous y passez beaucoup de temps, si votre famille y vit encore ou si vos revenus principaux viennent de ce pays.'],
      ['Les erreurs à éviter', 'La première erreur est de croire que revenir en Turquie règle automatiquement la fiscalité. La deuxième est de transférer des fonds sans préparer les justificatifs. La troisième est de conserver une société étrangère sans analyser la direction effective. La quatrième est de distribuer des dividendes ou vendre des actifs sans réfléchir au calendrier. La cinquième est d’acheter un bien en Turquie sans organiser la résidence fiscale.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste, un expert-comptable ou un conseiller patrimonial. Notre rôle est de coordonner votre retour en Turquie avec les bons interlocuteurs : analyse de votre résidence fiscale actuelle, préparation du dossier de retour, cartographie de vos revenus étrangers, analyse des sociétés et dividendes, plus-values et actifs étrangers, coordination avec fiscalistes turcs et étrangers, préparation bancaire, conformité, recherche immobilière, assurance santé et installation familiale.'],
    ],
    faq: [['Les Turcs de l’étranger peuvent-ils bénéficier d’une exonération fiscale en Turquie ?', 'Potentiellement, si le texte final les inclut et si leur situation respecte les conditions. Il faudra vérifier leur historique fiscal en Turquie, leur résidence actuelle, la nature des revenus étrangers et la date de retour.'], ['Le fait d’être citoyen turc suffit-il pour bénéficier du régime ?', 'Non. La citoyenneté ne suffit pas. Il faut analyser la résidence fiscale, l’historique fiscal, les revenus concernés et les conditions prévues par le texte final.'], ['Si je reviens en Turquie, mes revenus étrangers seront-ils automatiquement exonérés ?', 'Non. Il faut vérifier la nature des revenus, le pays de source, les conventions fiscales, la date du retour et votre situation personnelle.'], ['Puis-je garder ma société à l’étranger en vivant en Turquie ?', 'Potentiellement, mais il faut analyser la direction effective, les clients, les contrats, la banque, les dividendes et les risques fiscaux.'], ['Puis-je transférer mon argent en Turquie facilement ?', 'Oui, mais les banques peuvent demander des justificatifs sur l’origine des fonds, les revenus, les ventes d’actifs, les sociétés et la résidence fiscale.'], ['Bosphoras donne-t-il un conseil fiscal ?', 'Non. Bosphoras coordonne l’analyse privée et les bons interlocuteurs : fiscalistes, avocats, banques, comptables, assurance, immobilier et partenaires d’installation en Turquie.']],
  },
  en: {
    title: 'Turks Abroad: Turkey tax exemption, return planning and foreign income',
    metaTitle: 'Turks Abroad: Turkey Tax Exemption and Return Planning',
    description: 'Turks living abroad: returning to Turkey, tax residence, foreign income, dividends, capital gains, property, family relocation and potential tax exemption for new residents.',
    eyebrow: 'Turkish diaspora · Return to Turkey · Tax',
    hero: 'For Turkish citizens and families living abroad, returning to Turkey can be a personal, family, business and wealth decision. If Turkey confirms a favorable tax regime for certain new residents, the return should be prepared before moving funds, companies, income or family life.',
    cta: 'Request a private assessment',
    asideTitle: 'Before returning to Turkey',
    finalTitle: 'Returning to Turkey should be consistent from a tax, banking and family perspective',
    finalText: 'Before transferring funds, accounts, income or residence to Turkey, Bosphoras can organize a private review of your situation: tax, banking, companies, dividends, capital gains, property, insurance, family and relocation.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Your current tax residence', 'Your recent Turkish tax history', 'Your foreign income', 'Your companies and dividends', 'Your capital gains and foreign assets', 'Your property in Turkey and abroad', 'Banking and source of funds', 'Your real family relocation'],
    sections: [
      ['Why Turks abroad should prepare their return', 'Returning to Turkey is not only about buying a home or opening a bank account. If you have lived abroad for years, your situation may involve several countries: current tax residence, foreign business, professional income, dividends, capital gains, bank accounts, property, health insurance, pension, children’s schooling, family wealth and reporting obligations. Before returning, you should understand what remains in the departure country, what moves to Turkey and what may become relevant for Turkish tax purposes.'],
      ['The previous-years condition', 'The announced regime appears to target people who have not been Turkish tax residents or Turkish taxpayers during a previous period. For Turks abroad, this point is important. You should review whether you recently lived in Turkey, declared Turkish income, owned a Turkish company, held rental property, had tax registration, spent significant time in Turkey or received Turkish-source income.'],
      ['Foreign income that may be relevant', 'A Turk living abroad may have several categories of foreign income: dividends from a foreign company, salary, professional income, consulting income, real estate income, bank interest, investment portfolio income, capital gains, sale of a business, foreign pension or family wealth income. If Turkey confirms an exemption for certain foreign income of new residents, each category should be reviewed separately.'],
      ['Foreign business and return to Turkey', 'Many Turks abroad own businesses in their country of residence: companies in Germany, France, the Netherlands, Belgium, the United Kingdom, the UAE, Kazakhstan or family holding structures. If you return to Turkey, you should review where the company is effectively managed, where clients are located, where contracts are signed, where decisions are made, where banking is handled, where profits are taxed and how dividends are distributed.'],
      ['Dividends and capital gains before returning', 'If you own a company or an investment portfolio, timing is essential. Dividends paid before returning, dividends paid after returning, share sales before relocation, business sales after return, unrealized gains accumulated before the residence change and income generated after relocation may all lead to different outcomes. A poorly timed distribution or sale can create double taxation, banking issues or inconsistency in the residence file.'],
      ['Property abroad and property in Turkey', 'Many Turks abroad already own property in Turkey or plan to buy one. You should distinguish family residence in Turkey, rental property in Turkey, apartments kept abroad, family homes in the country of residence, foreign real estate investments, sale of foreign property and purchases in Istanbul, Bodrum, Antalya or Izmir. Foreign property may remain taxable where it is located. Turkish property may generate Turkish-source income.'],
      ['Banking, transfers and compliance', 'Returning to Turkey can involve significant transfers: personal savings, sale of real estate, dividends, sale of a company, investment portfolios, foreign accounts or family capital. Turkish banks may request source-of-funds evidence, tax filings, sale contracts, company documents, bank statements, proof of ownership, tax residence certificates, translated and apostilled documents and an explanation of the wealth structure.'],
      ['Family, children and real relocation', 'The return is not only a tax matter. It may involve family housing, children’s schooling, health insurance, medical coverage, travel between countries, the spouse, parents, business continuity, lifestyle and wealth security. If the family remains mainly abroad or the business continues to be managed from abroad, the tax return to Turkey may be harder to support.'],
      ['Departure country obligations', 'Leaving the current country of residence does not automatically end its tax system’s interest in you. The departure country may still consider you tax resident if your home, business, main assets, family, time spent or main income remain there. The exit from the departure country and the real installation in Turkey should be coordinated together.'],
      ['Mistakes to avoid', 'Do not assume returning to Turkey automatically solves tax issues. Do not transfer funds without preparing evidence. Do not keep a foreign company without reviewing effective management. Do not distribute dividends or sell assets without reviewing timing. Do not buy property in Turkey without organizing tax residence. Do not ignore family, school, insurance and proof of real relocation.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers, accountants or wealth advisors. Its role is to coordinate your return to Turkey with the right professionals: current residence review, return file preparation, foreign income mapping, company and dividend analysis, capital gains and asset review, coordination with Turkish and foreign tax advisors, banking preparation, compliance, property search, health insurance and family relocation.'],
    ],
    faq: [['Can Turks abroad benefit from a Turkish tax exemption?', 'Potentially, if the final text includes them and if their situation meets the conditions. Turkish tax history, current residence, type of foreign income and return date should be reviewed.'], ['Is Turkish citizenship enough to benefit from the regime?', 'No. Citizenship is not enough. Tax residence, tax history, income categories and final legal conditions must be reviewed.'], ['Will my foreign income automatically be exempt if I return to Turkey?', 'No. Income type, source country, treaties, return date and personal situation must be reviewed.'], ['Can I keep a foreign company while living in Turkey?', 'Potentially, but effective management, clients, contracts, banking, dividends and tax risks must be reviewed.'], ['Can I transfer money to Turkey easily?', 'Yes, but banks may request evidence of source of funds, income, asset sales, companies and tax residence.'], ['Does Bosphoras provide tax advice?', 'No. Bosphoras coordinates the private review and connects clients with suitable tax advisors, lawyers, banks, accountants, insurance and relocation partners.']],
  },
  ru: {
    title: 'Турки за рубежом: налоговая льгота в Турции, возвращение и иностранные доходы',
    metaTitle: 'Турки за рубежом: налоговая льгота в Турции и возвращение',
    description: 'Турки, живущие за рубежом: возвращение в Турцию, налоговая резиденция, иностранные доходы, дивиденды, прирост капитала, семья и банковская подготовка.',
    eyebrow: 'Турецкая диаспора · Возвращение в Турцию · Налоги',
    hero: 'Для турецких граждан и семей, живущих за рубежом, возвращение в Турцию может быть личным, семейным, деловым и имущественным решением. Если Турция подтвердит благоприятный режим для новых резидентов, возвращение нужно готовить заранее.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед возвращением в Турцию',
    finalTitle: 'Возвращение в Турцию должно быть логичным для налогов, банков и семьи',
    finalText: 'До перевода средств, счетов, доходов или резиденции в Турцию Bosphoras может организовать частный анализ вашей ситуации: налоги, банки, компании, дивиденды, прирост капитала, недвижимость, страхование, семья и переезд.',
    faqTitle: 'Частые вопросы',
    checklist: ['Текущая налоговая резиденция', 'Недавняя налоговая история в Турции', 'Иностранные доходы', 'Компании и дивиденды', 'Прирост капитала и иностранные активы', 'Недвижимость в Турции и за рубежом', 'Банк и происхождение средств', 'Реальный семейный переезд'],
    sections: [
      ['Почему туркам за рубежом нужно готовить возвращение', 'Возвращение в Турцию — это не только покупка жилья или открытие счета. Если вы много лет живете за рубежом, ваша ситуация может быть связана с несколькими странами: текущая налоговая резиденция, иностранный бизнес, профессиональные доходы, дивиденды, прирост капитала, счета, недвижимость, медицина, пенсия, школа детей, семейный капитал и отчетные обязанности.'],
      ['Условие предыдущих лет', 'Объявленный режим, по имеющейся информации, ориентирован на лиц, которые не были налоговыми резидентами или налогоплательщиками в Турции в предыдущий период. Для турков за рубежом это важный пункт. Нужно проверить, жили ли вы недавно в Турции, декларировали ли доход, имели ли турецкую компанию, арендную недвижимость, налоговую регистрацию, значительное пребывание или доходы из Турции.'],
      ['Иностранные доходы, которые могут быть важны', 'Турок, живущий за рубежом, может иметь разные категории иностранных доходов: дивиденды от иностранной компании, зарплату, профессиональные доходы, консалтинг, аренду, банковские проценты, инвестиционный портфель, прирост капитала, продажу бизнеса, иностранную пенсию или семейный доход. Если Турция подтвердит освобождение некоторых иностранных доходов новых резидентов, каждую категорию нужно анализировать отдельно.'],
      ['Иностранный бизнес и возвращение в Турцию', 'Многие турки за рубежом владеют бизнесом в стране проживания: компании в Германии, Франции, Нидерландах, Бельгии, Великобритании, ОАЭ, Казахстане или семейные holding-структуры. При возвращении нужно понять, где компания фактически управляется, где клиенты, договоры, решения, банк, налоги на прибыль и дивиденды.'],
      ['Дивиденды и прирост капитала до возвращения', 'Если у вас есть компания или инвестиционный портфель, календарь имеет значение. Дивиденды до возвращения, дивиденды после возвращения, продажа акций до переезда, продажа бизнеса после возвращения, скрытые gains до смены резиденции и доходы после переезда могут иметь разные последствия.'],
      ['Недвижимость за рубежом и в Турции', 'Многие турки за рубежом уже имеют недвижимость в Турции или планируют покупку. Нужно разделить семейную резиденцию, арендную недвижимость в Турции, квартиру за рубежом, семейный дом в стране проживания, иностранные инвестиции, продажу иностранного объекта и покупку в Стамбуле, Бодруме, Анталье или Измире.'],
      ['Банки, переводы и compliance', 'Возвращение может включать крупные переводы: накопления, продажу недвижимости, дивиденды, продажу компании, портфель, иностранные счета или семейный капитал. Турецкие банки могут запросить происхождение средств, налоговые декларации, договоры продажи, документы компании, выписки, доказательство собственности, сертификат резиденции, переводы, апостили и объяснение структуры капитала.'],
      ['Семья, дети и реальный переезд', 'Возвращение — не только налоговый вопрос. Оно может включать семейное жилье, школу детей, медицинскую страховку, перемещения между странами, супругу или супруга, родителей, продолжение бизнеса, уровень жизни и безопасность капитала. Если семья остается за рубежом или бизнес управляется оттуда, налоговое возвращение в Турцию сложнее обосновать.'],
      ['Обязанности страны выезда', 'Выезд из страны проживания не означает автоматического прекращения налоговой связи с ней. Страна выезда может продолжать считать вас резидентом, если дом, бизнес, основные активы, семья, время пребывания или основные доходы остаются там. Выход из страны выезда и реальная установка в Турции должны быть согласованы.'],
      ['Ошибки, которых нужно избегать', 'Не думайте, что возвращение в Турцию автоматически решает налоги. Не переводите средства без документов. Не сохраняйте иностранную компанию без анализа фактического управления. Не распределяйте дивиденды и не продавайте активы без анализа календаря. Не покупайте недвижимость в Турции без организации налоговой резиденции.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов, бухгалтеров или wealth advisors. Его роль — координировать ваше возвращение в Турцию с профильными специалистами: анализ текущей резиденции, подготовка файла возвращения, карта иностранных доходов, анализ компаний и дивидендов, приростов и активов, координация с турецкими и иностранными специалистами, подготовка банка, compliance, недвижимость, страхование и семейный переезд.'],
    ],
    faq: [['Могут ли турки за рубежом воспользоваться налоговой льготой в Турции?', 'Потенциально, если финальный текст их включает и ситуация соответствует условиям. Нужно проверить историю в Турции, текущую резиденцию, тип доходов и дату возвращения.'], ['Достаточно ли турецкого гражданства?', 'Нет. Гражданства недостаточно. Нужен анализ налоговой резиденции, истории, доходов и финальных условий закона.'], ['Будут ли иностранные доходы автоматически освобождены после возвращения?', 'Нет. Нужно проверить тип дохода, страну источника, соглашения, дату возвращения и личную ситуацию.'], ['Можно ли сохранить иностранную компанию, живя в Турции?', 'Потенциально, но нужно анализировать фактическое управление, клиентов, договоры, банки, дивиденды и налоговые риски.'], ['Можно ли легко перевести деньги в Турцию?', 'Да, но банки могут запросить документы о происхождении средств, доходах, продаже активов, компаниях и налоговой резиденции.'], ['Bosphoras дает налоговую консультацию?', 'Нет. Bosphoras координирует частный анализ и связывает клиентов с налоговыми специалистами, юристами, банками, бухгалтерами, страхованием и партнерами по переезду.']],
  },
  ar: {
    title: 'الأتراك في الخارج: الإعفاء الضريبي في تركيا والعودة والدخل الأجنبي',
    metaTitle: 'الأتراك في الخارج: الإعفاء الضريبي في تركيا والعودة',
    description: 'الأتراك المقيمون في الخارج: العودة إلى تركيا، الإقامة الضريبية، الدخل الأجنبي، الأرباح، المكاسب، العقار، الأسرة والبنوك.',
    eyebrow: 'الشتات التركي · العودة إلى تركيا · الضرائب',
    hero: 'بالنسبة للمواطنين الأتراك والعائلات التركية المقيمة في الخارج، قد تكون العودة إلى تركيا قراراً عائلياً ومالياً ومهنياً. إذا أكدت تركيا نظاماً ضريبياً مناسباً لبعض المقيمين الجدد، يجب تنظيم العودة قبل نقل الأموال أو الشركات أو الدخل أو الحياة العائلية.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل العودة إلى تركيا',
    finalTitle: 'العودة إلى تركيا يجب أن تكون منسجمة ضريبياً وبنكياً وعائلياً',
    finalText: 'قبل نقل الأموال أو الحسابات أو الدخل أو الإقامة إلى تركيا، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك: الضرائب، البنوك، الشركات، الأرباح، المكاسب، العقار، التأمين، الأسرة والانتقال.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['إقامتك الضريبية الحالية', 'تاريخك الضريبي الحديث في تركيا', 'الدخل الأجنبي', 'الشركات والأرباح', 'المكاسب والأصول الأجنبية', 'العقار في تركيا وخارجها', 'البنك ومصدر الأموال', 'الانتقال العائلي الحقيقي'],
    sections: [
      ['لماذا يجب على الأتراك في الخارج تحضير العودة', 'العودة إلى تركيا لا تعني فقط شراء منزل أو فتح حساب بنكي. إذا كنت تعيش في الخارج منذ سنوات، فقد تكون وضعيتك مرتبطة بعدة دول: الإقامة الضريبية الحالية، شركة أجنبية، دخل مهني، أرباح، مكاسب، حسابات بنكية، عقار، تأمين صحي، تقاعد، مدرسة الأطفال، ثروة عائلية والتزامات تصريحية.'],
      ['شرط السنوات السابقة', 'يبدو أن النظام المعلن يستهدف الأشخاص الذين لم يكونوا مقيمين ضريبياً أو مكلفين ضريبياً في تركيا خلال فترة سابقة. بالنسبة للأتراك في الخارج، هذا مهم جداً. يجب التحقق مما إذا كنت عشت مؤخراً في تركيا، صرحت بدخل، امتلكت شركة تركية، عقاراً مؤجراً، تسجيلاً ضريبياً، إقامة طويلة أو دخلاً من مصدر تركي.'],
      ['الدخل الأجنبي الذي قد يكون معنياً', 'قد يكون لدى التركي المقيم في الخارج عدة أنواع من الدخل الأجنبي: أرباح من شركة أجنبية، راتب، دخل مهني، استشارات، دخل عقاري، فوائد بنكية، محفظة استثمارية، مكاسب رأسمالية، بيع شركة، معاش أجنبي أو دخل عائلي. إذا أكدت تركيا إعفاء بعض الدخل الأجنبي للمقيمين الجدد، يجب تحليل كل فئة بشكل منفصل.'],
      ['شركة في الخارج والعودة إلى تركيا', 'كثير من الأتراك في الخارج يملكون شركات في بلد الإقامة: ألمانيا، فرنسا، هولندا، بلجيكا، المملكة المتحدة، الإمارات، كازاخستان أو holding عائلي. عند العودة إلى تركيا يجب تحليل أين تدار الشركة فعلياً، أين العملاء، العقود، القرارات، البنك، الضرائب على الأرباح وكيف توزع الأرباح.'],
      ['الأرباح والمكاسب قبل العودة', 'إذا كنت تملك شركة أو محفظة استثمارية، فإن التوقيت مهم. الأرباح قبل العودة، الأرباح بعد العودة، بيع الأسهم قبل الانتقال، بيع الشركة بعد العودة، المكاسب المتراكمة قبل تغيير الإقامة والدخل المتولد بعد الانتقال قد تؤدي إلى نتائج مختلفة.'],
      ['العقار في الخارج والعقار في تركيا', 'كثير من الأتراك في الخارج لديهم بالفعل عقار في تركيا أو يخططون للشراء. يجب التمييز بين السكن العائلي، العقار المؤجر في تركيا، شقة في الخارج، بيت عائلي في بلد الإقامة، استثمار عقاري أجنبي، بيع عقار في الخارج وشراء في إسطنبول أو بودروم أو أنطاليا أو إزمير.'],
      ['البنوك والتحويلات والامتثال', 'العودة إلى تركيا قد تشمل تحويلات مهمة: مدخرات، بيع عقار، أرباح، بيع شركة، محفظة استثمارية، حسابات أجنبية أو رأس مال عائلي. قد تطلب البنوك التركية مصدر الأموال، التصريحات الضريبية، عقود البيع، مستندات الشركة، كشوفات بنكية، إثبات الملكية، شهادة الإقامة الضريبية، ترجمات وتصديقات وشرح هيكل الثروة.'],
      ['الأسرة والأطفال والانتقال الحقيقي', 'العودة ليست موضوعاً ضريبياً فقط. قد تشمل السكن العائلي، مدرسة الأطفال، التأمين الصحي، التغطية الطبية، التنقل بين بلدين، الزوج أو الزوجة، الوالدين، استمرار العمل، مستوى الحياة وحماية الثروة. إذا بقيت الأسرة في الخارج أو استمرت الشركة تدار من هناك، قد يصعب تبرير العودة الضريبية إلى تركيا.'],
      ['التزامات بلد المغادرة', 'مغادرة بلد الإقامة الحالي لا تعني تلقائياً الخروج من نظامه الضريبي. قد يستمر بلد المغادرة في اعتبارك مقيماً إذا بقي المنزل أو الشركة أو الأصول الرئيسية أو الأسرة أو الوقت أو الدخل الرئيسي هناك. يجب تنسيق الخروج من بلد المغادرة مع التثبيت الحقيقي في تركيا.'],
      ['أخطاء يجب تجنبها', 'لا تفترض أن العودة إلى تركيا تحل كل المسائل الضريبية تلقائياً. لا تحول الأموال دون تحضير المستندات. لا تحتفظ بشركة أجنبية دون تحليل الإدارة الفعلية. لا توزع أرباحاً أو تبيع أصولاً دون دراسة التوقيت. لا تشتر عقاراً في تركيا دون تنظيم الإقامة الضريبية.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامي الضريبي أو المحاسب أو مستشار الثروة. دوره هو تنسيق عودتك إلى تركيا مع المختصين المناسبين: تحليل الإقامة الحالية، إعداد ملف العودة، خريطة الدخل الأجنبي، تحليل الشركات والأرباح، المكاسب والأصول، التنسيق مع مستشارين أتراك وأجانب، التحضير البنكي، الامتثال، العقار، التأمين والانتقال العائلي.'],
    ],
    faq: [['هل يمكن للأتراك في الخارج الاستفادة من إعفاء ضريبي في تركيا؟', 'محتمل إذا شملهم النص النهائي وكانت وضعيتهم تستوفي الشروط. يجب مراجعة التاريخ الضريبي في تركيا، الإقامة الحالية، نوع الدخل الأجنبي وتاريخ العودة.'], ['هل تكفي الجنسية التركية للاستفادة من النظام؟', 'لا. الجنسية لا تكفي. يجب تحليل الإقامة الضريبية، التاريخ الضريبي، أنواع الدخل والشروط النهائية.'], ['هل سيعفى الدخل الأجنبي تلقائياً إذا عدت إلى تركيا؟', 'لا. يجب مراجعة نوع الدخل، بلد المصدر، الاتفاقيات، تاريخ العودة والوضع الشخصي.'], ['هل يمكنني الاحتفاظ بشركة أجنبية أثناء العيش في تركيا؟', 'محتمل، لكن يجب تحليل الإدارة الفعلية، العملاء، العقود، البنك، الأرباح والمخاطر الضريبية.'], ['هل يمكن تحويل الأموال إلى تركيا بسهولة؟', 'نعم، لكن البنوك قد تطلب مستندات حول مصدر الأموال، الدخل، بيع الأصول، الشركات والإقامة الضريبية.'], ['هل يقدم Bosphoras استشارة ضريبية؟', 'لا. Bosphoras ينسق المراجعة الخاصة ويربط العملاء بالمستشارين الضريبيين والمحامين والبنوك والمحاسبين والتأمين وشركاء الانتقال.']],
  },
};

export function getTurksAbroadTaxExemptionMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function TurksAbroadTaxExemptionClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
