import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/turquie-vs-dubai-fiscalite-revenus-etrangers',
  en: '/en/turkey-vs-dubai-tax-residence-foreign-income',
  ru: '/ru/turtsiya-vs-dubay-nalogi-inostrannye-dohody',
  ar: '/ar/turkey-vs-dubai-tax-residence-foreign-income',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = { title:string; metaTitle:string; description:string; eyebrow:string; hero:string; cta:string; asideTitle:string; finalTitle:string; finalText:string; faqTitle:string; checklist:string[]; sections:Array<[string,string]>; faq:Array<[string,string]> };

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Turquie vs Dubaï : fiscalité, résidence, revenus étrangers et installation',
    metaTitle: 'Turquie vs Dubaï : fiscalité, résidence et revenus étrangers',
    description: 'Turquie vs Dubaï : comparaison pour entrepreneurs, investisseurs et familles patrimoniales. Fiscalité, revenus étrangers, résidence, société, banque, immobilier, santé, école et installation.',
    eyebrow: 'Comparaison fiscale · Turquie vs Dubaï',
    hero: 'Dubaï est devenu une référence mondiale pour les entrepreneurs et familles patrimoniales. La Turquie entre maintenant dans la comparaison avec un positionnement différent : proximité avec l’Europe, vie familiale, immobilier varié, médecine privée et projet d’exonération de long terme sur certains revenus étrangers.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant de comparer Turquie et Dubaï',
    finalTitle: 'Le meilleur choix dépend de votre dossier réel, pas d’un slogan fiscal',
    finalText: 'Avant de choisir une destination, Bosphoras peut organiser une analyse privée de votre situation : fiscalité, société, banque, immobilier, assurance santé, famille, succession et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Votre résidence fiscale actuelle', 'Vos revenus étrangers', 'Vos sociétés et dividendes', 'Vos plus-values et actifs', 'La banque et l’origine des fonds', 'Votre famille et vos enfants', 'Votre immobilier', 'Votre assurance santé et qualité de vie'],
    sections: [
      ['Dubaï : une référence mondiale, mais pas toujours adaptée à tous les profils', 'Dubaï attire grâce à son cadre international, son image business, ses zones franches, sa sécurité, son aéroport mondial, l’usage de l’anglais et son absence d’impôt personnel classique sur le revenu. Mais il faut aussi regarder le coût de la vie, les loyers premium, les écoles internationales, l’assurance santé privée, la chaleur, la substance économique réelle, les coûts de création et de maintien de structure et la sélection bancaire. Dubaï peut être excellent, mais pas toujours idéal pour une famille, un retraité ou un entrepreneur cherchant une base méditerranéenne plus quotidienne.'],
      ['Turquie : une alternative entre Europe, Moyen-Orient et Asie centrale', 'La Turquie offre une autre logique : proximité avec l’Europe, forte connectivité aérienne, coût de vie souvent plus flexible, villes dynamiques comme Istanbul, zones balnéaires comme Bodrum, Antalya, Izmir ou Alanya, immobilier plus accessible selon les quartiers, médecine privée développée, culture familiale forte et accès au Moyen-Orient, au Caucase et à l’Asie centrale. Si le nouveau régime fiscal est confirmé, elle peut devenir plus compétitive pour les personnes avec revenus étrangers importants.'],
      ['Fiscalité : comparer le cadre réel, pas seulement le slogan', 'Dubaï est souvent résumé par l’absence d’impôt personnel classique sur le revenu. La Turquie pourrait être résumée par une exonération potentielle de long terme sur certains revenus étrangers. Dans les deux cas, il faut éviter les slogans. Pour Dubaï, il faut vérifier si vous êtes simple résident ou entrepreneur actif, si vous avez une société aux Émirats, si votre activité a une substance réelle, si les banques comprennent votre structure et si votre ancien pays peut encore vous considérer résident fiscal. Pour la Turquie, il faut vérifier le texte final, votre historique fiscal, votre résidence réelle, la nature de vos revenus étrangers et vos revenus turcs éventuels.'],
      ['Pour un entrepreneur ou dirigeant', 'Dubaï peut être très attractif pour créer une société, facturer à l’international, recruter, ouvrir un bureau ou accéder au marché du Golfe. La Turquie peut être intéressante si votre activité est liée à l’Europe, la Turquie, le Caucase, le Kazakhstan, l’Asie centrale, le Moyen-Orient, l’import-export, l’industrie, les services B2B, la construction, l’immobilier, le tourisme, la santé ou la logistique. La vraie question est de savoir où votre entreprise peut fonctionner réellement avec banque, équipe, clients, contrats et résidence cohérente.'],
      ['Pour une famille patrimoniale', 'Dubaï peut être très fort pour la sécurité, les écoles internationales, le luxe, les banques privées, le réseau international et l’immobilier premium. La Turquie peut être forte pour la vie familiale, la médecine privée, la proximité avec l’Europe, l’immobilier varié, les villes historiques, les stations balnéaires, un coût de vie plus flexible et l’accès à plusieurs cultures. Une famille doit comparer école, assurance santé, langue, quartier, coût du logement, qualité de vie, mobilité, succession, banque et statut du conjoint.'],
      ['Banque et origine des fonds', 'Que vous choisissiez Dubaï ou la Turquie, la banque sera centrale. Vous devrez expliquer l’origine des fonds, les revenus étrangers, les dividendes, les plus-values, la vente de société, les sociétés étrangères, les comptes existants, les documents fiscaux, les contrats, les déclarations et la preuve de résidence. Un dossier bancaire mal préparé peut bloquer un projet même si le pays est fiscalement attractif.'],
      ['Immobilier : Dubaï ou Turquie ?', 'À Dubaï, le marché immobilier est très international, visible et structuré autour de promoteurs, de programmes neufs, de plans de paiement et de zones premium. En Turquie, Istanbul peut convenir à une vie business et familiale, Bodrum au luxe et à la mer Égée, Antalya à la retraite et à la vie balnéaire, Izmir à un cadre méditerranéen, Alanya à un coût plus accessible et Fethiye à une vie plus calme. Le choix dépend de l’objectif : résidence principale, résidence secondaire, investissement, revente, famille, retraite ou patrimoine.'],
      ['Santé, assurance et vie quotidienne', 'Dubaï offre une médecine privée très moderne, mais souvent coûteuse et dépendante de l’assurance. La Turquie dispose aussi d’un secteur médical privé développé, avec hôpitaux et cliniques réputés dans les grandes villes. Pour une famille ou un retraité, il faut comparer assurance santé, hôpitaux, spécialistes, médicaments, urgences, coût des soins, accès aux médecins et couverture du conjoint ou des enfants.'],
      ['Pays d’origine : attention à la sortie fiscale', 'Que vous partiez à Dubaï ou en Turquie, votre pays d’origine peut continuer à vous considérer résident fiscal si votre famille, votre foyer, votre entreprise, vos revenus, votre temps de présence ou vos principaux actifs restent liés à ce pays. Une installation internationale doit être cohérente dans les deux sens : sortie claire du pays d’origine et installation réelle dans le nouveau pays.'],
      ['Les erreurs à éviter', 'La première erreur est de choisir Dubaï ou la Turquie uniquement pour une phrase fiscale. La deuxième est de ne pas préparer la sortie fiscale du pays d’origine. La troisième est de créer une société sans substance réelle. La quatrième est de transférer des fonds sans justificatifs. La cinquième est de sous-estimer le coût de la vie, de l’école, de la santé et du logement. La sixième est de négliger la famille, la succession et l’assurance.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste, un expert-comptable ou un conseiller patrimonial. Notre rôle est de vous aider à comparer sérieusement la Turquie avec d’autres destinations comme Dubaï, puis à organiser la partie Turquie si cette option est cohérente : profil, revenus étrangers, sociétés, fiscalistes, banque, assurance santé, immobilier, installation familiale, succession et partenaires locaux.'],
    ],
    faq: [['Dubaï est-il fiscalement plus avantageux que la Turquie ?', 'Dubaï reste très attractif fiscalement, mais la Turquie pourrait devenir compétitive si le régime annoncé sur certains revenus étrangers est confirmé. Le choix dépend de votre profil réel.'], ['La Turquie peut-elle devenir une alternative à Dubaï ?', 'Oui, pour certains profils : familles, entrepreneurs liés à l’Europe ou à l’Asie centrale, retraités, investisseurs immobiliers ou clients cherchant une base plus proche de l’Europe.'], ['Dubaï est-il toujours meilleur pour créer une société ?', 'Pas forcément. Il faut analyser la substance, la banque, les coûts, l’activité réelle, les clients et les obligations du pays d’origine.'], ['La Turquie taxe-t-elle les revenus étrangers ?', 'Les résidents turcs sont en principe concernés par leurs revenus mondiaux. Le projet annoncé pourrait créer une exonération de long terme sur certains revenus étrangers pour nouveaux résidents qualifiés, sous réserve du texte final.'], ['Faut-il choisir uniquement sur la fiscalité ?', 'Non. Il faut comparer banque, santé, école, logement, famille, succession, coût de vie, mobilité, société, origine des fonds et qualité de vie.'], ['Bosphoras peut-il comparer Turquie et Dubaï ?', 'Oui. Bosphoras peut coordonner une analyse privée pour comprendre si la Turquie est cohérente par rapport à Dubaï et aux autres alternatives.']],
  },
  en: {
    title: 'Turkey vs Dubai: tax residence, foreign income, companies and relocation',
    metaTitle: 'Turkey vs Dubai: Tax Residence and Foreign Income',
    description: 'Turkey vs Dubai for UK, US and international expats: tax residence, foreign income, UAE business setup, Turkey foreign income project, banking, property, family and relocation.',
    eyebrow: 'Turkey vs Dubai · Tax residence comparison',
    hero: 'Dubai is a global reference for entrepreneurs and international families. Turkey is now entering the comparison with a different value proposition: proximity to Europe, family life, varied property markets, private healthcare and a potential long-term foreign-income regime for qualifying new residents.',
    cta: 'Request a private assessment',
    asideTitle: 'Before comparing Turkey and Dubai',
    finalTitle: 'The best base is the one that matches your real tax, banking and family situation',
    finalText: 'Before choosing a destination, Bosphoras can organize a private review of your situation: tax residence, companies, banking, property, healthcare, family, estate planning and relocation to Turkey.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Current tax residence', 'Foreign income streams', 'Companies and dividends', 'Capital gains and assets', 'Banking and source of funds', 'Family and children', 'Property strategy', 'Healthcare and lifestyle'],
    sections: [
      ['Dubai: a global benchmark, but not for every profile', 'Dubai attracts entrepreneurs, investors and families through its international business environment, free zones, safety, global airport, English-speaking ecosystem and absence of a classic personal income tax. But it also requires looking at high living costs, premium rents, international school fees, private health insurance, heat, real economic substance, company maintenance costs and selective banking. Dubai can be excellent, but it may not be the best fit for every family, retiree or entrepreneur.'],
      ['Turkey: an alternative between Europe, the Middle East and Central Asia', 'Turkey offers a different base: proximity to Europe, strong air connectivity, a more flexible cost of living, Istanbul as a major city, coastal locations such as Bodrum, Antalya, Izmir and Alanya, varied property prices, developed private healthcare and access to the Middle East, Caucasus and Central Asia. If the announced foreign-income regime is confirmed, Turkey could become more competitive for certain international profiles.'],
      ['Tax comparison: avoid slogans', 'Dubai is often summarized as no personal income tax. Turkey may be summarized by a potential long-term exemption on certain foreign income. In both cases, slogans are not enough. For Dubai, you should review whether you are a passive resident or active entrepreneur, whether you have a UAE company, economic substance, bank acceptance and continuing tax residence risks in the former country. For Turkey, you should review final legislation, Turkish tax history, real residence, foreign income types, companies and Turkish-source income.'],
      ['Entrepreneurs and business owners', 'Dubai can be attractive for company setup, international invoicing, hiring, office presence and access to the Gulf market. Turkey may be attractive if your activity relates to Europe, Turkey, the Caucasus, Kazakhstan, Central Asia, the Middle East, import-export, industry, B2B services, construction, real estate, tourism, healthcare or logistics. The real question is where your business can function with banking, team, clients, contracts and coherent residence.'],
      ['International families', 'Dubai is strong for safety, international schools, luxury, private banking, global networks and premium property. Turkey can be strong for family life, private healthcare, proximity to Europe, varied real estate, historic cities, coastal lifestyle, flexible cost base and access to multiple cultures. Families should compare schools, health insurance, language, neighborhood, housing cost, lifestyle, mobility, estate planning, banking and spouse status.'],
      ['Banking and source of funds', 'Whether you choose Dubai or Turkey, banking is central. You may need to explain source of funds, foreign income, dividends, capital gains, company sale, foreign companies, existing accounts, tax documents, contracts, filings and proof of residence. Banks want to understand how the money was earned, where it was declared, why it is moving and what your real activity is.'],
      ['Property: Dubai or Turkey?', 'Dubai real estate is highly international, visible and structured around developers, new projects, payment plans and premium districts. Turkey offers a different landscape: Istanbul for business and family life, Bodrum for luxury and the Aegean coast, Antalya for retirement and seaside living, Izmir for a Mediterranean lifestyle, Alanya for lower-cost living and Fethiye for a calmer environment. The right choice depends on whether you seek residence, investment, resale, family life, retirement or wealth planning.'],
      ['Healthcare, insurance and daily life', 'Dubai offers modern private healthcare, often with high costs and strong dependence on private insurance. Turkey also has a developed private medical sector, especially in major cities. For families and retirees, compare health insurance, hospitals, specialists, medication, emergencies, cost of care, access to doctors and coverage for spouse and children.'],
      ['Former country: exit tax and residence risks', 'Moving to Dubai or Turkey does not automatically end your former country’s tax interest. If family, home, company management, main income, time spent or major assets remain there, the former country may still consider you tax resident or impose reporting obligations. Exit planning and real relocation must be coordinated.'],
      ['Mistakes to avoid', 'Do not choose Dubai or Turkey based only on a tax phrase. Do not ignore exit planning from the former country. Do not create a company without substance. Do not move funds without evidence. Do not underestimate cost of living, schools, healthcare and housing. Do not ignore family, estate planning and insurance.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers, accountants or wealth advisors. Its role is to help compare Turkey with destinations such as Dubai and organize the Turkey side if suitable: profile review, foreign income mapping, company analysis, coordination with advisors, banking, healthcare, property, family relocation, estate planning and local partners.'],
    ],
    faq: [['Is Dubai more tax-efficient than Turkey?', 'Dubai remains very attractive for many profiles, but Turkey could become competitive if the announced foreign-income regime is confirmed. The right answer depends on your real profile.'], ['Can Turkey be an alternative to Dubai?', 'Yes, for some families, entrepreneurs linked to Europe or Central Asia, retirees, property investors or clients wanting a base closer to Europe.'], ['Is Dubai always better for company setup?', 'Not always. Substance, banking, costs, actual activity, clients and obligations in the former country must be reviewed.'], ['Does Turkey tax foreign income?', 'Turkish residents are generally concerned by worldwide income, but the announced project may create a long-term exemption for certain foreign income of qualifying new residents, subject to final rules.'], ['Should the choice be made only on tax?', 'No. Banking, healthcare, schools, housing, family, estate planning, cost of living, mobility, companies, source of funds and lifestyle all matter.'], ['Can Bosphoras compare Turkey and Dubai?', 'Yes. Bosphoras can coordinate a private review to assess whether Turkey is coherent compared with Dubai and other alternatives.']],
  },
  ru: {
    title: 'Турция vs Дубай: налоги, иностранные доходы, банки и переезд',
    metaTitle: 'Турция vs Дубай: налоги и иностранные доходы',
    description: 'Турция vs Дубай для русскоязычных инвесторов из России, Казахстана и СНГ: резиденция, иностранные доходы, компании, банки, недвижимость, семья и переезд.',
    eyebrow: 'Турция vs Дубай · Налоги и резиденция',
    hero: 'Дубай стал одной из главных баз для международного бизнеса и капитала. Турция входит в сравнение иначе: ближе к Европе, Кавказу и Центральной Азии, с сильной семейной жизнью, разной недвижимостью, медициной и потенциальным новым режимом для иностранных доходов.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед сравнением Турции и Дубая',
    finalTitle: 'Выбор должен соответствовать не только налогам, но и банкам, семье и реальной жизни',
    finalText: 'До выбора страны Bosphoras может организовать частный анализ вашей ситуации: налоги, компании, банки, недвижимость, медицина, семья, наследство и переезд в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Текущая налоговая резиденция', 'Иностранные доходы', 'Компании и дивиденды', 'Прирост капитала и активы', 'Банки и происхождение средств', 'Семья и дети', 'Недвижимость', 'Медицина и lifestyle'],
    sections: [
      ['Дубай: глобальная база, но не для всех', 'Дубай привлекает предпринимателей и инвесторов бизнес-средой, free zones, безопасностью, международным аэропортом, английским языком, private banking и отсутствием классического личного подоходного налога. Но нужно учитывать высокую стоимость жизни, аренду, школы, частную страховку, жаркий климат, substance компании, стоимость поддержки структуры и выборочность банков. Дубай подходит многим, но не всегда идеален для семьи, пенсионера или предпринимателя, которому нужна более живая база ближе к Европе и СНГ.'],
      ['Турция: альтернатива между Европой, Ближним Востоком и Центральной Азией', 'Турция предлагает другую логику: близость к Европе, сильное авиасообщение, более гибкую стоимость жизни, Стамбул, Бодрум, Анталью, Измир, Аланью, развитую частную медицину, семейную культуру и связь с Кавказом, Казахстаном, Узбекистаном, Кыргызстаном и Центральной Азией. Если новый режим по иностранным доходам будет подтвержден, Турция может стать более конкурентной для части клиентов.'],
      ['Налоги: сравнивать нужно реальность, а не лозунги', 'Дубай часто описывают как отсутствие личного налога. Турцию могут описывать как потенциальное освобождение некоторых иностранных доходов. Но нужны детали. Для Дубая важно понять: вы просто резидент или активный предприниматель, есть ли компания в ОАЭ, substance, банк, бывшая страна резиденции. Для Турции важно проверить финальный закон, налоговую историю, реальную резиденцию, типы иностранных доходов, компании и доходы из турецкого источника.'],
      ['Предприниматели и владельцы бизнеса', 'Дубай может быть силен для международного invoicing, офиса, найма и рынка Персидского залива. Турция может быть интересна, если бизнес связан с Европой, Турцией, Кавказом, Казахстаном, Центральной Азией, Ближним Востоком, импорт-экспортом, промышленностью, B2B, строительством, недвижимостью, туризмом, медициной или логистикой. Важно понять, где бизнес реально работает с банком, командой, клиентами и договорами.'],
      ['Семьи и private clients', 'Дубай силен безопасностью, школами, luxury, банками, международной сетью и premium-недвижимостью. Турция может быть сильна семейной жизнью, медициной, близостью к Европе, разнообразной недвижимостью, морскими городами, более гибкой стоимостью и культурной близостью. Семье нужно сравнивать школу, страховку, язык, район, жилье, качество жизни, перелеты, наследство, банк и статус супруга.'],
      ['Банки и происхождение средств', 'В Дубае и Турции банк будет центральным элементом. Нужно объяснить происхождение средств, иностранные доходы, дивиденды, gains, продажу компании, иностранные структуры, существующие счета, налоговые документы, договоры, декларации и доказательство резиденции. Банк хочет понимать, откуда деньги, где они декларировались и почему они поступают в страну.'],
      ['Недвижимость: Дубай или Турция', 'В Дубае рынок недвижимости международный, видимый и активный, с developer-проектами и платежными планами. В Турции выбор другой: Стамбул для бизнеса и семьи, Бодрум для luxury и Эгейского моря, Анталья для пенсии и моря, Измир для средиземноморского стиля, Аланья для более доступной жизни, Фетхие для спокойствия. Выбор зависит от цели: жизнь, инвестиция, аренда, перепродажа, семья, пенсия или капитал.'],
      ['Медицина, страховка и повседневная жизнь', 'Дубай предлагает современную частную медицину, но часто с высокой стоимостью и зависимостью от страховки. В Турции также развит частный медицинский сектор. Для семьи или пенсионера нужно сравнить страховку, больницы, специалистов, лекарства, emergency care, стоимость лечения, доступ к врачам и покрытие супруга и детей.'],
      ['Страна происхождения: не забывать выход', 'Переезд в Дубай или Турцию не означает автоматический выход из налоговой системы прежней страны. Если семья, дом, управление бизнесом, доходы, время пребывания или активы остаются там, прежняя страна может продолжать рассматривать вас как резидента или требовать отчетность.'],
      ['Ошибки, которых нужно избегать', 'Не выбирайте Дубай или Турцию только по налоговой фразе. Не игнорируйте выход из прежней страны. Не создавайте компанию без substance. Не переводите средства без документов. Не недооценивайте стоимость жизни, школ, медицины и жилья. Не забывайте семью, наследство и страховку.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов, бухгалтеров или wealth advisors. Его роль — помочь сравнить Турцию с Дубаем и другими вариантами, а затем организовать турецкую часть, если она подходит: профиль, доходы, компании, консультанты, банк, медицина, недвижимость, семья, наследство и местные партнеры.'],
    ],
    faq: [['Дубай выгоднее Турции по налогам?', 'Дубай остается очень привлекательным для многих профилей, но Турция может стать конкурентной, если новый режим иностранных доходов будет подтвержден. Нужно смотреть ваш реальный профиль.'], ['Может ли Турция быть альтернативой Дубаю?', 'Да, для некоторых семей, предпринимателей, связанных с Европой или Центральной Азией, пенсионеров, инвесторов в недвижимость и клиентов, которым нужна база ближе к Европе.'], ['Дубай всегда лучше для компании?', 'Не всегда. Нужно анализировать substance, банк, стоимость, реальную деятельность, клиентов и обязательства в прежней стране.'], ['Турция облагает иностранные доходы?', 'Резиденты Турции обычно рассматриваются по мировым доходам, но объявленный проект может создать долгосрочное освобождение некоторых иностранных доходов для квалифицированных новых резидентов.'], ['Выбирать нужно только по налогам?', 'Нет. Банки, медицина, школы, жилье, семья, наследство, стоимость жизни, перелеты, компании и источник средств также важны.'], ['Bosphoras может сравнить Турцию и Дубай?', 'Да. Bosphoras может координировать частный анализ, чтобы понять, подходит ли Турция по сравнению с Дубаем и другими альтернативами.']],
  },
  ar: {
    title: 'تركيا vs دبي: الضرائب، الإقامة، الدخل الأجنبي ونقل الثروة',
    metaTitle: 'تركيا vs دبي: الضرائب والإقامة والدخل الأجنبي',
    description: 'تركيا vs دبي للمستثمرين العرب والخليج: الضرائب، الإقامة، الدخل الأجنبي، الشركات، البنوك، العقار، الصحة، العائلة ونقل الثروة.',
    eyebrow: 'تركيا vs دبي · الضرائب والإقامة',
    hero: 'دبي أصبحت مرجعاً عالمياً للأعمال ورأس المال والعائلات الدولية. لكن تركيا تدخل المقارنة بطريقة مختلفة: قرب من أوروبا، حياة عائلية، عقارات متنوعة، طب خاص، ومدن ساحلية، مع مشروع قد يجعلها أكثر جاذبية لبعض أصحاب الدخل الأجنبي.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل مقارنة تركيا ودبي',
    finalTitle: 'الاختيار الصحيح هو الذي يناسب العائلة والبنوك والحياة الفعلية',
    finalText: 'قبل اختيار الوجهة، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك: الضرائب، الشركات، البنوك، العقار، التأمين الصحي، العائلة، الميراث والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['إقامتك الضريبية الحالية', 'الدخل الأجنبي', 'الشركات والأرباح', 'المكاسب والأصول', 'البنوك ومصدر الأموال', 'العائلة والأطفال', 'العقار', 'الصحة ونمط الحياة'],
    sections: [
      ['دبي: مرجع عالمي لكن ليست مناسبة للجميع', 'دبي تجذب المستثمرين ورواد الأعمال ببيئة الأعمال، المناطق الحرة، الأمن، المطار العالمي، اللغة الإنجليزية، البنوك الخاصة وغياب ضريبة دخل شخصية تقليدية. لكن يجب أيضاً حساب تكلفة الحياة العالية، الإيجارات، المدارس الدولية، التأمين الصحي، الحرارة، substance للشركة، تكاليف التأسيس والصيانة، وانتقائية البنوك. دبي ممتازة لبعض الملفات، لكنها ليست دائماً الأنسب لكل عائلة أو متقاعد أو رائد أعمال.'],
      ['تركيا: بديل بين أوروبا والشرق الأوسط وآسيا الوسطى', 'تركيا تقدم قاعدة مختلفة: قرب من أوروبا، رحلات جوية كثيرة، تكلفة معيشة أكثر مرونة، إسطنبول، بودروم، أنطاليا، إزمير، ألانيا، عقارات متنوعة، طب خاص متطور، ثقافة عائلية، واتصال بالشرق الأوسط والقوقاز وآسيا الوسطى. إذا تم تأكيد النظام الجديد للدخل الأجنبي، قد تصبح تركيا أكثر تنافسية لبعض المستثمرين.'],
      ['الضرائب: لا تقارن الشعارات فقط', 'دبي تختصر غالباً بعبارة لا توجد ضريبة دخل شخصية. تركيا قد تختصر بإعفاء محتمل لبعض الدخل الأجنبي. لكن التفاصيل مهمة. في دبي يجب فهم هل أنت مقيم فقط أم رائد أعمال نشط، هل لديك شركة إماراتية، هل توجد substance، هل البنك يقبل الهيكل، وهل بلدك السابق لا يزال يعتبرك مقيماً. في تركيا يجب مراجعة النص النهائي، التاريخ الضريبي، الإقامة الحقيقية، نوع الدخل الأجنبي والشركات والدخل من مصدر تركي.'],
      ['رواد الأعمال وأصحاب الشركات', 'دبي قوية لتأسيس الشركات، الفوترة الدولية، التوظيف، المكاتب والوصول إلى سوق الخليج. تركيا قد تكون مناسبة إذا كان النشاط مرتبطاً بأوروبا، تركيا، القوقاز، آسيا الوسطى، الشرق الأوسط، الاستيراد والتصدير، الصناعة، B2B، البناء، العقار، السياحة، الصحة أو اللوجستيك. السؤال هو أين يمكن أن يعمل النشاط فعلياً مع بنك وفريق وعملاء وعقود وإقامة منسجمة.'],
      ['العائلات والثروة الخاصة', 'دبي قوية في الأمن، المدارس الدولية، الرفاهية، البنوك الخاصة، الشبكات الدولية والعقار premium. تركيا قد تكون قوية في الحياة العائلية، الطب الخاص، القرب من أوروبا، العقار المتنوع، المدن التاريخية، السواحل، تكلفة أكثر مرونة والقرب الثقافي. يجب مقارنة المدرسة، التأمين، اللغة، المنطقة، السكن، نمط الحياة، السفر، الميراث، البنك ووضع الزوج أو الزوجة.'],
      ['البنوك ومصدر الأموال', 'سواء اخترت دبي أو تركيا، البنك سيكون محورياً. يجب شرح مصدر الأموال، الدخل الأجنبي، الأرباح، المكاسب، بيع شركة، الشركات الأجنبية، الحسابات، المستندات الضريبية، العقود، التصريحات وإثبات الإقامة. البنك يريد فهم من أين جاء المال، كيف تم كسبه، أين صرح به ولماذا يدخل البلد.'],
      ['العقار: دبي أم تركيا', 'سوق دبي العقاري عالمي ومرئي ومنظم حول مطورين ومشاريع جديدة وخطط دفع ومناطق premium. في تركيا، إسطنبول للحياة العائلية والأعمال، بودروم للفخامة والبحر، أنطاليا للتقاعد والساحل، إزمير لنمط متوسطي، ألانيا لتكلفة أكثر مرونة، وفتحية للهدوء. الاختيار يعتمد على الهدف: سكن رئيسي، استثمار، إعادة بيع، عائلة، تقاعد أو ثروة.'],
      ['الصحة والتأمين والحياة اليومية', 'دبي تقدم طباً خاصاً حديثاً لكن بتكاليف مرتفعة غالباً واعتماد كبير على التأمين. تركيا لديها أيضاً قطاع طبي خاص متطور في المدن الكبرى. للعائلة أو المتقاعد يجب مقارنة التأمين الصحي، المستشفيات، الأطباء، الأدوية، الطوارئ، تكلفة العلاج، تغطية الزوج أو الزوجة والأطفال.'],
      ['بلدك الأصلي: الخروج الضريبي مهم', 'الانتقال إلى دبي أو تركيا لا يعني تلقائياً الخروج من النظام الضريبي في بلدك السابق. إذا بقيت العائلة أو المنزل أو إدارة الشركة أو الدخل الرئيسي أو الأصول أو جزء كبير من وقتك هناك، فقد يستمر بلدك السابق في اعتبارك مقيماً أو يطلب التزامات تصريحية.'],
      ['أخطاء يجب تجنبها', 'لا تختر دبي أو تركيا بسبب جملة ضريبية فقط. لا تهمل الخروج من بلدك السابق. لا تنشئ شركة دون substance. لا تحول أموالاً دون مستندات. لا تقلل من تكلفة الحياة والمدارس والصحة والسكن. لا تنس العائلة والميراث والتأمين.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامي الضريبي أو المحاسب أو مستشار الثروة. دوره هو مساعدتك في مقارنة تركيا مع دبي ووجهات أخرى، ثم تنظيم الجزء التركي إذا كان مناسباً: تحليل الملف، الدخل، الشركات، المستشارون، البنوك، التأمين الصحي، العقار، العائلة، الميراث والشركاء المحليون.'],
    ],
    faq: [['هل دبي أفضل ضريبياً من تركيا؟', 'دبي تبقى جذابة جداً لكثير من الملفات، لكن تركيا قد تصبح منافسة إذا تم تأكيد نظام الدخل الأجنبي. الإجابة تعتمد على وضعك الحقيقي.'], ['هل يمكن أن تكون تركيا بديلاً لدبي؟', 'نعم لبعض العائلات ورواد الأعمال المرتبطين بأوروبا أو آسيا الوسطى والمتقاعدين والمستثمرين العقاريين ومن يريد قاعدة أقرب إلى أوروبا.'], ['هل دبي دائماً أفضل لتأسيس شركة؟', 'ليس دائماً. يجب تحليل substance، البنك، التكاليف، النشاط الحقيقي، العملاء والتزامات بلدك السابق.'], ['هل تفرض تركيا ضريبة على الدخل الأجنبي؟', 'المقيمون في تركيا قد يكونون معنيين بالدخل العالمي، لكن المشروع المعلن قد يمنح إعفاءً طويل الأجل لبعض الدخل الأجنبي للمقيمين الجدد المؤهلين وفق القواعد النهائية.'], ['هل يجب الاختيار بسبب الضرائب فقط؟', 'لا. البنوك، الصحة، المدارس، السكن، العائلة، الميراث، تكلفة الحياة، السفر، الشركة ومصدر الأموال كلها مهمة.'], ['هل يمكن لـ Bosphoras مقارنة تركيا ودبي؟', 'نعم. يمكن لـ Bosphoras تنسيق مراجعة خاصة لفهم ما إذا كانت تركيا مناسبة مقارنة بدبي والبدائل الأخرى.']],
  },
};

export function getTurkeyVsDubaiTaxMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function TurkeyVsDubaiTaxClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
