import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/turquie-vs-portugal-fiscalite-revenus-etrangers',
  en: '/en/turkey-vs-portugal-tax-residence-foreign-income',
  ru: '/ru/turtsiya-vs-portugaliya-nalogi-inostrannye-dohody',
  ar: '/ar/turkey-vs-portugal-tax-residence-foreign-income',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = { title:string; metaTitle:string; description:string; eyebrow:string; hero:string; cta:string; asideTitle:string; finalTitle:string; finalText:string; faqTitle:string; checklist:string[]; sections:Array<[string,string]>; faq:Array<[string,string]> };

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Turquie vs Portugal : fiscalité, résidence, revenus étrangers et installation',
    metaTitle: 'Turquie vs Portugal : fiscalité, résidence et revenus étrangers',
    description: 'Turquie vs Portugal : comparaison pour entrepreneurs, retraités, investisseurs et familles patrimoniales. Fiscalité, revenus étrangers, résidence, banque, immobilier, santé, famille et installation.',
    eyebrow: 'Comparaison fiscale · Turquie vs Portugal',
    hero: 'Pendant plusieurs années, le Portugal a été une destination de référence grâce à son ancien régime NHR. Aujourd’hui, le cadre est plus ciblé, tandis que la Turquie entre dans la comparaison avec un positionnement différent : proximité avec l’Europe, coût de vie flexible, immobilier varié, médecine privée, vie familiale et projet d’exonération de long terme sur certains revenus étrangers.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant de comparer Turquie et Portugal',
    finalTitle: 'Le bon choix dépend de votre fiscalité, mais aussi de votre vie réelle',
    finalText: 'Avant de choisir une destination, Bosphoras peut organiser une analyse privée de votre situation : fiscalité, banque, immobilier, assurance santé, famille, succession et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Votre résidence fiscale actuelle', 'Vos revenus étrangers', 'Pension, dividendes et plus-values', 'Vos sociétés et comptes bancaires', 'Votre assurance santé', 'Votre immobilier', 'Votre famille et vos héritiers', 'Votre pays d’origine et sa sortie fiscale'],
    sections: [
      ['Portugal : un pays attractif, mais un régime fiscal plus ciblé', 'Le Portugal reste une destination forte pour ceux qui veulent vivre dans l’Union européenne, l’espace Schengen et la zone euro. Il attire par sa qualité de vie, sa sécurité, son climat, Lisbonne, Porto, l’Algarve, sa communauté internationale et son système bancaire européen. Mais l’ancien régime NHR n’est plus disponible dans sa forme historique pour les nouveaux arrivants. Le nouveau cadre est davantage orienté vers certains profils qualifiés, l’innovation, la recherche, les startups ou des activités éligibles. Cela change la comparaison pour les retraités, rentiers, entrepreneurs et familles patrimoniales.'],
      ['Turquie : une alternative plus flexible pour certains profils', 'La Turquie n’a pas le même positionnement que le Portugal. Elle peut attirer des personnes qui recherchent la proximité avec l’Europe, un coût de vie plus flexible, un immobilier plus varié selon les villes, Istanbul comme centre business, Bodrum pour le luxe et la mer Égée, Antalya pour la retraite, Izmir pour un style méditerranéen, une médecine privée développée et une connexion avec le Moyen-Orient, le Caucase et l’Asie centrale. Si le régime turc annoncé est confirmé, elle peut devenir une option sérieuse pour certains profils qui ne rentrent pas dans le nouveau cadre portugais.'],
      ['Pour un retraité', 'Le Portugal a longtemps attiré les retraités européens. Aujourd’hui, un retraité doit vérifier pension étrangère, pension publique ou privée, retraite complémentaire, assurance santé, coût du logement, fiscalité de la pension, convention fiscale applicable, immobilier conservé dans le pays d’origine et succession. La Turquie peut intéresser certains retraités recherchant un coût de vie plus souple, la médecine privée, Antalya, Alanya, Bodrum ou Izmir, une vie familiale plus chaleureuse et une proximité avec l’Europe.'],
      ['Pour un entrepreneur ou consultant', 'Le Portugal peut rester intéressant pour des profils qualifiés entrant dans les activités éligibles du nouveau régime : recherche, innovation, enseignement supérieur, startups ou secteurs spécifiques. Mais un entrepreneur qui ne rentre pas dans ce cadre doit comparer plus largement. La Turquie peut être pertinente pour des activités liées à l’Europe, la Turquie, le Moyen-Orient, le Kazakhstan, l’Asie centrale, le Caucase, l’import-export, les services B2B, l’immobilier, le tourisme, la santé, l’industrie ou la logistique.'],
      ['Pour une famille patrimoniale', 'Une famille patrimoniale ne compare pas seulement les impôts. Elle compare écoles, hôpitaux, assurance santé, logement, banque, sécurité, langue, mobilité internationale, succession, coût de vie, qualité de vie, statut du conjoint et accès aux enfants ou petits-enfants. Le Portugal rassure par son cadre européen. La Turquie peut séduire par sa flexibilité, sa connectivité, sa diversité de villes, son immobilier, sa médecine privée et sa proximité avec plusieurs régions stratégiques.'],
      ['Banque et origine des fonds', 'Portugal ou Turquie : la banque reste centrale. Vous devrez pouvoir expliquer origine des fonds, revenus étrangers, dividendes, plus-values, vente de société, pension, comptes bancaires existants, déclarations fiscales, contrats, sociétés étrangères et résidence fiscale. Un pays peut être fiscalement attractif, mais si le dossier bancaire est mal préparé, l’installation peut devenir compliquée.'],
      ['Immobilier : Portugal ou Turquie ?', 'Au Portugal, les zones recherchées sont souvent Lisbonne, Porto, Algarve, Cascais, Estoril, Comporta ou Madère. En Turquie, les zones pertinentes peuvent être Istanbul, Bodrum, Antalya, Izmir, Alanya, Fethiye ou Mersin. Le choix dépend de votre objectif : résidence principale, retraite, résidence secondaire, investissement locatif, patrimoine familial, revente, vie avec enfants ou accès aux soins.'],
      ['Santé et assurance', 'Le Portugal offre un cadre européen rassurant, mais certains services privés peuvent être coûteux et l’accès aux soins dépend de votre statut, de votre couverture et de votre assurance. La Turquie dispose d’un secteur médical privé très développé dans les grandes villes. Il faut comparer assurance santé internationale, hôpitaux privés, spécialistes, médicaments, urgences, coût des soins, couverture du conjoint et suivi médical dans le pays d’origine.'],
      ['Pays d’origine : ne pas oublier la sortie fiscale', 'Que vous choisissiez le Portugal ou la Turquie, votre pays d’origine peut continuer à vous considérer résident fiscal si votre vie réelle reste principalement là-bas : foyer disponible, famille, société dirigée depuis ce pays, revenus principaux, actifs principaux ou temps de présence important. La sortie fiscale du pays d’origine doit être coordonnée avec l’installation réelle dans le nouveau pays.'],
      ['Les erreurs à éviter', 'La première erreur est de penser que l’ancien Portugal NHR existe encore pour tous les nouveaux arrivants. La deuxième est de choisir la Turquie uniquement parce qu’un régime fiscal est annoncé. La troisième est de comparer seulement les taux d’impôt sans regarder banque, famille, santé et immobilier. La quatrième est de négliger le pays d’origine. La cinquième est de transférer des fonds sans justificatifs. La sixième est d’acheter avant d’avoir testé la ville, le quartier, les hôpitaux et le coût de vie.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste, un expert-comptable ou un conseiller patrimonial. Notre rôle est de vous aider à comparer sérieusement la Turquie avec des destinations comme le Portugal, puis à organiser la partie Turquie si cette option est cohérente : analyse du profil, revenus étrangers, résidence fiscale, fiscalistes, banque, assurance santé, immobilier, installation familiale, succession et partenaires locaux.'],
    ],
    faq: [['Le Portugal NHR existe-t-il encore ?', 'L’ancien régime NHR a été remplacé pour les nouveaux arrivants par un régime plus ciblé, souvent appelé IFICI ou NHR 2.0, orienté vers certaines activités qualifiées, innovation, recherche, startups ou secteurs éligibles.'], ['La Turquie peut-elle devenir une alternative au Portugal ?', 'Oui, pour certains profils : entrepreneurs, retraités, familles patrimoniales, investisseurs ou personnes qui ne rentrent pas dans les critères du nouveau régime portugais.'], ['Le Portugal est-il plus sûr fiscalement que la Turquie ?', 'Le Portugal dispose d’un cadre européen plus établi. La Turquie doit encore confirmer les détails définitifs de son régime annoncé. Le bon choix dépend de votre profil réel.'], ['Faut-il choisir uniquement selon la fiscalité ?', 'Non. Il faut comparer banque, santé, assurance, immobilier, école, coût de vie, famille, succession, mobilité et obligations déclaratives.'], ['Bosphoras peut-il comparer Turquie et Portugal ?', 'Oui. Bosphoras peut coordonner une analyse privée pour comprendre si la Turquie est cohérente par rapport au Portugal et aux autres alternatives.']],
  },
  en: {
    title: 'Turkey vs Portugal: tax residence, foreign income, NHR 2.0 and relocation',
    metaTitle: 'Turkey vs Portugal: Tax Residence and Foreign Income',
    description: 'Turkey vs Portugal for UK, US and international clients: NHR 2.0, IFICI, foreign income, tax residence, banking, property, healthcare, family and relocation.',
    eyebrow: 'Turkey vs Portugal · NHR 2.0 comparison',
    hero: 'Portugal was long associated with the NHR regime for expats, retirees and international investors. The landscape has changed. Portugal remains attractive, but its new framework is more targeted, while Turkey is entering the comparison with a different proposition around location, lifestyle, private healthcare and a potential foreign-income regime.',
    cta: 'Request a private assessment',
    asideTitle: 'Before comparing Turkey and Portugal',
    finalTitle: 'A relocation decision should match your tax, banking and family reality',
    finalText: 'Before choosing a destination, Bosphoras can organize a private review of your situation: tax residence, banking, property, healthcare, family, estate planning and relocation to Turkey.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Current tax residence', 'Foreign income streams', 'Pensions, dividends and gains', 'Companies and bank accounts', 'Healthcare insurance', 'Property strategy', 'Family and heirs', 'Former-country exit position'],
    sections: [
      ['Portugal: attractive, but more targeted than before', 'Portugal remains a strong destination for those wanting the European Union, Schengen area and eurozone. It offers quality of life, safety, climate, Lisbon, Porto, the Algarve, an international community and a European banking system. But the historic NHR regime is no longer available in the same form for new arrivals. The current framework is more focused on qualified professionals, innovation, research, startups and eligible activities.'],
      ['Turkey: a flexible alternative for some profiles', 'Turkey has a different position from Portugal. It may attract people looking for proximity to Europe, flexible cost of living, diverse property markets, Istanbul as a business city, Bodrum for luxury and the Aegean, Antalya for retirement, Izmir for Mediterranean life, developed private healthcare and access to the Middle East, Caucasus and Central Asia. If Turkey confirms its announced foreign-income regime, it may become relevant for people who no longer fit the Portuguese framework.'],
      ['For UK and US clients', 'UK and US clients should compare Portugal and Turkey beyond tax headlines. UK pensions, UK property, US citizenship-based obligations, Social Security, IRA or 401k income, brokerage accounts, company ownership, reporting and banking documentation may all matter. The former country, the destination country and the banking file should be reviewed together.'],
      ['For retirees', 'Portugal has long attracted European retirees. Today, retirees should review pension income, public or private pension, healthcare coverage, housing cost, treaty position, property kept in the former country and estate planning. Turkey may appeal to retirees seeking a more flexible cost base, private healthcare, Antalya, Alanya, Bodrum, Izmir, family warmth and proximity to Europe.'],
      ['For entrepreneurs and consultants', 'Portugal may remain relevant for qualified profiles within eligible activities such as research, innovation, higher education, startups or specific sectors. Entrepreneurs outside that framework should compare more broadly. Turkey may fit activities linked to Europe, Turkey, the Middle East, Kazakhstan, Central Asia, the Caucasus, import-export, B2B services, property, tourism, healthcare, industry or logistics.'],
      ['Families and private clients', 'Families do not compare only tax. Schools, hospitals, insurance, housing, banking, safety, language, international mobility, estate planning, cost of living, spouse status and access to children or grandchildren all matter. Portugal provides a reassuring European framework. Turkey may offer flexibility, air connectivity, diverse cities, property options, private healthcare and proximity to strategic regions.'],
      ['Banking and source of funds', 'Portugal or Turkey: banking remains central. You may need to explain source of funds, foreign income, dividends, capital gains, company sale, pension income, existing accounts, tax filings, contracts, foreign companies and tax residence. A tax-attractive country can still become difficult if the banking file is not prepared.'],
      ['Property: Portugal or Turkey?', 'Portugal often means Lisbon, Porto, the Algarve, Cascais, Estoril, Comporta or Madeira. Turkey may mean Istanbul, Bodrum, Antalya, Izmir, Alanya, Fethiye or Mersin. The right choice depends on primary residence, retirement, second home, rental investment, family wealth, resale, life with children and healthcare access.'],
      ['Healthcare and insurance', 'Portugal offers a reassuring European environment, but private services may be expensive and healthcare access depends on status, coverage and insurance. Turkey has a developed private healthcare sector in major cities. International health insurance, private hospitals, specialists, medication, emergency care, cost of treatment, spouse coverage and continuing care in the former country should be compared.'],
      ['Mistakes to avoid', 'Do not assume the old Portugal NHR regime is still available for all new arrivals. Do not choose Turkey only because a tax regime has been announced. Do not compare only tax rates. Do not ignore the former country. Do not transfer funds without evidence. Do not buy property before testing the city, neighborhood, hospitals and cost of living.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers, accountants or wealth advisors. Its role is to help compare Turkey with destinations such as Portugal and organize the Turkey side if suitable: profile review, foreign income mapping, tax residence, advisors, banking, health insurance, property, family relocation, estate planning and local partners.'],
    ],
    faq: [['Does Portugal NHR still exist?', 'The historic NHR regime has been replaced for new arrivals by a more targeted framework often referred to as IFICI or NHR 2.0, focused on certain qualified activities, innovation, research, startups and eligible sectors.'], ['Can Turkey be an alternative to Portugal?', 'Yes, for some entrepreneurs, retirees, families, investors or people who do not fit the new Portuguese eligibility criteria.'], ['Is Portugal more stable than Turkey from a tax perspective?', 'Portugal has a more established European framework. Turkey still needs final details for its announced regime. The right choice depends on your real profile.'], ['Should the choice be based only on tax?', 'No. Banking, healthcare, insurance, property, schools, cost of living, family, estate planning, mobility and reporting obligations all matter.'], ['Can Bosphoras compare Turkey and Portugal?', 'Yes. Bosphoras can coordinate a private review to assess whether Turkey is coherent compared with Portugal and other alternatives.']],
  },
  ru: {
    title: 'Турция vs Португалия: налоги, иностранные доходы, резиденция и переезд',
    metaTitle: 'Турция vs Португалия: налоги и иностранные доходы',
    description: 'Турция vs Португалия для русскоязычных инвесторов из России, Казахстана и СНГ: резиденция, банки, недвижимость, семья, медицина и иностранные доходы.',
    eyebrow: 'Турция vs Португалия · Налоги и резиденция',
    hero: 'Португалия долго была популярна благодаря режиму NHR. Сейчас условия стали более узкими, а Турция входит в сравнение как более близкая к Европе, Кавказу и Центральной Азии альтернатива с разной недвижимостью, медициной, семейной жизнью и потенциальным режимом для иностранных доходов.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед сравнением Турции и Португалии',
    finalTitle: 'Выбор страны должен подходить вашей семье, банкам и реальной жизни',
    finalText: 'До выбора страны Bosphoras может организовать частный анализ вашей ситуации: налоги, банки, недвижимость, медицина, семья, наследство и переезд в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Текущая налоговая резиденция', 'Иностранные доходы', 'Пенсия, дивиденды и прирост капитала', 'Компании и счета', 'Медицинская страховка', 'Недвижимость', 'Семья и наследники', 'Выход из прежней страны'],
    sections: [
      ['Португалия: привлекательная, но более узкая система', 'Португалия остается сильным направлением для тех, кто хочет ЕС, Шенген и еврозону. Она привлекает качеством жизни, безопасностью, климатом, Лиссабоном, Порту, Алгарве, международным окружением и европейской банковской системой. Но прежний режим NHR больше не доступен в исторической форме для новых резидентов. Новый подход больше ориентирован на qualified professionals, innovation, research, startups и определенные виды деятельности.'],
      ['Турция: более гибкая альтернатива для некоторых профилей', 'Турция предлагает другую логику: близость к Европе, более гибкую стоимость жизни, разные рынки недвижимости, Стамбул как деловой центр, Бодрум, Анталью, Измир, развитую частную медицину и связь с Ближним Востоком, Кавказом, Казахстаном, Узбекистаном, Кыргызстаном и Центральной Азией. Если объявленный режим по иностранным доходам будет подтвержден, Турция может стать актуальной для тех, кто не подходит под новый португальский режим.'],
      ['Для клиентов из России, Казахстана и СНГ', 'Русскоязычным клиентам важно сравнивать не только налоги, но и банки, источник средств, валютные вопросы, недвижимость в стране происхождения, семью, медицину, перелеты и документы. Португалия дает европейский формат, но Турция может быть ближе географически и культурно, особенно для клиентов, связанных с Казахстаном, Центральной Азией, Кавказом и Турцией.'],
      ['Пенсионеры и passive income', 'Португалия долго привлекала европейских пенсионеров. Но сейчас пенсионеру нужно смотреть пенсию, недвижимость, аренду, медицину, страховку, банк, наследство и статус в прежней стране. Турция может быть интересна тем, кто хочет Анталью, Аланью, Бодрум, Измир, более гибкую стоимость жизни, медицину и семейную среду.'],
      ['Предприниматели и консультанты', 'Португалия может быть интересна qualified profiles в eligible activities. Турция может подходить бизнесам, связанным с Европой, Турцией, Ближним Востоком, Казахстаном, Центральной Азией, Кавказом, import-export, B2B, недвижимостью, туризмом, медициной, промышленностью или логистикой. Вопрос не только в налоге, а в том, где бизнес реально может работать с банком, клиентами и документами.'],
      ['Семья и private clients', 'Семья сравнивает школы, больницы, страховку, жилье, банки, безопасность, язык, перелеты, наследство, стоимость жизни, статус супруга и доступ к детям или внукам. Португалия дает европейскую стабильность. Турция может дать гибкость, авиасвязь, разные города, недвижимость, медицину и близость к нескольким регионам.'],
      ['Банки и происхождение средств', 'В Португалии и Турции банк будет требовать понятный файл: происхождение средств, иностранные доходы, дивиденды, gains, продажа компании, пенсия, счета, декларации, договоры, иностранные компании и налоговая резиденция. Даже привлекательная страна может стать сложной, если banking file не подготовлен.'],
      ['Недвижимость: Португалия или Турция', 'В Португалии часто смотрят Лиссабон, Порту, Алгарве, Cascais, Estoril, Comporta или Madeira. В Турции — Стамбул, Бодрум, Анталья, Измир, Аланья, Фетхие или Мерсин. Выбор зависит от цели: жизнь, пенсия, второй дом, аренда, family wealth, перепродажа, дети или доступ к медицине.'],
      ['Медицина и страховка', 'Португалия предлагает европейскую среду, но частные услуги могут быть дорогими, а доступ к медицине зависит от статуса и страховки. В Турции развит частный медицинский сектор в крупных городах. Нужно сравнивать страховку, больницы, специалистов, лекарства, emergency care, стоимость лечения и покрытие супруга и детей.'],
      ['Ошибки, которых нужно избегать', 'Не думайте, что старый Portugal NHR доступен всем новым резидентам. Не выбирайте Турцию только из-за объявленного режима. Не сравнивайте только ставки налогов. Не игнорируйте прежнюю страну. Не переводите средства без документов. Не покупайте недвижимость до проверки города, района, больниц и стоимости жизни.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов, бухгалтеров или wealth advisors. Его роль — помочь сравнить Турцию с Португалией и другими вариантами, а затем организовать турецкую часть, если она подходит: профиль, иностранные доходы, резиденция, консультанты, банк, страховка, недвижимость, семья, наследство и местные партнеры.'],
    ],
    faq: [['Старый режим Portugal NHR еще существует?', 'Для новых резидентов прежний NHR заменен более целевым режимом, часто называемым IFICI или NHR 2.0, ориентированным на квалифицированные виды деятельности, innovation, research и eligible sectors.'], ['Может ли Турция быть альтернативой Португалии?', 'Да, для некоторых предпринимателей, пенсионеров, семей, инвесторов и клиентов, которые не подходят под новые критерии Португалии.'], ['Португалия стабильнее Турции по налогам?', 'Португалия имеет более установленную европейскую систему. Турция должна подтвердить финальные детали объявленного режима. Выбор зависит от вашего реального профиля.'], ['Нужно выбирать только по налогам?', 'Нет. Банки, медицина, страховка, недвижимость, школы, стоимость жизни, семья, наследство и перелеты также важны.'], ['Bosphoras может сравнить Турцию и Португалию?', 'Да. Bosphoras может координировать частный анализ, чтобы понять, подходит ли Турция по сравнению с Португалией и другими вариантами.']],
  },
  ar: {
    title: 'تركيا vs البرتغال: الضرائب، الإقامة، الدخل الأجنبي ونقل الثروة',
    metaTitle: 'تركيا vs البرتغال: الضرائب والإقامة والدخل الأجنبي',
    description: 'تركيا vs البرتغال للمستثمرين العرب والخليج: الإقامة الضريبية، الدخل الأجنبي، البنوك، العقار، الصحة، العائلة ونقل الثروة.',
    eyebrow: 'تركيا vs البرتغال · الضرائب والإقامة',
    hero: 'كانت البرتغال لسنوات وجهة معروفة بسبب نظام NHR السابق. اليوم أصبح الإطار أكثر تحديداً، بينما تدخل تركيا المقارنة كخيار قريب من أوروبا والشرق الأوسط، مع عقارات متنوعة، طب خاص، حياة عائلية ومدن ساحلية.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل مقارنة تركيا والبرتغال',
    finalTitle: 'الاختيار الصحيح يجب أن يناسب العائلة والبنوك والحياة الفعلية',
    finalText: 'قبل اختيار الوجهة، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك: الضرائب، البنوك، العقار، التأمين الصحي، العائلة، الميراث والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['إقامتك الضريبية الحالية', 'الدخل الأجنبي', 'المعاش والأرباح والمكاسب', 'الشركات والحسابات البنكية', 'التأمين الصحي', 'العقار', 'العائلة والورثة', 'الخروج من بلدك السابق'],
    sections: [
      ['البرتغال: جذابة لكن النظام أصبح أكثر تحديداً', 'البرتغال تبقى وجهة قوية لمن يريد الاتحاد الأوروبي، شنغن واليورو. تجذب بجودة الحياة، الأمان، المناخ، لشبونة، بورتو، الغارف، المجتمع الدولي والنظام البنكي الأوروبي. لكن نظام NHR القديم لم يعد متاحاً بنفس الشكل للقادمين الجدد. الإطار الجديد أكثر ارتباطاً ببعض الأنشطة المؤهلة، الابتكار، البحث، الشركات الناشئة أو قطاعات محددة.'],
      ['تركيا: بديل أكثر مرونة لبعض الملفات', 'تركيا تقدم منطقاً مختلفاً: قرب من أوروبا، تكلفة معيشة أكثر مرونة، عقارات متنوعة، إسطنبول كمدينة أعمال، بودروم للفخامة، أنطاليا للتقاعد، إزمير لنمط متوسطي، طب خاص متطور، وربط مع الشرق الأوسط والقوقاز وآسيا الوسطى. إذا تم تأكيد النظام التركي للدخل الأجنبي، قد تصبح خياراً جدياً لمن لا يدخل ضمن الإطار البرتغالي الجديد.'],
      ['للمستثمرين العرب والخليج', 'بالنسبة للعائلات والمستثمرين من الإمارات، السعودية، قطر، الكويت، البحرين وعمان، المقارنة لا يجب أن تكون ضريبية فقط. يجب مقارنة البنوك، مصدر الأموال، العقار، العائلة، المدارس، الصحة، السفر، الخصوصية والميراث. البرتغال تقدم إطاراً أوروبياً، وتركيا قد تقدم قرباً ثقافياً وجغرافياً وتكلفة أكثر مرونة.'],
      ['المتقاعدون وأصحاب الدخل السلبي', 'البرتغال جذبت طويلاً المتقاعدين. اليوم يجب مراجعة المعاش، العقار، الإيجارات، التأمين الصحي، البنك، الميراث والالتزامات في بلد الإقامة السابق. تركيا قد تجذب من يبحث عن أنطاليا، ألانيا، بودروم، إزمير، تكلفة حياة أكثر مرونة، طب خاص وحياة عائلية أقرب.'],
      ['رواد الأعمال والمستشارون', 'البرتغال قد تبقى مناسبة لبعض الأنشطة المؤهلة. تركيا قد تكون مناسبة للأعمال المرتبطة بأوروبا، تركيا، الشرق الأوسط، آسيا الوسطى، القوقاز، الاستيراد والتصدير، B2B، العقار، السياحة، الصحة، الصناعة أو اللوجستيك. السؤال ليس فقط أين الضريبة أقل، بل أين يمكن للنشاط أن يعمل فعلياً مع بنك وعملاء ووثائق.'],
      ['العائلة والثروة الخاصة', 'العائلة تقارن المدارس، المستشفيات، التأمين، السكن، البنوك، الأمان، اللغة، السفر، الميراث، تكلفة الحياة، وضع الزوج أو الزوجة والوصول إلى الأبناء أو الأحفاد. البرتغال تعطي إطاراً أوروبياً مطمئناً. تركيا قد تقدم مرونة، رحلات جوية كثيرة، مدناً مختلفة، عقاراً متنوعاً وطباً خاصاً.'],
      ['البنوك ومصدر الأموال', 'في البرتغال أو تركيا، البنك يحتاج إلى ملف واضح: مصدر الأموال، الدخل الأجنبي، الأرباح، المكاسب، بيع شركة، معاش، حسابات، تصريحات ضريبية، عقود، شركات أجنبية وإقامة ضريبية. بلد جذاب ضريبياً يمكن أن يصبح معقداً إذا لم يكن الملف البنكي جاهزاً.'],
      ['العقار: البرتغال أم تركيا', 'في البرتغال، المناطق المعروفة هي لشبونة، بورتو، الغارف، كاشكايش، إستوريل، كومبورتا وماديرا. في تركيا، إسطنبول، بودروم، أنطاليا، إزمير، ألانيا، فتحية ومرسين. الاختيار يعتمد على الهدف: سكن رئيسي، تقاعد، منزل ثانٍ، استثمار إيجاري، ثروة عائلية، إعادة بيع، حياة مع الأطفال أو الوصول إلى الرعاية الصحية.'],
      ['الصحة والتأمين', 'البرتغال تقدم إطاراً أوروبياً مطمئناً، لكن بعض الخدمات الخاصة قد تكون مكلفة والوصول إلى الرعاية يعتمد على الوضع والتغطية والتأمين. تركيا لديها قطاع طبي خاص متطور في المدن الكبرى. يجب مقارنة التأمين الصحي الدولي، المستشفيات، الأطباء، الأدوية، الطوارئ، تكلفة العلاج وتغطية الزوج أو الزوجة والأطفال.'],
      ['أخطاء يجب تجنبها', 'لا تفترض أن نظام NHR القديم لا يزال متاحاً للجميع. لا تختر تركيا فقط لأن نظاماً ضريبياً تم الإعلان عنه. لا تقارن فقط معدلات الضرائب. لا تهمل بلدك السابق. لا تحول الأموال دون مستندات. لا تشتر عقاراً قبل تجربة المدينة والحي والمستشفيات وتكلفة الحياة.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامي الضريبي أو المحاسب أو مستشار الثروة. دوره هو مساعدتك في مقارنة تركيا بالبرتغال ووجهات أخرى، ثم تنظيم الجزء التركي إذا كان مناسباً: تحليل الملف، الدخل الأجنبي، الإقامة، المستشارون، البنوك، التأمين، العقار، العائلة، الميراث والشركاء المحليون.'],
    ],
    faq: [['هل ما زال نظام Portugal NHR القديم موجوداً؟', 'للقادمين الجدد، تم استبدال NHR القديم بنظام أكثر تحديداً غالباً يسمى IFICI أو NHR 2.0، ويركز على أنشطة مؤهلة مثل الابتكار والبحث وقطاعات محددة.'], ['هل يمكن أن تكون تركيا بديلاً للبرتغال؟', 'نعم لبعض رواد الأعمال والمتقاعدين والعائلات والمستثمرين أو من لا يدخلون ضمن معايير النظام البرتغالي الجديد.'], ['هل البرتغال أكثر استقراراً ضريبياً من تركيا؟', 'البرتغال لديها إطار أوروبي أكثر رسوخاً. تركيا تحتاج إلى تأكيد التفاصيل النهائية للنظام المعلن. الاختيار يعتمد على ملفك الحقيقي.'], ['هل يجب الاختيار حسب الضرائب فقط؟', 'لا. البنوك، الصحة، التأمين، العقار، المدارس، تكلفة الحياة، العائلة، الميراث والسفر كلها مهمة.'], ['هل يمكن لـ Bosphoras مقارنة تركيا والبرتغال؟', 'نعم. يمكن لـ Bosphoras تنسيق مراجعة خاصة لفهم ما إذا كانت تركيا مناسبة مقارنة بالبرتغال والبدائل الأخرى.']],
  },
};

export function getTurkeyVsPortugalTaxMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function TurkeyVsPortugalTaxClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
