import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/turquie-vs-italie-regime-non-dom-fiscalite',
  en: '/en/turkey-vs-italy-non-dom-tax-regime',
  ru: '/ru/turtsiya-vs-italiya-non-dom-nalogovyy-rezhim',
  ar: '/ar/turkey-vs-italy-non-dom-tax-regime',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = { title:string; metaTitle:string; description:string; eyebrow:string; hero:string; cta:string; asideTitle:string; finalTitle:string; finalText:string; faqTitle:string; checklist:string[]; sections:Array<[string,string]>; faq:Array<[string,string]> };

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Turquie vs Italie : régime non-dom, fiscalité des revenus étrangers et résidence',
    metaTitle: 'Turquie vs Italie : régime non-dom, fiscalité et résidence',
    description: 'Turquie vs Italie : comparaison pour investisseurs, entrepreneurs et familles patrimoniales. Régime non-dom italien, revenus étrangers, résidence fiscale, immobilier, banque, famille et installation.',
    eyebrow: 'Comparaison fiscale · Turquie vs Italie',
    hero: 'Si vous envisagez de quitter votre pays de résidence pour organiser votre vie, votre famille et votre patrimoine dans un pays plus favorable, l’Italie et la Turquie peuvent entrer dans la comparaison. La vraie question n’est pas seulement le montant de l’impôt, mais le pays qui correspond réellement à vos revenus, votre famille, vos banques et votre mode de vie.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant de comparer Turquie et Italie',
    finalTitle: 'La meilleure destination est celle qui correspond à votre vie réelle',
    finalText: 'Avant de choisir une destination, Bosphoras peut organiser une analyse privée de votre situation : fiscalité, revenus étrangers, dividendes, plus-values, immobilier, banque, assurance santé, famille, succession et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Vos revenus étrangers', 'Dividendes, plus-values et pensions', 'Votre résidence fiscale réelle', 'La banque et l’origine des fonds', 'Votre famille et vos enfants', 'Votre assurance santé', 'Votre immobilier', 'Vos obligations déclaratives'],
    sections: [
      ['Italie : un régime connu, mais plus coûteux', 'L’Italie propose un régime de taxation forfaitaire pour certains nouveaux résidents sur les revenus étrangers. Le contribuable peut opter pour une taxe forfaitaire annuelle au lieu d’une imposition ordinaire sur certains revenus étrangers. Ce régime a longtemps attiré les personnes avec dividendes, plus-values, portefeuilles financiers, holdings ou patrimoine international. Mais son coût a augmenté fortement, ce qui le rend surtout pertinent pour les profils disposant de revenus étrangers très importants.'],
      ['Turquie : une opportunité à suivre de près', 'La Turquie a annoncé un projet visant certains nouveaux résidents, avec une exonération potentielle de longue durée sur certains revenus et gains de source étrangère. Si le texte final confirme cette orientation, la Turquie pourrait devenir une alternative sérieuse pour des profils comparant Italie, Dubaï, Monaco, Suisse, Portugal, Chypre, Malte ou Royaume-Uni. Mais la Turquie ne doit pas être choisie uniquement pour un titre fiscal : il faut vérifier si votre vie réelle peut être organisée dans le pays.'],
      ['Comparer les bons critères', 'La comparaison ne doit pas se limiter au taux d’impôt. Il faut regarder revenus étrangers, dividendes, plus-values, pension, immobilier, succession, banque, assurance santé, coût de vie, écoles, conjoint, enfants, langue, mobilité internationale, conventions fiscales, obligations déclaratives, sécurité juridique et qualité de vie. Un régime fiscal attractif sur le papier peut être mal adapté à votre famille ou à vos banques.'],
      ['Pour un entrepreneur ou actionnaire', 'Si vous êtes entrepreneur, dirigeant ou actionnaire, il faut regarder où se trouve votre société, où elle est réellement dirigée, où sont les clients, où les contrats sont signés, où les dividendes seront distribués, où les plus-values seront réalisées et quel pays comprend votre structure. L’Italie peut être adaptée à certains très grands patrimoines internationaux. La Turquie peut être intéressante pour une base plus flexible entre Europe, Moyen-Orient et Asie centrale.'],
      ['Pour une famille patrimoniale', 'Pour une famille, la fiscalité n’est qu’un élément. Il faut comparer écoles, assurance santé, hôpitaux, logement, sécurité, langue, déplacements, communauté internationale, succession, banque privée et qualité de vie. L’Italie offre un cadre européen et culturel fort. La Turquie peut offrir une grande connectivité aérienne, des villes dynamiques, des zones balnéaires, une médecine privée développée et un coût de vie souvent plus compétitif.'],
      ['Pour un retraité ou rentier', 'Un retraité ou rentier doit comparer pension étrangère, revenus locatifs, portefeuille financier, assurance santé, coût du logement, hôpitaux, accessibilité, succession, banque et vie quotidienne. L’Italie peut attirer les personnes attachées au cadre européen. La Turquie peut attirer les retraités recherchant une vie plus flexible à Antalya, Bodrum, Izmir, Istanbul ou Alanya.'],
      ['Banque et conformité', 'Quel que soit le pays choisi, la banque sera centrale. Vous devrez probablement expliquer origine des fonds, revenus étrangers, dividendes, plus-values, sociétés, patrimoine familial, résidence fiscale, preuve de vie réelle, documents fiscaux, contrats et déclarations. La Turquie comme l’Italie doivent être abordées avec un dossier bancaire, fiscal et patrimonial préparé.'],
      ['Immobilier : Italie ou Turquie ?', 'L’immobilier est souvent au cœur de la décision. En Italie, les zones attractives peuvent être Milan, Rome, Florence, Toscane, Lac de Côme, Sardaigne ou Sicile. En Turquie, Istanbul, Bodrum, Antalya, Izmir, Alanya, Fethiye et Mersin peuvent correspondre à des budgets et styles de vie différents. Le choix dépend du budget, de la fiscalité locale, de l’accès aux soins, de la liquidité à la revente, de la famille et de la mobilité aérienne.'],
      ['Les erreurs à éviter', 'La première erreur est de comparer uniquement le montant de l’impôt. La deuxième est de choisir un pays sans vérifier la résidence fiscale réelle. La troisième est de croire qu’un régime non-dom règle automatiquement dividendes, plus-values, successions et revenus immobiliers. La quatrième est de négliger la banque et l’origine des fonds. La cinquième est de sous-estimer le coût réel de la vie, du logement, de la santé et de l’installation familiale.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste, un expert-comptable ou un conseiller patrimonial. Notre rôle est de vous aider à comparer sérieusement la Turquie avec d’autres destinations, dont l’Italie, et à organiser la partie Turquie si cette option est cohérente pour vous : profil, revenus étrangers, résidence fiscale, avocats, fiscalistes, banque, assurance santé, immobilier, famille, succession et partenaires locaux.'],
    ],
    faq: [['La Turquie est-elle plus avantageuse que l’Italie ?', 'Potentiellement, selon votre profil. L’Italie dispose d’un régime connu mais coûteux. La Turquie a annoncé un projet potentiellement attractif, mais il faut vérifier le texte final, votre situation et votre installation réelle.'], ['Faut-il choisir un pays uniquement pour la fiscalité ?', 'Non. Il faut aussi comparer famille, banque, santé, immobilier, succession, coût de vie, mobilité, obligations déclaratives et qualité de vie.'], ['Le régime non-dom règle-t-il automatiquement les revenus étrangers ?', 'Non. Dividendes, plus-values, pensions, revenus immobiliers et sociétés doivent être analysés séparément.'], ['La Turquie peut-elle remplacer l’Italie pour certains profils ?', 'Oui, pour certains entrepreneurs, familles ou investisseurs si leur vie réelle, leur banque, leurs revenus et leur patrimoine peuvent être organisés correctement en Turquie.'], ['Bosphoras peut-il comparer la Turquie avec l’Italie ?', 'Oui. Bosphoras peut coordonner une analyse privée avec les bons fiscalistes et partenaires pour comprendre si la Turquie est cohérente par rapport à votre profil et à vos alternatives.']],
  },
  en: {
    title: 'Turkey vs Italy Non-Dom Tax Regime: foreign income, residence and relocation planning',
    metaTitle: 'Turkey vs Italy Non-Dom Tax Regime: Foreign Income Guide',
    description: 'Turkey vs Italy non-dom tax regime for UK, US and international investors: foreign income, flat tax, residence, banking, property, family and relocation planning.',
    eyebrow: 'Turkey vs Italy · Non-dom comparison',
    hero: 'For UK, US and international families comparing relocation options, Italy and Turkey can both appear on the shortlist. The right question is not only which regime looks better on paper, but which country fits your income, companies, banking, family, property and real lifestyle.',
    cta: 'Request a private assessment',
    asideTitle: 'Before comparing Turkey and Italy',
    finalTitle: 'The right relocation base must match your income, family and banking reality',
    finalText: 'Before choosing a destination, Bosphoras can organize a private review of your situation: foreign income, dividends, capital gains, property, banking, healthcare, family, estate planning and relocation to Turkey.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Foreign income and investment portfolio', 'Dividends, gains and pension income', 'Tax residence position', 'Banking and source of funds', 'Family and children', 'Healthcare and insurance', 'Property strategy', 'Reporting obligations'],
    sections: [
      ['Italy: established, but increasingly expensive', 'Italy has a well-known regime for certain new residents with a flat annual tax on foreign income. It has attracted individuals with large foreign income, dividends, capital gains, portfolios, holdings and international wealth. However, the cost has increased, which means the regime is generally most relevant for people whose foreign income is large enough to justify a high annual flat tax.'],
      ['Turkey: an opportunity to monitor carefully', 'Turkey has announced a potential long-term exemption for certain foreign-source income and gains of qualifying new residents. If confirmed in final legislation, Turkey may become a serious alternative for people comparing Italy, Dubai, Monaco, Switzerland, Cyprus, Malta, Portugal or the UK. But Turkey should not be chosen only because of a tax headline. Real life, banking and documentation must support the move.'],
      ['For UK and US clients', 'British and American clients should look beyond simple tax comparisons. UK pension and property, US citizenship-based obligations, brokerage accounts, IRA or 401k income, company ownership, source-country taxation and banking documentation may all matter. A move to Turkey or Italy should be coordinated with advisors in the former country as well as local advisors in the destination country.'],
      ['Entrepreneurs and shareholders', 'If you own a company, the analysis should include where the company is incorporated, where it is effectively managed, where clients are located, where contracts are signed, where dividends are distributed, where capital gains may arise and which banks understand the structure. Italy can suit some very large international wealth profiles. Turkey may suit entrepreneurs seeking a more flexible base between Europe, the Middle East and Central Asia.'],
      ['Families and private clients', 'For a family, tax is only one part of the decision. Schools, healthcare, hospitals, housing, safety, language, travel, international community, estate planning, private banking and daily life all matter. Italy offers a European cultural environment. Turkey may offer strong air connectivity, dynamic cities, coastal lifestyle, private healthcare and a more flexible cost base.'],
      ['Retirees and passive-income profiles', 'Retirees and rentiers should compare pension income, rental income, investment portfolios, healthcare, housing cost, hospitals, accessibility, estate planning, banking and everyday life. Italy may appeal to those wanting a European Mediterranean setting. Turkey may appeal to those looking for Istanbul, Antalya, Bodrum, Izmir or Alanya with a different cost and lifestyle balance.'],
      ['Banking and compliance', 'Regardless of the destination, banks will be central. You may need to explain source of funds, foreign income, dividends, capital gains, companies, family wealth, tax residence, proof of real life, tax documents, contracts and filings. Neither Italy nor Turkey should be approached as a simple tax destination without a prepared banking and wealth file.'],
      ['Property comparison', 'Property often influences the decision. Italy may mean Milan, Rome, Florence, Tuscany, Lake Como, Sardinia or Sicily. Turkey may mean Istanbul, Bodrum, Antalya, Izmir, Alanya, Fethiye or Mersin. Budget, local taxes, healthcare access, resale liquidity, airport access, family needs and estate planning should all be considered.'],
      ['Mistakes to avoid', 'Do not compare only the headline tax cost. Do not relocate without verifying real tax residence. Do not assume a non-dom or foreign-income regime automatically solves dividends, capital gains, property income and inheritance. Do not ignore banking and source of funds. Do not underestimate the real cost of housing, healthcare and family installation.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers, accountants or wealth advisors. Its role is to help coordinate a serious comparison between Turkey and other destinations, including Italy, and to organize the Turkey side if it is suitable: profile review, foreign income mapping, advisors, banking, insurance, property, family relocation, estate planning and local partners.'],
    ],
    faq: [['Is Turkey more attractive than Italy?', 'Potentially, depending on your profile. Italy has an established but costly regime. Turkey has announced a potentially attractive project, but final rules and real-life suitability must be reviewed.'], ['Should I choose a country only for tax?', 'No. Family, banking, healthcare, property, estate planning, cost of living, mobility, reporting obligations and lifestyle should all be compared.'], ['Does a non-dom regime solve all foreign income issues?', 'No. Dividends, capital gains, pensions, property income and company structures should be reviewed separately.'], ['Can Turkey replace Italy for some clients?', 'Yes, for some entrepreneurs, families and investors if income, banking, residence and lifestyle can be organized coherently in Turkey.'], ['Can Bosphoras compare Turkey and Italy?', 'Yes. Bosphoras can coordinate a private review with suitable advisors to assess whether Turkey is coherent compared with Italy and other alternatives.']],
  },
  ru: {
    title: 'Турция vs Италия: non-dom режим, иностранные доходы и налоговая резиденция',
    metaTitle: 'Турция vs Италия: non-dom режим и налоги',
    description: 'Турция vs Италия для русскоязычных инвесторов из России, Казахстана и СНГ: иностранные доходы, резиденция, банки, недвижимость, семья и переезд.',
    eyebrow: 'Турция vs Италия · Резиденция и налоги',
    hero: 'Для русскоязычных предпринимателей, инвесторов и семей из России, Казахстана, Узбекистана, Кыргызстана и других стран СНГ Италия и Турция могут рассматриваться как альтернативы. Вопрос не только в налогах, а в том, какая страна подходит вашей семье, активам, банкам и образу жизни.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед сравнением Турции и Италии',
    finalTitle: 'Лучшая страна — та, где ваша жизнь и документы выглядят логично',
    finalText: 'До выбора страны Bosphoras может организовать частный анализ вашей ситуации: иностранные доходы, дивиденды, прирост капитала, недвижимость, банки, медицина, семья, наследство и переезд в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Иностранные доходы и активы', 'Дивиденды, gains и пенсия', 'Реальная налоговая резиденция', 'Банк и происхождение средств', 'Семья и дети', 'Медицина и страховка', 'Недвижимость', 'Документы и отчетность'],
    sections: [
      ['Италия: известный режим, но дорогая опция', 'Италия имеет известный режим для новых резидентов с фиксированным налогом на иностранные доходы. Он интересовал клиентов с крупными дивидендами, приростом капитала, портфелями, холдингами и международным капиталом. Но стоимость режима выросла, поэтому Италия чаще подходит тем, чьи иностранные доходы достаточно велики, чтобы оправдать высокий ежегодный платеж.'],
      ['Турция: возможность, которую нужно внимательно анализировать', 'Турция объявила потенциальный долгосрочный режим для некоторых иностранных доходов и gains новых резидентов. Если финальный закон подтвердит направление, Турция может стать альтернативой для тех, кто сравнивает Италию, Дубай, Монако, Швейцарию, Кипр, Мальту или Португалию. Но выбирать Турцию нужно не по заголовку, а по реальной жизни, банкам и документам.'],
      ['Для клиентов из России, Казахстана и СНГ', 'Клиентам из России, Казахстана, Узбекистана, Кыргызстана и СНГ нужно учитывать банковские переводы, документы о происхождении средств, валютные вопросы, недвижимость в стране происхождения, семейные обязательства, статус компаний и налоговую резиденцию. Турция может быть ближе культурно и географически, а Италия — более европейским вариантом, но обе требуют подготовки.'],
      ['Предприниматели и акционеры', 'Если у вас есть компания, нужно понять, где она зарегистрирована, где фактически управляется, где клиенты, где подписываются договоры, где распределяются дивиденды, где возникнут gains и какие банки понимают структуру. Италия может подходить очень крупным международным структурам. Турция может подходить предпринимателям, которым нужна база между Европой, Ближним Востоком и Центральной Азией.'],
      ['Семья и частный капитал', 'Для семьи налоги — только часть решения. Нужно сравнить школы, медицину, больницы, жилье, безопасность, язык, перелеты, международное окружение, наследство, private banking и ежедневную жизнь. Италия дает европейский культурный образ. Турция может дать авиасвязь, динамичные города, морские направления, частную медицину и более гибкую стоимость жизни.'],
      ['Пенсионеры и passive income', 'Пенсионеры и рантье должны сравнить пенсию, аренду, портфели, медицину, стоимость жилья, больницы, доступность, наследство, банки и ежедневный комфорт. Италия может быть интересна тем, кто хочет европейскую среду. Турция может быть интересна тем, кто смотрит на Стамбул, Анталью, Бодрум, Измир или Аланью.'],
      ['Банки и compliance', 'В любом случае банки будут важны. Нужно объяснять происхождение средств, иностранные доходы, дивиденды, gains, компании, семейный капитал, налоговую резиденцию, доказательства реальной жизни, налоговые документы, договоры и декларации. Ни Турцию, ни Италию нельзя рассматривать как простой налоговый адрес без подготовленного файла.'],
      ['Недвижимость: Италия или Турция', 'Недвижимость часто влияет на выбор. В Италии это могут быть Милан, Рим, Флоренция, Тоскана, Комо, Сардиния или Сицилия. В Турции — Стамбул, Бодрум, Анталья, Измир, Аланья, Фетхие или Мерсин. Нужно учитывать бюджет, налоги, медицину, ликвидность, аэропорты, семью и наследование.'],
      ['Ошибки, которых нужно избегать', 'Не сравнивайте только налоговый платеж. Не переезжайте без проверки реальной резиденции. Не думайте, что non-dom или иностранная льгота автоматически решает дивиденды, gains, недвижимость и наследство. Не игнорируйте банк и источник средств. Не недооценивайте стоимость жилья, медицины и семейной установки.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов, бухгалтеров или wealth advisors. Его роль — помочь серьезно сравнить Турцию с другими странами, включая Италию, и организовать турецкую часть, если она подходит: профиль, иностранные доходы, консультанты, банки, страховка, недвижимость, семья, наследство и местные партнеры.'],
    ],
    faq: [['Турция выгоднее Италии?', 'Потенциально, но зависит от профиля. Италия имеет известный, но дорогой режим. Турция объявила потенциально интересный проект, но нужны финальные правила и анализ реальной жизни.'], ['Можно ли выбирать страну только по налогам?', 'Нет. Нужно сравнивать семью, банки, медицину, недвижимость, наследство, стоимость жизни, перелеты, отчетность и lifestyle.'], ['Non-dom режим решает все иностранные доходы?', 'Нет. Дивиденды, прирост капитала, пенсии, недвижимость и компании нужно анализировать отдельно.'], ['Может ли Турция заменить Италию?', 'Для некоторых предпринимателей, семей и инвесторов — да, если доходы, банки, резиденция и образ жизни могут быть логично организованы в Турции.'], ['Bosphoras может сравнить Турцию и Италию?', 'Да. Bosphoras может координировать частный анализ с профильными специалистами, чтобы понять, подходит ли Турция по сравнению с Италией и другими вариантами.']],
  },
  ar: {
    title: 'تركيا vs إيطاليا: نظام non-dom، الدخل الأجنبي والإقامة الضريبية',
    metaTitle: 'تركيا vs إيطاليا: نظام non-dom والضرائب',
    description: 'تركيا vs إيطاليا للمستثمرين العرب والخليج: الدخل الأجنبي، الإقامة الضريبية، البنوك، العقار، العائلة، الصحة ونقل الثروة.',
    eyebrow: 'تركيا vs إيطاليا · الضرائب والإقامة',
    hero: 'بالنسبة للمستثمرين والعائلات العربية من الإمارات والسعودية وقطر والكويت والبحرين وعمان، قد تكون إيطاليا وتركيا ضمن الخيارات. السؤال ليس فقط أي نظام ضريبي أفضل، بل أي بلد يناسب الدخل، البنوك، العائلة، العقار ونمط الحياة.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل مقارنة تركيا وإيطاليا',
    finalTitle: 'البلد المناسب هو الذي يناسب عائلتك وبنوكك وحياتك الفعلية',
    finalText: 'قبل اختيار الوجهة، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك: الدخل الأجنبي، الأرباح، المكاسب، العقار، البنوك، التأمين الصحي، العائلة، الميراث والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['الدخل الأجنبي والأصول', 'الأرباح والمكاسب والمعاش', 'الإقامة الضريبية الحقيقية', 'البنوك ومصدر الأموال', 'العائلة والأطفال', 'الصحة والتأمين', 'العقار', 'المستندات والالتزامات'],
    sections: [
      ['إيطاليا: نظام معروف لكنه مكلف', 'إيطاليا لديها نظام معروف لبعض المقيمين الجدد يقوم على ضريبة سنوية ثابتة على الدخل الأجنبي. جذب هذا النظام أشخاصاً لديهم أرباح، مكاسب رأسمالية، محافظ مالية، holdings وثروات دولية. لكن تكلفة النظام ارتفعت، لذلك يصبح مناسباً غالباً لمن لديهم دخل أجنبي كبير جداً يبرر دفع مبلغ سنوي مرتفع.'],
      ['تركيا: فرصة يجب دراستها بحذر', 'أعلنت تركيا عن مشروع قد يمنح بعض المقيمين الجدد معاملة طويلة الأجل لبعض الدخل والمكاسب من مصدر أجنبي. إذا أكد القانون النهائي هذا الاتجاه، قد تصبح تركيا بديلاً جدياً لمن يقارن إيطاليا، دبي، موناكو، سويسرا، قبرص، مالطا أو البرتغال. لكن لا يجب اختيار تركيا بسبب عنوان ضريبي فقط، بل يجب أن تدعم الحياة والبنوك والمستندات هذا الانتقال.'],
      ['للمستثمرين من الخليج والدول العربية', 'المستثمر العربي يجب أن ينظر إلى البنوك، مصدر الأموال، الشركات العائلية، العقار في الخليج أو أوروبا، العائلة، المدارس، الصحة، الخصوصية، السفر والورثة. تركيا قد تكون أقرب ثقافياً وجغرافياً لبعض العائلات، بينما تقدم إيطاليا إطاراً أوروبياً. القرار يجب أن يكون عملياً وليس نظرياً.'],
      ['رواد الأعمال والمساهمون', 'إذا كنت تملك شركة، يجب تحليل مكان تسجيلها، أين تدار فعلياً، أين العملاء، أين العقود، أين توزع الأرباح، أين تظهر المكاسب، وأي بنوك تفهم الهيكل. إيطاليا قد تناسب بعض الثروات الدولية الكبيرة. تركيا قد تناسب من يريد قاعدة مرنة بين أوروبا والشرق الأوسط وآسيا الوسطى.'],
      ['العائلة والثروة الخاصة', 'بالنسبة للعائلة، الضرائب جزء واحد فقط. يجب مقارنة المدارس، المستشفيات، التأمين الصحي، السكن، الأمان، اللغة، السفر، المجتمع الدولي، الميراث، البنوك الخاصة ونمط الحياة. إيطاليا تقدم صورة أوروبية وثقافية قوية. تركيا قد تقدم رحلات جوية كثيرة، مدناً ديناميكية، سواحل، طباً خاصاً وتكاليف أكثر مرونة.'],
      ['المتقاعدون والدخل السلبي', 'المتقاعد أو صاحب الدخل السلبي يجب أن يقارن المعاش، الإيجارات، المحافظ المالية، التأمين الصحي، تكلفة السكن، المستشفيات، سهولة الوصول، الميراث، البنوك والحياة اليومية. إيطاليا قد تناسب من يريد المتوسط الأوروبي. تركيا قد تناسب من ينظر إلى إسطنبول، أنطاليا، بودروم، إزمير أو ألانيا.'],
      ['البنوك والامتثال', 'مهما كانت الوجهة، البنوك أساسية. قد تحتاج إلى شرح مصدر الأموال، الدخل الأجنبي، الأرباح، المكاسب، الشركات، الثروة العائلية، الإقامة الضريبية، إثبات الحياة الفعلية، المستندات الضريبية، العقود والتصريحات. لا يجب التعامل مع تركيا أو إيطاليا كعنوان ضريبي بسيط دون ملف واضح.'],
      ['العقار: إيطاليا أم تركيا', 'العقار يؤثر غالباً على القرار. في إيطاليا قد تكون ميلانو، روما، فلورنسا، توسكانا، بحيرة كومو، سردينيا أو صقلية. في تركيا قد تكون إسطنبول، بودروم، أنطاليا، إزمير، ألانيا، فتحية أو مرسين. يجب مقارنة الميزانية، الضرائب المحلية، الصحة، إعادة البيع، المطار، الأسرة والميراث.'],
      ['أخطاء يجب تجنبها', 'لا تقارن فقط مبلغ الضريبة. لا تنتقل دون التحقق من الإقامة الضريبية الحقيقية. لا تفترض أن non-dom أو إعفاء الدخل الأجنبي يحل تلقائياً الأرباح والمكاسب والعقار والميراث. لا تتجاهل البنوك ومصدر الأموال. لا تقلل من تكلفة السكن والصحة والانتقال العائلي.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامي الضريبي أو المحاسب أو مستشار الثروة. دوره هو المساعدة في مقارنة تركيا بوجهات أخرى، منها إيطاليا، وتنظيم الجزء التركي إذا كان مناسباً: تحليل الملف، الدخل الأجنبي، المستشارون، البنوك، التأمين، العقار، العائلة، الميراث والشركاء المحليون.'],
    ],
    faq: [['هل تركيا أفضل من إيطاليا؟', 'قد تكون كذلك حسب الملف. إيطاليا لديها نظام معروف لكنه مكلف. تركيا أعلنت مشروعاً قد يكون جذاباً، لكن يجب انتظار القواعد النهائية وتحليل الحياة الفعلية.'], ['هل يجب اختيار البلد بسبب الضرائب فقط؟', 'لا. يجب مقارنة العائلة، البنوك، الصحة، العقار، الميراث، تكلفة الحياة، السفر، الالتزامات ونمط الحياة.'], ['هل نظام non-dom يحل كل الدخل الأجنبي؟', 'لا. الأرباح، المكاسب، المعاش، دخل العقار والشركات يجب تحليلها بشكل منفصل.'], ['هل يمكن أن تكون تركيا بديلاً لإيطاليا؟', 'نعم لبعض رواد الأعمال والعائلات والمستثمرين إذا كان بالإمكان تنظيم الدخل والبنوك والإقامة ونمط الحياة بشكل منطقي في تركيا.'], ['هل يمكن لـ Bosphoras مقارنة تركيا وإيطاليا؟', 'نعم. يمكن لـ Bosphoras تنسيق مراجعة خاصة مع المختصين لفهم ما إذا كانت تركيا مناسبة مقارنة بإيطاليا والبدائل الأخرى.']],
  },
};

export function getTurkeyVsItalyNonDomMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function TurkeyVsItalyNonDomClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
