import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, CheckCircle2, FileText, Landmark, ShieldCheck } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import type { Locale } from '@/lib/i18n';

const paths: Record<Locale, string> = {
  fr: '/turquie-vs-chypre-fiscalite-non-dom-revenus-etrangers',
  en: '/en/turkey-vs-cyprus-non-dom-tax-residence',
  ru: '/ru/turtsiya-vs-kipr-non-dom-nalogi-rezidentsiya',
  ar: '/ar/turkey-vs-cyprus-non-dom-tax-residence',
};

const assessmentHref: Record<Locale, string> = {
  fr: '/diagnostic-prive',
  en: '/en/private-assessment',
  ru: '/ru/chastnaya-konsultatsiya',
  ar: '/ar/تقييم-خاص',
};

type PageContent = { title:string; metaTitle:string; description:string; eyebrow:string; hero:string; cta:string; asideTitle:string; finalTitle:string; finalText:string; faqTitle:string; checklist:string[]; sections:Array<[string,string]>; faq:Array<[string,string]> };

const content: Record<Locale, PageContent> = {
  fr: {
    title: 'Turquie vs Chypre : fiscalité, régime non-dom, revenus étrangers et résidence',
    metaTitle: 'Turquie vs Chypre : fiscalité, non-dom et revenus étrangers',
    description: 'Turquie vs Chypre : comparaison pour entrepreneurs, investisseurs et familles patrimoniales. Régime non-dom chypriote, fiscalité, revenus étrangers, dividendes, résidence fiscale, banque, immobilier et installation.',
    eyebrow: 'Comparaison fiscale · Turquie vs Chypre',
    hero: 'Chypre est l’une des destinations les plus étudiées par les entrepreneurs, investisseurs, rentiers et familles patrimoniales qui cherchent un cadre fiscal européen favorable. La Turquie entre dans la comparaison avec une autre logique : Istanbul, Bodrum, Antalya, coût de vie plus flexible, médecine privée, connectivité aérienne et projet d’exonération de long terme sur certains revenus étrangers.',
    cta: 'Demander une analyse privée',
    asideTitle: 'Avant de comparer Turquie et Chypre',
    finalTitle: 'Le meilleur choix dépend de vos revenus, de vos banques et de votre vie réelle',
    finalText: 'Avant de choisir une destination, Bosphoras peut organiser une analyse privée de votre situation : fiscalité, société, banque, immobilier, assurance santé, famille, succession et installation en Turquie.',
    faqTitle: 'Questions fréquentes',
    checklist: ['Dividendes et revenus passifs', 'Plus-values et portefeuille financier', 'Société étrangère ou holding', 'Résidence fiscale réelle', 'Banque et origine des fonds', 'Immobilier et vie familiale', 'Santé et assurance', 'Sortie fiscale du pays d’origine'],
    sections: [
      ['Chypre : un régime non-dom connu et européen', 'Chypre dispose d’un régime non-dom qui attire depuis plusieurs années des entrepreneurs, investisseurs et profils à revenus passifs. Le pays offre un cadre européen, une résidence fiscale possible sous conditions, un système juridique et bancaire international, une forte présence de l’anglais, une proximité avec l’Europe et le Moyen-Orient, et un écosystème de services aux entreprises. Mais le régime doit être analysé avec votre situation réelle, vos revenus, votre société, vos banques et votre pays de départ.'],
      ['Pourquoi Chypre attire les entrepreneurs et investisseurs', 'Chypre est souvent étudiée par les personnes qui ont des dividendes étrangers, revenus de société, portefeuille financier, plus-values sur titres, intérêts, consulting, business en ligne, holding personnelle, société internationale ou revenus locatifs. Le régime non-dom peut être très compétitif pour certains revenus passifs, mais il ne faut jamais supposer qu’il règle automatiquement tous les revenus et toutes les obligations.'],
      ['Turquie : une alternative plus large pour certains profils', 'La Turquie peut intéresser les personnes qui recherchent Istanbul comme base business et familiale, Bodrum pour le luxe, Antalya ou Alanya pour la retraite, Izmir pour une vie méditerranéenne, un coût de vie plus flexible, un immobilier plus varié, une médecine privée développée et une proximité avec l’Europe, le Moyen-Orient, le Caucase et l’Asie centrale. Si le projet turc sur les revenus étrangers est confirmé, elle pourrait devenir une alternative sérieuse à Chypre pour certains profils.'],
      ['Fiscalité : comparer les revenus un par un', 'Il ne faut pas comparer Chypre et la Turquie avec un seul chiffre. Il faut regarder séparément dividendes, plus-values, intérêts, revenus locatifs, pension, revenus professionnels, consulting, e-commerce, SaaS, société étrangère, holding, succession et immobilier. Chypre peut être très compétitive pour certains revenus passifs et profils non-dom. La Turquie peut devenir compétitive si votre profil entre dans le régime annoncé et si votre installation réelle est cohérente.'],
      ['Pour un entrepreneur ou actionnaire', 'Si vous êtes entrepreneur, dirigeant ou actionnaire, vous devez analyser où se trouve votre société, où elle est réellement dirigée, où sont les clients, où les contrats sont signés, où la banque accepte votre structure, où les dividendes sont distribués, où les plus-values peuvent apparaître et où vous vivez réellement. Chypre peut être pertinente pour certains groupes internationaux ou holdings. La Turquie peut être pertinente pour des activités liées à l’Europe, la Turquie, le Kazakhstan, l’Asie centrale, le Caucase, le Moyen-Orient, l’import-export, l’industrie, les services B2B, l’immobilier, la santé, le tourisme ou la logistique.'],
      ['Banque, conformité et origine des fonds', 'Chypre et la Turquie ont un point commun : la banque demandera un dossier clair. Il faut pouvoir expliquer origine des fonds, revenus étrangers, dividendes, plus-values, sociétés, comptes existants, contrats, déclarations fiscales, preuve de résidence, activité réelle, bénéficiaires effectifs et structure patrimoniale. Un dossier bancaire mal préparé peut bloquer l’ouverture de compte, les transferts, la société, l’achat immobilier ou les investissements.'],
      ['Immobilier : Chypre ou Turquie ?', 'À Chypre, les zones recherchées peuvent être Limassol, Nicosie, Larnaca, Paphos ou Ayia Napa. En Turquie, les zones pertinentes peuvent être Istanbul, Bodrum, Antalya, Izmir, Alanya, Fethiye ou Mersin. Le choix dépend de votre objectif : résidence principale, résidence secondaire, investissement locatif, retraite, famille, revente, accès aux soins, succession et proximité de l’aéroport.'],
      ['Famille, santé et qualité de vie', 'La fiscalité ne suffit pas. Une famille doit comparer écoles, assurance santé, hôpitaux, langue, communauté internationale, coût du logement, vie quotidienne, sécurité, mobilité, statut du conjoint et succession. Chypre peut rassurer par son cadre européen et anglophone. La Turquie peut séduire par son dynamisme, sa diversité, ses grandes villes, sa médecine privée, sa vie familiale et ses zones balnéaires.'],
      ['Pays d’origine : ne pas oublier la sortie fiscale', 'Que vous choisissiez Chypre ou la Turquie, votre pays d’origine peut continuer à vous considérer résident fiscal si votre vie réelle reste principalement là-bas : foyer disponible, famille, société dirigée localement, revenus principaux, actifs principaux ou présence importante. Une installation internationale doit être cohérente dans les deux sens : sortie claire du pays d’origine et installation réelle dans le nouveau pays.'],
      ['Les erreurs à éviter', 'La première erreur est de choisir Chypre uniquement parce que le régime non-dom est connu. La deuxième est de choisir la Turquie uniquement parce qu’un régime fiscal est annoncé. La troisième est de comparer seulement les dividendes sans regarder plus-values, revenus professionnels, pensions, immobilier et succession. La quatrième est de négliger la banque et l’origine des fonds. La cinquième est de créer une société sans substance réelle.'],
      ['Comment Bosphoras peut vous accompagner', 'Bosphoras ne remplace pas un avocat fiscaliste, un expert-comptable ou un conseiller patrimonial. Notre rôle est de vous aider à comparer sérieusement la Turquie avec des destinations comme Chypre, puis à organiser la partie Turquie si cette option est cohérente : profil, revenus étrangers, dividendes, plus-values, fiscalistes, banque, assurance santé, immobilier, famille, succession et partenaires locaux.'],
    ],
    faq: [['Chypre est-elle plus avantageuse fiscalement que la Turquie ?', 'Potentiellement, pour certains profils non-dom avec dividendes, intérêts ou revenus passifs. Mais la Turquie pourrait devenir compétitive si le régime annoncé est confirmé.'], ['La résidence fiscale à Chypre peut-elle être obtenue en 60 jours ?', 'La règle des 60 jours existe sous conditions strictes : présence minimale, absence de résidence fiscale ailleurs selon les règles applicables, liens économiques et logement permanent à Chypre.'], ['Le régime non-dom chypriote exonère-t-il tous les revenus ?', 'Non. Chaque revenu doit être analysé séparément : dividendes, intérêts, plus-values, salaires, pensions, immobilier et revenus professionnels.'], ['La Turquie peut-elle devenir une alternative à Chypre ?', 'Oui, pour certains profils recherchant une base plus large : Istanbul, Bodrum, Antalya, accès à l’Asie centrale, vie familiale, immobilier varié et médecine privée.'], ['Faut-il choisir uniquement selon la fiscalité ?', 'Non. Il faut comparer banque, santé, immobilier, famille, coût de vie, résidence réelle, société, succession, mobilité et pays d’origine.'], ['Bosphoras peut-il comparer Turquie et Chypre ?', 'Oui. Bosphoras peut coordonner une analyse privée pour comprendre si la Turquie est cohérente par rapport à Chypre et aux autres alternatives.']],
  },
  en: {
    title: 'Turkey vs Cyprus Non-Dom: tax residence, dividends, banking and relocation',
    metaTitle: 'Turkey vs Cyprus Non-Dom: Tax Residence Guide',
    description: 'Turkey vs Cyprus non-dom for UK, US and international clients: tax residence, dividends, capital gains, foreign income, company setup, banking, property and relocation.',
    eyebrow: 'Turkey vs Cyprus · Non-dom comparison',
    hero: 'Cyprus is a direct competitor for entrepreneurs, investors and international families looking at a European non-dom regime. Turkey offers a different proposition: Istanbul, Bodrum, Antalya, flexible living costs, private healthcare, regional access and a potential foreign-income regime for qualifying new residents.',
    cta: 'Request a private assessment',
    asideTitle: 'Before comparing Turkey and Cyprus',
    finalTitle: 'The right base must fit your income, company, banking and family reality',
    finalText: 'Before choosing a destination, Bosphoras can organize a private review of your situation: tax, company, banking, property, healthcare, family, estate planning and relocation to Turkey.',
    faqTitle: 'Frequently asked questions',
    checklist: ['Dividends and passive income', 'Capital gains and portfolio income', 'Company or holding structure', 'Real tax residence', 'Banking and source of funds', 'Property and family life', 'Healthcare insurance', 'Exit position from former country'],
    sections: [
      ['Cyprus: an established European non-dom option', 'Cyprus is widely considered by entrepreneurs, investors and private clients because it offers an EU framework, an international legal and banking environment, English-speaking services, access to Europe and the Middle East and a known non-dom regime. For some profiles, Cyprus can be particularly attractive for dividends, interest income, holding structures and international business.'],
      ['Why Cyprus attracts international entrepreneurs', 'Cyprus is often reviewed by people with foreign dividends, company income, investment portfolios, capital gains, interest income, consulting activity, online business, personal holding structures, international companies or rental income. The non-dom regime may be efficient for certain passive income, but it must be matched with real residence, banking, substance and former-country rules.'],
      ['Turkey: a broader base for some profiles', 'Turkey may appeal to people seeking Istanbul as a business and family base, Bodrum for luxury, Antalya or Alanya for seaside life, Izmir for a Mediterranean lifestyle, flexible cost of living, varied property, developed private healthcare and proximity to Europe, the Middle East, the Caucasus and Central Asia. If the announced Turkish regime is confirmed, it may become a serious alternative for some clients comparing Cyprus, Dubai, Portugal, Italy or Malta.'],
      ['Compare income categories separately', 'Turkey and Cyprus should not be compared with one headline number. Dividends, capital gains, interest, rental income, pension, professional income, consulting, e-commerce, SaaS, foreign companies, holdings, inheritance and property may all be treated differently. Cyprus may be very competitive for certain passive-income profiles. Turkey may become attractive for qualifying new residents if final rules allow it and the relocation is coherent.'],
      ['Entrepreneurs and shareholders', 'Business owners should review where the company is incorporated, where it is effectively managed, where clients are located, where contracts are signed, where banks accept the structure, where dividends are distributed and where capital gains may arise. Cyprus may suit some holding or service structures. Turkey may suit activities linked to Europe, Turkey, Kazakhstan, Central Asia, the Middle East, import-export, B2B services, property, healthcare, tourism or logistics.'],
      ['Banking and compliance', 'Cyprus and Turkey both require a clear banking file. Banks may ask for source of funds, foreign income, dividends, gains, companies, existing accounts, contracts, tax filings, proof of residence, real activity, beneficial owners and wealth structure. A weak file can block account opening, transfers, company activity, property acquisition or investments.'],
      ['Property and lifestyle', 'Cyprus may mean Limassol, Nicosia, Larnaca, Paphos or Ayia Napa. Turkey may mean Istanbul, Bodrum, Antalya, Izmir, Alanya, Fethiye or Mersin. The right property decision depends on primary residence, second home, rental investment, retirement, family life, resale, healthcare access, estate planning and airport connectivity.'],
      ['Family, healthcare and daily life', 'Tax is only one part of relocation. Families should compare schools, healthcare insurance, hospitals, language, international community, housing cost, daily life, safety, mobility, spouse status and estate planning. Cyprus can reassure through its EU and English-speaking environment. Turkey may appeal through dynamic cities, private healthcare, family life, coastal regions and regional connectivity.'],
      ['Former country exit position', 'Moving to Cyprus or Turkey does not automatically end your former country’s tax interest. If home, family, company management, main income, major assets or significant time remain there, the former country may still treat you as resident or impose reporting obligations. Exit planning and real relocation should be coordinated.'],
      ['Mistakes to avoid', 'Do not choose Cyprus only because the non-dom regime is known. Do not choose Turkey only because a tax regime has been announced. Do not compare dividends only while ignoring gains, professional income, pension, property and inheritance. Do not ignore banking, source of funds, company substance and former-country exit.'],
      ['How Bosphoras can support you', 'Bosphoras does not replace tax lawyers, accountants or wealth advisors. Its role is to help compare Turkey with destinations such as Cyprus and organize the Turkey side if suitable: profile review, foreign income mapping, dividends and gains, advisors, banking, healthcare, property, family relocation, estate planning and local partners.'],
    ],
    faq: [['Is Cyprus more tax-efficient than Turkey?', 'Potentially for some non-dom profiles with dividends, interest or passive income. Turkey may become competitive for some new residents if the announced regime is confirmed.'], ['Can Cyprus tax residence be obtained with 60 days?', 'The 60-day rule exists under conditions, including minimum presence, no tax residence elsewhere under applicable rules, economic ties and permanent accommodation in Cyprus.'], ['Does Cyprus non-dom exempt all income?', 'No. Dividends, interest, gains, employment income, pensions, property income and professional income should be reviewed separately.'], ['Can Turkey be an alternative to Cyprus?', 'Yes, for some entrepreneurs, families and investors seeking Istanbul, Bodrum, Antalya, Central Asia access, private healthcare, varied property and family lifestyle.'], ['Should the choice be only tax-based?', 'No. Banking, healthcare, property, family, cost of living, real residence, company substance, estate planning, mobility and former-country rules matter.'], ['Can Bosphoras compare Turkey and Cyprus?', 'Yes. Bosphoras can coordinate a private review to assess whether Turkey is coherent compared with Cyprus and other alternatives.']],
  },
  ru: {
    title: 'Турция vs Кипр non-dom: налоги, резиденция, дивиденды и банки',
    metaTitle: 'Турция vs Кипр non-dom: налоги и резиденция',
    description: 'Турция vs Кипр для русскоязычных инвесторов из России, Казахстана и СНГ: non-dom, дивиденды, иностранные доходы, банки, недвижимость, семья и переезд.',
    eyebrow: 'Турция vs Кипр · Non-dom и резиденция',
    hero: 'Кипр — один из прямых конкурентов Турции для предпринимателей, инвесторов, рантье и семей, которые смотрят на non-dom, дивиденды и международные структуры. Турция предлагает другой формат: Стамбул, Бодрум, Анталья, связь с Европой, Кавказом и Центральной Азией, медицина и семейная жизнь.',
    cta: 'Запросить частный анализ',
    asideTitle: 'Перед сравнением Турции и Кипра',
    finalTitle: 'Выбор должен подходить доходам, банкам, семье и реальной жизни',
    finalText: 'До выбора страны Bosphoras может организовать частный анализ вашей ситуации: налоги, компании, банки, недвижимость, медицина, семья, наследство и переезд в Турцию.',
    faqTitle: 'Частые вопросы',
    checklist: ['Дивиденды и passive income', 'Прирост капитала и портфель', 'Компания или holding', 'Реальная налоговая резиденция', 'Банк и происхождение средств', 'Недвижимость и семья', 'Медицина и страховка', 'Выход из прежней страны'],
    sections: [
      ['Кипр: известный европейский non-dom', 'Кипр часто рассматривают предприниматели и инвесторы благодаря европейскому формату, английскому языку, международным услугам, банкам, proximity к Европе и Ближнему Востоку и известному режиму non-dom. Он может быть интересен для дивидендов, процентов, холдингов и международных структур, но режим должен соответствовать реальной резиденции, банкам, substance и правилам прежней страны.'],
      ['Почему Кипр привлекает инвесторов', 'Кипр смотрят клиенты с иностранными дивидендами, доходами компаний, портфелем, приростом капитала, процентами, consulting, онлайн-бизнесом, personal holding, международной компанией или арендными доходами. Но нельзя считать, что non-dom автоматически решает все вопросы. Каждый вид дохода, банк и структура должны быть проверены отдельно.'],
      ['Турция: более широкая база для некоторых профилей', 'Турция может быть интересна тем, кто ищет Стамбул как бизнес- и семейную базу, Бодрум для luxury, Анталью или Аланью для моря, Измир для средиземноморской жизни, гибкую стоимость, разную недвижимость, частную медицину и доступ к Европе, Ближнему Востоку, Кавказу, Казахстану, Узбекистану, Кыргызстану и Центральной Азии.'],
      ['Сравнивать нужно каждый доход отдельно', 'Нельзя сравнивать Кипр и Турцию одной цифрой. Нужно отдельно смотреть дивиденды, gains, проценты, аренду, пенсии, профессиональные доходы, consulting, e-commerce, SaaS, иностранные компании, holding, наследство и недвижимость. Кипр может быть очень конкурентным для некоторых passive-income профилей. Турция может стать конкурентной, если финальные правила подтвердят режим и установка будет реальной.'],
      ['Предприниматели и акционеры', 'Владельцам компаний нужно понять, где зарегистрирована компания, где фактически управляется, где клиенты, где подписываются договоры, какой банк принимает структуру, где распределяются дивиденды, где появляются gains и где вы реально живете. Кипр может подходить holdings и services. Турция может подходить бизнесам, связанным с Европой, Турцией, Казахстаном, Центральной Азией, Ближним Востоком, import-export, B2B, недвижимостью, медициной, туризмом или логистикой.'],
      ['Банки и compliance', 'Кипр и Турция потребуют понятный банковский файл: происхождение средств, иностранные доходы, дивиденды, gains, компании, счета, договоры, декларации, доказательство резиденции, реальная деятельность, бенефициары и структура капитала. Слабый файл может остановить счет, переводы, компанию, недвижимость или инвестиции.'],
      ['Недвижимость и lifestyle', 'На Кипре это могут быть Limassol, Nicosia, Larnaca, Paphos или Ayia Napa. В Турции — Стамбул, Бодрум, Анталья, Измир, Аланья, Фетхие или Мерсин. Выбор зависит от цели: основное жилье, второй дом, аренда, пенсия, семья, перепродажа, медицина, наследство и аэропорт.'],
      ['Семья, медицина и ежедневная жизнь', 'Налоги — только часть выбора. Семье нужно сравнить школы, страховку, больницы, язык, международное окружение, стоимость жилья, безопасность, перелеты, статус супруга и наследство. Кипр дает европейскую и англоязычную среду. Турция может дать динамичные города, медицину, семейную жизнь, море и связь с несколькими регионами.'],
      ['Прежняя страна: выход важен', 'Переезд на Кипр или в Турцию не означает автоматический выход из налоговой системы прежней страны. Если дом, семья, управление компанией, основные доходы, активы или время остаются там, прежняя страна может продолжать считать вас резидентом или требовать отчетность.'],
      ['Ошибки, которых нужно избегать', 'Не выбирайте Кипр только из-за известного non-dom. Не выбирайте Турцию только из-за объявленного режима. Не сравнивайте только дивиденды, забывая gains, профессиональные доходы, пенсии, недвижимость и наследство. Не игнорируйте банк, источник средств, substance компании и выход из прежней страны.'],
      ['Как Bosphoras может помочь', 'Bosphoras не заменяет налоговых юристов, бухгалтеров или wealth advisors. Его роль — помочь сравнить Турцию с Кипром и другими вариантами, а затем организовать турецкую часть, если она подходит: профиль, доходы, дивиденды, gains, консультанты, банк, медицина, недвижимость, семья, наследство и местные партнеры.'],
    ],
    faq: [['Кипр выгоднее Турции?', 'Потенциально для некоторых non-dom профилей с дивидендами, процентами или passive income. Турция может стать конкурентной, если объявленный режим подтвердят.'], ['Можно ли стать налоговым резидентом Кипра за 60 дней?', 'Правило 60 дней существует при условиях: минимальное пребывание, отсутствие резиденции в другой стране по применимым правилам, экономические связи и постоянное жилье на Кипре.'], ['Кипрский non-dom освобождает все доходы?', 'Нет. Дивиденды, проценты, gains, зарплата, пенсии, недвижимость и профессиональные доходы нужно анализировать отдельно.'], ['Может ли Турция быть альтернативой Кипру?', 'Да, для некоторых предпринимателей, семей и инвесторов, которым важны Стамбул, Бодрум, Анталья, доступ к Центральной Азии, медицина, недвижимость и семейная жизнь.'], ['Выбирать нужно только по налогам?', 'Нет. Банки, медицина, недвижимость, семья, стоимость жизни, реальная резиденция, substance, наследство, перелеты и прежняя страна тоже важны.'], ['Bosphoras может сравнить Турцию и Кипр?', 'Да. Bosphoras может координировать частный анализ, чтобы понять, подходит ли Турция по сравнению с Кипром и другими вариантами.']],
  },
  ar: {
    title: 'تركيا vs قبرص non-dom: الضرائب، الإقامة، الأرباح والبنوك',
    metaTitle: 'تركيا vs قبرص non-dom: الضرائب والإقامة',
    description: 'تركيا vs قبرص للمستثمرين العرب والخليج: non-dom، الدخل الأجنبي، الأرباح، البنوك، العقار، العائلة، الصحة والإقامة.',
    eyebrow: 'تركيا vs قبرص · Non-dom والإقامة',
    hero: 'قبرص من الوجهات التي يدرسها المستثمرون ورواد الأعمال والعائلات الدولية بسبب نظام non-dom الأوروبي. تركيا تدخل المقارنة بمنطق مختلف: إسطنبول، بودروم، أنطاليا، عقارات متنوعة، طب خاص، حياة عائلية وقرب من أوروبا والشرق الأوسط وآسيا الوسطى.',
    cta: 'طلب تحليل خاص',
    asideTitle: 'قبل مقارنة تركيا وقبرص',
    finalTitle: 'الاختيار الصحيح يجب أن يناسب الدخل والبنوك والعائلة والحياة الفعلية',
    finalText: 'قبل اختيار الوجهة، يمكن لـ Bosphoras تنظيم مراجعة خاصة لوضعك: الضرائب، الشركات، البنوك، العقار، التأمين الصحي، العائلة، الميراث والانتقال إلى تركيا.',
    faqTitle: 'الأسئلة الشائعة',
    checklist: ['الأرباح والدخل السلبي', 'المكاسب والمحفظة الاستثمارية', 'الشركة أو holding', 'الإقامة الضريبية الحقيقية', 'البنوك ومصدر الأموال', 'العقار والعائلة', 'الصحة والتأمين', 'الخروج من البلد السابق'],
    sections: [
      ['قبرص: خيار non-dom أوروبي معروف', 'قبرص تجذب المستثمرين ورواد الأعمال بسبب الإطار الأوروبي، اللغة الإنجليزية، الخدمات الدولية، البنوك، القرب من أوروبا والشرق الأوسط ونظام non-dom المعروف. قد تكون مناسبة لبعض الأرباح والفوائد والهياكل الدولية، لكن يجب أن يكون ذلك منسجماً مع الإقامة الفعلية، البنك، substance وقواعد البلد السابق.'],
      ['لماذا تجذب قبرص المستثمرين', 'تدرس قبرص عادة من قبل من لديهم أرباح من شركات أجنبية، محافظ مالية، مكاسب رأسمالية، فوائد، consulting، أعمال رقمية، holding شخصي، شركات دولية أو إيجارات. لكن non-dom لا يحل كل شيء تلقائياً. يجب تحليل كل دخل وكل بنك وكل هيكل بشكل منفصل.'],
      ['تركيا: قاعدة أوسع لبعض الملفات', 'تركيا قد تناسب من يبحث عن إسطنبول كقاعدة أعمال وعائلة، بودروم للفخامة، أنطاليا أو ألانيا للبحر، إزمير لنمط متوسطي، تكلفة أكثر مرونة، عقارات متنوعة، طب خاص متطور وقرب من أوروبا، الشرق الأوسط، القوقاز وآسيا الوسطى. إذا تم تأكيد النظام التركي للدخل الأجنبي، قد تصبح بديلاً جدياً لقبرص لبعض المستثمرين.'],
      ['يجب مقارنة كل نوع دخل على حدة', 'لا يجب مقارنة قبرص وتركيا برقم واحد. يجب النظر إلى الأرباح، المكاسب، الفوائد، الإيجارات، المعاش، الدخل المهني، consulting، e-commerce، SaaS، الشركات الأجنبية، holding، الميراث والعقار. قبرص قد تكون قوية لبعض الدخل السلبي. تركيا قد تصبح جذابة إذا كان الملف يدخل ضمن النظام النهائي وكانت الإقامة حقيقية.'],
      ['رواد الأعمال والمساهمون', 'يجب تحليل أين الشركة مسجلة، أين تدار فعلياً، أين العملاء، أين العقود، أي بنك يقبل الهيكل، أين توزع الأرباح، أين تظهر المكاسب وأين تعيش فعلياً. قبرص قد تناسب بعض الهياكل الدولية. تركيا قد تناسب أنشطة مرتبطة بأوروبا، تركيا، الخليج، آسيا الوسطى، الاستيراد والتصدير، B2B، العقار، الصحة، السياحة أو اللوجستيك.'],
      ['البنوك والامتثال', 'قبرص وتركيا تتطلبان ملفاً بنكياً واضحاً: مصدر الأموال، الدخل الأجنبي، الأرباح، المكاسب، الشركات، الحسابات، العقود، التصريحات، إثبات الإقامة، النشاط الحقيقي، المستفيدون الفعليون وهيكل الثروة. ملف ضعيف قد يعرقل الحسابات والتحويلات والشركة والعقار.'],
      ['العقار ونمط الحياة', 'في قبرص يمكن النظر إلى ليماسول، نيقوسيا، لارنكا، بافوس أو أيا نابا. في تركيا يمكن النظر إلى إسطنبول، بودروم، أنطاليا، إزمير، ألانيا، فتحية أو مرسين. الاختيار يعتمد على السكن الرئيسي، المنزل الثاني، الاستثمار الإيجاري، التقاعد، العائلة، إعادة البيع، الصحة والمطار.'],
      ['العائلة والصحة والحياة اليومية', 'الضرائب ليست كل شيء. يجب مقارنة المدارس، التأمين الصحي، المستشفيات، اللغة، المجتمع الدولي، تكلفة السكن، الأمان، السفر، وضع الزوج أو الزوجة والميراث. قبرص توفر إطاراً أوروبياً وإنجليزياً. تركيا قد توفر مدناً ديناميكية، طباً خاصاً، حياة عائلية وسواحل متنوعة.'],
      ['البلد السابق: الخروج مهم', 'الانتقال إلى قبرص أو تركيا لا يعني تلقائياً الخروج من نظام البلد السابق. إذا بقي البيت، العائلة، إدارة الشركة، الدخل الرئيسي، الأصول أو الوقت هناك، قد يستمر البلد السابق في اعتبارك مقيماً أو يطلب التزامات تصريحية.'],
      ['أخطاء يجب تجنبها', 'لا تختر قبرص فقط لأن non-dom معروف. لا تختر تركيا فقط لأن نظاماً تم الإعلان عنه. لا تقارن الأرباح فقط وتنسى المكاسب، الدخل المهني، المعاش، العقار والميراث. لا تهمل البنك ومصدر الأموال وsubstance والخروج من البلد السابق.'],
      ['كيف يمكن أن يساعد Bosphoras', 'لا يحل Bosphoras محل المحامي الضريبي أو المحاسب أو مستشار الثروة. دوره هو مساعدتك في مقارنة تركيا بقبرص ووجهات أخرى، ثم تنظيم الجزء التركي إذا كان مناسباً: الملف، الدخل، الأرباح، المكاسب، المستشارون، البنوك، الصحة، العقار، العائلة، الميراث والشركاء المحليون.'],
    ],
    faq: [['هل قبرص أفضل ضريبياً من تركيا؟', 'قد تكون كذلك لبعض ملفات non-dom مع أرباح أو فوائد أو دخل سلبي. تركيا قد تصبح منافسة إذا تم تأكيد النظام المعلن.'], ['هل يمكن الحصول على إقامة ضريبية في قبرص خلال 60 يوماً؟', 'توجد قاعدة 60 يوماً بشروط: حضور أدنى، عدم وجود إقامة ضريبية في بلد آخر حسب القواعد، روابط اقتصادية وسكن دائم في قبرص.'], ['هل يعفي non-dom في قبرص كل الدخل؟', 'لا. الأرباح، الفوائد، المكاسب، الرواتب، المعاشات، العقار والدخل المهني يجب تحليلها بشكل منفصل.'], ['هل يمكن أن تكون تركيا بديلاً لقبرص؟', 'نعم لبعض رواد الأعمال والعائلات والمستثمرين الذين يبحثون عن إسطنبول، بودروم، أنطاليا، الطب الخاص، العقار المتنوع والحياة العائلية.'], ['هل يجب الاختيار حسب الضرائب فقط؟', 'لا. البنوك، الصحة، العقار، العائلة، تكلفة الحياة، الإقامة الحقيقية، الشركة، الميراث والسفر مهمة أيضاً.'], ['هل يمكن لـ Bosphoras مقارنة تركيا وقبرص؟', 'نعم. يمكن لـ Bosphoras تنسيق مراجعة خاصة لمعرفة ما إذا كانت تركيا مناسبة مقارنة بقبرص والبدائل الأخرى.']],
  },
};

export function getTurkeyVsCyprusNonDomMetadata(locale: Locale): Metadata {
  const c = content[locale];
  const canonical = `https://bosphoras.com${paths[locale]}`;
  return { title: `${c.metaTitle} | Bosphoras`, description: c.description, alternates: { canonical, languages: { fr: `https://bosphoras.com${paths.fr}`, en: `https://bosphoras.com${paths.en}`, ru: `https://bosphoras.com${paths.ru}`, ar: `https://bosphoras.com${paths.ar}`, 'x-default': `https://bosphoras.com${paths.fr}` } }, openGraph: { title: c.title, description: c.description, url: canonical, siteName: 'Bosphoras', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: c.title }] }, twitter: { card: 'summary_large_image', title: c.title, description: c.description, images: ['/images/og-default.jpg'] } };
}

export function TurkeyVsCyprusNonDomClientPage({ locale }: { locale: Locale }) {
  const c = content[locale];
  return (
    <>
      <StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: c.title, description: c.description, inLanguage: locale, datePublished: '2026-05-11', dateModified: '2026-05-11', author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: `https://bosphoras.com${paths[locale]}` }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: c.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} />
      <Header locale={locale} currentPath={paths[locale]} />
      <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="bg-[#f8f1e7] text-[#101827]">
        <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1400px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">{c.eyebrow}</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-[1.05] tracking-[-0.045em] md:text-7xl">{c.title}</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">{c.hero}</p><Link href={assessmentHref[locale]} className="mt-10 inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1400px] gap-8 lg:grid-cols-[0.75fr_1.25fr]"><aside className="h-fit border border-[#d8c7a1] bg-[#fffaf0] p-8 lg:sticky lg:top-28"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">{c.asideTitle}</h2><ul className="mt-6 space-y-3 text-sm leading-7 text-[#3e4857]">{c.checklist.map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#8a6728]" />{item}</li>)}</ul></aside><div className="space-y-5">{c.sections.map(([sectionTitle, text], index) => <article key={sectionTitle} className="border border-[#d8c7a1] bg-white p-7 md:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#8a6728]">{String(index + 1).padStart(2, '0')}</p><h2 className="mt-4 font-serif text-3xl tracking-[-0.025em] text-[#121826] md:text-4xl">{sectionTitle}</h2><p className="mt-5 text-base leading-8 text-[#3e4857]">{text}</p></article>)}</div></div></section>
        <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em] md:text-6xl">{c.finalTitle}</h2><p className="mt-6 text-lg leading-9 text-[#3e4857]">{c.finalText}</p><Link href={assessmentHref[locale]} className="mt-8 inline-flex items-center justify-center gap-3 bg-[#121826] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-white">{c.cta}<ArrowRight size={16} /></Link></div></section>
        <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><FileText className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.03em]">{c.faqTitle}</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{c.faq.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
