import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, Building2, CheckCircle2, Factory, ShieldCheck, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';

const url = 'https://bosphoras.com/en/turkey-manufacturing-corporate-tax-12-5';
const title = 'Manufacturing in Turkey: 12.5% Corporate Tax, Production and Investment | Bosphoras';
const description = 'Bosphoras guide to manufacturing and industrial investment in Turkey after Law No. 7582: 12.5% corporate tax to review for certain production income, factory setup, export, organized industrial zones, company, permits, tax, SGK, energy, logistics and substance.';
const updatedAt = '2026-06-05';

const cards = [
  ['12.5% framework to review', 'Turkey’s 2026 tax reform increases the interest of Turkey for certain manufacturers. The reduced rate must be verified according to activity, income and implementation rules.'],
  ['Real manufacturing', 'The benefit should not be presented as automatic: real production, factory, equipment, staff, accounting and industrial substance must be demonstrated.'],
  ['Export and regional markets', 'Turkey may serve as an industrial base between Europe, the Gulf, Central Asia, North Africa and emerging markets.'],
  ['Full project scope', 'An industrial file involves company formation, land, organized industrial zone, permits, energy, customs, SGK, tax, banking, insurance and logistics.'],
];

const examples = [
  ['Textile or apparel factory', 'Production, subcontracting, export, quality control, logistics, certificates, workforce and energy costs.'],
  ['Agri-food and packaging', 'Food processing, packaging, storage, cold chain, standards, export and regional distribution.'],
  ['Machinery, parts and materials', 'Component manufacturing, assembly, maintenance, B2B contracts, customs, transport and certification.'],
  ['Industrial base for foreign investors', 'Company setup, land, industrial zone, recruitment, banking, permits, taxation and operational management.'],
];

const checks = ['real industrial activity performed in Turkey','type of income potentially covered by the reduced rate','industrial zone, land, lease or factory','machines, staff, SGK, energy and insurance','accounting, invoicing, customs and export','lawyer, tax advisor, accountant, bank and permits'];

const faqs = [
  ['Is the 12.5% rate automatic for all manufacturers?', 'No. The activity, income type, real production, company, accounting, implementation rules and exact conditions must be verified.'],
  ['Which sectors may be reviewed?', 'Textile, agri-food, packaging, materials, machinery, spare parts, processing, assembly, equipment and export-oriented production may be reviewed according to the file.'],
  ['Why is Turkey interesting for manufacturing?', 'Turkey combines geography, workforce, supplier network, logistics, customs, industrial zones, export capabilities and proximity to several regional markets.'],
  ['What is Bosphoras’ role?', 'Bosphoras coordinates local contacts: lawyer, tax advisor, accountant, bank, industrial zone, property, recruitment, insurance, transport and operational partners.'],
  ['Which risks should be checked before investing?', 'Permits, land, energy, compliance, environment, SGK, customs, tax, supplier contracts, quality, financing, insurance and local governance.'],
];

export const metadata: Metadata = { title, description, alternates: { canonical: url, languages: { fr: 'https://bosphoras.com/industrie-fabrication-turquie-impot-societe-12-5', en: url, ru: 'https://bosphoras.com/ru/proizvodstvo-turtsiya-nalog-na-pribyl-12-5', ar: 'https://bosphoras.com/ar/turkey-manufacturing-corporate-tax-12-5', 'x-default': 'https://bosphoras.com/industrie-fabrication-turquie-impot-societe-12-5' } }, openGraph: { title, description, url, siteName: 'Bosphoras', locale: 'en_US', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: title }] }, twitter: { card: 'summary_large_image', title, description, images: ['/images/og-default.jpg'] } };

export default function Page() {
  return (
    <><StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: title, description, inLanguage: 'en-US', datePublished: '2026-05-07', dateModified: updatedAt, author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: url, about: ['Turkey manufacturing', 'corporate tax 12.5%', 'Law 7582', 'industry in Turkey', 'foreign investors', 'industrial investment'] }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} /><Header locale="en" currentPath="/en/turkey-manufacturing-corporate-tax-12-5" /><main className="bg-[#f8f1e7] text-[#101827]">
      <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Private guide · Turkey Manufacturing 2026 · Updated on June 5, 2026</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Manufacturing in Turkey: 12.5% corporate tax, production and investment</h1><p className="mt-8 max-w-3xl text-lg leading-9 text-white/80">Turkey is strengthening its industrial attractiveness with a tax framework to be reviewed for certain production income. For a foreign investor, the subject is not limited to the 12.5% rate: real manufacturing, substance, permits, industrial zone, staff, energy, customs, accounting and implementation rules must all be verified.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/en/private-assessment" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Request a private assessment<ArrowRight size={16} /></Link><Link href="/en/services/legal-tax-advisory" className="inline-flex items-center justify-center border border-[#d2a863]/70 px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#d2a863]">View tax support</Link></div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[0.85fr_1.15fr]"><aside className="border border-[#d8c7a1] bg-[#fffaf0] p-8"><Factory className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">Why Turkey attracts manufacturers</h2><p className="mt-5 leading-8 text-[#3e4857]">Turkey combines workforce, industrial know-how, organized industrial zones, supplier networks, ports, roads, customs, proximity to Europe and access to Gulf, Central Asian and North African markets.</p></aside><div><h2 className="font-serif text-4xl tracking-[-0.03em]">The 4 essential points</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{cards.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-6"><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></div></section>
      <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1300px]"><h2 className="font-serif text-4xl tracking-[-0.035em] md:text-6xl">Concrete industrial project examples</h2><p className="mt-6 max-w-4xl text-lg leading-9 text-[#3e4857]">Each industry has its own constraints: land, energy, licenses, storage, quality, customs, standards and human resources. The diagnostic must come before any financial commitment.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examples.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-7"><Building2 className="mb-5 h-6 w-6 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Checklist before investing in a factory</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{checks.map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div><div className="mt-8 border-l-4 border-[#8a6728] bg-white p-8"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><p className="mt-5 text-lg leading-9 text-[#3e4857]">A reduced rate only has value if the industrial project is real, documented, compliant and manageable. Tax should follow the operation, not the other way around.</p></div></div></section>
      <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 md:grid-cols-[1fr_0.8fr] md:items-center"><div><Users className="h-8 w-8 text-[#d2a863]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.035em] md:text-6xl">Structure the investment before buying</h2><p className="mt-6 max-w-2xl text-lg leading-9 text-white/75">Bosphoras coordinates a private review of the industrial project: company, tax, bank, land, industrial zone, permits, insurance, energy, recruitment, transport and local partners.</p></div><Link href="/en/private-assessment" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-5 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Request a private assessment<ArrowRight size={16} /></Link></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1000px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">FAQ</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faqs.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main><Footer locale="en" /></>
  );
}
