import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, Building2, CheckCircle2, Landmark, ShieldCheck, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';

const url = 'https://bosphoras.com/family-office-turquie-istanbul';
const title = 'Family office en Turquie à Istanbul : fiscalité, patrimoine et résidence | Bosphoras';
const description = 'Guide Bosphoras pour créer ou coordonner un family office en Turquie à Istanbul : loi n°7582, revenus étrangers, résidence fiscale, héritage, banque, immobilier, assurance, société, substance, fiscalité et accompagnement privé.';
const updatedAt = '2026-06-05';

const cards = [
  ['Définition', 'Un family office en Turquie est une structure de coordination privée pour organiser résidence, patrimoine, banque, fiscalité, immobilier, assurance, santé, mobilité et héritage.'],
  ['Pourquoi Istanbul ?', 'Istanbul combine position géographique, réseau bancaire, accès aux avocats, fiscalistes, bureaux premium, immobilier, santé privée et relations d’affaires régionales.'],
  ['Lien avec la loi n°7582', 'La réforme publiée au Resmî Gazete n°33270 renforce l’intérêt des nouveaux résidents, revenus étrangers, héritage et structures de services internationales.'],
  ['Rôle de Bosphoras', 'Bosphoras coordonne les interlocuteurs utiles sans remplacer avocat, fiscaliste, banque, comptable ou professionnel réglementé.'],
];

const examples = [
  ['Famille internationale qui s’installe', 'Coordination résidence, logement, école, santé, assurance, banque, fiscalité et sécurité quotidienne à Istanbul, Bodrum ou Antalya.'],
  ['Entrepreneur avec revenus étrangers', 'Analyse des dividendes, plus-values, sociétés étrangères, contrats, flux bancaires, pays d’origine et application éventuelle de l’article 20/D.'],
  ['Patrimoine immobilier et financier', 'Suivi des actifs, reporting, assurances, fiscalité, succession, donation, immobilier, comptes bancaires et documents familiaux.'],
  ['Groupe familial international', 'Coordination holding, centre de services, bureau privé, fiscalité, avocats, comptables, recrutement, bureaux et déplacements VIP.'],
];

const checks = ['résidence fiscale actuelle et future','origine des fonds et preuves bancaires','sociétés étrangères et revenus hors Turquie','héritage, donation et organisation familiale','banque, assurance, immobilier et santé privée','avocat, fiscaliste, comptable et règles d’application'];

const faqs = [
  ['Qu’est-ce qu’un family office en Turquie ?', 'C’est une organisation privée destinée à coordonner patrimoine, fiscalité, banque, immobilier, assurance, santé, résidence, documents et décisions familiales depuis la Turquie.'],
  ['La Turquie remplace-t-elle Dubaï ou Monaco ?', 'Pas automatiquement. La Turquie peut devenir une base familiale et opérationnelle forte, mais le choix dépend de la résidence fiscale, des revenus, du pays d’origine, de la famille et de la substance réelle.'],
  ['La loi n°7582 change-t-elle l’intérêt d’un family office ?', 'Oui, elle renforce l’intérêt de certains profils internationaux grâce aux sujets revenus étrangers, nouveaux résidents, héritage, centres de services qualifiés et Istanbul Finance Center.'],
  ['Bosphoras donne-t-il un conseil fiscal ?', 'Non. Bosphoras coordonne le diagnostic privé avec les professionnels qualifiés et aide à structurer la feuille de route.'],
  ['Quels sujets doivent être vérifiés avant de s’installer ?', 'Résidence fiscale, source des revenus, conventions fiscales, banque, origine des fonds, assurances, immobilier, succession, société et obligations déclaratives.'],
];

export const metadata: Metadata = { title, description, alternates: { canonical: url, languages: { fr: url, en: 'https://bosphoras.com/en/family-office-turkey-istanbul', ru: 'https://bosphoras.com/ru/family-office-turtsiya-stambul', ar: 'https://bosphoras.com/ar/family-office-turkey-istanbul', 'x-default': url } }, openGraph: { title, description, url, siteName: 'Bosphoras', locale: 'fr_FR', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: title }] }, twitter: { card: 'summary_large_image', title, description, images: ['/images/og-default.jpg'] } };

export default function Page() {
  return (
    <><StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: title, description, inLanguage: 'fr-FR', datePublished: '2026-05-07', dateModified: updatedAt, author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: url, about: ['family office Turkey', 'Istanbul family office', 'Law 7582', 'foreign income', 'tax residence', 'wealth planning'] }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} /><Header locale="fr" currentPath="/family-office-turquie-istanbul" /><main className="bg-[#f8f1e7] text-[#101827]">
      <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Guide privé · Family Office Turquie · Mis à jour le 5 juin 2026</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Family office en Turquie à Istanbul : fiscalité, patrimoine et résidence</h1><p className="mt-8 max-w-3xl text-lg leading-9 text-white/80">La Turquie devient une base à étudier pour les familles internationales qui veulent organiser résidence, patrimoine, banque, fiscalité, immobilier, assurance, santé privée, mobilité et héritage. Avec la loi n°7582 publiée au Resmî Gazete n°33270, le sujet doit être traité comme un dossier structuré, documenté et coordonné avec des professionnels qualifiés.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/diagnostic-prive" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Demander une analyse privée<ArrowRight size={16} /></Link><Link href="/services/conseil-juridique-fiscal" className="inline-flex items-center justify-center border border-[#d2a863]/70 px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#d2a863]">Voir l’accompagnement fiscal</Link></div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[0.85fr_1.15fr]"><aside className="border border-[#d8c7a1] bg-[#fffaf0] p-8"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">Pourquoi Istanbul attire les familles patrimoniales ?</h2><p className="mt-5 leading-8 text-[#3e4857]">Istanbul offre un accès rapide à l’Europe, au Golfe, à l’Asie centrale et aux marchés émergents. La ville combine banques, avocats, fiscalistes, immobilier premium, écoles, santé privée, hôtels, transferts VIP, bureaux équipés et réseau d’affaires régional.</p></aside><div><h2 className="font-serif text-4xl tracking-[-0.03em]">Les 4 points essentiels</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{cards.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-6"><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></div></section>
      <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1300px]"><h2 className="font-serif text-4xl tracking-[-0.035em] md:text-6xl">Exemples concrets d’utilisation</h2><p className="mt-6 max-w-4xl text-lg leading-9 text-[#3e4857]">Un family office en Turquie peut être léger ou très structuré. L’important est de clarifier les fonctions réelles, les responsabilités, les pays concernés et les documents à produire.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examples.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-7"><Building2 className="mb-5 h-6 w-6 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Checklist avant de structurer un family office</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{checks.map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div><div className="mt-8 border-l-4 border-[#8a6728] bg-white p-8"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><p className="mt-5 text-lg leading-9 text-[#3e4857]">Un family office ne doit pas être vendu comme une solution fiscale magique. C’est une organisation de coordination patrimoniale et familiale, à construire selon le dossier et les pays concernés.</p></div></div></section>
      <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 md:grid-cols-[1fr_0.8fr] md:items-center"><div><Users className="h-8 w-8 text-[#d2a863]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.035em] md:text-6xl">Un seul interlocuteur pour coordonner la Turquie</h2><p className="mt-6 max-w-2xl text-lg leading-9 text-white/75">Bosphoras coordonne avocats, fiscalistes, banques, comptables, assurances, immobilier, bureaux, santé privée, transferts VIP et services familiaux, selon le dossier.</p></div><Link href="/diagnostic-prive" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-5 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Demander un diagnostic privé<ArrowRight size={16} /></Link></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1000px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Questions fréquentes</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faqs.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main><Footer locale="fr" /></>
  );
}
