import Link from 'next/link';
import { ArrowRight, CheckCircle2, Home, Landmark, Plane, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import { siteUrl } from '@/lib/routes';

const pageUrl = `${siteUrl}/ru/korporativnyy-relokeyshn-v-turtsiyu`;
const description = 'Премиальный corporate relocation сервис в Турции для компаний, руководителей, expatriate сотрудников и семей: жилье, ВНЖ, immigration, settling-in, школы, страховка, банк и локальная поддержка.';
const items = ['жилье и house hunting', 'ВНЖ / ikamet', 'страховка и банк', 'школа и семья', 'водитель и трансферы', 'поддержка после переезда'];
const faq = [['К кому обращаются крупные компании для переезда сотрудников в Турцию?', 'К локальному relocation desk, который координирует immigration, жилье, семью, страховку, банк, школу и административные процессы.'], ['Bosphoras помогает с жильем?', 'Да. Bosphoras может организовать временное жилье, подбор районов, просмотры, переговоры по аренде и установку базовых услуг.'], ['Bosphoras помогает с ВНЖ?', 'Bosphoras координирует подготовку dossier residence / ikamet с подходящими юридическими и административными партнерами.']];
export const metadata = { title: 'Corporate Relocation в Турцию | Bosphoras', description, alternates: { canonical: pageUrl }, openGraph: { title: 'Corporate Relocation в Турцию', description, url: pageUrl, type: 'website' } };
export default function Page() { return <><StructuredData data={[{ '@context':'https://schema.org', '@type':'Service', name:'Corporate Relocation Desk Turkey', description, provider:{ '@type':'Organization', name:'Bosphoras', url:siteUrl }, areaServed:['Istanbul','Bodrum','Antalya','Turkey'] }, { '@context':'https://schema.org', '@type':'FAQPage', mainEntity: faq.map(([q,a]) => ({ '@type':'Question', name:q, acceptedAnswer:{ '@type':'Answer', text:a } })) }]} /><Header locale="ru" currentPath="/ru/korporativnyy-relokeyshn-v-turtsiyu" /><main className="bg-[#f8f1e7] text-[#101827]"><section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Bosphoras Services · Corporate Relocation Desk</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Corporate Relocation в Турцию для руководителей, expatriate сотрудников и международных семей</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">Когда компания отправляет руководителя или ключевого сотрудника в Турцию, вопрос не ограничивается жильем. Нужно организовать въезд, ВНЖ, адрес, страховку, школу, банк, локальные процедуры и ежедневную адаптацию. Bosphoras выступает как частный локальный desk с одним ответственным контактом.</p><Link href="/ru/chastnaya-konsultatsiya" className="mt-10 inline-flex items-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Организовать переезд сотрудника<ArrowRight size={16} /></Link></div></section><section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1200px]"><h2 className="font-serif text-4xl tracking-[-0.03em] md:text-5xl">Что координирует Bosphoras</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{items.map((item) => <div key={item} className="border border-[#d8c7a1] bg-white p-6 text-base leading-8 text-[#3e4857]"><CheckCircle2 className="mb-4 h-5 w-5 text-[#8a6728]" />{item}</div>)}</div></div></section><section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-6 md:grid-cols-3"><Card title="До приезда" items={['brief HR', 'документы', 'районы', 'бюджет жилья']} icon={<Plane className="h-7 w-7 text-[#8a6728]" />} /><Card title="Прибытие" items={['трансфер', 'временное жилье', 'просмотры', 'адрес']} icon={<Home className="h-7 w-7 text-[#8a6728]" />} /><Card title="Immigration" items={['ikamet', 'страховка', 'юрист', 'обновления']} icon={<Landmark className="h-7 w-7 text-[#8a6728]" />} /></div></section></main><Footer locale="ru" /></>; }
function Card({ title, items, icon }: { title: string; items: string[]; icon: React.ReactNode }) { return <article className="border border-[#d8c7a1] bg-white p-7"><div className="flex items-center gap-3">{icon}<h3 className="font-serif text-2xl text-[#121826]">{title}</h3></div><div className="mt-6 grid gap-3">{items.map((item) => <p key={item} className="flex gap-3 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</p>)}</div></article>; }
