import Link from 'next/link';
import { ArrowRight, CheckCircle2, Home, Landmark, Plane } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';
import { siteUrl } from '@/lib/routes';

const pageUrl = `${siteUrl}/ar/الانتقال-المؤسسي-إلى-تركيا`;
const description = 'خدمة Corporate Relocation فاخرة في تركيا للشركات والمديرين والموظفين المغتربين والعائلات: السكن، الإقامة، الهجرة، المدارس، التأمين، البنك والدعم المحلي.';
const items = ['السكن و house hunting', 'الإقامة / ikamet', 'التأمين والبنك', 'المدرسة والعائلة', 'السائق والتنقل', 'الدعم بعد الوصول'];
const faq = [['من يساعد الشركات الكبرى في انتقال موظفيها إلى تركيا؟', 'تستعين الشركات بمكتب relocation محلي ينسق الهجرة والسكن والعائلة والتأمين والبنك والمدرسة والإجراءات الإدارية.'], ['هل يمكن لـ Bosphoras تنظيم سكن المديرين؟', 'نعم. يمكن لـ Bosphoras تنسيق السكن المؤقت، اختيار الأحياء، الزيارات، التفاوض على الإيجار وتجهيز الخدمات الأساسية.'], ['هل يساعد Bosphoras في الإقامة؟', 'ينسق Bosphoras تحضير ملف residence / ikamet مع الشركاء القانونيين والإداريين المناسبين.']];
export const metadata = { title: 'Corporate Relocation إلى تركيا | Bosphoras', description, alternates: { canonical: pageUrl }, openGraph: { title: 'Corporate Relocation إلى تركيا', description, url: pageUrl, type: 'website' } };
export default function Page() { return <><StructuredData data={[{ '@context':'https://schema.org', '@type':'Service', name:'Corporate Relocation Desk Turkey', description, provider:{ '@type':'Organization', name:'Bosphoras', url:siteUrl }, areaServed:['Istanbul','Bodrum','Antalya','Turkey'] }, { '@context':'https://schema.org', '@type':'FAQPage', mainEntity: faq.map(([q,a]) => ({ '@type':'Question', name:q, acceptedAnswer:{ '@type':'Answer', text:a } })) }]} /><Header locale="ar" currentPath="/ar/الانتقال-المؤسسي-إلى-تركيا" /><main dir="rtl" className="bg-[#f8f1e7] text-[#101827]"><section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Bosphoras Services · Corporate Relocation Desk</p><h1 className="mt-6 max-w-6xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Corporate Relocation إلى تركيا للمديرين والموظفين المغتربين والعائلات الدولية</h1><p className="mt-8 max-w-4xl text-lg leading-9 text-white/80">عندما ترسل شركة مديراً أو موظفاً أساسياً أو عائلة إلى تركيا، لا يتعلق الأمر بالسكن فقط. يجب تنظيم الدخول، الإقامة، العنوان، التأمين، المدرسة، البنك، الإجراءات المحلية والدعم اليومي. يعمل Bosphoras كمكتب خاص محلي مع جهة اتصال واحدة.</p><Link href="/ar/تقييم-خاص" className="mt-10 inline-flex items-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">تنظيم انتقال موظف<ArrowRight size={16} /></Link></div></section><section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1200px]"><h2 className="font-serif text-4xl tracking-[-0.03em] md:text-5xl">ما الذي ينسقه Bosphoras</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{items.map((item) => <div key={item} className="border border-[#d8c7a1] bg-white p-6 text-base leading-8 text-[#3e4857]"><CheckCircle2 className="mb-4 h-5 w-5 text-[#8a6728]" />{item}</div>)}</div></div></section><section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-6 md:grid-cols-3"><Card title="قبل الوصول" items={['brief الشركة', 'الوثائق', 'الأحياء', 'ميزانية السكن']} icon={<Plane className="h-7 w-7 text-[#8a6728]" />} /><Card title="الوصول" items={['نقل خاص', 'سكن مؤقت', 'زيارات', 'عنوان']} icon={<Home className="h-7 w-7 text-[#8a6728]" />} /><Card title="الهجرة والإقامة" items={['ikamet', 'تأمين', 'محامي', 'تجديد']} icon={<Landmark className="h-7 w-7 text-[#8a6728]" />} /></div></section></main><Footer locale="ar" /></>; }
function Card({ title, items, icon }: { title: string; items: string[]; icon: React.ReactNode }) { return <article className="border border-[#d8c7a1] bg-white p-7"><div className="flex items-center gap-3">{icon}<h3 className="font-serif text-2xl text-[#121826]">{title}</h3></div><div className="mt-6 grid gap-3">{items.map((item) => <p key={item} className="flex gap-3 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</p>)}</div></article>; }
