'use client';

import { useEffect } from 'react';

const countryDialCodes = [
  { code: '+33', flag: '🇫🇷', label: 'France' }, { code: '+49', flag: '🇩🇪', label: 'Germany' }, { code: '+44', flag: '🇬🇧', label: 'United Kingdom' }, { code: '+41', flag: '🇨🇭', label: 'Switzerland' }, { code: '+32', flag: '🇧🇪', label: 'Belgium' }, { code: '+1', flag: '🇺🇸', label: 'United States' }, { code: '+1', flag: '🇨🇦', label: 'Canada' }, { code: '+90', flag: '🇹🇷', label: 'Turkey' }, { code: '+7', flag: '🇰🇿', label: 'Kazakhstan' }, { code: '+7', flag: '🇷🇺', label: 'Russia' }, { code: '+34', flag: '🇪🇸', label: 'Spain' }, { code: '+39', flag: '🇮🇹', label: 'Italy' }, { code: '+351', flag: '🇵🇹', label: 'Portugal' }, { code: '+31', flag: '🇳🇱', label: 'Netherlands' }, { code: '+43', flag: '🇦🇹', label: 'Austria' }, { code: '+971', flag: '🇦🇪', label: 'United Arab Emirates' }, { code: '+966', flag: '🇸🇦', label: 'Saudi Arabia' }, { code: '+974', flag: '🇶🇦', label: 'Qatar' }, { code: '+965', flag: '🇰🇼', label: 'Kuwait' }, { code: '+86', flag: '🇨🇳', label: 'China' }, { code: '+81', flag: '🇯🇵', label: 'Japan' }, { code: '+82', flag: '🇰🇷', label: 'South Korea' }, { code: '+91', flag: '🇮🇳', label: 'India' }, { code: '+212', flag: '🇲🇦', label: 'Morocco' }, { code: '+213', flag: '🇩🇿', label: 'Algeria' }, { code: '+216', flag: '🇹🇳', label: 'Tunisia' }, { code: '+20', flag: '🇪🇬', label: 'Egypt' }, { code: '+380', flag: '🇺🇦', label: 'Ukraine' }, { code: '+995', flag: '🇬🇪', label: 'Georgia' }, { code: '+994', flag: '🇦🇿', label: 'Azerbaijan' }, { code: '+998', flag: '🇺🇿', label: 'Uzbekistan' }, { code: '+996', flag: '🇰🇬', label: 'Kyrgyzstan' }, { code: '+52', flag: '🇲🇽', label: 'Mexico' }, { code: '+55', flag: '🇧🇷', label: 'Brazil' }, { code: '+61', flag: '🇦🇺', label: 'Australia' }, { code: '+27', flag: '🇿🇦', label: 'South Africa' },
];

const nextLabels: Record<string, string> = { fr: 'Suivant', en: 'Next', ru: 'Далее', ar: 'التالي', zh: '下一步', de: 'Weiter', es: 'Siguiente', it: 'Avanti', pt: 'Seguinte' };
const validationMessages: Record<string, string> = {
  fr: 'Merci de compléter nom, prénom, téléphone avec indicatif et email avant le paiement.',
  en: 'Please complete last name, first name, phone with country code and email before payment.',
  ru: 'Заполните фамилию, имя, телефон с кодом страны и email перед оплатой.',
  ar: 'يرجى إكمال الاسم والهاتف مع رمز الدولة والبريد الإلكتروني قبل الدفع.',
  zh: '付款前请填写姓名、带国家代码的电话和邮箱。',
  de: 'Bitte geben Sie Nachname, Vorname, Telefon mit Ländervorwahl und E-Mail vor der Zahlung ein.',
  es: 'Complete apellido, nombre, teléfono con prefijo y email antes del pago.',
  it: 'Completa cognome, nome, telefono con prefisso ed email prima del pagamento.',
  pt: 'Complete apelido, nome, telefone com indicativo e email antes do pagamento.',
};
const paymentErrorMessages: Record<string, string> = {
  fr: 'Le paiement Stripe n’est pas disponible. Vérifiez la configuration Stripe dans Vercel.',
  en: 'Stripe payment is not available. Please check the Stripe configuration in Vercel.',
  ru: 'Оплата Stripe недоступна. Проверьте настройки Stripe в Vercel.',
  ar: 'دفع Stripe غير متاح. يرجى التحقق من إعدادات Stripe في Vercel.',
  zh: 'Stripe付款不可用。请检查Vercel中的Stripe配置。',
  de: 'Stripe-Zahlung ist nicht verfügbar. Bitte prüfen Sie die Stripe-Konfiguration in Vercel.',
  es: 'El pago Stripe no está disponible. Revise la configuración Stripe en Vercel.',
  it: 'Il pagamento Stripe non è disponibile. Controlla la configurazione Stripe in Vercel.',
  pt: 'O pagamento Stripe não está disponível. Verifique a configuração Stripe na Vercel.',
};
const backNeedles = ['retour', 'back', 'назад', 'رجوع', '返回', 'zurück', 'volver', 'indietro', 'voltar'];
function currentLocale() { const p = window.location.pathname.toLowerCase(); if (p.startsWith('/en/')) return 'en'; if (p.startsWith('/ru/')) return 'ru'; if (p.startsWith('/ar/')) return 'ar'; if (p.startsWith('/zh/')) return 'zh'; if (p.startsWith('/de/')) return 'de'; if (p.startsWith('/es/')) return 'es'; if (p.startsWith('/it/')) return 'it'; if (p.startsWith('/pt/')) return 'pt'; return 'fr'; }
function euroToNumber(value: string) { const amount = Number(value.replace(/[^0-9,.-]/g, '').replace(',', '.')); return Number.isFinite(amount) ? Math.round(amount) : 0; }
function getSummary() { return (document.querySelector('[data-transfer-summary="true"]') || Array.from(document.querySelectorAll('aside')).find((aside) => /€|CHF|\$|£/.test(aside.textContent || ''))) as HTMLElement | undefined; }
function getPassengerCard() { return getSummary()?.previousElementSibling as HTMLElement | undefined; }
function passengerInputs() { const card = getPassengerCard(); if (!card) return [] as HTMLInputElement[]; return Array.from(card.querySelectorAll('input')).filter((input) => input.type !== 'checkbox' && input.dataset.transferDialCode !== 'true') as HTMLInputElement[]; }
function getDialInput() { return getPassengerCard()?.querySelector('input[data-transfer-dial-code="true"]') as HTMLInputElement | null; }
function createDialDatalist() { const datalist = document.createElement('datalist'); datalist.id = 'transfer-dial-codes'; countryDialCodes.forEach((c) => { const o = document.createElement('option'); o.value = c.code; o.label = `${c.flag} ${c.label}`; datalist.appendChild(o); }); return datalist; }
function createDialInput() { if (!document.getElementById('transfer-dial-codes')) document.body.appendChild(createDialDatalist()); const input = document.createElement('input'); input.dataset.transferDialCode = 'true'; input.className = 'h-14 rounded-2xl border border-gray-200 bg-gray-50 px-3 text-sm font-black text-gray-900 outline-none focus:border-black'; input.setAttribute('aria-label', 'Country code'); input.setAttribute('list', 'transfer-dial-codes'); input.inputMode = 'tel'; input.value = '+33'; return input; }
function enhancePhonePrefix() { const inputs = passengerInputs(); const phone = inputs[2]; if (!phone || phone.parentElement?.dataset.transferPhoneGroup) return; phone.type = 'tel'; phone.inputMode = 'tel'; phone.autocomplete = 'tel-national'; const wrapper = document.createElement('div'); wrapper.dataset.transferPhoneGroup = 'true'; wrapper.className = 'grid grid-cols-[92px_1fr] gap-2 md:col-span-2'; phone.parentElement?.insertBefore(wrapper, phone); wrapper.appendChild(createDialInput()); wrapper.appendChild(phone); }
function findBackButton(card: HTMLElement) { return (Array.from(card.querySelectorAll('button')) as HTMLButtonElement[]).find((button) => backNeedles.some((needle) => (button.textContent || '').toLowerCase().includes(needle))); }
function addMobileNextButton() { if (document.querySelector('[data-transfer-mobile-next="true"]')) return; const card = getPassengerCard(); const summary = getSummary(); if (!card || !summary) return; const backButton = findBackButton(card); if (!backButton || !backButton.parentElement) return; const row = document.createElement('div'); row.dataset.transferNavigationRow = 'true'; row.className = 'mt-6 flex w-full items-center justify-between gap-3 md:hidden'; row.style.display = 'flex'; row.style.width = '100%'; row.style.justifyContent = 'space-between'; backButton.parentElement.insertBefore(row, backButton); row.appendChild(backButton); backButton.style.marginRight = 'auto'; const button = document.createElement('button'); button.type = 'button'; button.dataset.transferMobileNext = 'true'; button.textContent = nextLabels[currentLocale()] || nextLabels.en; button.className = backButton.className || 'rounded-2xl border border-black px-6 py-4 text-xs font-black uppercase tracking-[0.14em] text-black md:hidden'; button.classList.add('md:hidden'); button.style.marginLeft = 'auto'; button.onclick = () => { const top = summary.getBoundingClientRect().top + window.scrollY - 88; window.scrollTo({ top: Math.max(0, top), behavior: 'smooth' }); }; row.appendChild(button); }
function buildPhone() { const inputs = passengerInputs(); const raw = inputs[2]?.value.trim() || ''; if (raw.startsWith('+')) return raw.replace(/[\s().-]/g, ''); const dialRaw = getDialInput()?.value.trim() || '+33'; const dial = dialRaw.startsWith('+') ? dialRaw : `+${dialRaw.replace(/[^0-9]/g, '')}`; return `${dial}${raw.replace(/[^0-9]/g, '').replace(/^0+/, '')}`; }
function mark(input: HTMLInputElement | undefined | null, invalid: boolean) { if (!input) return; input.style.borderColor = invalid ? '#dc2626' : ''; input.style.boxShadow = invalid ? '0 0 0 4px rgba(220,38,38,0.10)' : ''; }
function validatePassenger() { const inputs = passengerInputs(); const lastName = inputs[0], firstName = inputs[1], phone = inputs[2], email = inputs[3]; const values = { lastName: lastName?.value.trim() || '', firstName: firstName?.value.trim() || '', phone: buildPhone(), email: email?.value.trim() || '' }; const badLast = values.lastName.length < 2, badFirst = values.firstName.length < 2, badPhone = !/^\+[1-9]\d{7,14}$/.test(values.phone.replace(/[\s().-]/g, '')), badEmail = !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(values.email); mark(lastName, badLast); mark(firstName, badFirst); mark(phone, badPhone); mark(getDialInput(), badPhone); mark(email, badEmail); if (badLast || badFirst || badPhone || badEmail) { lastName?.scrollIntoView({ behavior: 'smooth', block: 'center' }); alert(validationMessages[currentLocale()] || validationMessages.en); return null; } return values; }
function lineValue(keys: string[]) { const s = getSummary(); const lines = (s?.innerText || document.body.innerText).split('\n').map((x) => x.trim()).filter(Boolean); const line = lines.find((item) => keys.some((k) => item.toLowerCase().startsWith(k.toLowerCase()))); if (!line) return ''; const i = line.indexOf(':'); return i >= 0 ? line.slice(i + 1).trim() : line; }
function checkoutAmount() { const s = getSummary(); const dataAmount = Number(s?.dataset.transferAmount || 0); if (Number.isFinite(dataAmount) && dataAmount > 0) return Math.round(dataAmount * 100) / 100; const amount = (Array.from(s?.querySelectorAll('span') || []) as HTMLSpanElement[]).reverse().find((span) => /€|CHF|\$|£/.test(span.textContent || ''))?.textContent || ''; return euroToNumber(amount); }
async function triggerConfirmationEmail() { const params = new URLSearchParams(window.location.search); const sessionId = params.get('session_id'); if (params.get('payment') !== 'success' || !sessionId) return; const key = `bosphoras-email-${sessionId}`; if (sessionStorage.getItem(key) || localStorage.getItem(key)) return; sessionStorage.setItem(key, 'pending'); try { const res = await fetch('/api/transfer/confirmation-email', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId }) }); if (res.ok) localStorage.setItem(key, 'sent'); else sessionStorage.removeItem(key); } catch { sessionStorage.removeItem(key); } }
async function startCheckout(button: HTMLButtonElement) { enhancePhonePrefix(); const passenger = validatePassenger(); if (!passenger) return; const summary = getSummary(); const total = checkoutAmount(); if (!total) { alert(paymentErrorMessages[currentLocale()] || paymentErrorMessages.en); return; } const trip = lineValue(['Trajet', 'Trip', 'Route', 'Маршрут', 'المسار', '路线', 'Fahrt', 'Trayecto', 'Tragitto', 'Trajeto']); const [pickup, dropoff] = trip.split('→').map((p) => p.trim()); const d = lineValue(['Durée', 'Duration', 'Длительность', 'المدة', '时长', 'Dauer', 'Duración', 'Durata', 'Duração']); const minutes = d.match(/(\d+)\s*min/i)?.[1] || ''; const km = d.match(/([0-9]+(?:[,.][0-9]+)?)\s*km/i)?.[1]?.replace(',', '.') || ''; const toll = euroToNumber(lineValue(['Péage', 'Toll', 'Maut', 'Peaje', 'Pedaggio', 'Portagem'])); const original = button.innerHTML; button.disabled = true; button.innerHTML = 'Stripe...'; try { const response = await fetch('/api/transfer/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ locale: currentLocale(), total, currency: summary?.dataset.transferCurrency || 'EUR', paymentMode: summary?.dataset.transferPaymentMode || 'online_full', balanceOnBoard: summary?.dataset.transferBalance || '0', pickup: pickup || 'Pickup', dropoff: dropoff || 'Drop-off', vehicle: summary?.dataset.transferVehicle || lineValue(['Voiture', 'Car', 'Auto', 'Fahrzeug', 'Coche', 'Veículo']), date: lineValue(['Date', 'Datum', 'Fecha', 'Data']), flightNumber: lineValue(['Vol', 'Flight', 'Flug', 'Vuelo', 'Volo', 'Voo', 'Рейс']), passengerCount: lineValue(['Passagers', 'Passengers', 'Passagiere', 'Pasajeros', 'Passeggeri', 'Passageiros']), routeMinutes: minutes, distanceKm: km, tollPrice: toll, tip: 0, firstName: passenger.firstName, lastName: passenger.lastName, phone: passenger.phone, email: passenger.email }) }); const data = await response.json(); if (!response.ok || !data.url) throw new Error(data.error || 'checkout_failed'); window.location.href = data.url; } catch { alert(paymentErrorMessages[currentLocale()] || paymentErrorMessages.en); button.disabled = false; button.innerHTML = original; } }
function isPaymentButton(button: HTMLButtonElement) { return Boolean(button.closest('[data-transfer-summary="true"]') || (button.closest('aside') && /€|CHF|\$|£/.test(button.closest('aside')?.textContent || ''))); }
export function TransferCheckoutEnhancer() { useEffect(() => { triggerConfirmationEmail(); const refresh = () => { enhancePhonePrefix(); addMobileNextButton(); }; const observer = new MutationObserver(refresh); observer.observe(document.body, { childList: true, subtree: true }); refresh(); const onClick = (event: MouseEvent) => { const button = (event.target as HTMLElement | null)?.closest('button') as HTMLButtonElement | null; if (!button || !isPaymentButton(button)) return; event.preventDefault(); event.stopPropagation(); startCheckout(button); }; document.addEventListener('click', onClick, true); return () => { observer.disconnect(); document.removeEventListener('click', onClick, true); }; }, []); return null; }
