import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, Building2, CheckCircle2, Landmark, ShieldCheck, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';

const url = 'https://bosphoras.com/ru/kvalifitsirovannye-servisnye-tsentry-turtsiya';
const title = 'Квалифицированные сервисные центры в Турции: налоговые преимущества, условия и примеры | Bosphoras';
const description = 'Гид Bosphoras по квалифицированным сервисным центрам в Турции после Закона №7582, опубликованного в Resmî Gazete №33270: Nitelikli hizmet merkezi, международные группы, иностранные доходы, функции поддержки, substance, офисы, сотрудники и контракты.';
const updatedAt = '2026-06-05';

const cards = [
  ['Определение', 'Квалифицированный сервисный центр, Nitelikli hizmet merkezi, — турецкая структура для оказания услуг связанным компаниям за пределами Турции.'],
  ['Кому подходит', 'Международные группы, операционные холдинги, family offices, консалтинг, IT-платформы, finance, HR, reporting и customer support.'],
  ['Иностранные доходы', 'Модель основана на услугах, выставляемых связанным иностранным компаниям, с понятной документацией источника доходов.'],
  ['Local substance', 'Компания должна доказать реальное присутствие: офисы, сотрудники, контракты, счета, governance, банк, бухгалтерия и операции.'],
];

const examples = [
  ['Региональный финансовый центр', 'Reporting, consolidation, controlling, treasury, intra-group invoicing и банковский контроль для нескольких стран.'],
  ['Legal и compliance support', 'Команда в Стамбуле для контрактов, compliance, governance, регуляторного контроля и внутренней документации.'],
  ['IT, data и back-office hub', 'Турецкая структура может вести IT support, data, process, operations, customer support и координацию между странами.'],
  ['HR и talent platform', 'Турция может быть базой для рекрутинга, обучения, international mobility, payroll coordination и support команд группы.'],
];

const checks = ['структура группы и страны','связанные иностранные компании','точная природа услуг из Турции','контракты, счета и transfer pricing','офисы, сотрудники, governance и бухгалтерия','банк, KYC, финансовые потоки и операционные доказательства'];

const faqs = [
  ['Что такое квалифицированный сервисный центр в Турции?', 'Это турецкая компания, оказывающая квалифицированные услуги связанным компаниям за рубежом, с реальной деятельностью, сильной документацией и логикой международной группы.'],
  ['Налоговая выгода автоматическая?', 'Нет. Право зависит от деятельности, доходов, иностранных связанных компаний, local substance, доказательств и правил применения.'],
  ['Какие услуги могут быть релевантны?', 'Finance, accounting, legal, HR, data, IT, audit, reporting, purchasing, sales, customer support, compliance и функции головного офиса могут анализироваться.'],
  ['Почему это важно для иностранных инвесторов?', 'Турция хочет привлечь реальные региональные функции. Квалифицированный сервисный центр может стать альтернативой Дубаю, Сингапуру, Амстердаму или Лондону по потребностям группы.'],
  ['Какова роль Bosphoras?', 'Bosphoras координирует частный анализ с юристами, налоговыми консультантами, бухгалтерами, банками, офисами, рекрутингом и локальными партнерами. Bosphoras не заменяет регулируемых специалистов.'],
];

export const metadata: Metadata = { title, description, alternates: { canonical: url, languages: { fr: 'https://bosphoras.com/centres-services-qualifies-turquie-avantages-fiscaux', en: 'https://bosphoras.com/en/qualified-service-centers-turkey-tax-benefits', ru: url, ar: 'https://bosphoras.com/ar/qualified-service-centers-turkey-tax-benefits', 'x-default': 'https://bosphoras.com/centres-services-qualifies-turquie-avantages-fiscaux' } }, openGraph: { title, description, url, siteName: 'Bosphoras', locale: 'ru_RU', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: title }] }, twitter: { card: 'summary_large_image', title, description, images: ['/images/og-default.jpg'] } };

export default function Page() {
  return (
    <><StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: title, description, inLanguage: 'ru-RU', datePublished: '2026-05-07', dateModified: updatedAt, author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: url, about: ['Law 7582', 'Resmî Gazete 33270', 'qualified service center', 'Nitelikli hizmet merkezi', 'Turkey tax benefits', 'foreign investors'] }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} /><Header locale="ru" currentPath="/ru/kvalifitsirovannye-servisnye-tsentry-turtsiya" /><main className="bg-[#f8f1e7] text-[#101827]">
      <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Частный гид · Налоги Турции 2026 · Обновлено 5 июня 2026</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Квалифицированные сервисные центры в Турции: налоговые преимущества, условия и примеры</h1><p className="mt-8 max-w-3xl text-lg leading-9 text-white/80">Закон Турции №7582, опубликованный в Resmî Gazete №33270 от 4 июня 2026 года, вводит понятие квалифицированного сервисного центра, Nitelikli hizmet merkezi. Для иностранных инвесторов и международных групп это не просто создание компании в Турции: нужна реальная, документированная и операционная платформа услуг, связанная с иностранными доходами.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/ru/chastnaya-konsultatsiya" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Запросить частный анализ<ArrowRight size={16} /></Link><Link href="/ru/uslugi/yuridicheskie-nalogovye-konsultatsii" className="inline-flex items-center justify-center border border-[#d2a863]/70 px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#d2a863]">Налоговое сопровождение</Link></div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[0.85fr_1.15fr]"><aside className="border border-[#d8c7a1] bg-[#fffaf0] p-8"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">Почему Турция создала этот режим</h2><p className="mt-5 leading-8 text-[#3e4857]">Цель — привлечь headquarters и support-функции для иностранных рынков: finance, reporting, legal, compliance, data, IT, HR, purchasing, sales и customer support. Стамбул может стать базой между Европой, Заливом, Центральной Азией и развивающимися рынками.</p></aside><div><h2 className="font-serif text-4xl tracking-[-0.03em]">4 ключевых пункта</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{cards.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-6"><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></div></section>
      <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1300px]"><h2 className="font-serif text-4xl tracking-[-0.035em] md:text-6xl">Конкретные примеры сервисных центров</h2><p className="mt-6 max-w-4xl text-lg leading-9 text-[#3e4857]">Квалифицированный сервисный центр может быть интересен турецким, европейским, ближневосточным или азиатским группам, которые хотят координировать реальные региональные функции из Стамбула. Каждый кейс должен проверяться квалифицированными специалистами.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examples.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-7"><Building2 className="mb-5 h-6 w-6 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Checklist перед структурированием</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{checks.map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div><div className="mt-8 border-l-4 border-[#8a6728] bg-white p-8"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><p className="mt-5 text-lg leading-9 text-[#3e4857]">Ключевой пункт — substance. Компания без команды, офиса, реальных контрактов или защищаемой операционной деятельности не должна представляться как квалифицированный сервисный центр.</p></div></div></section>
      <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 md:grid-cols-[1fr_0.8fr] md:items-center"><div><Users className="h-8 w-8 text-[#d2a863]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.035em] md:text-6xl">Сначала структура, потом действие</h2><p className="mt-6 max-w-2xl text-lg leading-9 text-white/75">Bosphoras координирует частный анализ с нужными локальными контактами: юрист, налоговый консультант, бухгалтер, банк, офисы, рекрутинг и операционные партнеры.</p></div><Link href="/ru/chastnaya-konsultatsiya" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-5 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Запросить частный анализ<ArrowRight size={16} /></Link></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1000px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Частые вопросы</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faqs.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main><Footer locale="ru" /></>
  );
}
