import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, Building2, CheckCircle2, Factory, ShieldCheck, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';

const url = 'https://bosphoras.com/industrie-fabrication-turquie-impot-societe-12-5';
const title = 'Industrie en Turquie : impôt société 12,5 %, fabrication et investissement | Bosphoras';
const description = 'Guide Bosphoras sur l’industrie et la fabrication en Turquie après la loi n°7582 : impôt société 12,5 % à analyser pour certains revenus de production, usine, export, zone industrielle, société, permis, fiscalité, SGK, énergie, logistique et substance.';
const updatedAt = '2026-06-05';

const cards = [
  ['Cadre 12,5 % à analyser', 'La réforme fiscale 2026 renforce l’intérêt de la Turquie pour certains fabricants. Le taux réduit doit être vérifié selon l’activité, le revenu et les règles d’application.'],
  ['Fabrication réelle', 'L’avantage ne doit pas être présenté comme automatique : il faut une production réelle, une usine, des équipements, des salariés, une comptabilité et une substance industrielle.'],
  ['Export et marché régional', 'La Turquie peut servir de base industrielle entre Europe, Golfe, Asie centrale, Afrique du Nord et marchés émergents.'],
  ['Projet complet', 'Un dossier industriel touche société, terrain, zone organisée, permis, énergie, douane, SGK, fiscalité, banque, assurance et logistique.'],
];

const examples = [
  ['Usine textile ou habillement', 'Production, sous-traitance, export, contrôle qualité, logistique, certificats, main-d’œuvre et coûts énergétiques.'],
  ['Agro-industrie et packaging', 'Transformation alimentaire, emballage, stockage, chaîne froide, normes, export et distribution régionale.'],
  ['Machines, pièces et matériaux', 'Fabrication de composants, assemblage, maintenance, contrats B2B, douane, transport et certification.'],
  ['Base industrielle pour investisseurs étrangers', 'Création de société, terrain, zone industrielle, recrutement, banques, permis, fiscalité et pilotage opérationnel.'],
];

const checks = ['activité industrielle réellement exercée en Turquie','type de revenus concernés par le taux réduit','zone industrielle, terrain, bail ou usine','machines, salariés, SGK, énergie et assurance','comptabilité, facturation, douane et export','avocat, fiscaliste, comptable, banque et permis'];

const faqs = [
  ['Le taux de 12,5 % est-il automatique pour tous les fabricants ?', 'Non. Il faut vérifier l’activité, le type de revenu, la production réelle, la société, la comptabilité, les règles d’application et les conditions exactes du dispositif.'],
  ['Quels secteurs peuvent être étudiés ?', 'Textile, agro-industrie, packaging, matériaux, machines, pièces détachées, transformation, assemblage, équipements et production exportatrice peuvent être analysés selon le dossier.'],
  ['Pourquoi la Turquie est intéressante pour l’industrie ?', 'La Turquie combine position géographique, main-d’œuvre, réseau fournisseurs, logistique, douanes, zones industrielles, export et proximité avec plusieurs marchés régionaux.'],
  ['Quel est le rôle de Bosphoras ?', 'Bosphoras coordonne les interlocuteurs locaux : avocat, fiscaliste, comptable, banque, zone industrielle, immobilier, recrutement, assurance, transport et partenaires opérationnels.'],
  ['Quels risques vérifier avant d’investir ?', 'Permis, terrain, énergie, conformité, environnement, SGK, douane, fiscalité, contrats fournisseurs, qualité, financement, assurance et gouvernance locale.'],
];

export const metadata: Metadata = { title, description, alternates: { canonical: url, languages: { fr: url, en: 'https://bosphoras.com/en/turkey-manufacturing-corporate-tax-12-5', ru: 'https://bosphoras.com/ru/proizvodstvo-turtsiya-nalog-na-pribyl-12-5', ar: 'https://bosphoras.com/ar/turkey-manufacturing-corporate-tax-12-5', 'x-default': url } }, openGraph: { title, description, url, siteName: 'Bosphoras', locale: 'fr_FR', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: title }] }, twitter: { card: 'summary_large_image', title, description, images: ['/images/og-default.jpg'] } };

export default function Page() {
  return (
    <><StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: title, description, inLanguage: 'fr-FR', datePublished: '2026-05-07', dateModified: updatedAt, author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: url, about: ['Turkey manufacturing', 'corporate tax 12.5%', 'Law 7582', 'industry in Turkey', 'foreign investors', 'industrial investment'] }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} /><Header locale="fr" currentPath="/industrie-fabrication-turquie-impot-societe-12-5" /><main className="bg-[#f8f1e7] text-[#101827]">
      <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Guide privé · Industrie Turquie 2026 · Mis à jour le 5 juin 2026</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Industrie en Turquie : impôt société 12,5 %, fabrication et investissement</h1><p className="mt-8 max-w-3xl text-lg leading-9 text-white/80">La Turquie renforce son attractivité industrielle avec un cadre fiscal à analyser pour certains revenus de production. Pour un investisseur étranger, le sujet ne se limite pas au taux de 12,5 % : il faut vérifier la fabrication réelle, la substance, les permis, la zone industrielle, les salariés, l’énergie, la douane, la comptabilité et les règles d’application.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/diagnostic-prive" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Demander une analyse privée<ArrowRight size={16} /></Link><Link href="/services/conseil-juridique-fiscal" className="inline-flex items-center justify-center border border-[#d2a863]/70 px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#d2a863]">Voir l’accompagnement fiscal</Link></div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[0.85fr_1.15fr]"><aside className="border border-[#d8c7a1] bg-[#fffaf0] p-8"><Factory className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">Pourquoi la Turquie attire les industriels ?</h2><p className="mt-5 leading-8 text-[#3e4857]">La Turquie combine main-d’œuvre, savoir-faire, zones industrielles organisées, réseau fournisseurs, ports, routes, douanes, proximité européenne et accès aux marchés du Golfe, d’Asie centrale et d’Afrique du Nord.</p></aside><div><h2 className="font-serif text-4xl tracking-[-0.03em]">Les 4 points essentiels</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{cards.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-6"><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></div></section>
      <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1300px]"><h2 className="font-serif text-4xl tracking-[-0.035em] md:text-6xl">Exemples concrets de projets industriels</h2><p className="mt-6 max-w-4xl text-lg leading-9 text-[#3e4857]">Chaque industrie a ses contraintes : terrain, énergie, licences, stockage, qualité, douane, normes et ressources humaines. Le diagnostic doit précéder tout engagement financier.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examples.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-7"><Building2 className="mb-5 h-6 w-6 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Checklist avant d’investir dans une usine</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{checks.map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div><div className="mt-8 border-l-4 border-[#8a6728] bg-white p-8"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><p className="mt-5 text-lg leading-9 text-[#3e4857]">Un taux réduit n’a de valeur que si le projet industriel est réel, documenté, conforme et pilotable. La fiscalité doit suivre l’opération, pas l’inverse.</p></div></div></section>
      <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 md:grid-cols-[1fr_0.8fr] md:items-center"><div><Users className="h-8 w-8 text-[#d2a863]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.035em] md:text-6xl">Structurer l’investissement avant d’acheter</h2><p className="mt-6 max-w-2xl text-lg leading-9 text-white/75">Bosphoras coordonne une lecture privée du projet industriel : société, fiscalité, banque, terrain, zone industrielle, permis, assurance, énergie, recrutement, transport et partenaires locaux.</p></div><Link href="/diagnostic-prive" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-5 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Demander un diagnostic privé<ArrowRight size={16} /></Link></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1000px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Questions fréquentes</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faqs.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main><Footer locale="fr" /></>
  );
}
