import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, Building2, CheckCircle2, Factory, ShieldCheck, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';

const url = 'https://bosphoras.com/ru/proizvodstvo-turtsiya-nalog-na-pribyl-12-5';
const title = 'Производство в Турции: налог на прибыль 12,5%, фабрика и инвестиции | Bosphoras';
const description = 'Гид Bosphoras по производству и промышленным инвестициям в Турции после Закона №7582: налог 12,5% для анализа по отдельным производственным доходам, фабрика, экспорт, промышленные зоны, компания, разрешения, налоги, SGK, энергия, логистика и substance.';
const updatedAt = '2026-06-05';

const cards = [
  ['Режим 12,5% к анализу', 'Налоговая реформа 2026 повышает интерес к Турции для отдельных производителей. Ставку нужно проверять по деятельности, доходу и правилам применения.'],
  ['Реальное производство', 'Преимущество не автоматическое: нужны производство, фабрика, оборудование, сотрудники, бухгалтерия и industrial substance.'],
  ['Экспорт и региональные рынки', 'Турция может быть индустриальной базой между Европой, Заливом, Центральной Азией, Северной Африкой и emerging markets.'],
  ['Полный проект', 'Промышленный dossier включает компанию, землю, промышленную зону, разрешения, энергию, таможню, SGK, налоги, банк, страхование и логистику.'],
];

const examples = [
  ['Текстильная фабрика', 'Производство, subcontracting, экспорт, контроль качества, логистика, сертификаты, рабочая сила и энергозатраты.'],
  ['Agro-industry и packaging', 'Пищевая переработка, упаковка, хранение, cold chain, стандарты, экспорт и региональная дистрибуция.'],
  ['Машины, детали и материалы', 'Производство компонентов, assembly, maintenance, B2B контракты, таможня, транспорт и сертификация.'],
  ['Индустриальная база для инвесторов', 'Создание компании, земля, промышленная зона, рекрутинг, банки, разрешения, налоги и операционное управление.'],
];

const checks = ['реальная промышленная деятельность в Турции','тип дохода, возможно подпадающего под сниженный режим','промышленная зона, земля, аренда или фабрика','оборудование, сотрудники, SGK, энергия и страхование','бухгалтерия, счета, таможня и экспорт','юрист, налоговый консультант, бухгалтер, банк и разрешения'];

const faqs = [
  ['Ставка 12,5% автоматическая для всех производителей?', 'Нет. Нужно проверить деятельность, тип дохода, реальное производство, компанию, бухгалтерию, правила применения и точные условия режима.'],
  ['Какие сектора можно анализировать?', 'Текстиль, agro-industry, packaging, материалы, машины, запчасти, переработка, assembly, оборудование и экспортное производство могут анализироваться по dossier.'],
  ['Почему Турция интересна для производства?', 'Турция объединяет географию, рабочую силу, сеть поставщиков, логистику, таможню, промышленные зоны, экспорт и близость к региональным рынкам.'],
  ['Какова роль Bosphoras?', 'Bosphoras координирует локальные контакты: юрист, налоговый консультант, бухгалтер, банк, промышленная зона, недвижимость, рекрутинг, страхование, транспорт и операционные партнеры.'],
  ['Какие риски проверить до инвестиций?', 'Разрешения, земля, энергия, compliance, environment, SGK, таможня, налоги, контракты поставщиков, качество, финансирование, страхование и local governance.'],
];

export const metadata: Metadata = { title, description, alternates: { canonical: url, languages: { fr: 'https://bosphoras.com/industrie-fabrication-turquie-impot-societe-12-5', en: 'https://bosphoras.com/en/turkey-manufacturing-corporate-tax-12-5', ru: url, ar: 'https://bosphoras.com/ar/turkey-manufacturing-corporate-tax-12-5', 'x-default': 'https://bosphoras.com/industrie-fabrication-turquie-impot-societe-12-5' } }, openGraph: { title, description, url, siteName: 'Bosphoras', locale: 'ru_RU', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: title }] }, twitter: { card: 'summary_large_image', title, description, images: ['/images/og-default.jpg'] } };

export default function Page() {
  return (
    <><StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: title, description, inLanguage: 'ru-RU', datePublished: '2026-05-07', dateModified: updatedAt, author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: url, about: ['Turkey manufacturing', 'corporate tax 12.5%', 'Law 7582', 'industry in Turkey', 'foreign investors', 'industrial investment'] }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} /><Header locale="ru" currentPath="/ru/proizvodstvo-turtsiya-nalog-na-pribyl-12-5" /><main className="bg-[#f8f1e7] text-[#101827]">
      <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Частный гид · Производство Турция 2026 · Обновлено 5 июня 2026</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Производство в Турции: налог 12,5%, фабрика и инвестиции</h1><p className="mt-8 max-w-3xl text-lg leading-9 text-white/80">Турция усиливает промышленную привлекательность налоговым режимом, который нужно анализировать для отдельных производственных доходов. Для иностранного инвестора вопрос не ограничивается ставкой 12,5%: нужно проверить реальное производство, substance, разрешения, промышленную зону, сотрудников, энергию, таможню, бухгалтерию и правила применения.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/ru/chastnaya-konsultatsiya" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Запросить частный анализ<ArrowRight size={16} /></Link><Link href="/ru/uslugi/yuridicheskie-nalogovye-konsultatsii" className="inline-flex items-center justify-center border border-[#d2a863]/70 px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#d2a863]">Налоговое сопровождение</Link></div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[0.85fr_1.15fr]"><aside className="border border-[#d8c7a1] bg-[#fffaf0] p-8"><Factory className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">Почему Турция привлекает производителей</h2><p className="mt-5 leading-8 text-[#3e4857]">Турция объединяет рабочую силу, промышленное know-how, организованные промышленные зоны, сеть поставщиков, порты, дороги, таможню, близость к Европе и доступ к рынкам Залива, Центральной Азии и Северной Африки.</p></aside><div><h2 className="font-serif text-4xl tracking-[-0.03em]">4 ключевых пункта</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{cards.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-6"><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></div></section>
      <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1300px]"><h2 className="font-serif text-4xl tracking-[-0.035em] md:text-6xl">Конкретные примеры промышленных проектов</h2><p className="mt-6 max-w-4xl text-lg leading-9 text-[#3e4857]">У каждой отрасли свои ограничения: земля, энергия, лицензии, хранение, качество, таможня, стандарты и кадры. Диагностика должна быть до финансового обязательства.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examples.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-7"><Building2 className="mb-5 h-6 w-6 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Checklist перед инвестицией в фабрику</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{checks.map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div><div className="mt-8 border-l-4 border-[#8a6728] bg-white p-8"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><p className="mt-5 text-lg leading-9 text-[#3e4857]">Сниженная ставка имеет смысл только если промышленный проект реален, документирован, соответствует требованиям и управляем. Налоги должны следовать операции, а не наоборот.</p></div></div></section>
      <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 md:grid-cols-[1fr_0.8fr] md:items-center"><div><Users className="h-8 w-8 text-[#d2a863]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.035em] md:text-6xl">Структурировать инвестицию до покупки</h2><p className="mt-6 max-w-2xl text-lg leading-9 text-white/75">Bosphoras координирует частный анализ промышленного проекта: компания, налоги, банк, земля, промышленная зона, разрешения, страхование, энергия, рекрутинг, транспорт и локальные партнеры.</p></div><Link href="/ru/chastnaya-konsultatsiya" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-5 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Запросить частный анализ<ArrowRight size={16} /></Link></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1000px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Частые вопросы</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faqs.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main><Footer locale="ru" /></>
  );
}
