import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, Building2, CheckCircle2, Globe2, Scale, ShieldCheck, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';

const url = 'https://bosphoras.com/turquie-vs-dubai-investisseurs-fiscalite';
const title = 'Turquie vs Dubaï pour investisseurs : fiscalité, résidence et business | Bosphoras';
const description = 'Comparatif Bosphoras Turquie vs Dubaï pour investisseurs étrangers : fiscalité, résidence, loi n°7582, revenus étrangers, Istanbul Finance Center, transit trade, industrie, family office, banque, substance et stratégie patrimoniale.';
const updatedAt = '2026-06-05';

const cards = [
  ['Deux modèles différents', 'Dubaï reste un hub international puissant. La Turquie ajoute une dimension industrielle, familiale, médicale, immobilière, logistique et régionale.'],
  ['Fiscalité à analyser', 'La loi n°7582 change l’intérêt de la Turquie pour certains profils : revenus étrangers, nouveaux résidents, héritage, IFM, services qualifiés et production.'],
  ['Substance réelle', 'Le choix ne doit pas être guidé seulement par une promesse fiscale : résidence, banque, société, bureaux, équipes, contrats et pays d’origine comptent.'],
  ['Double présence possible', 'Certains investisseurs peuvent combiner Dubaï et Turquie selon les fonctions : holding, résidence, famille, industrie, commerce, services ou immobilier.'],
];

const examples = [
  ['Famille internationale', 'Dubaï peut rester une base financière mondiale ; Istanbul peut devenir une base familiale, médicale, immobilière et opérationnelle proche de l’Europe.'],
  ['Entrepreneur avec revenus étrangers', 'La Turquie peut être étudiée pour la résidence, l’article 20/D, les revenus étrangers et le coût opérationnel, sous conditions strictes.'],
  ['Groupe de commerce international', 'Dubaï et la Turquie peuvent être comparés pour transit trade, banque, contrats, logistique, facture, substance et pays de destination.'],
  ['Projet industriel', 'La Turquie peut être plus pertinente que Dubaï pour production réelle, usine, main-d’œuvre, fournisseurs, zones industrielles et export régional.'],
];

const checks = ['résidence fiscale réelle et pays d’origine','type de revenus : étrangers, turcs, dividendes, plus-values','banques, KYC, origine des fonds et flux financiers','société, substance, bureaux, salariés et contrats','famille, école, santé, immobilier et style de vie','avocat, fiscaliste, comptable et conventions fiscales'];

const faqs = [
  ['La Turquie est-elle fiscalement meilleure que Dubaï ?', 'Pas automatiquement. Dubaï et la Turquie répondent à des logiques différentes. Le bon choix dépend de la résidence, des revenus, de la famille, du pays d’origine, de la substance et du projet.'],
  ['Pourquoi la Turquie devient plus intéressante en 2026 ?', 'La loi n°7582 renforce plusieurs sujets : revenus étrangers, nouveaux résidents, héritage, Istanbul Finance Center, transit trade, centres de services qualifiés et industrie.'],
  ['Dubaï reste-t-il pertinent ?', 'Oui. Dubaï reste un hub global fort pour finance, image internationale, immobilier, banque et mobilité. La comparaison doit être faite dossier par dossier.'],
  ['Peut-on combiner Turquie et Dubaï ?', 'Oui, certains profils peuvent structurer une double présence : Dubaï pour certaines fonctions, Turquie pour famille, opérationnel, industrie, services ou ancrage régional.'],
  ['Quel est le rôle de Bosphoras ?', 'Bosphoras coordonne l’analyse privée Turquie avec les bons interlocuteurs : fiscaliste, avocat, banque, comptable, immobilier, assurance, santé, bureaux et services privés.'],
];

export const metadata: Metadata = { title, description, alternates: { canonical: url, languages: { fr: url, en: 'https://bosphoras.com/en/turkey-vs-dubai-investors-tax', ru: 'https://bosphoras.com/ru/turtsiya-vs-dubai-investory-nalogi', ar: 'https://bosphoras.com/ar/turkey-vs-dubai-investors-tax', 'x-default': url } }, openGraph: { title, description, url, siteName: 'Bosphoras', locale: 'fr_FR', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: title }] }, twitter: { card: 'summary_large_image', title, description, images: ['/images/og-default.jpg'] } };

export default function Page() {
  return (
    <><StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: title, description, inLanguage: 'fr-FR', datePublished: '2026-05-07', dateModified: updatedAt, author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: url, about: ['Turkey vs Dubai', 'foreign investors', 'tax residence', 'Law 7582', 'Dubai investors', 'Turkey tax strategy'] }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} /><Header locale="fr" currentPath="/turquie-vs-dubai-investisseurs-fiscalite" /><main className="bg-[#f8f1e7] text-[#101827]">
      <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Guide privé · Turquie vs Dubaï · Mis à jour le 5 juin 2026</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Turquie vs Dubaï pour investisseurs : fiscalité, résidence et business</h1><p className="mt-8 max-w-3xl text-lg leading-9 text-white/80">Dubaï et la Turquie ne jouent pas exactement le même rôle. Dubaï reste un hub international majeur ; la Turquie devient une option plus forte pour certains investisseurs grâce à la loi n°7582, à Istanbul Finance Center, au transit trade, à l’industrie, aux revenus étrangers, au family office et à une implantation régionale réelle.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/diagnostic-prive" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Demander une analyse privée<ArrowRight size={16} /></Link><Link href="/services/conseil-juridique-fiscal" className="inline-flex items-center justify-center border border-[#d2a863]/70 px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#d2a863]">Voir l’accompagnement fiscal</Link></div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[0.85fr_1.15fr]"><aside className="border border-[#d8c7a1] bg-[#fffaf0] p-8"><Scale className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">Comparer sans caricaturer</h2><p className="mt-5 leading-8 text-[#3e4857]">Le bon choix n’est pas “Turquie ou Dubaï” de manière absolue. Il faut comparer la résidence fiscale, les revenus, la famille, la banque, les sociétés, le coût opérationnel, la substance, la langue, les marchés visés et la stratégie patrimoniale.</p></aside><div><h2 className="font-serif text-4xl tracking-[-0.03em]">Les 4 points essentiels</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{cards.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-6"><Globe2 className="mb-5 h-6 w-6 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></div></section>
      <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1300px]"><h2 className="font-serif text-4xl tracking-[-0.035em] md:text-6xl">Exemples concrets de comparaison</h2><p className="mt-6 max-w-4xl text-lg leading-9 text-[#3e4857]">La comparaison doit partir d’un cas réel. Un investisseur financier, une famille patrimoniale, un industriel et un groupe de commerce international n’ont pas les mêmes critères.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examples.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-7"><Building2 className="mb-5 h-6 w-6 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Checklist avant de choisir Turquie ou Dubaï</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{checks.map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div><div className="mt-8 border-l-4 border-[#8a6728] bg-white p-8"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><p className="mt-5 text-lg leading-9 text-[#3e4857]">Une comparaison sérieuse doit éviter les slogans fiscaux. Elle doit partir de la résidence réelle, des flux, de la famille, des sociétés, de la banque et de la substance opérationnelle.</p></div></div></section>
      <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 md:grid-cols-[1fr_0.8fr] md:items-center"><div><Users className="h-8 w-8 text-[#d2a863]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.035em] md:text-6xl">Décider avec une feuille de route privée</h2><p className="mt-6 max-w-2xl text-lg leading-9 text-white/75">Bosphoras coordonne l’analyse Turquie : résidence, fiscalité, banque, société, immobilier, assurance, santé privée, bureaux, family office, transferts VIP et partenaires locaux.</p></div><Link href="/diagnostic-prive" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-5 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Demander un diagnostic privé<ArrowRight size={16} /></Link></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1000px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Questions fréquentes</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faqs.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main><Footer locale="fr" /></>
  );
}
