import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowRight, Building2, CheckCircle2, Landmark, ShieldCheck, Users } from 'lucide-react';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StructuredData } from '@/components/StructuredData';

const url = 'https://bosphoras.com/en/family-office-turkey-istanbul';
const title = 'Family Office in Turkey and Istanbul: Tax, Wealth and Residence | Bosphoras';
const description = 'Bosphoras guide to coordinating a family office in Turkey and Istanbul: Law No. 7582, foreign income, tax residence, inheritance, banking, property, insurance, company structuring, substance, private healthcare and private coordination.';
const updatedAt = '2026-06-05';

const cards = [
  ['Definition', 'A family office in Turkey is a private coordination structure for residence, wealth, banking, tax, property, insurance, healthcare, mobility and inheritance.'],
  ['Why Istanbul?', 'Istanbul combines geography, banking access, lawyers, tax advisors, premium offices, property, private healthcare and regional business relationships.'],
  ['Connection with Law No. 7582', 'The reform published in Official Gazette No. 33270 reinforces the interest of new residents, foreign income, inheritance and international service structures.'],
  ['Bosphoras role', 'Bosphoras coordinates useful contacts without replacing lawyers, tax advisors, banks, accountants or regulated professionals.'],
];

const examples = [
  ['International family relocation', 'Coordination of residence, housing, schooling, healthcare, insurance, banking, tax and daily security in Istanbul, Bodrum or Antalya.'],
  ['Entrepreneur with foreign income', 'Review of dividends, capital gains, foreign companies, contracts, banking flows, country of origin and possible Article 20/D application.'],
  ['Property and financial wealth', 'Asset follow-up, reporting, insurance, tax, succession, gifts, property, bank accounts and family documents.'],
  ['International family group', 'Coordination of holding, service center, private office, tax, lawyers, accountants, recruitment, offices and VIP travel.'],
];

const checks = ['current and future tax residence','source of funds and banking evidence','foreign companies and income outside Turkey','inheritance, gifts and family organization','banking, insurance, property and private healthcare','lawyer, tax advisor, accountant and implementation rules'];

const faqs = [
  ['What is a family office in Turkey?', 'It is a private organization coordinating wealth, tax, banking, property, insurance, healthcare, residence, documents and family decisions from Turkey.'],
  ['Does Turkey replace Dubai or Monaco?', 'Not automatically. Turkey can become a strong family and operational base, but the choice depends on tax residence, income, country of origin, family needs and real substance.'],
  ['Does Law No. 7582 increase the interest of a family office?', 'Yes. It strengthens the interest of certain international profiles through foreign income, new residents, inheritance, qualified service centers and Istanbul Finance Center.'],
  ['Does Bosphoras provide tax advice?', 'No. Bosphoras coordinates the private assessment with qualified professionals and helps structure the roadmap.'],
  ['What must be checked before relocating?', 'Tax residence, income source, tax treaties, banking, source of funds, insurance, property, succession, company structure and reporting obligations.'],
];

export const metadata: Metadata = { title, description, alternates: { canonical: url, languages: { fr: 'https://bosphoras.com/family-office-turquie-istanbul', en: url, ru: 'https://bosphoras.com/ru/family-office-turtsiya-stambul', ar: 'https://bosphoras.com/ar/family-office-turkey-istanbul', 'x-default': 'https://bosphoras.com/family-office-turquie-istanbul' } }, openGraph: { title, description, url, siteName: 'Bosphoras', locale: 'en_US', type: 'article', images: [{ url: '/images/og-default.jpg', width: 1200, height: 630, alt: title }] }, twitter: { card: 'summary_large_image', title, description, images: ['/images/og-default.jpg'] } };

export default function Page() {
  return (
    <><StructuredData data={[{ '@context': 'https://schema.org', '@type': 'Article', headline: title, description, inLanguage: 'en-US', datePublished: '2026-05-07', dateModified: updatedAt, author: { '@type': 'Organization', name: 'Bosphoras' }, publisher: { '@type': 'Organization', name: 'Bosphoras' }, mainEntityOfPage: url, about: ['family office Turkey', 'Istanbul family office', 'Law 7582', 'foreign income', 'tax residence', 'wealth planning'] }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }]} /><Header locale="en" currentPath="/en/family-office-turkey-istanbul" /><main className="bg-[#f8f1e7] text-[#101827]">
      <section className="bg-[#121826] px-5 pb-20 pt-32 text-white md:px-8 md:pt-40"><div className="mx-auto max-w-[1300px]"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#d2a863]">Private guide · Turkey Family Office · Updated on June 5, 2026</p><h1 className="mt-6 max-w-5xl font-serif text-4xl leading-tight tracking-[-0.04em] md:text-7xl">Family office in Turkey and Istanbul: tax, wealth and residence</h1><p className="mt-8 max-w-3xl text-lg leading-9 text-white/80">Turkey is becoming a jurisdiction to review for international families looking to coordinate residence, wealth, banking, tax, property, insurance, private healthcare, mobility and inheritance. With Law No. 7582 published in Official Gazette No. 33270, the topic must be handled as a structured, documented file coordinated with qualified professionals.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/en/private-assessment" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Request a private assessment<ArrowRight size={16} /></Link><Link href="/en/services/legal-tax-advisory" className="inline-flex items-center justify-center border border-[#d2a863]/70 px-8 py-4 text-xs font-bold uppercase tracking-[0.16em] text-[#d2a863]">View tax support</Link></div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto grid max-w-[1300px] gap-10 lg:grid-cols-[0.85fr_1.15fr]"><aside className="border border-[#d8c7a1] bg-[#fffaf0] p-8"><Landmark className="h-8 w-8 text-[#8a6728]" /><h2 className="mt-6 font-serif text-3xl">Why Istanbul attracts wealth families</h2><p className="mt-5 leading-8 text-[#3e4857]">Istanbul gives fast access to Europe, the Gulf, Central Asia and emerging markets. The city combines banks, lawyers, tax advisors, premium property, schools, private healthcare, hotels, VIP transfers, serviced offices and regional business networks.</p></aside><div><h2 className="font-serif text-4xl tracking-[-0.03em]">The 4 essential points</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{cards.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-6"><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></div></section>
      <section className="bg-[#fffaf0] px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1300px]"><h2 className="font-serif text-4xl tracking-[-0.035em] md:text-6xl">Concrete use cases</h2><p className="mt-6 max-w-4xl text-lg leading-9 text-[#3e4857]">A family office in Turkey can be light or highly structured. The key is to clarify real functions, responsibilities, countries involved and documents to produce.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examples.map(([t, d]) => <article key={t} className="border border-[#d8c7a1] bg-white p-7"><Building2 className="mb-5 h-6 w-6 text-[#8a6728]" /><h3 className="font-serif text-2xl text-[#121826]">{t}</h3><p className="mt-4 text-sm leading-7 text-[#3e4857]">{d}</p></article>)}</div></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1100px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">Checklist before structuring a family office</h2><div className="mt-8 grid gap-3 md:grid-cols-2">{checks.map((item) => <div key={item} className="flex gap-3 border border-[#d8c7a1] bg-white p-5 text-sm leading-7 text-[#3e4857]"><CheckCircle2 className="mt-1 h-4 w-4 flex-none text-[#8a6728]" />{item}</div>)}</div><div className="mt-8 border-l-4 border-[#8a6728] bg-white p-8"><ShieldCheck className="h-8 w-8 text-[#8a6728]" /><p className="mt-5 text-lg leading-9 text-[#3e4857]">A family office should not be sold as a magic tax solution. It is a wealth and family coordination organization to be built according to the file and the countries involved.</p></div></div></section>
      <section className="bg-[#121826] px-5 py-16 text-white md:px-8 md:py-24"><div className="mx-auto grid max-w-[1200px] gap-10 md:grid-cols-[1fr_0.8fr] md:items-center"><div><Users className="h-8 w-8 text-[#d2a863]" /><h2 className="mt-6 font-serif text-4xl tracking-[-0.035em] md:text-6xl">One point of contact to coordinate Turkey</h2><p className="mt-6 max-w-2xl text-lg leading-9 text-white/75">Bosphoras coordinates lawyers, tax advisors, banks, accountants, insurance, property, offices, private healthcare, VIP transfers and family services according to the file.</p></div><Link href="/en/private-assessment" className="inline-flex items-center justify-center gap-3 bg-[#d2a863] px-8 py-5 text-xs font-bold uppercase tracking-[0.16em] text-[#101827]">Request a private assessment<ArrowRight size={16} /></Link></div></section>
      <section className="px-5 py-16 md:px-8 md:py-24"><div className="mx-auto max-w-[1000px]"><h2 className="font-serif text-4xl tracking-[-0.03em]">FAQ</h2><div className="mt-8 grid gap-px bg-[#d8c7a1]">{faqs.map(([q, a]) => <article key={q} className="bg-[#f8f1e7] p-7"><h3 className="font-serif text-2xl text-[#121826]">{q}</h3><p className="mt-4 leading-8 text-[#3e4857]">{a}</p></article>)}</div></div></section>
      </main><Footer locale="en" /></>
  );
}
